### ISSUE TITLE
Class App\Models\User contains 1 abstract method and must therefore be declared

### ISSUE THREAD

**Issue by Fardeen-sumatoglobal** [spatie/laravel-activitylog#1011]
I am getting this error Class App\Models\User contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\Models\User::getActivitylogOptions)
Recently Updated to Laravel 9 with
Activity log Version : 4.4.0
Php Version : 8.0.14
this error pops up in my projects
Help Wanted

**Comment by constantinosergiou** [comment]
@Fardeen-sumatoglobal  you need add this on all of your models that you use activitylogs

```
use Spatie\Activitylog\LogOptions;
```
and then inside the class: 
```
 public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }
    ```
