### ISSUE TITLE
Retrieving activity model on saving activity log

### ISSUE THREAD

**Issue by enstain** [spatie/laravel-activitylog#102]
Method `log()` of `ActivityLogger` class creates instance of activity model and save data, but return `ActivityLogger` object instead of saved activity eloquent instance. I have no idea yet how can I use `ActivityLogger` object returning by `log()` method, so I'd suggest the `log()` should return saved activity model instance. 

If for some reasons it's not possible, at least `ActivityLogger` class could have method with name like `retrieveModel()` to do such thing.

**Comment by freekmurze** [comment]
Why do you want to have the `Activity`-model being returned?

**Comment by enstain** [comment]
The package provides switching default Activity model to my custom model, which means that I'm able to extend fields and methods of Activity model, but ActivityLogger class doesn't know about my extendings, however it works with it, so it's my task to work with my extended Activity model after it was created. But I should use `$activity = Activity::all()->last()` instead of direct retrieving model instance. If you mention such method to retrieve activity model, so you keep in mind too that you could want to have the Activity-model being returned somewhen.

In opposite your question, I can ask you the same, why do I have the `ActivityLogger` object after method `log()` called? Ok, for example it could be a chain of `..->log()..->log()..->log()` logging process, but saved activity instance could be returned explicitly by calling smth like `retrieveModel()` at least.

**Comment by freekmurze** [comment]
I've tagged a new version where the `log()` function returns the custom activity model.

https://github.com/spatie/laravel-activitylog/blob/1.10.2/tests/ActivityloggerTest.php#L206-L226
