### ISSUE TITLE
performedOn($model) does not call the tapActivity() for the corresponding model

### ISSUE THREAD

**Issue by FrancisMawn** [spatie/laravel-activitylog#1022]
**Describe the bug**
Hi. I came across this issue while writing my tests. I'm not sure if that's intentional or not, but to me it seems like an oversight...? If you manually generate an activity and set its subject, the `tapActivity()` method on that subject model will not get called.

**To Reproduce**
Add a `tapActivity()` method on the user model.
Run the following code:

```php
$user = User::factory()->create();
$activity = activity()->performedOn($user)->log('Some activity');
```

**Expected behavior**
I would expect the the `tapActivity()` handler to get called during the creation of the activity.

**Versions (please complete the following information)**
- PHP: 8.0
- Database: Mysql 8
- Laravel: 9.2
- Package: 4.4

**Comment by Gummibeer** [comment]
Feel free to provide a PR to improve that behavior.

**Comment by AlexVanderbist** [comment]
Thanks!
