### ISSUE TITLE
Command bug with another db (migrate:fresh --seed)

### ISSUE THREAD

**Issue by ercanbilginmedianova** [spatie/laravel-activitylog#1036]
**Describe the bug**
I got this error when i use another MySql database.

updated database.php in config and added this line in .env file 
```bash
ACTIVITY_LOGGER_DB_CONNECTION=activity
```

i run this command on command line
```bash
php artisan migrate:fresh --seed
```

**Versions (please complete the following information)**
- PHP: 8
- Database: MySQL 
- Laravel: 9
- Package: v4 

**Exception**
Illuminate\Database\QueryException 

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'activity_log' already exists (SQL: create table activity_log (id bigint unsigned not null auto_increment primary key, log_name varchar(255) null, description text not null, subject_type varchar(255) null, subject_id bigint unsigned null, causer_type varchar(255) null, causer_id bigint unsigned null, properties json null, created_at timestamp null, updated_at timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by runtimeinteractive** [comment]
I too am getting the same issue, however, mine is while I'm running tests. Any solution?

**Comment by camaech** [comment]
Ran into the same issue: Added a PR for it https://github.com/spatie/laravel-activitylog/pull/1139
