### ISSUE TITLE
Migrate of nothing on fresh install

### ISSUE THREAD

**Issue by aldiskatel** [spatie/laravel-activitylog#1041]
I currently installed new log but it does nothing on migration

**Screenshots**

**Versions (please complete the following information)**
- PHP: 7.4.28
- Database: mysql
- Laravel: 8
- Package: laravellog

**Stack Trace**
The full stack trace of the thrown exception.
<img width="1109" alt="Screen Shot 2022-04-22 at 14 07 10" src="https://user-images.githubusercontent.com/20250991/164613649-abc239cb-a3d9-4aea-b51a-d3f29a50d23f.png">

**Comment by Gummibeer** [comment]
You can't be on v4 of the package as you are using PHP7.4.
https://github.com/spatie/laravel-activitylog/blob/4.0.0/composer.json

So you should also refer to the correct version of the docs matching your installed package version.
https://spatie.be/docs/laravel-activitylog/v3/introduction
