### ISSUE TITLE
Can not remove unwanted default columns on activity_log table

### ISSUE THREAD

**Issue by razavistag** [spatie/laravel-activitylog#1047]
**Cannot remove unwanted default columns**
on activity log we cannot delete the default values because there is an error occuring `SQLSTATE[42S22]: Column not found: 1054 Unknown column "log_name" in 'field list' (SQL: insert into "activity_log"("log_name").... `

following migration file can successfully remove the default column on `activity_log`
```
    public function up()
    {
        Schema::table('activity_log', function (Blueprint $table) {
            $table->dropColumn(['log_name', 'description', 'subject_type']);
        });
    }
```
![image](https://user-images.githubusercontent.com/79866399/168916891-87747ca0-2588-4e68-a551-2e9e1e41fd9d.png)

**Versions**
- PHP:  8.1
- Database:  Mysql
- Laravel: 8

**Exception**
it will be better if it allows for inserting or updating data without having default columns.

**Comment by Gummibeer** [comment]
Every package has requirements. This is by far not a bug but an invalid expectation.
