### ISSUE TITLE
withProperties and `date`

### ISSUE THREAD

**Issue by jeroenbourgois** [spatie/laravel-activitylog#105]
Hi!

When I add a `date` and `name` key to the `withProperties` array, this is in the database:
`{"date":{"date":"2016-11-25 09:03:46.000000","timezone_type":3,"timezone":"Europe\/Brussels"},"name":"ok"}`

When I remove the date key, only the `name` key is retained. Then I log just `x` and `y` props like so:
```
activity()
      ->withProperties([
        'x' => Date::now(),
        'y' => 'ok',
      ])
      ->log("test");
```

And this is what is saved:
`{"x":{"date":"2016-11-25 09:06:02.000000","timezone_type":3,"timezone":"Europe\/Brussels"},"y":"ok"}`

Any idea what I am doing wrong?

**Comment by freekmurze** [comment]
On first sight this seems ok to me. What are you expecting?

**Comment by jeroenbourgois** [comment]
oh my god, now I see :P blame it on the Friday! 😄

**Comment by freekmurze** [comment]
No problem, good thing it's almost weekend 😄
