### ISSUE TITLE
Issue overriding causer and batching logs within jobs

### ISSUE THREAD

**Issue by JTineyPL** [spatie/laravel-activitylog#1054]
**Describe the bug**
Overriding the causer with `CauserResolver::setCauser($model);` and batching logs with `LogBatch::startBatch();` within a job results in null `causer_type`, `causer_id` and `batch_uuid` columns after processing the first job (They are only set properly when the first job is processed after starting Horizon).

**To Reproduce**
1. Define log options on User model and add `LogsActivity` and `CausesActivity` traits:
```
public function getActivitylogOptions(): LogOptions
{
    return LogOptions::defaults()
        ->logFillable()
        ->logOnlyDirty()
        ->dontSubmitEmptyLogs();
}
```

2. Create a job such as:
```
LogBatch::startBatch();
CauserResolver::setCauser(User::inRandomOrder()->first());

// Make some changes
$user = User::inRandomOrder()->first();
$user->name = Str::random();
$user->save();

LogBatch::endBatch();
```

3. Dispatch job 5 times
4. `sail artisan horizon`
5. Columns `causer_type`, `causer_id` and `batch_uuid` are only set while executing the first job.

**Expected behavior**
The causer and batch uuid should always be set, as instructed.

**Versions**
- PHP: 8.1
- Database: MySQL 8.0.29
- Laravel: 9.15
- Package: 4.5.3

**Additional context**
Undoing this change restores the expected behaviour: https://github.com/spatie/laravel-activitylog/commit/0d0075b9c56ed0c282f59037e71cdaa6a052d336. I'm personally rolling back to 4.5.0 for now.

**Comment by Mo7sin** [comment]
Same issue here, I'm working with events and listeners here not jobs.

**Comment by farandal** [comment]
Same issue,
When using laravel queue:work and LogBatch::startBatch();
It seems setCauser only works for the first event in the queue.

Nevertheless, when running the queue with queue:listen, the issue dosn't seems to appear. 

```
class ImportJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    protected $user;

    public function __construct($user, ...)
    {
        $this->user                = $user;
        ...
    }

    public function handle()
    {
        \Log::info($this->user); // this logs the user
        CauserResolver::setCauser($this->user); // this sets the causer
        LogBatch::startBatch(); // start the batch
        \CauserResolver::getCauser();  // This 
        $validateProductsToImportJob = new ImportJob(
            $this->user,
           ...
        );
...
```

We have found the issue is related to this commit. 
https://github.com/spatie/laravel-activitylog/commit/0d0075b9c56ed0c282f59037e71cdaa6a052d336
