### ISSUE TITLE
Logging model events not working during unit test

### ISSUE THREAD

**Issue by baselbj** [spatie/laravel-activitylog#1055]
**Describe the bug**
I am tiring to assert that loges are running successfully, but when running unit test and trying to assertDatabaseHas any logs, no records found. This only happens when using (LogsActivity trait)  but when logging activity manually the log is saved to the database and I can assert it. 

**Expected behavior**
finding log records in the database during unit test.

**Versions (please complete the following information)**
- PHP: 8.0.19 
- Database: sqlite, memory
- Laravel: 9.9.0
- Package:

**Comment by trea** [comment]
Event::fake() can accept a list of events to fake which allows you to still get your model events and make assertions about other events. For example, if you wanted to dispatch a `UserDeactivated` event without its listener being fired while also verifying that the activity log record is saved you could do something like this:

```php
public function testModelChangeFiresOtherEvent() {
    Event::fake(UserDeactivated::class);
    
    $user = User::factory()->active()->create();
    
    $time = now();
    $user->deactivate($time);
    
    $this->assertDatabaseHas("activity_log", ["subject_type" => User::class, "subject_id" => $user->id, "deactivated_at" => $time]);
    
    Event::assertDispatched(UserDeactivated::class);
}
```
