### ISSUE TITLE
update log after restoring event

### ISSUE THREAD

**Issue by deraak** [spatie/laravel-activitylog#1062]
**Describe the bug**

After restoring a item the package logs `restored` and `updated`  event.
In `getActivitylogOptions` the updated_at filed is ignored in  `logExcept` method but the `shouldLogEvent` method in logsActivity trait check the dontLogIfAttributesChangedOnly

```PHP
public function getActivitylogOptions(): LogOptions
{
        return LogOptions::defaults()
            ->useLogName('category')
            ->logOnly(['*'])
            ->logOnlyDirty()
            ->logExcept([
                'created_at', 'updated_at', 'deleted_at'
            ]);
 }
```
The restore which is correct
```SQL
insert into
  `activity_log` (
    `log_name`,
    `properties`,
    `causer_id`,
    `causer_type`,
    `batch_uuid`,
    `event`,
    `subject_id`,
    `subject_type`,
    `description`,
    `updated_at`,
    `created_at`
  )
values
  (
    'category',
    '...',
    1,
    'App\Models\Admin',
    null,
    'restored',
    6,
    'App\Models\Category',
    'restored',
    '2022-07-04 15:34:28',
    '2022-07-04 15:34:28'
  )
```

This log is wrong since I set the updated_at in logExcept method
```SQL
insert into
  `activity_log` (
    `log_name`,
    `properties`,
    `causer_id`,
    `causer_type`,
    `batch_uuid`,
    `event`,
    `subject_id`,
    `subject_type`,
    `description`,
    `updated_at`,
    `created_at`
  )
values
  (
    'category',
    '{\"attributes\":[],\"old\":[]}',
    1,
    'App\Models\Admin',
    null,
    'updated',
    6,
    'App\Models\Category',
    'updated',
    '2022-07-04 15:34:28',
    '2022-07-04 15:34:28'
  )
```

**Versions (please complete the following information)**
- PHP: v8.1.4
- Database: 
- Laravel: v9.16.0 
- Package: latest version

**Comment by abhaypithadiya** [comment]
Hey! Any Update on this bug?

**Comment by Gummibeer** [comment]
This one isn't wrong - as the `updated_at` wasn't logged, like you configured it.

> Exclude these attributes from being logged.

The attribute wasn't logged. You would probably want `dontSubmitEmptyLogs()` to prevent the empty `updated` log.
