### ISSUE TITLE
BC not noted in upgrade notes, and not migrated completely

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-activitylog#1069]
**Describe the bug**
Relating to #767, it seems the logic around how deleted records are stored has changed without any notice in the UPGRADING.md file. This causes a discrepancy within upgrading to v4 as there are now old and new records for deleted being handled and stored differently. I'm not disagreeing with the change whatsoever, but not having it listed as well as no proper migration that would update old records properly seems like a half measure

**To Reproduce**
Upgrade from v3 to v4

**Expected behavior**
After migrating to v4, following all instructions in the UPGRADING.md, all deleted records (past and present) should be in the relative same format, having the deleted attributes present under the `old` key in the properties.

**Screenshots**

**Versions (please complete the following information)**
- PHP: 8.0
- Database: mysql 
- Laravel: 9.22
- Package: laravel-activitylog

**Comment by Gummibeer** [comment]
As these records are deleted it's impossible to restore the information. And as nothing relies on this data it's not breaking.
It's up to the user how to handle the difference.

**Comment by ragingdave** [comment]
I think maybe there was a misunderstanding here, I meant that the activity log records reflecting a delete model event differ between v3 and v4 in the structure. As mentioned the full migration of old v3 records would be to move the logged properties to match the updated structure that deleted model events are now storing as.
