### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError Trait "spatie\Activitylog\Traits\LogsActivity" not found

### ISSUE THREAD

**Issue by mohamedElsayedIbrahim** [spatie/laravel-activitylog#1071]
Trait "spatie\Activitylog\Traits\LogsActivity" not found when i used it in model "Laravel 7"
here is a link for error screenshot
https://flareapp.io/share/B5ZpYngP#F1
![image](https://user-images.githubusercontent.com/63871883/182101408-8b92a926-d2dc-4aa1-ac47-a89162e89335.png)

i check the vendor folder package is already install and located there

**Comment by Gummibeer** [comment]
You should use the proper FQCN in import and also upgrade your Laravel version as V7 is way out of support.
