### ISSUE TITLE
'App\Models\User' does not implement method 'getActivitylogOptions' - Laravel 9

### ISSUE THREAD

**Issue by ComputerMaverick69** [spatie/laravel-activitylog#1079]
**Describe the bug**
Adding the `use LogsActivity` to your user model throws the error as stated in the subject above.

**To Reproduce**
To reproduce this in Laravel 9 simply add the `use LogsActivity` to your user model

**Versions (please complete the following information)**
- PHP:  8.1.6
- Database: 10.4.21-MariaDB
- Laravel: 9.19
- Package: Spatie ActivityLog

**Comment by MACscr** [comment]
Show your code. pretty sure you didnt add it correctly. It does indeed work with laravel 9 and models. im using it now.

**Comment by ComputerMaverick69** [comment]
Find the code below

```
<?php

namespace App\Models;

use App\Notifications\MyWelcomeNotification;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Permission\Traits\HasRoles;
use Spatie\WelcomeNotification\ReceivesWelcomeNotification;

class User extends Authenticatable // This is where the error is thrown
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;
    use ReceivesWelcomeNotification;
    use LogsActivity;  
    

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function sendWelcomeNotification(Carbon $validUntil)
    {
        $this->notify(new MyWelcomeNotification($validUntil));
    }
}
```

**Comment by ComputerMaverick69** [comment]
> Show your code. pretty sure you didnt add it correctly. It does indeed work with laravel 9 and models. im using it now.

I added the code block. Do see where i have made the mistake.

**Comment by chris-skilltech** [comment]
@ComputerMaverick69 you need to add a method called getActivityLogOptions to your model i.e.

`public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults();
    }`

**Comment by ComputerMaverick69** [comment]
> @ComputerMaverick69 you need to add a method called getActivityLogOptions to your model i.e.
> 
> `public function getActivitylogOptions(): LogOptions { return LogOptions::defaults(); }`

When i do that  get a different error `Undefined type 'App\Models\LogOptions'`. I believe adding the LogsActivity trait is supposed to implement `getActivitylogOptions` by default. At least that's what i saw from examples in the documentation.

**Comment by ComputerMaverick69** [comment]
> @ComputerMaverick69 you need to add a method called getActivityLogOptions to your model i.e.
> 
> `public function getActivitylogOptions(): LogOptions { return LogOptions::defaults(); }`

Yea.... Thanks for pointing that out.
