### ISSUE TITLE
composite key error illegal offset type

### ISSUE THREAD

**Issue by maxdiable** [spatie/laravel-activitylog#1091]
hi,
i use model with composite key.
I introduced the traits "use LogsActivity;", but as soon as I save it it gives me the error:
 "illegal offset type"

my model is.

`
use LogsActivity;
protected $table = 'PERMISSION_ROLE';
    protected $primaryKey = ['permission_id', 'role_id'];
    public $incrementing = false;
    public $timestamps = false;
    protected $connection = Common::CONN_ORACLE_ALL;

 public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logAll();
    }

    protected function setKeysForSaveQuery($query)
    {
        $keys = $this->getKeyName();
        if(!is_array($keys)){
            return parent::setKeysForSaveQuery($query);
        }

        foreach($keys as $keyName){
            $query->where($keyName, '=', $this->getKeyForSaveQuery($keyName));
        }

        return $query;
    }

    protected function getKeyForSaveQuery($keyName = null)
    {
        if(is_null($keyName)){
            $keyName = $this->getKeyName();
        }

        if (isset($this->original[$keyName])) {
            return $this->original[$keyName];
        }

        return $this->getAttribute($keyName);
    }
`

any help ?

br max

**Comment by Gummibeer** [comment]
Composite keys aren't supported by Laravel so aren't by that package.

**Comment by maxdiable** [comment]
ok, but without LogsActivity everything works correctly :(

**Comment by Gummibeer** [comment]
You use any package for composite primary key support? This package doesn't provide compatibility with any composite PK package. And as CPK aren't a core Laravel feature this package doesn't support them either.

**Comment by maxdiable** [comment]
hi,
i not use package for composite primary key.
thanks anyway I will try to find other solutions

br
Max
