### ISSUE TITLE
Logging replicated pivot model fails

### ISSUE THREAD

**Issue by PascalHesselink** [spatie/laravel-activitylog#1093]
**Describe the bug**
When using the following, the activity logger is unable to log this due to a missing model ID

**To Reproduce**
PostPostCategory.php
```php
<?php

namespace App\Models;

use App\Traits\LogsActivity;
use Illuminate\Database\Eloquent\Relations\Pivot;

class PostPostCategory extends Pivot
{
    use LogsActivity;

    protected $table = "post_post_category";

    protected $guarded = [];

    public $timestamps = false;
}
```

Trying to run the following code:
```php
$item = PostPostCategory::first();
$item->replicate()->save();
```

LogsActivity trait
```php
<?php

namespace App\Traits;

use Spatie\Activitylog\LogOptions;

trait LogsActivity
{
    use \Spatie\Activitylog\Traits\LogsActivity;

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
                ->logOnly(['*']);
    }
```

**Expected behaviour**
When replicating the pivot model, it's expected to create a 'created' logging item in the database. 

**Versions (please complete the following information)**
- PHP: 8.1.0
- Database: MySQL
- Laravel: 9.31.0
- Package Version: 4.5.3 (tried also 4.6.0 and 4.4.0)

**Additional context**
We've spent some hours for debugging the error before we knew why we got the error. 
Our research results in the following:
When replicating AND saving the model, the logger tries to log this activity. But when using the `->save()` no ID is returned. The `LogsActivity.php` trait is trying to execute a `->fresh()` on a model instance that has no reference (ID) so it's trying to insert an empty instance but still trying to refer to an existing model. The function `attributeValuesToBeLogged` is causing this problem, when manually replacing `($this->exists && $this?->id)` instead of `($this->exists)` fixes the problem (for us, for now) but leaves the database with an empty `subject_id` field. This is expected, but not the wanted result.

**Exception**
```SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select * from `post_post_category` where `` = 0 and `` = 0 limit 1)```

**Comment by bytephase** [comment]
Same issue when using activities on Pivot model, Not adding the description as getting exactly same Exceptions

**Comment by Gummibeer** [comment]
We have a test that covers exactly what you've described and everything works - have even added some more tests to it and all is fine.
https://github.com/spatie/laravel-activitylog/blob/fc57d9cfd5da33d8eae6294b4fa9e6155f250d4f/tests/LogsActivityTest.php#L98-L115

**Comment by PascalHesselink** [comment]
Hello @Gummibeer 

I see your model 'Article' that is used for the test DOES NOT extend the Pivot, so indeed your test will work because you didn't extend the right class.

You should extend: use Illuminate\Database\Eloquent\Relations\Pivot;

**Comment by Gummibeer** [comment]
Pivots aren't "real models" and have, in most cases, no primary key at all. So the `incrementing` is disabled and because of that no ID is retrieved. You can enable it again by setting the `incrementing` property to `true` again.
Without primary key the model can't be the subject of any events and as logging model events doesn't make sense without a subject the models have to have a primary key.

**Comment by PascalHesselink** [comment]
Hello @Gummibeer 

Thanks for your reply, adding the incrementing property to true solves this issue. Thanks for the solution!
