### ISSUE TITLE
Automatic log creation on model variations does not work

### ISSUE THREAD

**Issue by Taoshan98** [spatie/laravel-activitylog#1096]
**Describe the bug**
I am implementing the automatic logging of the Models, after several attempts, I have noticed that the component is not working, I have followed the guide given in the documentation but nothing to do.

This is my code:
- Model
```php
<?php
namespace App\Models;

use App\Core\Traits\SpatieLogsActivity;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class CustomerInfo extends Model
{
    use SpatieLogsActivity;
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'customer_id',
        'avatar',
        'country',
        'vat',
        'language',
        'timezone',
        'currency',
    ];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logOnly(['vat']);
    }
}
```

- Controller 
```php
public function update(Request $request, $id)
    {
        Customer::where('id', $id)->update([
            'company_name' => $request->customerName,
        ]);

        CustomerInfo::where('customer_id', $id)->update([
            'vat' => $request->customerVat,
            'country' => $request->country,
            'language' => $request->language,
            'timezone' => $request->timezone,
            'currency' => $request->currency,
        ]);


        $activity = Activity::all()->last();
        
        dd($activity);
    }
```
**Expected behavior**
What I am trying to do is intercept any event that is update or creation of the CustomerInfo Model, in this case I was just testing the fillable attribute `vat`. Unfortunately, when from my interface, I send the update request by calling the `update` method the logs are not created, am I doing something wrong?

In addition, if I try to retrieve the last record from the `activity_log` table with the statement 
```php 
$activity = Activity::all()->last();
```
as described in the documentation, in my case `$activity` returns `null`. 

At this moment the component only works if I am writing the log with the command 
```php
activity()->log(' Look mum, I logged something ');
```

**Versions **
- PHP: 8.1.3
- Database: Mysql 
- Laravel: 9.22.1
- Package: 4.5.3

**Comment by Gummibeer** [comment]
Hey,
you aren't doing Eloquent Model updates but direct DB calls. So no events are fired.
Instead of `CustomerInfo::where('customer_id', $id)->update()` you should do `CustomerInfo::where('customer_id', $id)->firstOrFail()->update()`.

Or even better would be to use route binding.
https://laravel.com/docs/9.x/routing#:~:text=Laravel%20route%20model%20binding%20provides,that%20matches%20the%20given%20ID.

I recommend to you to learn more about the framework basics.
