### ISSUE TITLE
dontLogIfAttributesChangedOnly still logging updated_at

### ISSUE THREAD

**Issue by jvbalcita** [spatie/laravel-activitylog#1113]
**Describe the bug**
`dontLogIfAttributesChangedOnly` is still logging the updated_at column

Here's my code

```public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->useLogName('Asset')
            ->logAll()
            ->dontLogIfAttributesChangedOnly(['is_shared', 'deployments', 'updated_at'])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(fn(string $eventName) => ucwords($eventName));
    }
```

There's no error but when in frontend the view of the activity log whenever I hit save or update without any changes is still logging the updated_at cause the view to show a blank activity

**Expected behavior**
The updated_at should not be logging if it is added to the `dontLogIfAttributesChangedOnly`

**Screenshots**

![image](https://user-images.githubusercontent.com/26690711/201043922-b3b1e9f0-82b4-4f93-9b2c-8faca35dcb62.png)

**Versions (please complete the following information)**
- PHP: 8.1
- Database: 8.0
- Laravel: 9.39
- Package: Laravel Spatie Activity Log

**Comment by devhubpl** [comment]
I have similiar problem with dontLogIfAttributesChangedOnly(['password', 'updated_at'])
Using with User model:
```
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->dontLogIfAttributesChangedOnly(['password', 'updated_at'])
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs();
    }

    public function tapActivity(\Spatie\Activitylog\Contracts\Activity $activity)
    {
        $activity->ip_address = request()->ip();
        $activity->user_agent = request()->userAgent();
    }
```
When updating only password, all is ok, activity record is not created.
`\App\Models\User::find(2)->update(['password' => bcrypt('password1')]);`
But when updating with other fields, new activity record **has password** field, but **not updated_at**.
```
>>> \App\Models\User::find(2)->update(['name' => 'Julian Kuvalis', 'password' => bcrypt('password1')]);
=> true

>>> \App\Models\User::find(2)->activities()->latest()->first();;
=> Spatie\Activitylog\Models\Activity {#5798
     id: 186,
     log_name: "default",
     description: "updated",
     ip_address: "127.0.0.1",
     user_agent: "Symfony",
     subject_type: "App\Models\User",
     event: "updated",
     subject_id: 2,
     causer_type: null,
     causer_id: null,
     properties: "{"attributes":{"name":"Julian Kuvalis","password":"$2y$10$ZOc4OEX.P6YHmihkxvE8a.ouGoVCAUMavMAnp\/C29QMr.HHJ38kDm"},"old":{"name":"Julian Kuvalis Sr","password":"$2y$10$CCawlglCgb49CXtp8iX0Gebv9PYc3lCXnZbCFh.dP.deeP\/fV5C
8W"}}",
     batch_uuid: null,
     created_at: "2022-11-13 18:47:43",
     updated_at: "2022-11-13 18:47:43",
   }

```
Using:
spatie/laravel-activitylog: 4.6.0
laravel/framework: v9.35.1
PHP: 8.1.2
mariadb-server-10.6

**Comment by isalman-khan** [comment]
i tried to add these variable in the model, and worked for me 

 protected static $logAttributes = ['*'];
 protected static $logOnlyDirty = true;
 protected static $submitEmptyLogs = false;

**Comment by skdishansachin** [comment]
I have the same problem. Any fix or answer for this?

```php
public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logAll()
            ->logOnlyDirty()
            ->dontSubmitEmptyLogs()
            ->dontLogIfAttributesChangedOnly(['updated_at'])
            ->setDescriptionForEvent(fn (string $eventName) => "Product :subject.name was {$eventName} by :causer.name");
    }
```
