### ISSUE TITLE
Update on login

### ISSUE THREAD

**Issue by essteffan** [spatie/laravel-activitylog#113]
Hello.
I'm new on laravel-activitylog and i have the following issue.

I added log when user logged in, but in db also adds update event even if nothing is updated  

{"attributes":
{"name":"Denis Narcisa","email":"kpintea@ghita.com"},"old":
{"name":"Denis Narcisa","email":"kpintea@ghita.com"}}

How can i skip this update?

**Comment by freekmurze** [comment]
Add those attribute to `$ignoreChangedAttributes`

https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#ignoring-changes-to-certain-attributes
