### ISSUE TITLE
Activity not logged for the bulk action

### ISSUE THREAD

**Issue by Nileshsinh-Rathod** [spatie/laravel-activitylog#1130]
The activity is not logged for the bulk action, As an admin I wanted to update status for the users and wanted to log the activity but that won't work with `whereIn` method. 

Here is the code for the bulk update.
 `User::whereIn('id', $request->get('id'))->update(['status' => 0]);` 

Is there any way to log such activities ?

**Comment by Gummibeer** [comment]
This is because of this runs a plain SQL query and doesn't touch eloquent models at all.
You would have to retrieve models first and update them in a loop.
