### ISSUE TITLE
Index "PRIMARY" marked as corrupted

### ISSUE THREAD

**Issue by crayon1337** [spatie/laravel-activitylog#1137]
**Describe the bug**
I ran into a problem earlier today so basically the index PRIMARY for table `activity_log` is corrupted. I do have almost 20k rows in the table. I tried to do `OPTIMIZE TABLE` but that was not successful. 

**To Reproduce**
I don't actually know how to re-produce that. I have an application up and running for almost 3 years and the table has 20k rows.

**Expected behavior**
The index should NOT be corrupted.

**Screenshots**
![image](https://user-images.githubusercontent.com/17085444/207588914-1f089e84-9324-4ae1-bb76-41edd17b855e.png)

**Versions (please complete the following information)**
- PHP: 7.2.17
- Database: MariaDB 10.0.38
- Laravel: 5.8.7
- Package: 3.2

**Comment by Gummibeer** [comment]
It's a problem with your database and has nothing to do with that package.
