### ISSUE TITLE
Cannot load activity log when deploy it on cpanel (Could not check compatibility between Spatie\Activitylog\Models\Activity::getExtraProperty)

### ISSUE THREAD

**Issue by mmuqiitf** [spatie/laravel-activitylog#1141]
**Describe the bug**
I have a to deploy my project into cpanel. But when i deploy it, there is an error to load activity log in the browser. 

**To Reproduce**
-

**Expected behavior**
It should load the activity log in browser

**Screenshots**
![image](https://user-images.githubusercontent.com/24507383/209108327-3dc2eb9d-3e3e-4aba-a8d6-5bab4135ba8f.png)

**Versions (please complete the following information)**
- PHP: 8.1
- Database: MySQL (PhpMyAdmin)
- Laravel: 8.75
- Package: 4.6

**Exception**
Symfony\Component\ErrorHandler\Error\
FatalError

Could not check compatibility between Spatie\Activitylog\Models\Activity::getExtraProperty(string $propertyName, ?Spatie\Activitylog\Models\mixed $defaultValue = NULL): Spatie\Activitylog\Models\mixed and Spatie\Activitylog\Contracts\Activity::getExtraProperty(string $propertyName, Spatie\Activitylog\Contracts\mixed $defaultValue): Spatie\Activitylog\Contracts\mixed, because class Spatie\Activitylog\Models\mixed is not available

**Stack Trace**
Could not check compatibility between Spatie\Activitylog\Models\Activity::getExtraProperty(string $propertyName, ?Spatie\Activitylog\Models\mixed $defaultValue = NULL): Spatie\Activitylog\Models\mixed and Spatie\Activitylog\Contracts\Activity::getExtraProperty(string $propertyName, Spatie\Activitylog\Contracts\mixed $defaultValue): Spatie\Activitylog\Contracts\mixed, because class Spatie\Activitylog\Models\mixed is not available

in [/home/lppmitenasac/simpenmas2.itenas.ac.id/vendor/spatie/laravel-activitylog/src/Models/Activity.php ](https://github.com/spatie/laravel-activitylog/issues/new?assignees=&labels=bug&template=bug-report.md&title=)(line 74)

**Comment by Gummibeer** [comment]
You are definitely not on PHP8.1 - must be PHP7.4 or older.
https://www.php.net/manual/de/language.types.mixed.php
