### ISSUE TITLE
Logger does not log values changed by Model Observers

### ISSUE THREAD

**Issue by robertmarney** [spatie/laravel-activitylog#1149]
**Describe the bug**
When logging is set to logDirtyOnly on a model, and that model uses a model observer (e.g. in saving, updating, or creating) to write an attribute value, the log does not capture this field.

**To Reproduce**
Create a model with the following options

```php
/**
     * @return LogOptions
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logFillable()->logOnlyDirty()->dontSubmitEmptyLogs();
    }

```

Create a model observer with any of creating, saving, updating methods and write an attribute value:

``` php
$myModel->foo = 'bar';
```

Ensure this observer is wired in `AppServiceProvider.php`

e.g. 
```php
MyModel::observe(MyObserver::class);
```

Complete the event (e.g. create if using the creating), without sending the attribute set by observer (e.g. `foo` in this case)

Observe the logger not logging the attribute.

**Expected behavior**
The logger should consider this attribute as dirty or a mechanism to trigger the writing.

**Screenshots**

**Versions (please complete the following information)**
- PHP: 8.1.03
- Database:  Mysql 8.1
- Laravel: 9.45.1
- Package: 4.7.2

To get around this I have a quick and dirty fix that I call from my observer created / updated event hooks (not the creating or updating as before)

```php

public function appendObserverValue(string $attribute, mixed $value)
    {
        $originalValue = $this->getAttribute($attribute);
        $this->setAttribute($attribute, $value);

        if ($value === $originalValue) {
            return;
        }

        $lastEditProperties = $this->unsetRelation('lastEdit')->lastEdit->properties;

        Arr::set($lastEditProperties, "attributes.{$attribute}", $value);

        if ($this->lastEdit->event === 'updated') {
            Arr::set($lastEditProperties, "old.{$attribute}", $originalValue);
        }

        $this->lastEdit->properties = $lastEditProperties;

        DB::transaction(function () {
            $this->lastEdit->saveQuietly();
            $this->saveQuietly();
        });
    }

    public function lastEdit(): MorphOne
    {
        return $this->morphOne(ActivityLog::class, 'subject')
            ->whereIn('description', ['created', 'updated'])
            ->orderBy('id', 'desc');
    }

```

**Comment by Gummibeer** [comment]
It's the order of the event listeners - the package runs before your observer, so the old values are fetched before the observer can change anything.
Change the order of the listeners and everything should be fine.
