### ISSUE TITLE
Collisions with other trait method

### ISSUE THREAD

**Issue by gamingumar** [spatie/laravel-activitylog#115]
Thank for this amazing package, i am having an issue

Trait method activity has not been applied, because there are collisions with other trait methods on App\User

if a model uses both traits LogsActivity and CausesActivity it throws the error.

I can implement my own but is their a different solution?

Thanks

**Comment by gamingumar** [comment]
i figured out the way around this using php traits conflict handling.

if we have a user model and want to log activity on user model and we also want it to be the causer

use CausesActivity, LogsActivity {
        LogsActivity::activity insteadof CausesActivity;
        CausesActivity::activity as log;
    }
now we have 2 available methods, activity and log.

Thanks.

Not closing the issue because this doesn't work by default

**Comment by freekmurze** [comment]
Thanks for posting your solution. Closing this for now and will fix the collision in the next major version of the package.

**Comment by freekmurze** [comment]
Addressed in v5 (#1452) with renamed methods (`activitiesAsSubject()`, `activitiesAsCauser()`) and a new `HasActivity` combining trait.
