### ISSUE TITLE
LogBatch static methods

### ISSUE THREAD

**Issue by keizah7** [spatie/laravel-activitylog#1172]
`Non-static method Spatie\Activitylog\LogBatch::startBatch() cannot be called statically`

<img width="934" alt="image" src="https://user-images.githubusercontent.com/49227202/222568103-26738892-0a53-4e6e-8c44-4fde22e0e274.png">

```
public function startBatch(): void
{
    if (! $this->isOpen()) {
        $this->uuid = $this->generateUuid();
    }

    $this->transactions++;
}
```

docs is not updated?

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/blob/main/src/Facades/LogBatch.php
