### ISSUE TITLE
Display Username instead of Id

### ISSUE THREAD

**Issue by fabzster** [spatie/laravel-activitylog#1174]
Hi 

I would like to show the causer_name when retrieving logs instead of the causer_id for display purposes only
what is the best way to achieve this?

Kind Regards

**Comment by itsdwizzy** [comment]
You can just use the relationship method `causer()` provided in the `Spatie\Activitylog\Models\Activity` model:

```
Activity::with('causer')->get();
```

**Comment by fabzster** [comment]
thank you so much
