### ISSUE TITLE
Log Name Does not Change

### ISSUE THREAD

**Issue by andykoe24** [spatie/laravel-activitylog#1177]
**Describe the bug**
Hi,

I am using ActivityLog as a trait in my user model, but it doesn't capture my log name and keeps saving default in my database.
Does anyone know how to solve this?

**Screenshots**
![image](https://user-images.githubusercontent.com/112467629/226501293-7ec62d4f-805e-4d10-bcd0-fea8407c1259.png)

**Versions (please complete the following information)**
- PHP: 8++
- Database: Mysql
- Laravel: 9
- Package:

**Comment by boryn** [comment]
What happens when you try to specify the logname at the `getActivitylogOptions()` level?

```php
public function getActivitylogOptions()
{
    return LogOptions::defaults()
                     ->useLogName('system');
}
```

**Comment by rik43** [comment]
fix this in docs
https://spatie.be/docs/laravel-activitylog/v4/advanced-usage/using-multiple-logs

not actual: 
protected static $logName = 'custom_log_name_for_this_model';

**Comment by leecolarelli-tgb** [comment]
Can confirm that `useLogName()` method on `getActivitylogOptions()` works correctly for me, whilst adding a property to the model does not.

Docs need updating.

Laravel 11.11
laravel-activitylog 4.8
php 8.3
