### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by csogilvie** [spatie/laravel-activitylog#118]
I follow the instructions at https://docs.spatie.be/laravel-activitylog/v1/installation-and-setup which involves installing the package via composer, and adding it to the Providers array.

However, at that point:

vagrant@cprra:~/cprra$ php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
Nothing to publish for tag [migrations].

It's as if it doesn't load the file in?

This is using PHP7.1 and Laravel 5.3...

**Comment by freekmurze** [comment]
Could you put a `dd` statement somewhere in `vendor/spatie/activitylog/src/ActivitylogServiceProvider.php` to make sure it's being loaded?

**Comment by csogilvie** [comment]
Apparently I needed to run `php artisan config:clear` before  I ran the rest of the commands. This now works (and the issue was found from a different package).
