### ISSUE TITLE
Log is not capturing from commands or queues

### ISSUE THREAD

**Issue by saitarun135** [spatie/laravel-activitylog#1181]
Consider an example to update a book price ,in my books model i am using trait and getActivitylogOptions() it was working fine.i will mention which scenario it was working and which scenario it was not working.

**working scenario**
- when ever i update any price by using ORM level either Web or API.

**Not working scenario**
- if i want to update a book price in sale time ,for that i am using **queue-jobs or schedulars(CLI)** concept in this command file or job class  also i will update through ORM(model based) but it's not creating any log activity in my table

I am using like this in my queue class
`Books::where('id',$id)->update(['price'=>2354]);`

**Versions**
- PHP: 8.0.23
- Database:  10.6.11-MariaDB
- Laravel: 8.83.27
- Package: 4.1

**Comment by Gummibeer** [comment]
You are running the SQL update on query builder and not model level. That's why there's no event to capture.
