### ISSUE TITLE
Logs not populated when running db:seed

### ISSUE THREAD

**Issue by DiarQoroviqi** [spatie/laravel-activitylog#1190]
**Describe the bug**
When running the db:seed command from terminal it does not save the logs, it only save the logs when running a seed for a specific seeder.

**To Reproduce**
I have a model that already uses the trait LogsActivity;
```
class ContentEntry extends Model
{
	use HasFactory;
	use SoftDeletes;
	use LogsActivity;

    public function getActivitylogOptions(): LogOptions
	{
		return LogOptions::defaults()
			->logAll()
			->logOnlyDirty()
			->dontSubmitEmptyLogs();
	}
}
```

and a seeder for it `ContentEntrySeeder`. So when running directly the seeder `php artisan db:seed --class=ContentEntrySeeder` it works fine and adds the logs, but when running only db:seed(there a other seeders) without specifying the --class it do not add logs for `ContentEntry` model

**Versions (please complete the following information)**
- PHP: 8.1
- Database: Mysql
- Laravel: 10
- Package:

**Comment by geeky3** [comment]
Hi, @DiarQoroviqi ,

I tried to reproduce the issue with steps mentioned and some simple data but I was not able to reproduce it.

May be you can help me to reproduce it by sharing your use case data.

#### Following are my system technical specifications:

```php``` => ```8.1.18```
```laravel``` => ```10.10```
```spatie/laravel-activitylog``` => ```"^4.7"```

#### Following is my code, let me know if I am missing anything or may be you can create a repository for demonstrating the issue.

#### Model
![image](https://github.com/spatie/laravel-activitylog/assets/31416195/c3213a1c-39f9-4ecc-b54f-1bf6e0f3dddb)



#### Seeder
![image](https://github.com/spatie/laravel-activitylog/assets/31416195/347556b5-e004-4bb4-9cf1-9135d3255c27)
![image](https://github.com/spatie/laravel-activitylog/assets/31416195/dd068879-107b-44a4-a6ba-6b88f4c9c93b)

#### Running Seeder
![image](https://github.com/spatie/laravel-activitylog/assets/31416195/0392fa9b-c69e-4700-a0fb-fbe79701bdf6)

#### DB entries
![image](https://github.com/spatie/laravel-activitylog/assets/31416195/4a85a230-72f4-4fcd-abc7-cf03ecdd0062)
