### ISSUE TITLE
laravel 5.4

### ISSUE THREAD

**Issue by nmkr** [spatie/laravel-activitylog#120]
please merge to 5.4 too, thanks

**Comment by freekmurze** [comment]
I'll make a compatibly release as soon L5.4 is officially released

**Comment by nmkr** [comment]
thank you, but is there a way to get it installed under the current 5.4-dev?

**Comment by freekmurze** [comment]
You can now install the package in Laravel 5.4

**Comment by iraklisg** [comment]
I have a fresh installed Laravel 5.4 app and try 

`igeorgas@dhd-105:~/webApps/apptree2$ composer require laravel-activitylog`

I get the following error:
                                                                                                                                                       
```
[InvalidArgumentException]                                                                                                                           
Could not find package laravel-activitylog at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

This is the config property of my package.json 

```
"config": {
    "preferred-install": "dist",
    "sort-packages": true
}
```

Any advice please ?

**Comment by iraklisg** [comment]
Please ignore my comment, stupid me... its `$ composer require spatie/laravel-activitylog`
