### ISSUE TITLE
Update logs empty nulls

### ISSUE THREAD

**Issue by boryn** [spatie/laravel-activitylog#1206]
**Describe the bug**

While logging activities on a model with soft deletes, having this setting (without logging `created` events):
```php
protected static $recordEvents = ['updated', 'deleted', 'restored'];
```

and

```php
public function getActivitylogOptions(): LogOptions
{
    return LogOptions::defaults()
                     ->logAll()
                     ->logOnlyDirty()
                     ->logExcept([
                         'updated_at',
                         'deleted_at',
                     ])
                     ->dontLogIfAttributesChangedOnly([
                         'is_ready',
                         'suggested_time',
                     ])
                     ->dontSubmitEmptyLogs();
}
```
there are nulls logged for the `updated` event like this:

```json
{"old": {"id": null, "end": null, "start": null, "is_ready": null, "created_at": null}, "attributes": {"id": 20629138, "end": "2023-07-06", "is_ready": false, "created_at": "2023-07-02T07:29:41.000000Z"}}
```
It seems more like the `created` event being logged? Though I don't have it in the `$recordEvents` attribute and in the `activity_log` table these rows are logged with the `updated` event.

**Expected behavior**
The "null" old values should not be logged at all for the `updated` event. Especially when there is null id.

**Screenshots**
![image](https://github.com/spatie/laravel-activitylog/assets/807297/63fe2322-b524-4c4a-98db-903e33450154)

**Versions (please complete the following information)**
- PHP: 8.1
- Database: MySQL 8.0.20
- Laravel: 10.8
- Package: 4.7.3

**Comment by codeArtisanry** [comment]
@boryn 
Your `getActivitylogOptions()`  Helped me
Thanks

**Comment by timyourivh** [comment]
Same occurs to me, I have this:

<details>
  <summary>Versions</summary>
  
  ```
 PHP: 8.2.0
 Laravel: v10.4.1
 Package: 4.7.3
  ```
</details>

<details>
  <summary>Model</summary>
  
  ```php
  // Simplified version of my model
  
  
  use Spatie\Activitylog\LogOptions;
  use Spatie\Activitylog\Traits\LogsActivity;
  use App\Events;
  
  class Customer extends Model
  {
      use LogsActivity;
      
      // Included this as probable cause.
      protected $dispatchesEvents = [
          'created' => Events\CustomerCreated::class,
          'updated' => Events\CustomerUpdated::class,
          'deleted' => Events\CustomerDeleted::class,
      ];
      
      protected $fillable = [
          'name',
      ];
      
      public function getActivitylogOptions(): LogOptions
      {
          return LogOptions::defaults()
              ->logOnly(['name']);
      }
      
      // ...
  }
  ```
</details>

<details>
  <summary>Controller</summary>
  
  ```php
/**
 * Store a newly created resource in storage.
 */
public function store(Request $request)
{
    $validated = $request->validate([
        'name' => ['required', 'string', 'min:1', 'max:255', 'unique:customers,name'],
    ]);

    $customer = Customer::create([
        'name' => $validated['name'],
    ]);

    // (...)
    
    return redirect()->route('customers.index');
}
  ```
</details>

And when creating a customer it inserts this entry:

|log_name|description|subject_id|subject_type|event|causer_id|causer_type|properties|batch_uuid|
|-|-|-|-|-|-|-|-|-|
|default|updated|7|App\Models\Customer|updated|bb00215f-7b0f-4e7e-9d50-1672ab3b0fee|App\Models\User\Types\TenantUser| { "old": { "nam... |null|

With the properties column containing this:

```json
{
    "old": {
        "name": null
    },
    "attributes": {
        "name": "The Coolest Company"
    }
}
```

While I have never updated this record, only created. Is this a bug?
