### ISSUE TITLE
Phone number field is not checked as a string and does not update correctly

### ISSUE THREAD

**Issue by MahdiBagheri71** [spatie/laravel-activitylog#1219]
**Describe the bug :**

The phone number field that is defined as a string in the database does not work properly and is checked as a numeric value. For example, it does not distinguish between 0913 and 913, while there is a difference between these two strings and the record is updated.

**To Reproduce:**

Package: 4.7
Expected behavior The phone number field should be checked as a string and its changes should be recorded in the database.

**Versions:**

PHP: 8.2
Database: mysql
Laravel: 10.0
Package: 4.7

**Comment by debuqer** [comment]
Have you tried to use _useAttributeRawValues_?

This tells ActiviyLogger to use the Raw value of attributes instead of casting them

**Comment by MahdiBagheri71** [comment]
> Have you tried to use _useAttributeRawValues_?
> 
> This tells ActiviyLogger to use the Raw value of attributes instead of casting them

not work :(
