### ISSUE TITLE
Pagination and order for all activities?

### ISSUE THREAD

**Issue by Kovah** [spatie/laravel-activitylog#123]
It seems that the Activity model does not support pagination and ordering. As all activities are stored as database entries I wondered why the two methods are not available although they would be very usefull to create a paginated acitivity overview.

Currently I have to build a new pagination by using the `forPage()` collection method which is quite inconvenient.

**Comment by freekmurze** [comment]
`Activity` is just a plain Eloquent model. You can use all the Eloquent methods you know and love.
