### ISSUE TITLE
Laravel LTS compatibility

### ISSUE THREAD

**Issue by jakjr** [spatie/laravel-activitylog#124]
Hi.

This package could be considerable compatible with LTS Laravel 5.1 if the LTS version of Laravel requires PHP >= 5.5.9 and laravel-activitylog is ^7.0 ?

Thanks

**Comment by freekmurze** [comment]
For our packages we don't consider the LTS version of Laravel but only the version we used in our projects (which in most cases is the latest and greatest version of Laravel).
