### ISSUE TITLE
Update documentation website

### ISSUE THREAD

**Issue by Rasmus-Bertell** [spatie/laravel-activitylog#1254]
**Describe the bug**
Documentation in https://docs.spatie.be/laravel-activitylog displays only documentation for v1 and v2 even though v3 and v4 are published.

**Expected behavior**
All relevant versions should be available.

**Comment by reppair** [comment]
Ah, yes, I just came to the issues to report the same.

Anyone who wonders where to find the missing docs can look into the project `/docs` folder (for the selected branch) - https://github.com/spatie/laravel-activitylog/tree/main/docs

**Comment by chuckienorton** [comment]
Thanks @reppair  - it took me a minute to figure out where that was!

**Comment by wblondel** [comment]
As of 9 January 2024, documentation for v3 and v4 are available on the website
