### ISSUE TITLE
 Laravel-activitylog not installing

### ISSUE THREAD

**Issue by FaizullahFirozi** [spatie/laravel-activitylog#1256]
@php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].

**Comment by disto** [comment]
I have the same problem

**Comment by Maaz-revolo** [comment]
Facing Same issue

**Comment by surajkhanal** [comment]
Facing the same issue.

**Comment by Maaz-revolo** [comment]
Thanks it works.
