### ISSUE TITLE
Properties empty []

### ISSUE THREAD

**Issue by avisentinlektor** [spatie/laravel-activitylog#1275]
### Discussed in https://github.com/spatie/laravel-activitylog/discussions/1274

<div type='discussions-op-text'>

<sup>Originally posted by **avisentinlektor** February  7, 2024</sup>
"spatie/laravel-activitylog": "^4.5.2"
"php": "8.0.7"

After the update, in the table of acitivity_log the properties are always an empty array.
id;log_name;description;subject_id;subject_type;causer_id;causer_type;properties;created_at;updated_at;batch_uuid;event
3937584;default;updated;6289344;App\Models\Eloquent\Sede\Lettura;24;App\Models\Eloquent\System\User;[];2024-02-06 17:08:53;2024-02-06 17:08:53;\N;updated

How i can fix?

</div>

**Comment by Gummibeer** [comment]
You already have the discussion open - absolutely no reason to open another issue!
