### ISSUE TITLE
Migration wasn't created

### ISSUE THREAD

**Issue by kwadejeffrey** [spatie/laravel-activitylog#1290]
**Describe the bug**
After installing the package, the migrate file wasn't created.

**To Reproduce**
I don't even know what to write
eg: Configuration, Migration, Model, Controller/Command

**Expected behavior**

**Screenshots**

**Versions (please complete the following information)**
- PHP: 8.1
- Database: MySQL
- Laravel: 10
- Package: 4.8

**Additional context**

**Exception**
The thrown exception message.

**Stack Trace**
The full stack trace of the thrown exception.

**Comment by cirolaferrara** [comment]
`php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"`
