### ISSUE TITLE
Unknown data type: 'uuid' after Laravel 11 update

### ISSUE THREAD

**Issue by jamesautodude** [spatie/laravel-activitylog#1317]
**Describe the bug**
Getting error of "unknown data type "uuid"

**To Reproduce**
- Be on or upgrade to Laravel 11
- Run: `php artisan migrate` in command line
- Error will occur (at least in my case)

**Expected behavior**
Be able to run migrations without an error.

**Versions (please complete the following information)**
- PHP: 8.1
- Database: MariaDB 
- Laravel: 11
- Package: 4.8

**Exception**
`General error: 4161 Unknown data type: 'uuid' (Connection: mariadb, SQL: alter table `activity_log` add `batch_uuid` uuid null after `properties`)`

**Stack Trace**
```
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕ 
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

      +8 vendor frames 

  9   database/migrations/2024_07_28_054025_add_batch_uuid_column_to_activity_log_table.php:11
      Illuminate\Database\Schema\Builder::table("activity_log", Object(Closure))
      +37 vendor frames 

  47  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

**Comment by SlimDeluxe** [comment]
It seems your MariaDB version is too old. [UUID column type](https://mariadb.com/kb/en/uuid-data-type/) support has been added in 10.7.
So consider upgrading MariaDB to at least 10.11, which is the next currently supported version.

**Comment by amfischer** [comment]
I'm getting this same error, but we're running MySQL 8.0.30

**Comment by SlimDeluxe** [comment]
I don't use MySQL but it appears the UUID column data type is not supported at all in any version :shrug: They [show](https://dev.mysql.com/blog-archive/mysql-8-0-uuid-support/) using BINARY(16) as an equivalent.
I think this package should not use the uuid column type since it's not supported by all systems and Laravel does not seem to be using a fallback. As it seems there's no way it would work at all for an app that uses MySQL.
