### ISSUE TITLE
Installation issue on Laravel 5.2.45 and PHP 7

### ISSUE THREAD

**Issue by kalemdzievski** [spatie/laravel-activitylog#132]
Hi, am having this problem with composer dependencies while trying to install laravel-activitylog.
Here is the error:

Problem 1
    - Installation request for spatie/laravel-activitylog ^1.12 -> satisfiable by spatie/laravel-activitylog[1.12.0].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - spatie/laravel-activitylog 1.12.0 requires illuminate/config ~5.3.0|~5.4.0 -> satisfiable by illuminate/config[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.9].
    - don't install illuminate/config v5.3.0|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.3.16|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.3.23|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.3.4|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.2.45
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].

**Comment by freekmurze** [comment]
The latest version of this package is only compatible with Laravel 5.3 and up.

Try installing `1.11.0` of this package or below.

**Comment by kalemdzievski** [comment]
Solved my issue. Thank you. Great library. :)

**Comment by tobias-kuendig** [comment]
@freekmurze The requirements sections should be updated to reflect this: https://docs.spatie.be/laravel-activitylog/v1/requirements :+1:
