### ISSUE TITLE
Auto-closing PRs and Issues via GitHub/Spatie Bot

### ISSUE THREAD

**Issue by stevebauman** [spatie/laravel-activitylog#1322]
I really think auto-closing PR's and issues on this repo is doing much more harm than good.

There has been many well produced PR's that were closed but would have added value, as well as many bug issues reported that have been closed -- not because they're resolved, but simply because they've sat open for too long. This feels like the equivalent of sweeping things under the rug, and gives the appearance of an active repository but in truth is not.

It may be worthwhile to recruit some active developers seeking to support this package, as I'm sure maintaining all these active packages is not getting any easier and you are stretched very thin. I'll throw my hat into the ring if you're interested.

Also, please don't take this as any offence, I'm eternally grateful for the work you all have produced at Spatie, but I feel this package is getting neglected and it could use some TLC 🙏

**Comment by patinthehat** [comment]
@stevebauman Thank you! Unfortunately,  sometimes things are missed due to the dheer number of active packages under the Spatie github org. Are there any PRs in particular you think deserve a second (first) look?
