### ISSUE TITLE
Nothing to publish for tag [migrations].

### ISSUE THREAD

**Issue by vpakg** [spatie/laravel-activitylog#133]
Using PHP 7.1 
Laravel 5.3
"spatie/laravel-activitylog": "^1.12",

Running `php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"`

I get `Nothing to publish for tag [migrations].`

So I can't publish and migrate the activity_log table.

**Comment by freekmurze** [comment]
Did you add the service provider (and saved that file) prior to running the command?

```php
// config/app.php
'providers' => [
    ...
    Spatie\Activitylog\ActivitylogServiceProvider::class,
];
```

**Comment by vpakg** [comment]
Yep, service provider is there, the methods actually get called but throws an error since there is no table to save the information to. I've used this packaged on a previous project and didn't have the issue, was wondering if this was a version problem or something else.

**Comment by freekmurze** [comment]
Does it work in a vanilla Laravel app?

**Comment by vpakg** [comment]
It seems to work on a new installation. Not sure what's happening. Created the migration manually from the stub. Thanks for the help, will update if I find out what was happening.

**Comment by MatthiasHertel** [comment]
maybe your configs are cached:

try this before migrate:

`php artisan config:clear`
