### ISSUE TITLE
$ignoreChangedAttributes is ignored when updating model in the model file

### ISSUE THREAD

**Issue by JoshMountain** [spatie/laravel-activitylog#137]
My `Post.php` model looks like this:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;

class Post extends Model
{
    use SoftDeletes;
    use LogsActivity;

    protected $fillable = [
        'title',
        'content',
    ];

    protected static $ignoreChangedAttributes = [
        'views',
    ];

    protected static $logAttributes = [
        'title',
        'content',
    ];

    /**
     * @return bool
     */
    public function addView() {
        return $this->update(['views' => $this->views+1]);
    }
}
```

When I call `$post->addView()` in other files, I am getting an activity logged with no changes made.

**Comment by freekmurze** [comment]
@alexvanderbist Can you take a look at this one?

**Comment by AlexVanderbist** [comment]
Hi Josh,

I've taken a look at your issue and noticed a couple of things. 

First of all for the `update` method to work I had to add `views` to the `fillable` array. After doing that I ran into the same issue you described where the `update` method would be logged. I'll have a look at why that's happening.

In the meantime, as a workaround you could use the `increment` method since that doesn't seem to trigger the Activitylog: 
```php
return $this->increment('views');
```

**Comment by AlexVanderbist** [comment]
Hi again,

It seems like the `updated_at` property was triggering the Activitylog and thus needs to be ignored as well:
```php
protected static $ignoreChangedAttributes = [
    'views', 'updated_at'
];
```
Let me know if this fixes the issue for you.

**Comment by JoshMountain** [comment]
@AlexVanderbist Thanks that does help. Are the timestamp fields not ignored by default? I thought that was the case.

**Comment by AlexVanderbist** [comment]
@JoshMountain I assumed `updated_at` would be ignored by default as well but that might be confusing for people that (for example) only want to update the `updated_at` timestamp. 

I'll add a note in the docs clarifying this. Thanks!
