### ISSUE TITLE
How to make log file last forever in the log table ?

### ISSUE THREAD

**Issue by diazsasak** [spatie/laravel-activitylog#143]
How to make log file last forever in the log table ?

**Comment by diazsasak** [comment]
delete_records_older_than_days option only used when clean-command is executed. so if i never execute clean-command there is no log will be deleted forever. thanks :D

**Comment by hakimihamdan88** [comment]
what if accidentally execute clean command?

**Comment by Gummibeer** [comment]
@hakimihamdan88 in this case the entries are deleted. So the only thing you can do is to load a backup.

**Comment by toby1991** [comment]
> what if accidentally execute clean command?

use `php artisan make:command XXX`, then change the `protected $signature = 'activitylog:clean'` to over write the clean command
