### ISSUE TITLE
Bug on laravel 5.4

### ISSUE THREAD

**Issue by diazsasak** [spatie/laravel-activitylog#144]
The package ships with a CausesActivity trait which can be added to any model that you use as a causer. It provides an activity relationship which returns all activities that are caused by the model.

If you include it in the User model you can simply retrieve all the current users activities like this : 
`\Auth::user()->activity;`

on my User model : 
`use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\Traits\CausesActivity;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use LogsActivity;
    use CausesActivity;`

when i try to text deleting record on other model i got error : 
FatalErrorException in User.php line 11:
Trait method activity has not been applied, because there are collisions with other trait methods on App\User

**Comment by freekmurze** [comment]
See #115
