### ISSUE TITLE
Multiple user for causer_id

### ISSUE THREAD

**Issue by allylla-0623** [spatie/laravel-activitylog#145]
I used the package successfully, but I've encounter a problem with the causer. How would I use the activity log if i have more than 1 users(customer and admin). I successfully used this for my customer user by changing the default_auth_driver. And I'm using Auth::guard()

 Thank you very much.

**Comment by freekmurze** [comment]
We've recently released a new major version of the package that has support for multiple guards.

**Comment by freekmurze** [comment]
Currently this package does not support multiple guards. 

I'll revisit this issue when creating a new major version (could be a while though)
