### ISSUE TITLE
Issue with model $events property

### ISSUE THREAD

**Issue by godforhire** [spatie/laravel-activitylog#146]
When using Laravel's `$events` property on the model ([link](https://laravel.com/docs/5.4/eloquent#events)),  this package's methods for event logging do not get called. I suppose that's expected behavior, but is there a way to have both? If not, I will just dispatch events from my controllers.

**Comment by AlexVanderbist** [comment]
Hi,

Laravel will indeed ignore the package's events when you start using custom events in `$events`.

I'd suggest using model observers as they do not override the package's events.

You could also broadcast the `eloquent.created: App\Model` event from your custom event listener with the model as payload but that's a dirty work around imo.

Good luck!

**Comment by godforhire** [comment]
Hi, thanks for the reply. I'll give model observers a go.

**Comment by ejklock** [comment]
Hi!

I create an Observer for my model

But events not firing when i call methods on try catch block


`public function update(AdLocalUserUpdateRequest $req,$user){
            try {
                $update=$req->except('_token', 'role');
                $this->users=$this->accountRepository->update($update, $user)->roles()->update(['user_id'=>$user,'role_id' => $req->role]);
                session()->flash('alert-warning','Conta atualizada com sucesso');
            }  catch (ValidatorException $e) {
                $error= $e->getMessageBag();
                session()->flash('errors',$error);
            } catch (QueryException $e) {
                session()->flash('alert-danger',$e->getMessage());
            }finally{
                return redirect()->route('adm.accounts.index');
            }
    }`
My Observer Class:

`class AdUserObserver
{
    public function created(AdUser $user)
    {
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }
    public function creating(AdUser $user)
    {
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }

    /**
     * Listen to the User deleting event.
     *
     * @param AdUser $user
     * @return void
     */
    public function deleting(AdUser $user)
    {
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }

    public function updating(AdUser $user) {
        $user->updated_by=Auth::user()->name;
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }

    public function updated(AdUser $user){
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }

    public function deleted(AdUser $user){
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }

    public function saved(AdUser $user){
        $activity = Activity::all()->last();
        $activity->description;
        $activity->subject;
    }


}`

The observer is only called out of the try catch block
Any tips?
