### ISSUE TITLE
[Question] How to log causer with LogsActivity

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-activitylog#149]
I just had a look at https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/LogsActivity.php#L33-L37 and wondered if there is any way to invoke `->causedBy(auth()->user())` into this?

I am currently logging `created, updated, deleted, restored` on models where all these actions are caused by a user. Would that be possible just with the trait you provide or would I need to create an observer like this to handle the case?

```php
<?php

namespace App\Models\Observers;

use App\Models\Post;

class PostObserver
{
    public function created(Post $post)
    {
        activity()->causedBy(auth()->user())->performedOn($post)->log('created');
    }

    public function updated(Post $post)
    {
        activity()->causedBy(auth()->user())->performedOn($post)->log('updated');
    }

    public function deleted(Post $post)
    {
        activity()->causedBy(auth()->user())->performedOn($post)->log('deleted');
    }

    public function restored(Post $post)
    {
        activity()->causedBy(auth()->user())->performedOn($post)->log('restored');
    }
}
```

**Comment by aboldyrev** [comment]
Not necessary. User Model, committed the action is stored in the table. Provided that the user has authenticated.
As I know.
(Sorry for my English)

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this issue?

**Comment by danhunsaker** [comment]
The code at https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/LogsActivity.php#L34, which is responsible for writing the log entry, does _not_ include a `causedBy()` method call, so no, this value is not stored for entries added by the `LogsActivity` trait.
