### ISSUE TITLE
Have a custom log_name on Logging Model Events

### ISSUE THREAD

**Issue by cleanique-coders** [spatie/laravel-activitylog#15]
Is it possible to have custom `log_name` on Logging Model Events?

Currently, on `activity()`, I can pass in custom `log_name`, but how can I have a custom `log_name` on Model that using `Spatie\Activitylog\Traits\LogsActivity` trait? 

Probably something similar like `getDescriptionForEvent`?

**Comment by freekmurze** [comment]
I'd accept a PR that adds this to the package.

**Comment by freekmurze** [comment]
This is possible in version `1.2.0`. Big thank you to @patrickguevara for adding it.
