### ISSUE TITLE
Using Sentinel: What class as default_auth_driver in config?

### ISSUE THREAD

**Issue by sugo23** [spatie/laravel-activitylog#150]
What class do I have to put in my config as `default_auth_driver` in order to use Sentinel's auth system?

I tried a few classes, but I keep getting errors like:

`Auth guard [Sentinel] is not defined.`

**Comment by sebastiandedeyne** [comment]
How is this issue relevant to this package?

**Comment by sugo23** [comment]
I am sorry, if that question was not appropriate in this place. I think that in order to work with sentinel, the code of laravel-activitylog has to be changed.

I eliminated in `ActivityLogger.php` the `$this->auth` property and used instead `Sentinel::getUser();`on 2 places.

Thant works :-)
