### ISSUE TITLE
Modifying Methods of ActivityLogger.php without touching it's code

### ISSUE THREAD

**Issue by sugo23** [spatie/laravel-activitylog#154]
Is it possible to set up my own class that extends ActivityLogger and use it?

I want to add a few things (for example logging IP address in separate database column), but don't want to change the code of the package, so I can still update it.

**Comment by freekmurze** [comment]
Currently there's no way of customizing the `ActivityLogger` itself.

You have two options to add the IP address to a logged item.

1. You can leverage [custom properties](https://docs.spatie.be/laravel-activitylog/v1/basic-usage/logging-activity#setting-custom-properties).

2. You could create an observer on the `Activity` model and let it add the IP address to the row whenever an `Activity` model is created.
