### ISSUE TITLE
Installation issue on Laravel 5.4 and PHP 7

### ISSUE THREAD

**Issue by iqiuye** [spatie/laravel-activitylog#162]
Hi, am having this problem with composer dependencies while trying to install laravel-activitylog.
Here is the error:

$ composer require spatie/laravel-activitylog
Using version ^1.12 for spatie/laravel-activitylog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.9
    - Conclusion: don't install laravel/framework v5.4.9
    - Can only install one of: laravel/framework[v5.4.0, v5.4.9].
    - don't install laravel/framework v5.4.9|remove illuminate/database v5.4.0
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.4.9
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.4.9
    - Installation request for laravel/framework (locked at v5.4.9, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.9].
    - Installation request for illuminate/database (locked at v5.4.0) -> satisfiable by illuminate/database[v5.4.0], laravel/framework[v5.4.0].

**Comment by freekmurze** [comment]
Seems to be working fine here. Could you try to install the package in a vanilla Laravel app to see if that works?

**Comment by andros27** [comment]
help me to solving this 
Problem 1
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].

**Comment by freekmurze** [comment]
Install PHP 7.1
