### ISSUE TITLE
How to get activitylog details joining with other table ?

### ISSUE THREAD

**Issue by kabeda** [spatie/laravel-activitylog#166]
Hi,
In the activity_log table, the ‘causer_id’ is the id of who does the action and the ‘subject_id’ is the id of who get the action. Am I right ?
When I use Activity::all(), I have all the events done on a Model.

But I didn’t find a right SQL request to retrieve the name of the causer and the subject.

With this request :

> select `activity_log`.`id`, `activity_log`.`created_at`, `activity_log`.`log_name`, `activity_log`.`description`, `users`.`name` from `activity_log` inner join `users` on `users`.`id` = `activity_log`.`subject_id` where `log_name` = 'Users'

I get the Users names using the subject_id but I can’t find how to retrieve with only one request also Users names using the causer_id.

Can some body helps ?

**Comment by kabeda** [comment]
Hi,
I must specify that I use [Datatables](https://github.com/yajra/laravel-datatables) in my code I wrote 
 ```
        $activity=Activity::all();
            $datatables = Datatables::of($activity);
            $datatables->editColumn('created_at', function ($activity) {
                return (Carbon::parse($activity->created_at)->format('d/m/Y H:i'));
            });
            $datatables->editColumn('pseudo', function ($activity) {
                return ($activity->causer->pseudo);
            });
            $datatables->editColumn('parent', function ($activity) {
                return ($activity->subject->pseudo);
            });
```
But if I have five lines to read, I get ten SQL requests (the double of lines).
I wonder if it's possible to reduce SQL requests' numbers.

**Comment by sebastiandedeyne** [comment]
Do you still need help on this issue, or has it been resolved?
