### ISSUE TITLE
Is it possible to avoid the automatic mode?

### ISSUE THREAD

**Issue by kabeda** [spatie/laravel-activitylog#167]
Hi,
When I create a new record, I have a new event recorded. That's OK.
I use the same table in my database to save the customers and the admins identified by a boolean field (false admin, true customer). I need to record the attribution of an admin to a client as a special event. But when an admin creates a customer, a simple created event is recorded.
So, there's two options:
1. Stop the auto method, record the special event and restart the auto method?
2. Change the description when using the attribution.

Can anyone guide me?

**Comment by sebastiandedeyne** [comment]
I'd suggest nog using this package's automatic recording, and write your own logic in a `created` method registered in `boot`, or via an Eloquent observer.
