### ISSUE TITLE
Add JWT user on Model activity

### ISSUE THREAD

**Issue by ventouris** [spatie/laravel-activitylog#169]
I have a model called Documents that I want to log the activity. On the Document.php file I have added this code:

```
    protected static $logAttributes = [
        'expired', 
        'published', 
        'title'
    ];
```

If I keep only this, then the causedBy are not included on the logs (I use JWT auth for a REST API). If I add this on my controller during the update of document:

```
        $user = JWTAuth::parseToken()->authenticate();
        activity()
            ->causedBy($user)
            ->performedOn($document)
            ->log('new');
```

I have a new log entry with the causedBy user, but then I don't have the attributes values I added on the Model.

So I ended up with one line with attributes and without user and one line with user but without attributes. Any idea?

**Comment by ventouris** [comment]
Any news on this?

**Comment by freekmurze** [comment]
The tests seem to indicate that this functionality is working properly. So I guess it's caused by something in your specific project.

Did you add the `LogsActivity` trait to your model?

If it keeps failing, try to install the package in a vanilla Laravel application.

**Comment by ventouris** [comment]
Yes. Here is one of my Models. The User.

```
<?php

namespace App;

use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable
{
    use Notifiable;
    use LogsActivity;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected static $logAttributes = [
        'name',
        'email',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Automatically creates hash for the user password.
     *
     * @param  string  $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }
}
```

**Comment by ventouris** [comment]
And here is the UserController

```
<?php

namespace App\Api\V1\Controllers;

use App\User;
use JWTAuth;
use App\Http\Controllers\Controller;
use App\Api\V1\Requests\SignUpRequest;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Spatie\Activitylog\Traits\LogsActivity;


class SignUpController extends Controller
{   
    use LogsActivity;
    
    public function signUp(SignUpRequest $request, JWTAuth $JWTAuth)
    {    
        $user = new User($request->all());
        if(!$user->save()) {
            throw new HttpException(500);
        }

        $currentuser = JWTAuth::parseToken()->authenticate();
        activity()
            ->causedBy($currentuser)
            ->performedOn($user)
            ->log('new');
        
        if(!env('SIGN_UP_RELEASE_TOKEN')) {
            return response()->json([
                'status' => 'ok'
            ], 201);
        }

        $token = $JWTAuth->fromUser($user);
        return response()->json([
            'status' => 'ok',
            'token' => $token
        ], 201);
    }
}
```

**Comment by freekmurze** [comment]
The `LogsActivity` trait will only log the attributes if your user model is changing. Could you try to update a property on your model and save it and check if something gets logged?

**Comment by ventouris** [comment]
I don't have an update action on User model. Just create and delete. But I have the same code in other models. Here are the DB records for that model:

```
16,default,updated,45,App\Conteststatus,NULL,NULL,"{""attributes"":....long json....},""old"":...long. json...}",2017-04-19 22:01:05,2017-04-19 22:01:05

17,default,update,45,App\Conteststatus,31,App\User,[],2017-04-19 22:01:06,2017-04-19 22:01:06
```

**Comment by freekmurze** [comment]
Going back to the original question

```
        activity()
            ->causedBy($user)
            ->performedOn($document)
            ->log('new');
```

That piece of code won't log the attributes. Only if you create, update or delete a model where the `LogsActivity` trait is applied upon will attributes be logged. You can see some examples in the tests of this package.

If this keeps failing in your project, try to install the package in a vanilla Laravel app. If you discovery an error in the package, submit a failing test for us to look at.
