### ISSUE TITLE
Bulk insert of a model doesn't trigger the activity logger

### ISSUE THREAD

**Issue by ventouris** [spatie/laravel-activitylog#170]
I have a model with those logAttributes:

```
protected static $logAttributes = [
        'id',
        'product_id',
        'supplier_id',
        'quantity',
        'type'
    ];
```
When I want to bulk insert an array of those models like this:

`Sample::insert(json_decode($samples, true));`

The activity doesn't trigger and nothing is logged on the database.

**Comment by theatrain** [comment]
Shouldn't you be using Sample::createMany() and not insert? I don't recognise insert as an eloquent method.

**Comment by freekmurze** [comment]
To create a a model use the static `create` method. I don't recognize `insert` either.

**Comment by ranusu** [comment]
is this solved or there any way to solve batch insert ?
