### ISSUE TITLE
Exception while dirty check

### ISSUE THREAD

**Issue by krembo** [spatie/laravel-activitylog#185]
Hey guys, I'm trying to use the latest version of activitylog which is 1.15.0, I believe.
And it fails on both create and update (both with `$logOnlyDirty ` set to `false` or `true`) with the next exception:
```
ErrorException in DetectsChanges.php line 79:
Object of class Illuminate\Support\Collection could not be converted to int
```

**Comment by freekmurze** [comment]
I've just tagged release `1.15.1` that should fix this.

**Comment by krembo** [comment]
That was fast! Thanks. No exceptions now.
But somehow this log-only-dirty option doesn't work for me... It always logs the whole list of parameters.

**Comment by krembo** [comment]
Found the problem. The `$logOnlyDirty` should be used as _protected static_ attribute.
I was using it as _protected_ only. 
Please, update docs for that part, because it is used there also without _static_.
Thank you for a great work!

**Comment by freekmurze** [comment]
Could you send a PR to our docs? There's an edit button on to of every page. 👍

**Comment by krembo** [comment]
Just did that )
