### ISSUE TITLE
Is there an example of a nice implementation of displaying activity on the front end?

### ISSUE THREAD

**Issue by sunscreem** [spatie/laravel-activitylog#186]
Specifically I need to set some accessors on the activity model before I pass this data to Vue, and I wondered if anyone has already done such a thing?

**Comment by freekmurze** [comment]
Don't have a specific example but you could choose to use [laravel-fractal](https://github.com/spatie/laravel-fractal) to transform the models to something you can consume via Vue.

**Comment by sunscreem** [comment]
Thanks Freek. I've been looking for an excuse to play with fractal! :)
