### ISSUE TITLE
Doesn't Support lower version of php

### ISSUE THREAD

**Issue by Yethroy** [spatie/laravel-activitylog#188]
I tried to install it and it fails.
[InvalidArgumentException]                                                                          
  Could not find package spatie/laravel-activitylog at any version matching your PHP version 5.5.9.0

**Comment by sebastiandedeyne** [comment]
This package only supports PHP7+

You could try using the old package, but note that we don't provide support on it anymore.

https://github.com/spatie/activitylog/blob/master/composer.json
