### ISSUE TITLE
Eloquent events not registered (static::$dispatcher not set = null)

### ISSUE THREAD

**Issue by eightyfive** [spatie/laravel-activitylog#189]
Hi,

I'm having trouble registering events on my Model in `bootLogsActivity` method.

When `bootLogsActivity` is called, the `Eloquent\Model::$dispatcher` is not yet set:
https://github.com/illuminate/database/blob/v5.3.23/Eloquent/Model.php#L1273

I also confirmed that the `prepare` connection method is **not** being called before `bootLogsActivity` method:
https://github.com/illuminate/database/blob/v5.3.23/DatabaseManager.php#L190

I'm quite sure this has little to do with `laravel-activitylog` but I was wondering if you could give me a hand, I'm out of ideas...

**Comment by freekmurze** [comment]
Hi, like you already suspected this is more a question for a general Laravel community forum such as the Laracast Forum. Try asking that question there. Good luck!

**Comment by eightyfive** [comment]
Yes indeed. Had to do with my own App lifecycle.

For further reference and even if not related:
https://laracasts.com/discuss/channels/eloquent/eloquent-events-being-not-registered-staticdispatcher-not-set-null

Thanks.
