### ISSUE TITLE
Not logging changed value when logOnlyDirty = true

### ISSUE THREAD

**Issue by jcxm360** [spatie/laravel-activitylog#190]
LogOnlyDirty logs when a changed value = 1, but not when a changed value = 0. Instead it return empty arrays

Value = 1: {"attributes":{"active":1},"old":{"active":0}} 
vs 
Value = 0: {"attributes":[],"old":[]}

It does this also when value is changed to empty. 

It does log successfully when the related attribute is the only one listed in $logAttributes but if other attributes are listed then it fails to log.

**Comment by freekmurze** [comment]
Would you mind PR'ing a failing test?

**Comment by nealyip** [comment]
I also found that problem which occurs in 

spatie/laravel-activitylog/src/Traits/DetectsChanges.php

$properties = array (
  'attributes' => 
  array (
    'name' => 'David',
    'email' => 'test@gmail.com',
    'tel' => '123456789',
    'boolean_a' => 0,
    'boolean_b' => 1,
  ),
  'old' => 
  array (
    'name' => 'David',
    'email' => 'test@gmail.com',
    'tel' => '123456789',
    'boolean_a' => 1,
    'boolean_b' => 0,
  ),
);
var_dump(array_udiff($properties['attributes'],$properties['old'],
    function ($new, $old) {
        return $new <=> $old;
    }
));

**Comment by jcxm360** [comment]
Sorry I'm not sure how to PR a failing test. What about nealyip's fix he pushed to nealyip/laravel-activitylog, is that a fix for this?

**Comment by maximebeaudoin** [comment]
I also think `array_udiff_assoc` is better way to computes the difference of arrays with additional index check.

See http://php.net/manual/en/function.array-udiff-assoc.php

**Comment by gendalfbug** [comment]
please  check,  before 
`
       if ($this->shouldlogOnlyDirty() && isset($properties['old'])) {
            $attributesNew = array_diff_assoc($properties['attributes'], $properties['old'] );
            $attributesOld = array_diff_assoc($properties['old'], $properties['attributes']  );
            $properties = ['attributes' => $attributesNew, 'old' => $attributesOld];
        }
`
after

`           if ($this->shouldlogOnlyDirty() && isset($properties['old'])) {
            $attributesNew = array_diff_assoc($properties['attributes'], $properties['old'] );
            $attributesOld = array_diff_assoc($properties['old'], $properties['attributes']  );
            $properties = ['attributes' => $attributesNew, 'old' => $attributesOld];
        }
`

**Comment by freekmurze** [comment]
This is fixed in the latest release.

**Comment by andersLAL** [comment]
nealyip's fix does not work for my case, unfortunately, where values are changed to null. This triggers a database update and therefore I would expect them to be logged also, but they are not. Instead, only the updated_at timestamp is logged, despite that being in the ignored attributes list. gendalfbug's fix seems to work for that case.

**Comment by fotonmoton** [comment]
sorry for necroposting, but I have same bug. If I comment out `$protected $logOnlyDirty = true` 
all attributes comes into log, But when I am unccoment `$protected $logOnlyDirty = true`  one property doesn't logs and I have also two empty arrays.

`
Laravel: 5.5.40
laravel-activitylog: 2.5.1
`
