### ISSUE TITLE
Description character length

### ISSUE THREAD

**Issue by PunchRockgroin** [spatie/laravel-activitylog#191]
Howdy! Thanks for this package first off.

My issue and/or feature request is either to add a message in the docs about the log "description" length being limited to the VARCHAR limit (255), or change the description column to text in the migration. 

I've run into SQL errors when using placeholders in the log descriptions, particularly when it comes to using HTML in the content and urls as placeholders, because the character length of the field can then become greater than 255.

Thanks again!

**Comment by freekmurze** [comment]
Sure, send a PR to our docs. (There's an `edit` button on the top of every page.)
