### ISSUE TITLE
Undefined variable: anEloquentModel

### ISSUE THREAD

**Issue by ds-manish** [spatie/laravel-activitylog#192]
**ERROR**
```
Undefined variable: anEloquentModel
```

From where we can define variable `$anEloquentModel`.
As per the documentation on
`https://github.com/spatie/docs.spatie.be/blob/master/resources/views/laravel-activitylog/v1/basic-usage/logging-activity.md`
```
activity()
   ->causedBy($userModel)
   ->performedOn($someContentModel)
   ->log('edited');
```
 from where `$userModel` and `$someContentModel` variables are defined.

**CODE**
```
activity()
            ->performedOn($anEloquentModel)
            ->causedBy(Auth::user())
            ->withProperties(['customProperty' => 'customValue'])
            ->log('Look, I logged something');
```

**Comment by sebastiandedeyne** [comment]
`$anEloquentModel` is the model instance that the logged activity applies to.

For example, if a user edited a blog post in the application, you'd pass your post instance to `performedOn`.

```php
$post = Post::find(1);

$post->title = 'New title';

$post->save();

activity()
    ->performedOn($post)
    ->causedBy(Auth::user())
    ->log('edited');
```

If the activity has nothing to do with any other models, you can skip `performedOn`.

```php
$user = Auth::user();

$user->logout();

activity()
    ->causedBy($user)
    ->log('loggedOut');
```

**Comment by ds-manish** [comment]
will this `->performedOn($post)`
add to `subject_id` and `subject_type` in `activity_log` table?

what data will be posted to `subject_id` and `subject_type` in `activity_log` table with following code??
```
$post = Post::find(1);

$post->title = 'New title';

$post->save();

activity()
    ->performedOn($post)
    ->causedBy(Auth::user())
    ->log('edited');
```

**Comment by ds-manish** [comment]
do you have any full example for it??

**Comment by ds-manish** [comment]
how to get activity by id??

**Comment by freekmurze** [comment]
```
Spatie\Activitylog\Models\Activity::find($activityId);
```

**Comment by sujalpatel022** [comment]
My User is in different local App/Model/User. How to use in causedBy() function with custom model location
