### ISSUE TITLE
Query all changes by particular user

### ISSUE THREAD

**Issue by Lawrence-Dawson** [spatie/laravel-activitylog#193]
How would I go about finding all changes made by a particular user? And also all changes made by a particular user to a specific model.

I'm able to follow the documentation well when it comes to logging custom changes and changes to models. I'm just struggling when it comes to causer specific queries.

Any help would be greatly appreciated,

Lawrence

**Comment by freekmurze** [comment]
> How would I go about finding all changes made by a particular user 

```php
$allActivity = User::find()->activity;
```

> How would I go about finding all changes made by a particular user 
```php
$allActivity = User::find()->activity->filter(Spatie\Activitylog\Models\Activity $activity) {
   return $activity->subject_type === $modelClassName && $activity->subject-Id === $modelId
};
```

That last one will load up all activity. Pretty sure there has to be a way to do the filtering in the query itself but don't know how to do that by heart.

**Comment by Lawrence-Dawson** [comment]
Brilliant stuff! Thank you!
