### ISSUE TITLE
Can't generator migration on Laravel 5.4

### ISSUE THREAD

**Issue by kenzouno1** [spatie/laravel-activitylog#203]
I'm put this to `config/app.php` and run command 

`php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"`

In console view return messsage `Publishing complete` and i run `php artisan migrate`  but nothing happens.

**Comment by kjdion84** [comment]
try doing `php artisan migrate:refresh`

**Comment by freekmurze** [comment]
Try clearing your config cache and try again.
