### ISSUE TITLE
laravel 4.2 custom log names

### ISSUE THREAD

**Issue by NestorAcevedo** [spatie/laravel-activitylog#204]
Hi, I am reading the documentation. What I need is some like [https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/using-multiple-logs](url) but on Laravel 4.2

Seeing the table structure seems not to have any log_name field so I think above documentation applies only for Laravel >= 5

How could I to log separated Logs?

Regards

**Comment by freekmurze** [comment]
All our packages are Laravel 5 only. To us Laravel 4 is 💀 . We are not going to bother with backporting stuff. Of course you're free to use our code to backport to L4 yourself.
