### ISSUE TITLE
Activity is not logged when updating a collection (rather than an individual element)

### ISSUE THREAD

**Issue by isaiahgrant** [spatie/laravel-activitylog#206]
To whom it may concern,

Maybe intended behavior, but just something I came across.

For example:

public function onSubmit(Request $request) {
    $modelData = ['attr' => $request->my_attr];
    //This works
    MyModel::where("id", $request->model_id)->firstOrFail()->update($modelData);
    //This does not
    //MyModel::where("id", $request->model_id)->firstOrFail()->update($modelData);
}

Note: The update in the database does execute as intended.

**Comment by freekmurze** [comment]
The line under `this works` is exactly the same as `this does not`

But I suspect that you found out that when updating several models at once using a query does not log activity (wheres updating a single model does work).

We'll this is normal. Eloquent will only send out events (that the package picks up on) when updating a single model.

**Comment by isaiahgrant** [comment]
Apologies for the misleading information (thank you copy/paste!). I am glad you were able to diagnose what I was getting at though, where(...)->update(...) (without the firstOrFail()).

Thank you for the rapid response.

Best
