### ISSUE TITLE
Can i use this on Multi Auth ?

### ISSUE THREAD

**Issue by codeitlikemiley** [spatie/laravel-activitylog#208]
let say i have 3 Model that Uses 3 Different Auth Guard 

set in config/auth.php

one for web(default user) , admin , employee...

Do i Need to Do Set Up Anything to Make it Work For Multi Auth?

**Comment by freekmurze** [comment]
see #333

**Comment by freekmurze** [comment]
I don't think so, it'll just work.

**Comment by codeitlikemiley** [comment]
Hi Freek After Testing Out Using 3 Different Auth....

This Would NOT Work on the Fly If You Use 3 Different Auth

IT Always Uses The Default Driver which is 'web'

the only work around on this is if i edit your 

public function __construct

this line on ActivityLogger.php
```
else {
            $this->causedBy = $auth->guard($this->authDriver)->user(); // replace this line
        }
```
replace with
```php
$guards = collect(config('auth.guards'))->keys()->all();
foreach ($guards as $guard) {
           if(auth()->guard($guard)->check()){
            $this->causedBy = auth()->guard($guard)->user();
            break;
           }
        }
```

**Comment by codeitlikemiley** [comment]
Basically I fetch all the Guards I Created On auth.php ...

then Loop on the guards to check what guard has a Login User

If there is a login User then that will be set as $this->causeBy value...

Hope you can Merge this piece of code... i made ...

thanks

**Comment by freekmurze** [comment]
Coul you create a PR for this, with tests to prove that there is a problem and this is a right fix?
