### ISSUE TITLE
What if have already used Activity for another class/facade?

### ISSUE THREAD

**Issue by peacerevolution** [spatie/laravel-activitylog#21]
Hello!

Thank you for this wonderful logging framework. I'm planning to deploy it on my system but I find that it is going to cause a conflict since the Facade "Activity" has been used for another class. Is it possible to configure it?

**Comment by sebastiandedeyne** [comment]
The facade is optional, you're not required to register it to use the package.

You could either write your own facade, or resolve the activity log through dependency injection or the app helper:

```php
app('laravel-activitylog');
// or...
app(Spatie\Activitylog\Activitylogger::class);
```

Alternatively, you can actually register the facade under whatever name you want in `config/app.php`:

```php
'aliases' => [
    // ...
    'OtherName' => Spatie\Activitylog\ActivitylogFacade::class,
],
```
