### ISSUE TITLE
Search by properties??

### ISSUE THREAD

**Issue by Albvadi** [spatie/laravel-activitylog#210]
Hi,
thanks for this super usefull package!

It´s possible search by a extra property??
For example:
```php
activity()->withProperties(['special_code' => 123456])->log(':causer.username modify something...');
```
And now, get all logs with the same code, something like:
```php
Activity::whereProperty('special_code', 123456)-get();
```

Thanks again!

**Comment by freekmurze** [comment]
The extra properties are stored as json. So you could just use the Eloquent query builder for that: https://laravel.com/docs/5.4/queries#json-where-clauses
