### ISSUE TITLE
Log related model

### ISSUE THREAD

**Issue by thavorac** [spatie/laravel-activitylog#214]
Consider there is a model Post, Comment and User. How can i retrieve "User A comment B on post C" without writing the logic in controller? 

I want to use event logging only but as far as i understand, we can only log each model separately.
This is what i get on model Comment:
```
[
   'attributes' => [
        'text' => 'Lorum',
        'post' => 112
    ]
];
```

but instead, i want to see it like this:

```
[
   'attributes' => [
        'text' => 'Lorum',
        'post' => [
             'id' => 112,
             'title' => 'Post A'
        ]
    ]
];
```
I know i can use "post.title" but  i need to get its full detail. Is there anyway to do this?

**Comment by freekmurze** [comment]
> i need to get its full detail

By full detail, you mean other attributes for `post`?

**Comment by thavorac** [comment]
yes, i mean other attributes for post.

**Comment by freekmurze** [comment]
There really no way to automatically get all the attributes of a model. If you need more attributes of `Post` to be logged you need to specify that manually.
