### ISSUE TITLE
Conflict between LogsActivity & CausesActivity when used together

### ISSUE THREAD

**Issue by Omranic** [spatie/laravel-activitylog#215]
### Scenario
**User** model is a causer, and at the same time it's being logged for any changes, which means we've to use both `LogsActivity` & `CausesActivity` traits, right? In such case conflict happens since both traits has the a method with the same signature:

```php
public function activity(): MorphMany
```

Any thoughts?

**Comment by freekmurze** [comment]
I think we can't fix this without making breaking changes. I'll take care of this when creating a new major version.

**Comment by denitsa-cm** [comment]
@freekmurze Is there any updates on this?

**Comment by Gummibeer** [comment]
In addition to the conflict the method name isn't 100% correct. It's a `morphMany()` relation but the name is singular.

* `CausesActivity::activity()` == `HasActivity::actions()`
* `LogsActivity::activity()`

**Comment by freekmurze** [comment]
This is addressed in the v5 branch (#1452). We've renamed the conflicting methods:

- `LogsActivity::activities()` becomes `activitiesAsSubject()`
- `CausesActivity::actions()` becomes `activitiesAsCauser()`

There's also a new `HasActivity` trait that combines both and provides `activities()` as a convenience alias.

Would love feedback on the naming.
