### ISSUE TITLE
What would be the best way to log logins and logouts?

### ISSUE THREAD

**Issue by Gino** [spatie/laravel-activitylog#218]
Hello,

I just installed your package but I am wondering, what would be the best way to log logins and logouts?

Thank you.

Kind regards,
Gino

**Comment by sebastiandedeyne** [comment]
Depending on your application, I'd suggest the options:

- If users can log in or out from multiple places, fire an event when the y log in or out, and register an event listener that logs activity.
- If it's a more simple app, loggin the activity in the auth controllers should suffice (if you're using Laravel's default auth scaffolding, you might need to override some methods)
