### ISSUE TITLE
MorphMap vs. CausedBy scope

### ISSUE THREAD

**Issue by kicco** [spatie/laravel-activitylog#219]
Hi! 
I noticed there's a problem when you use polymorphic `MorphMap` in your Providers. So basically if you

```
 Relation::morphMap([
            'user' => 'YourApp\User',
])
```
and then you 
```
Activity::inLog('login')->causedBy(YourApp\User::find(289))->all
```

Then you're in for a bad time, because what gets stored in the activity_log table would be `user` instead of the actual class name, as seen on the `Activity@scopeCausedBy`. 
To solve this I think it would be enough to just consult `MorphTo::morphMap` and use that specific key if present. This also applies to other instances where the same mapping might occur (ForSubject scope, namely).

Thanks for your time and libs, I hope this helps a little.

**Comment by freekmurze** [comment]
Hi,

I'd accept a PR with tests that fixes any problems revolving around this issue.
