### ISSUE TITLE
[doubt] Override implications

### ISSUE THREAD

**Issue by michelecurletta** [spatie/laravel-activitylog#22]
Does the updating static method override implementation below, cause the inability to attach other logic to the updating event of the model (from outside the trait, e.g. from another module)?
```
 static::updating(function (Model $model) {
                //temporary hold the original attributes on the model
                //as we'll need these in the updating event
                $oldValues = $model->replicate()->setRawAttributes($model->getOriginal());
                $model->oldAttributes = static::logChanges($oldValues);
            });
```
[It is](https://laravel.com/docs/5.2/eloquent#events) a better way to do that, isn't it?
What do you think about?

**Comment by freekmurze** [comment]
I'm thing that if you add another `static::updating` in your model both your and the packages function will be executed. Try it out to know for sure.
