### ISSUE TITLE
I want to get Post owner by user_id

### ISSUE THREAD

**Issue by baqirfarooq** [spatie/laravel-activitylog#220]
Retrive all post with owner from activity table by User how this is possible whats relation i create in Post Model

**Comment by baqirfarooq** [comment]
In activity table i have user_id, loggable_type, loggable_id 
Every Post Create with Log of user which create i want to show post with user in Post Lop

**Comment by freekmurze** [comment]
I'm not sure I understand your question right, but I'm thinking it isn't a good idea to manage post ownership via the activity log.
