### ISSUE TITLE
Disable on demand

### ISSUE THREAD

**Issue by damosse31** [spatie/laravel-activitylog#225]
Hi !

is it possible to disable logging on demand with something like that :

`User::withoutActivityLog->update($request->all());`

It will be useful for example if I have somes scheduled tasks that edit somes fields in user and I don't want to log theses changes in activity_log.

Regards.

**Comment by freekmurze** [comment]
I assume your logging model changes. You can only specify on which events you want that. There's currently no other way of disabling/enabling that on the fly.

https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#customizing-the-events-being-logged

**Comment by freekmurze** [comment]
This feature may be coming to the package soon 😄 

https://twitter.com/LasseRafn/status/891741979322843136

**Comment by LasseRafn** [comment]
PR: #226

**Comment by Quix0r** [comment]
Hi, what is the minimum version of Laravel to be compatible with this change? I have 5.3 here (to old, I know).
