### ISSUE TITLE
Add column to activity_log table

### ISSUE THREAD

**Issue by Matienzo** [spatie/laravel-activitylog#227]
Hi, Is it possible to add a column in the `activity_log` table?
Something like `related_model_id`. And in that case how should be included in the method `Activity::log()`

Greetings from Ushuaia, Tierra del fuego

**Comment by freekmurze** [comment]
You can manually add a column to the migration (or create a new migration that adds a column to `activity_log`.

If needed you can also specify a custom model in `activity_model` key in the config file.
