### ISSUE TITLE
Call to undefined function activity()

### ISSUE THREAD

**Issue by Matienzo** [spatie/laravel-activitylog#228]
Hi. 
I'm having this error when I call the `activity()` function. I followed the package instructions.
The only way I can save an activity is by the `Activity` Facade  `Activity::log()`

**Comment by freekmurze** [comment]
This is the line in `composer.json` that makes sure the helpers file contains the `activity` function gets loaded: https://github.com/spatie/laravel-activitylog/blob/master/composer.json#L45

Have you tried dumping the autoloader?

**Comment by Furqanaa** [comment]
@freekmurze, I'm having the same problem and I don't see that line into my composer.json, I'm using ``` "spatie/laravel-activitylog": "3.2.2"```
What should I do?

**Comment by Gummibeer** [comment]
@Furqanaa the mentioned line doesn't have to be in your `composer.json` but in the one of this package.
You could try a `composer dump-autoload`.
