### ISSUE TITLE
->by(null) throws exception

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-activitylog#230]
Is there a way to pass `null` in the `by()` method? Or what is the workaround for this?

For example, I saw the constructor attempts to use the current auth user automatically. However, there are certain activities which I am logging that are done by the "system", therefore the currently logged in user should not be attributed to them.

Please advise.

**Comment by kjdion84** [comment]
```
Activity::create([
    'log_name' => 'default',
    'description' => 'Created Assignment',
    'subject_id' => $assignment->id,
    'subject_type' => 'App\Assignment',
    'properties' => collect($assignment),
]);
```

Meh.

**Comment by freekmurze** [comment]
I'm going to keep the current behaviour for `by` as for most people this just works ok. I think it's good that it's blows up when `null` is passed.

The `ActivityLogger` is macroable. So you can your own methods to it. You could add a method named `possiblyBy` (or something better)` that returns the instance when `null` is passed to it or calls `by` when a model or model id is being passed to it.
