### ISSUE TITLE
[laravel-55] Activity::getChangesAttribute() and Eloquent\Model::$changes conflicts?

### ISSUE THREAD

**Issue by mattdfloyd** [spatie/laravel-activitylog#233]
https://github.com/spatie/laravel-activitylog/blob/master/src/Models/Activity.php#L46
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L36

This may simply be a problem with my implementation of a custom activity model and not an issue that needs to be addressed. But I thought I'd pose it anyways.

Given:
```php
class CustomActivityModel extends Activity
{
    function getCustomPropertyAttribute(): Collection
    {
        return $this->changes;
    }
}
```

Previous behavior would reach to the `getChangesAttribute()` mutator. With change detection implemented on `Illuminate\Database\Eloquent\Model` in Laravel 5.5, `(new CustomActivityModel)->custom_property` will attempt to return the inherited instance variable from `Model` rather than the mutated attribute from `Activity`.

Possible solutions:
- Rename `getChangesAttribute()` to `getSubjectChangesAttribute()`
- Rename `getChangesAttribute()` to `changes()`
- Don't access mutated attributes from child classes; instead use `$this->getAttribute('changes')`

**Comment by freekmurze** [comment]
The tests on the `laravel-55` seem to continue to pass. Could you PR a failing test and/or fix?
