### ISSUE TITLE
Recursively check traits or clarify docs on SoftDeletes and restored event

### ISSUE THREAD

**Issue by curtisblackwell** [spatie/laravel-activitylog#234]
I tried `use SoftDeletes` on a trait that also has `use LogsActivity`, which I use on a couple models. It confused me when restored events were not logged.

I tracked it down to the `eventsToBeRecorded()` method in `LogsActivity.php` where I saw this code:

```php
if (collect(class_uses(__CLASS__))->contains(SoftDeletes::class)) {
    $events->push('restored');
}
```

…so I tried `dd(class_uses(__CLASS__))` and realized it doesn't check traits within traits. I think it would be helpful to either recursively check traits or state more clearly in the docs that we need to `use SoftDeletes` directly on the models we're logging.

I'm happy to submit a PR either way. What do you think?

**Comment by freekmurze** [comment]
I've tagged a new version `1.15.4` that should fixes this. Reopen if the problem should persist.

**Comment by curtisblackwell** [comment]
Ah, nice. I wasn't aware of that helper. This worked, thanks!
