### ISSUE TITLE
Mass Update not logging

### ISSUE THREAD

**Issue by joecme** [spatie/laravel-activitylog#240]
I noticed there was mention of this, but someone marked it as solved.  I'm still having an issue, or is this something that is not possible at this time?

Model::where('user_id', $oldID)->update(['user_id' => $newID]);

This does not trigger any logging activity.  I haven't tried deleting yet.

**Comment by sebastiandedeyne** [comment]
That's because when you use `update` it uses Laravel's query builder. The logger can only listen to events sent out by Eloquent models.

If you want to use Eloquent instead, you'll have to retrieve the models, and update them in some sort of loop one by one.
