### ISSUE TITLE
Automatic logging for CRUD operations doesn't work on models ( without specifying trait )

### ISSUE THREAD

**Issue by shaklev** [spatie/laravel-activitylog#241]
I've followed the setup guide for the project ( https://docs.spatie.be/laravel-activitylog/v1/installation-and-setup ) , after setting up the package , it couldn't automatically log  ( create ,update , delete ) operations on models .
I've added the `LogActivity ( Spatie\Activitylog\Traits\LogsActivity )` trait to my `User` model & now I can log   ( create , update ,delete ) on the `User` model.

If this is the practice , i think it should be included in the README.md file, or maybe i'm just making a mistake in the setup of the package.

**Comment by freekmurze** [comment]
This is explained in the "Logging Model Events" section of the docs

https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events
