### ISSUE TITLE
->withProperties BadMethodCallException 

### ISSUE THREAD

**Issue by jamesmills** [spatie/laravel-activitylog#243]
The activity logger is working fine but when I try and send some properties with the activity I am receiving an error

`
activity()->performedOn($order)
            ->log('Deactivating delivery')
            ->withProperties(['customProperty' => 'customValue']);
`

I am getting 

`
local.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::withProperties()
`

Using package version 1.15.5 
Laravel Framework version 5.2.45

**Comment by freekmurze** [comment]
Try this:

```
activity()
->performedOn($order) 
->withProperties(['customProperty' => 'customValue']);
->log('Deactivating delivery')
```

**Comment by jamesmills** [comment]
Perfect, sorry I should have spotted that. Thanks.

**Comment by ddavaham** [comment]
I know this is rather old, but I fell for this as well, more so because the number of properties I am storing is quite large so I just put the longest line at the bottom of the stack. Maybe add some sort of bullet point in the documentation dictating that the order the methods are called matters.
