### ISSUE TITLE
Laravel 5.5 release

### ISSUE THREAD

**Issue by lasselehtinen** [spatie/laravel-activitylog#249]
I've noticed that there is a laravel55 branch, but there is still some work to be done. Like composer references to 5.5 dev-branch and so on. Is there some plans to finish it?

I can also contribute to the branch if necessary, just let me know what needs to be done.

**Comment by freekmurze** [comment]
Meanwhile `v2.0` of this package, which is compatible with Laravel 5.5, has been released: https://github.com/spatie/laravel-activitylog/blob/2.0.0/composer.json

**Comment by lasselehtinen** [comment]
Awesome, thanks! I will try it out tomorrow.
