### ISSUE TITLE
Log read/fetch events

### ISSUE THREAD

**Issue by Roemerb** [spatie/laravel-activitylog#254]
Hi guys,

Thanks for the great work. I'm using this library for a project for the Netherlands government and they'd like to log when data is accessed. I was wondering if it' possible to log this activity too somehow, like when a model is fetched from the database. If this is not currently an option,  does anyone know if this would be possible to implement at all? Like, is there any way it's possible to detect when a model is fetched (i.e. an Event)?

Thanks in advance! We'll definitely send a postcard to Belgium when we're done!

**Comment by freekmurze** [comment]
I don't think there are events for that. I don't know how your app is structured, but if you use repositories (= more or less just a dedicated class that's responsible for fetching / saving data) you could do the logging there. 

You could opt to even use the decorator pattern. But it all depends on how your app is built.

Here's a lesson on repositories and decorators on Laracasts: https://laracasts.com/lessons/decorating-repositories

Looking forward to that postcard!
