### ISSUE TITLE
Eloquent Relationship to Models

### ISSUE THREAD

**Issue by Bronco84** [spatie/laravel-activitylog#255]
I was wondering if it's possible to access the Activity Model via eloquent relationship. 
For example, storing this method on an example Account Model...

```
public function Activity()
{
    return $this->hasMany('Spatie\Activitylog\Models\Activity', 'account_id', 'subject_id');
}
```

Would allow you to call...

```
 \App\Account::find(id)->with('actvity.users')->get()
```

And receive the activity log for that account. In this case I joined the users for referencing usernames instead of ids for displaying on the view.

I'm learning the ins and outs of laravel, so I'm sure this is just a limitation of my knowledge and may not be possible, but at least wanted to run it by you guys.

Thanks!

**Comment by freekmurze** [comment]
You can already get to the related activity of an model via

`$yourModel->activity`

https://github.com/spatie/laravel-activitylog/blob/87113d180cdb490860b90705bb6c7dbdfde7f34d/src/Traits/CausesActivity.php#L12
