### ISSUE TITLE
Fuzzy Search For Causer?

### ISSUE THREAD

**Issue by ChristopherCarranza** [spatie/laravel-activitylog#256]
This may be because i'm not as well versed with Laravel and Eloquent as i could be, but is there a way to do a fuzzy search on the `causer`? More specifically the causer name.  I'm trying to implement a [DataTables](https://yajrabox.com/docs/laravel-datatables/master) style page for displaying my logs where they are able to just start typing in a user they'd like to find logs for.

<img width="1018" alt="screen shot 2017-09-02 at 10 51 21 am" src="https://user-images.githubusercontent.com/23194412/29996962-f15f2bf6-8fcd-11e7-8841-41edeef80c9d.png">
.

**Comment by AlexVanderbist** [comment]
Consider the following endpoint for your fuzzy search API call:
```
public function fuzzySearch(string $searchQuery)
{
    return Activity::with(['causer' => function ($query) use ($searchQuery) {
        $query->where('name', 'like', "%{$searchQuery}%");
    }])->get();
}
```
This will load all activity including the causers that have a name that includes the fuzzy search query.
