### ISSUE TITLE
Reviewing log data

### ISSUE THREAD

**Issue by securit** [spatie/laravel-activitylog#257]
laravel-activitylog records the id of the user making the change and the id of the user that has changed the record.  The model does not associate this with the user... ie there is no relationship in the model.

Is this the perfect excuse for using one of the new Laravel 5.5 resources?

**Comment by freekmurze** [comment]
> laravel-activitylog records the id of the user making the change and the id of the user that has changed the record. The model does not associate this with the user... ie there is no relationship in the model.

I'm thinking this should work. Can you PR a failing test?
