### ISSUE TITLE
Parse error expecting '{' in

### ISSUE THREAD

**Issue by stijnvanouplines** [spatie/laravel-activitylog#26]
Hi there,

I'm getting this error message when I do `php artisan config:clear`:

`Parse error: parse error, expecting '{' in /Users/stijn/www/Sites/inventory/vendor/spatie/laravel-activitylog/src/helpers.php on line 6`

Does anyone know what's wrong?

Thanks,
Stijn

**Comment by freekmurze** [comment]
Not sure, what could be causing this. Are you using the latest version of this package and PHP 7?

**Comment by kohenkatz** [comment]
This is almost definitely caused by not running on PHP 7.

**Comment by stijnvanouplines** [comment]
PHP 7 was the problem. I updated my OSX PHP from version 5 to 7.

Thanks!

**Comment by franciscocorrales** [comment]
I get this error, and I have PHP 7.

```
$ php --version
PHP 7.0.11-2+deb.sury.org~trusty+2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11-2+deb.sury.org~trusty+2, Copyright (c) 1999-2016, by Zend Technologies
```
