### ISSUE TITLE
Activity::changes must return a relationship instance

### ISSUE THREAD

**Issue by fabiolrs** [spatie/laravel-activitylog#264]
Hi,

I've just updated from version 1 to the latest.

I used to show users the changes they had made using this:

`{{ json_encode($activity->changes, JSON_PRETTY_PRINT) }}`

Now, when doing that, I am getting this:

`Spatie\Activitylog\Models\Activity::changes must return a relationship instance. (View: /home/vagrant/*****/log/view.blade.php)`

Any help is appreciated.

**Comment by freekmurze** [comment]
Try this: `{{ json_encode($activity->changes(), JSON_PRETTY_PRINT) }}`

**Comment by brunonetadmin** [comment]
Hi, i´m facing a similar problem, $activity->changes returns this error, but $activity->changes() returns nothing.

**Comment by dramosv90** [comment]
Hi, i'm having the same issue, $activity->changes() returns empty array. I'm using 2.3 version.

**Comment by denitsa-cm** [comment]
Same error here `Spatie\Activitylog\Models\Activity::changes must return a relationship instance.`.

**Comment by freekmurze** [comment]
@denitsa-cm you're probably on v1 of the package.

**Comment by denitsa-cm** [comment]
@freekmurze I'm on 

```
            "name": "spatie/laravel-activitylog",
            "version": "2.4.1",
```

`$activity->changes()` returns the collection for me, instead of just `$activity->changes`

**Comment by freekmurze** [comment]
Currently it is set up so `changes` is a function, not a property that returns a collection with changes.

I might revise this in a future major version.
