### ISSUE TITLE
Subject type set to table name instead of model

### ISSUE THREAD

**Issue by sander-tjuna** [spatie/laravel-activitylog#265]
When using the activity logger on my 'Article' model I get the table name as subject instead of the Model. I tried changing the name of the model and this worked. Also changing the namespace of the model worked for me. 

How come it doesn't work when the namespace is App\Article ?

**Comment by freekmurze** [comment]
Could you give us some code that is failing for you?

**Comment by sander-tjuna** [comment]
@freekmurze I'm using the trait on my model, just as I use it on all my other models. So I can't really provide code.

**Comment by freekmurze** [comment]
Can you PR a failing test?

**Comment by bbashy** [comment]
@sander-tjuna Have you made your own morphMap for that Article model maybe?

**Comment by GioChocolateBro** [comment]
@bbashy thanks! this was the culprit other developer had left this behind in the appserviceprovider (the morphmap). It was doing nothing. Thanks for pointing me (us @sander-tjuna) there!

**Comment by bbashy** [comment]
@GioChocolateBro Good to hear. It did sound like that was the problem :)

**Comment by freekmurze** [comment]
👍
