### ISSUE TITLE
Using forceDelete on a Model throws an error ...::logChanges() must be an instance of Illuminate\Database\Eloquent\Model, null given

### ISSUE THREAD

**Issue by bte2** [spatie/laravel-activitylog#266]
Perhaps, I am missing something very simple, but when I try to forceDelete a model that uses trait softDelete I get an error that says null was passed to logChanges from attributeValuesToBeLogged('deleted').

Diving through method attributeValuesToBeLogged it has
`$properties['attributes'] = static::logChanges($this->exists ? $this->fresh() : $this);`

When $this->exists is evaluated to false it calls $this->fresh(), which tries to pull the model from the db, but it doesn't exist anymore.

Below is what I came up with #267, but it seems a bit hacky and I am sure there is a better way
`$tmp = $this;`
`$properties['attributes'] = static::logChanges($this->exists ? $tmp->fresh() ?? $this : $this);`

**Comment by carlosrgzm** [comment]
Hi, I'm having same issue here. 

The scenario is the same, it fails when I trying to do:

```
$attachment = Attachment::find($id);
$attachment->forcedelete();
```

**Comment by Thijmen** [comment]
Same here, seems to be something with forceDelete. Perhaps something with deleted_at?

**Comment by carlosrgzm** [comment]
Working fine after mergin #267 so this issue can be closed. Thank you!
