### ISSUE TITLE
Is this intended functionality?

### ISSUE THREAD

**Issue by rappasoft** [spatie/laravel-activitylog#268]
I have the LogsActivity trait on my users model.

 If I login and go to my update profile page and change my name 3 times, this is the result.

**Original:** **first_name**: Admin **last_name**: Istrator

**First update:**

 **first_name**: Anthony **last_name**: Rappa

**Database**: {"attributes":{"first_name":"Anthony","last_name":"Rappa"},"old":{"first_name":"Admin","last_name":"Istrator"}}

**Second Update:**

 **first_name**: Spatie **last_name**: Spatie

**Database**: {"attributes":{"first_name":"Spatie","last_name":"Spatie"},"old":{"first_name":"Admin","last_name":"Istrator"}}

**Third Update:**

 **first_name**: Jane **last_name**: Doe

**Database:** {"attributes":{"first_name":"Jane","last_name":"Doe"},"old":{"first_name":"Admin","last_name":"Istrator"}}

As you can see the old key is always set to the original value. Is that what it is suppose to be and not the previously old value?

**Comment by freekmurze** [comment]
Not sure why it's doing that. Current test seem to indicate that this is working as intended. Could you PR a failing test for me to fix?

**Comment by rappasoft** [comment]
I can give you an actual project to test: https://github.com/rappasoft/laravel-5-boilerplate/tree/feature/5.5

It must be something weird, maybe theres another package thats effecting it's outcome, i'll start removing pieces until I can figure out what's causing it.

**Comment by derekphilipau** [comment]
This is happening for me as well.  In DetectsChanges.php, the old attributes are being saved into $model->oldAttributes using data from $model->getOriginal() (which is the "old" of the current object), which are then saved out to 'old' in the db.  Which means that the _very first original_ gets propagated through each change.

Using the same test as @rappasoft, here is a dump of the output from getOriginal():
````
[2017-09-18 14:26:39] local.ERROR: DAU: getoriginal: Array
(
    [id] => 1
    [first_name] => Admin
    [last_name] => Istrator
    ....
````

**Comment by nasirkhan** [comment]
Tested the @rappasoft project and it happened for me as well. 

as @derekphilipau mentioned the `$model->getOriginal()` is keeping the very first value and assigning back again and again.

**Comment by nasirkhan** [comment]
anyone from Spatie team could reproduce the issue on your projects,or the one mentioned above?

**Comment by Shuyinsama** [comment]
Using the latest branch of feature/5.5 and this package it seems it's functioning as intended now. I just started a new project from @rappasoft and created and changed a users name a couple of times and the old data seems to be taken over.

**Comment by rappasoft** [comment]
I'll take @Shuyinsama's word for it. You can close @freekmurze thanks!
