### ISSUE TITLE
Feature Request: Ability to use :causer, :subject inside getDescriptionForEvent()

### ISSUE THREAD

**Issue by rappasoft** [spatie/laravel-activitylog#269]
You can set placeholders when using the log(), why do I only have access to the event name when setting the description via the model method getDescriptionForEvent()? 

It would be very useful to be able to have those placeholders in there. For example:

**":causer.name has {$eventName} :subject.name"**

Unless i'm missing something, the above does not work.

**Comment by freekmurze** [comment]
i'd accept a PR that adds this to the package.

**Comment by rappasoft** [comment]
I'll give it a shot.

**Comment by rappasoft** [comment]
Looking at the source, the override function is being passed to the log method in the trait, therefore should be getting passed through the replacePlaceholders() method. 

Unless i'm reading it wrong.
