### ISSUE TITLE
TypeError in DetectsChanges Trait on Model update

### ISSUE THREAD

**Issue by kohenkatz** [spatie/laravel-activitylog#27]
When I try to do an update of a model that is using the `LogsActivity` Trait, I get the following error:

```
Type error: Argument 1 passed to App\Address::logChanges() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in C:\Web\my-app\vendor\spatie\laravel-activitylog\src\Traits\DetectsChanges.php on line 20
```

Here is the line in question:

    $oldValues = $model->replicate()->setRawAttributes($model->getOriginal());

When I break that line into two, it works:

    $oldValues = $model->replicate();
    $oldValues->setRawAttributes($model->getOriginal());

Any thoughts?

As far as I can tell, the Eloquent `Model` function `setRawAttributes` says it returns `$this`, but it seems to be returning `null` instead.

PHP Version: reproducible on both `7.0.2` and `7.0.9`
Laravel Version: Officially `5.2.x-dev 29ba2e3` in composer, which is same as `5.2.41`
Laravel-ActivityLog Version: `1.2.1`

Complete code of Model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Phaza\LaravelPostgis\Eloquent\PostgisTrait;
use Spatie\Activitylog\Traits\LogsActivity;

class Address extends Model
{

	use PostgisTrait, LogsActivity;

	protected $postgisFields = ['location',];

	protected $fillable = [
		'street_address1',
		'street_address2',
		'city',
		'state',
		'country',
		'zipcode',
		'location',
	];

}
```

**Comment by freekmurze** [comment]
Could you add a failing test to the test suite to prove that this is indeed failing?

**Comment by freekmurze** [comment]
Please reopen after you've added some failing tests.

**Comment by kohenkatz** [comment]
@freekmurze Sorry for the delay. Other projects have to be taken care of first then I will get you some tests.

**Comment by freekmurze** [comment]
No problem man, there's no rush. I completely understand that client projects have priority.

**Comment by kohenkatz** [comment]
Turns out that this was caused by a bug in a different package. I have filed an issue there.
