### ISSUE TITLE
Cannot use CausesActivity trait with LogsActivity trait

### ISSUE THREAD

**Issue by Rhythmgarg** [spatie/laravel-activitylog#270]
When I tried to apply CausesActivity trait with LogsActivity trait, `Trait method activity has not been applied, because there are collisions with other trait methods on App\\Ship\\Parents\\Models\\UserModel` Exception is thrown? Is this the expected behavior?
I was hoping to log any user changes as well as changes caused by any user.

**Comment by freekmurze** [comment]
This is a known issue (#224) which will be handled in the next major release.
