### ISSUE TITLE
Default log all attributes?

### ISSUE THREAD

**Issue by jmagnuss** [spatie/laravel-activitylog#273]
Thanks, using this package in multiple projects!
One issue that keeps occurring is we add a new attribute but forget to add it to the logAttributes list. , so we get blank change history.

Any option to have it include values for all attributes instead of only those listed?

Thanks!

**Comment by introwit** [comment]
@jmagnuss Hey thank you for creating the issue and the suggestion :) Can you explain a bit more on what other than the already available `protected static $logFillable = true;` would be desirable?

**Comment by introwit** [comment]
@jmagnuss have noticed that `$logFillable` wasn't in the docs so have sent a [PR there](https://github.com/spatie/docs.spatie.be/pull/198). You can close the issue if you feel it is enough or let me know if still, this isn't what you were looking for :)

**Comment by jmagnuss** [comment]
No this is fine!  I was surprised there was no facility to "just log everything".  Thanks!
