### ISSUE TITLE
Installation Error Laravel 5.3 

### ISSUE THREAD

**Issue by alibaraneser** [spatie/laravel-activitylog#276]
Hey,

I cannot install on laravel 5.3 and I need to code require code in composer json.

Example : 

"spatie/laravel-activitylog" : "bla@dev"

**Comment by sebastiandedeyne** [comment]
You'll need to require version 1 of this package for Laravel 5.3 compatibility.

https://github.com/spatie/laravel-activitylog/tree/v1
