### ISSUE TITLE
Activity::performedOn($user)->get();

### ISSUE THREAD

**Issue by naknode** [spatie/laravel-activitylog#279]
Hi,

Ever since finding this package, I have used it in my all projects and since recommended it. Well done.

Anyway, looking at the documentation, I see a lack of "getting" logs.

I tried this `Activity::performedOn($user)->get();`

But of course, I get

```
Call to undefined method Spatie\Activitylog\Models\Activity::performedOn()
```

How would I get logs based on the `subject_id`?

**Comment by naknode** [comment]
I realize I could just use Eloquent ORM: `Activity::where('subject_id', '=', $user->id)->get();` I suppose that will do.

**Comment by smoleniuch** [comment]
But that can lead to id collisions, what if you have different subjects with same ids?You must specify subject_type also.Im wondering if there is any eloquent way to retrive models based on activity subject/causer.

**Comment by AlexVanderbist** [comment]
I think we'd merge a PR adding a `performedOn` scope to the `Activity` model that just adds that query for subject type & id :)

**Comment by shijin156** [comment]
Duplicate of #
