### ISSUE TITLE
Set `subject_id` & `subject_type`

### ISSUE THREAD

**Issue by sohelamin** [spatie/laravel-activitylog#280]
Is there any way to set directly `subject_id` & `subject_type` so it will reduce some queries in some cases?

**Comment by freekmurze** [comment]
I think you can just set it, those or just attributes of an eloquent model.

**Comment by sohelamin** [comment]
I know it can be done via Model, but how can I do that by `activity()` helper function?

**Comment by freekmurze** [comment]
No you can't do it directly, only way is to chain on `causedBy` demonstrated in the readme.

**Comment by kayaelle** [comment]
Hello - Can I have further clarification on what you mean by chain on causedBy? 

I am using the activity log to reference a page open. It is not active on a model directly although I'd like to reference the associated model using subject_id and subject type. Perhaps I should just use properties for that data instead for this type of activity?
