### ISSUE TITLE
Return log with causer and subject nested relations

### ISSUE THREAD

**Issue by saqueib** [spatie/laravel-activitylog#281]
Is there any way I can load nested relation for **causer** and **subject**. 
For example, I have `Post` and `Attachment` 

```php
Activity::with('subject.attachments', 'causer')->latest()
```

This works but I also have other `Topics` model which doesn't have this attachments relation so it blows 

```
Call to undefined relationship [attachments] on model [App\Topic]
```

How I can solve this, I am login many other models as well.

**Comment by AlexVanderbist** [comment]
Hi @saqueib 

Use `$activity->load('subject.attachments')` to conditionally load the relationship when you're sure that the `subject` does have the `attachments` relationship.

(I think) another option would be to use `protected $with = ['attachments']` on your `subject` model to always include the `attachments` relationship.

**Comment by skcin7** [comment]
I'm having this exact same issue at the moment. When attempting to eager load for models that don't have the relationship, it causes an error. @saqueib, have you been able to find a solution to this yet?

**Comment by fernandocoronatomf** [comment]
Is there anyway to get the associated model name from the attributes?
Like

` properties: "{"attributes":{"name":"Project Name","project_status_id_text":"72f76a5e-63cf-11e8-83e0-080027e27fee"},"old":{"name":"Project Name","project_stat
us_id_text":"b48608b4-63ce-11e8-b55c-080027e27fee"}}",
`

It does not make sense to show on the UI: changed from ID to ID
I need the actual project status name... 

Any thoughts?

**Comment by Gummibeer** [comment]
`$activity->subject->name` - the subject is just a simple polymorphic relation in the activity model.
If you want to get the name the model had you can log the whole changed model and not just the dirty columns or put it into the extra values. You could also edit the logged description to contain the name.

**Comment by fernandocoronatomf** [comment]
@Gummibeer Sorry, I think maybe I did not make myself clear enough.
I don't want to get the $subject->name... I would like a way to inside the properties json, when I log project_status_id, instead of saving the ID, it could save the actual name of that entity.

`properties: "{"attributes":{"name":"Project Name","project_status_id_text":"72f76a5e-63cf-11e8-83e0-080027e27fee"},"old":{"name":"Project Name","project_stat us_id_text":"b48608b4-63ce-11e8-b55c-080027e27fee"}}",

This could be changed to

`properties: "{"attributes":{"name":"Project Name","project_status_id_text":"New Status"},"old":{"name":"Project Name","project_stat us_id_text":"Old Status"}}",

`

`

**Comment by Gummibeer** [comment]
@skcin7 just check if subject is `instanceof` or `method_exists()`.

@AlexVanderbist even if the `$with` property would solve it I don't recommend to use this property if you don't 100% know what you do.
If you load two models each other you will get a memory limit exception cause they nest each other again and again. Also if you want to get the project one time without the attachments you can't so you will produce useless queries. And if you use `toArray()` for API or other things you will have to exclude the relationship before to don't return unrequested data.

**Comment by saqueib** [comment]
@fernandocoronatomf add a fillable attribute with nested relation, something like this 

```php
// relation to get the status text from model
$logAttributes = ['project_status.name'];
```
then you will be able to get the `project_status_id_text`

**Comment by fernandocoronatomf** [comment]
@saqueib I can see what you are saying, but that is not very helpful or just help me out understanding what you meant...

If I have the project_status_id in my properties new values json, how exactly getting it from $subject->projectStatus->name would help?

I would like to loop through the json properties and just print them on my VUE component

**Comment by robjbrain** [comment]
I've found two work arounds to this.

### Solution One
Firstly you could modify `replacePlaceholders` method here:
https://github.com/spatie/laravel-activitylog/blob/492fa4c24586bc8328ca569442052b2119efcfed/src/ActivityLogger.php#L198-L201

And utilise array_reduce() instead:

```php
$nestedProperty = explode('.', $propertyName);

return array_reduce($nestedProperty, function($attributeValue, $propertyName) {
    return $attributeValue->$propertyName;
}, $attributeValue);

//$attributeValue = $attributeValue->toArray();

//return array_get($attributeValue, $propertyName, $match);
```

Note you shouldn't just copy and paste this as it will need some additional checks to see if the property exists and is an object, but you get the idea.

### Solution Two
The second solution is to use a regular expression to match all the relationships and preload them.

Simply append the following to the top of `replacePlaceholders()`

```php
if (preg_match_all('/:([a-z0-9._-]+)\.[a-z0-9_-]+/i', $description, $matches)) {
    $activity->load($matches[1]);
}
```

What this will do is match all the properties minus the final attribute. So in the case of:

> ':causer.name added :subject.user.name to the :subject.group.name Research Group'

It will match the following:

```
$matches = array:3 [
  0 => "causer"
  1 => "subject.user"
  2 => "subject.group"
]
```

And then load those relationships on the model.

Then when `toArray()` is called the relations will exist within the array.



Would a PR for one of these be accepted?

**Comment by robjbrain** [comment]
It's actually incredibly easy to overwride the activitylogger class and implement this yourself.

Simply create a new class:

```php
<?php

namespace App;

use Spatie\Activitylog\ActivityLogger;
use Spatie\Activitylog\Contracts\Activity;

class CustomActivityLogger extends ActivityLogger
{
    /**
     * @param string $description
     * @param \Spatie\Activitylog\Contracts\Activity $activity
     * @return string
     */
    protected function replacePlaceholders(string $description, Activity $activity): string
    {
        if (preg_match_all('/:([a-z0-9._-]+)\.[a-z0-9_-]+/i', $description, $matches)) {
            $activity->load($matches[1]);
        }

        return parent::replacePlaceholders($description, $activity);
    }
}
```

Then in `AppServiceProvider.php` (or wherever you'd like) simply bind your new logger to the service container:

```php
$this->app->bind(\Spatie\Activitylog\ActivityLogger::class, \App\CustomActivityLogger::class);
```

And tada it works!

**Comment by Gummibeer** [comment]
@robjbrain I would change the `array_get()` to a `data_get()` call - this function can handle arrays and objects and works perfect to get for notated keys.

@fernandocoronatomf after a long time we get a new feature that could help you #472 .
This PR introduces `tapActivity()` method on the subject model. In this method you can manipulate the activity model like you want. Also load data from relations and put the in the properties collection.

**Comment by robjbrain** [comment]
Hey @Gummibeer I didn't have array_get() in my code that is what's in the current spatie implementation, you're right though that works fine. Perhaps the main package should be updated to include it?

Example:

```php
return data_get($attributeValue, $propertyName, $match);            
//$attributeValue = $attributeValue->toArray();

//return array_get($attributeValue, $propertyName, $match);
```

**Comment by robjbrain** [comment]
As for `tapActivity` i've looked at your commit and I feel like it's pretty limited.

If a single model has 10 activities that it might be the subject of and thus 10 unique descriptions, simply calling tapActivity() won't let you know what relations you should load in order to build the description in any single case/

If you update the description then you also have to update the tapActivity() method.

If only one activity requires some heavy lifting out of 10 then you're going to do that heavy lifting un-necessarily whenever the other 9 are having their descriptions generated, since tapActivity() will be called each time and you won't know what log it's for.

Perhaps there should be a `getActivityDescription()` or `buildActivityDescription()` method available on the subject models that can do some extra work if required and that also receives the log_name.

**Comment by Gummibeer** [comment]
@robjbrain that was my idea behind 😉
I'm in holiday atm - so if you want to create a PR I would be happy to accept it. 😊
In best case with a new unit test that tests the mixed getter.
