### ISSUE TITLE
Call to undefined method disableLogging()

### ISSUE THREAD

**Issue by uyab** [spatie/laravel-activitylog#282]
I'm using version 1.15.5, and as stated in documentation, it should have ability to enable/disable logging at runtime:
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#

But it look like version 1.x doesn't have that functionality.

**Comment by ankitasoman** [comment]
I am also using 1.15.5, getting same error while disable logging.

**Comment by introwit** [comment]
@uyab @ankitasoman Hi, as noted in the [Changelog](https://github.com/spatie/laravel-activitylog/blob/ee927e8035110254f0f40f2d33da87e2382af759/CHANGELOG.md#1160---2017-06-28) this feature was added in the `v1.16.0` of the package. We have [updated the docs](https://github.com/spatie/docs.spatie.be/commit/a520a59cb697baf43dea2d1e83f13dfce7695656) about this, thank you for pointing this issue out :)

**Comment by ankitasoman** [comment]
@introwit cant upgrade package to 1.16.0. Seems like you haven't published a tag.

**Comment by introwit** [comment]
@ankitasoman @uyab Done :) [Release](https://github.com/spatie/laravel-activitylog/releases/tag/v1.16.0)
