### ISSUE TITLE
Model attribute accessor is called multiple times

### ISSUE THREAD

**Issue by nealyip** [spatie/laravel-activitylog#285]
If a model is using an attribute accessor 
[https://laravel.com/docs/5.5/eloquent-mutators](https://laravel.com/docs/5.5/eloquent-mutators)

```
    public function getFirstNameAttribute($value)
    {
        return ucfirst($value);
    }
```

The logChanges method from DetectChanges trait will call it many times as the collect function is used inside the foreach loop. 
If the accessor is used to trigger some heavy function, that function will be called the number of attributesToBeLogged times and impacting the performance. So caching the collection is suggested.

**Comment by freekmurze** [comment]
Let's handle this further in #286

**Comment by luizguilhermefr** [comment]
+1

Is this bug fixed?
