### ISSUE TITLE
withProperties function and changes same array?

### ISSUE THREAD

**Issue by kalismeras61** [spatie/laravel-activitylog#288]
I am using blow function for my project but i want to insert db also changes attributes an array. How can i do it ?
Like this: {"attributes":{"photo_id":420},"old":{"photo_id":418,{"activityCSS":"<div class=\"sl-left bg-warning\"> <i class=\"ti-file\"><\/i><\/div>"}}}

   activity()
                ->performedOn($user)
                ->causedBy($user)
                ->withProperties(['activityCSS' => '<div class="sl-left bg-warning"> <i class="ti-file"></i></div>'])
                ->log('profile photo changed.');

**Comment by freekmurze** [comment]
The package can log changed attributes for you. 

Take a look at the relevant docs: https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events#logging-model-events

**Comment by kalismeras61** [comment]
Yes , but i want to be log with custom property and changes in same time. Can you write me an example?
