### ISSUE TITLE
On event callback

### ISSUE THREAD

**Issue by CrixuAMG** [spatie/laravel-activitylog#291]
Is there some way of triggering a callback whenever a model that uses trait is updated/created/deleted?
Basically, what I want to do is notify all connected users (which are connected via a relation) when something happens with the model.

Is there some way of doing this?

Thanks in advance!

**Comment by AlexVanderbist** [comment]
Hi @CrixuAMG 

You can use Laravel's native model events to do something like this: https://laravel.com/docs/5.5/eloquent#events

**Comment by CrixuAMG** [comment]
Completely forgot about them... Thanks!
