### ISSUE TITLE
published Config file throwing error

### ISSUE THREAD

**Issue by nomadme** [spatie/laravel-activitylog#292]
After publishing the config file with `php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"` is throwing error below:

    Type error: Argument 2 passed to Illuminate\View\FileViewFinder::__construct() must be of the type array, null given, called in .../vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php on line 64

But without publishing the config file, it just runs normal. But I wan't to update few things on the config.

Laravel version: 5.4.36
activitylog version: 1.16.0

**Comment by freekmurze** [comment]
We don't support `v1` anymore. Can you upgrade to `v2`?

**Comment by nomadme** [comment]
I can't upgrade to Laravel 5.5. I have to stick with 5.4 for a while. 

I debugged it for a while, but couldn't find the exact root of it. Could you give me a bit direction why it is failing on generated config file?

**Comment by introwit** [comment]
@nomadme can you paste the contents of your `config/view.php` file?

**Comment by nomadme** [comment]
'paths' => [
        realpath(base_path('resources/views')),
    ],
    'compiled' => realpath(storage_path('framework/views')),

**Comment by introwit** [comment]
@nomadme change it to what the default laravel install brings in:
```php
'paths' => [
    resource_path('views'),
],
```
Also this isn't a package specific issue, still I think this will solve the problem for you :)
