### ISSUE TITLE
Get Changes from "Manual" Logging

### ISSUE THREAD

**Issue by brunonetadmin** [spatie/laravel-activitylog#295]
Its possible to implement the function to get the changes in a Model, using manual logging?

Making the default "manual" logging:
activity()
   ->performedOn($anEloquentModel)
   ->causedBy($user)
   ->log('Look, I logged something');
And then getting with:
$myactivity->changes()

To make something (example) like this:
* User DEFAULT user changes in the model. Changes:
From: 
Title:  OLD | Status: 0
To:
Title: NEW | Status: 1

**Comment by fabiolrs** [comment]
Can't you do something like

```
$anEloquentModel = Model::find(1);

$anEloquentModelBeforeChanges = $anEloquentModel->toArray(); // <<< make a toArray to have to old model unchanged on this variable

$anEloquentModel->property = true; // <<< change whatever you want
$anEloquentModel->save()

$anEloquentModelAfterChanges = $anEloquentModel->toArray();
```

This was you have two arrays with before and after properties of the model.

**Comment by brunonetadmin** [comment]
Well, maybe it can. But its more a "hacky" way, what i propose its a package functionality to make things better.

For example:
In my blade template:
@foreach ($activities->changes() as activity)
OLD: {!! $activity->old_value !!}
NEW: {!! $activity->new_value !!} 
@endforeach

Or something like that. The Package handles the comparations of the two arrays.

**Comment by fabiolrs** [comment]
That would not work, because changes() returns a collection of before and after of any given model.

You could easily do something like this in your Blade

`array_diff( json_decode($activity->changes(), true)['old'] , json_decode($activity->changes(), true)['attributes'] )`

That will get you an array of changes, since changes has a before and after.
