### ISSUE TITLE
Call to undefined method withTrashed()

### ISSUE THREAD

**Issue by MustafaHussaini** [spatie/laravel-activitylog#297]
when i set `'subject_returns_soft_deleted_models' => true`

`{{
   "success":false,"error":{"code":0,"message":"Call to undefined method 
   Illuminate\\Database\\Query\\Builder::withTrashed()"
}}`

laravel v5.5
laravel-activitylog 2.2

**Comment by freekmurze** [comment]
Make sure your model uses the `SoftDeletes` trait.

```
// in your model
    use SoftDeletes;
```

**Comment by MustafaHussaini** [comment]
all models should use the `SoftDeletes` trait?
I have some models with no `softDeletes` support.
one thing more can we revert changes?

**Comment by bluec** [comment]
Same problem in #456 I don't feel forcing all our models to use `SoftDeletes` trait is a solution
