### ISSUE TITLE
Model logging, deleted users and custom properties

### ISSUE THREAD

**Issue by mattfaulk** [spatie/laravel-activitylog#299]
Hi there,

Firstly, I want to say this is a great logging solution, I have been using it for a few months and have found it very easy to use.

I have noticed that when a user model is deleted, this causes a bit of an issue as it obviously can't enumerate the user model. I don't really want to enable softDeletes on my user model and saw another post which suggested logging a custom property might be the solution.

I think I could make this work, I could log a custom property with the user name at the time of logging the model event. If the user model no longer exists, I could fallback to the logged user name custom property. 

My question is; is it possible to perform model logging and log a custom property at the same time?

Ultimately, what I am trying to achieve here is to manage the logs in such a way that I can report on events even after a user has been deleted. If there's a better way, feel free to point that out too!

Thanks.

**Comment by freekmurze** [comment]
> is it possible to perform model logging and log a custom property at the same time?

I think so yes. Here's how you can add custom properties: https://docs.spatie.be/laravel-activitylog/v2/basic-usage/logging-activity#setting-custom-properties

**Comment by mattfaulk** [comment]
Thanks - maybe a silly question... will that work?

If we are logging events that are performed on a model [create, update, delete], the code to add a log entry isn't specifically called from the model - I assume it uses an observer?

**Comment by mattfaulk** [comment]
OK - I've taken a different route with this.

For anyone else trying to add extra properties when logging model evens, the easiest way I have found is to customise the LogsActivity Trait. 

To do this, simply take a copy of the LogsActivity trait, change the namespace and reference it in your model instead of the default. 

Don't forget to use DetectsChanges in your new trait if you change the namespace.

Once done, you can customise the boot method to add your new properties as additional information to the withProperties function.

Here is an example:

```
protected static function bootCustomTrait()
    {
        static::eventsToBeRecorded()->each(function ($eventName) {
            return static::$eventName(function (Model $model) use ($eventName) {
                if (! $model->shouldLogEvent($eventName)) {
                    return;
                }

                $description = $model->getDescriptionForEvent($eventName);

                $logName = $model->getLogNameToUse($eventName);

                $prop1 = 'new property 1';

                $prop2 = 'new property 2';

                $properties = array_merge( $model->attributeValuesToBeLogged($eventName), ['prop1' => $prop1, 'prop2' => $prop2] );

                if ($description == '') {
                    return;
                }

                app(ActivityLogger::class)
                    ->useLog($logName)
                    ->performedOn($model)
                    ->withProperties($properties)
                    ->log($description);
            });
        });
    }
```

**Comment by maj0rr** [comment]
Hey @freekmurze ,
thanks for this great solution to log activities!
I ran into exactly the same problem that @mattfaulk had.

Are you able to give us the ability to use this "Feature"? 
That would be great.

Thanks!!
