### ISSUE TITLE
Xzibit programmed the LogsActivity trait.

### ISSUE THREAD

**Issue by mikemand** [spatie/laravel-activitylog#3]
If `eventsToBeRecorded` must return a `Collection`, why is it being `collect`ed again?

https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/LogsActivity.php#L16

**Comment by freekmurze** [comment]
You're right: this call isn't necessary. When creating packages we experiment a bit with the types the functions should return. I guess at some point `eventsToBeRecorded` was an array. 

I've removed that `collect` call on master.
