### ISSUE TITLE
multilingual?

### ISSUE THREAD

**Issue by jespersgaard** [spatie/laravel-activitylog#30]
hello

it is possible to use multilingual so that users see the activities in their own language?

best regards Martin

**Comment by freekmurze** [comment]
Not out the box. But here's an idea: instead of logging the descriptions of the events, you could store a key that points to a translation you keep in a db or file.

**Comment by dct24** [comment]
@jespersgaard 

You can make a service provider and translate those 3 hard coded descriptions (updated, created, deleted)  there in a boot method:

`public function boot()
    {
        Activity::saving(function (Activity $activity) {
            $desc = $activity->description;
            if( $desc == 'updated' || $desc == 'created' || $desc == 'deleted'){
                $activity->description = trans('logs.'.$desc);
            }
        });
    }`

**Comment by kikoseijo** [comment]
And if you do it on the model customise the description for an event, you can use this one:

...on Model
```php
public function getDescriptionForEvent(string $eventName): string
    {
        return "Se ha " .trans('logs.'.$eventName) . " la exportación  #:subject.id";
    }
```

Happy coding!
