### ISSUE TITLE
BeforeHandlerInterface not found Laravel 5.3 in migrate 

### ISSUE THREAD

**Issue by gendalfbug** [spatie/laravel-activitylog#300]
[Symfony\Component\Debug\Exception\FatalErrorException]                   
  Interface 'Spatie\Activitylog\Handlers\BeforeHandlerInterface' not found

**Comment by AlexVanderbist** [comment]
Hi @gendalfbug 

For Laravel 5.3 you'll need to use v1 of this package (https://github.com/spatie/laravel-activitylog/tree/v1).
