### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by hakimihamdan88** [spatie/laravel-activitylog#302]
How do I listen all event by activity() ?

thank you for great library btw.

**Comment by freekmurze** [comment]
Here's one way to go about it. Use [your own model](https://github.com/spatie/laravel-activitylog/blob/2748d926aeff18d2dab3b83ef395d22766f67e6a/config/activitylog.php#L38) and fire you own event when a model gets created:

```php
// in your custom activity model

public static function boot() {
   static::created(function(YourCustomModel $model) {
       event(new YourEventClass($model); 
   });
}
```

**Comment by hakimihamdan88** [comment]
im looking for something like this

```

$events->listen(
    'Spatie\Laravel-activitylog',
    'App\Listeners\ActivityEventSubscriber@onLog'
);
