### ISSUE TITLE
Can't install on Laravel 5.4.36

### ISSUE THREAD

**Issue by dcaldessa** [spatie/laravel-activitylog#305]
I am trying to install the package on my install of laravel 5.4.36, I keep getting an error 

I understand that the latest version 2.3.0 cannot be run on laravel 5.4, but i also cannot install v 2.0-2.2.0. 
I look at your documentation under requirements and all i see is this

The activitylog package requires PHP 7.0+ and Laravel 5.2 or higher.
The latest version requires Laravel 5.5.

So why can't I install versions 2.0-2.2.0?

Edit 1 So in the meantime I have installed v1.16.0

when I run 
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
no migration is created.... 

this is installed on a fresh laravel 5.4 install.

**Comment by dcaldessa** [comment]
So upon further investigation I have figured out that from 2.0 upwards is not supported for laravel 5.4 , I should have not found out the hard way that this was indeed the case, you all need to update the github page to reflect this to your potential users. I have now installed v1.16.1 as I cannot at this time upgrade to laravel 5.5.

**Comment by cmorfe** [comment]
I have the same problem. I read the version 2.0.0 added support for Laravel 5.5 and dropped support for older laravel versions. Could I use version 1.16.0 for Laravel 5.4 instead?

**Comment by dcaldessa** [comment]
I installed 1.16.0 for my laravel 5.4 install, I'll be using that since it looks like 2.0 and higher is for laravel 5.5.

**Comment by cmorfe** [comment]
I'll try the same..

**Comment by dcaldessa** [comment]
The instructions for running the command 
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"

is inconsistent I had to run it like 
php artisan vendor:publish --provider= Spatie\Activitylog\ActivitylogServiceProvider --tag= migrations

When i ran the command without quotes I was able to get the migration. This should be noted. 

Anyway It looks like it is installed now, I'll be working with it in my project to see if I can get the logging to work ..
thanks

**Comment by cmorfe** [comment]
It's worth mentioning though I didn't came across that issue because I wanted to publish both the migration and the config file so I ran the command without the tags, like:
php artisan vendor:publish --provider= Spatie\Activitylog\ActivitylogServiceProvider
and it's all installed and working... or at least tested... it works fine so far.
