### ISSUE TITLE
How to 'fake' the old and new properties

### ISSUE THREAD

**Issue by designvoid** [spatie/laravel-activitylog#307]
I would like to manually add a log entry but I want it follow the same format as logged model events so I want an 'old' value and a 'new' value.

Basically its to track changes to a many to many relationship.

Is this possible?

**Comment by freekmurze** [comment]
You can get these values by calling `$activity->changes()`. There's an example in the docs: https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events

**Comment by designvoid** [comment]
Hiya,
Sorry, I'm not sure I explained properly - I want to manually add a log event to the database in the same format as model events.

**Comment by freekmurze** [comment]
You can manually set properties on the activity by using custom properties.

Here's an example: https://docs.spatie.be/laravel-activitylog/v2/basic-usage/logging-activity#setting-custom-properties
