### ISSUE TITLE
Can i fill the properties field with the changed attributes on update from multiauth.

### ISSUE THREAD

**Issue by rcloeck** [spatie/laravel-activitylog#309]
Hi i love your class, but i have a small issue i can't seem to figure out.

i use multi auth and when i update a user from within my admin auth then i don't see the attributes that are being changed.  is there a way to fill the properties field with this info?

**Comment by AlexVanderbist** [comment]
Hi @rcloeck 

Have you tried `$activity->changes`?

**Comment by AlexVanderbist** [comment]
This might be related to #222

**Comment by AlexVanderbist** [comment]
Closing this for now due to inactivity
