### ISSUE TITLE
Support for laravel 5 and php5 

### ISSUE THREAD

**Issue by nyanwin17** [spatie/laravel-activitylog#31]
I can't able to install on laravel 5 and php 5 because dependency requirements are too high

**Comment by aguimaraes** [comment]
@nyanwin17 their libraries are intentionally for PHP 7 or superior. Judging by the source code.

**Comment by freekmurze** [comment]
Yes, all our new packages now require PHP 7. Here some more info on that decision: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/

**Comment by franciscocorrales** [comment]
+1 on this.
Dependency requirements are too high.
