### ISSUE TITLE
[Question] How Do I Display logs in a view

### ISSUE THREAD

**Issue by dcaldessa** [spatie/laravel-activitylog#310]
I have the logging implemented in my project and it is logging the events that I have created which is good. Now what I want to do is display the logs in a View page along with the user the log recorded. 

How exactly do I do this ? I am still new to laravel so still figuring it all out. If anyone can give me some help that would be great. I have read the documentation but there is no example of pulling the information to a view or if there is I am not understanding it .

thanks.

**Comment by freekmurze** [comment]
All activity is logged in a table named `activity`. There's a corresponding `Activity` model to interact with. Review the documentation on Eloquent to learn how to pull data out of the database using a model: https://laravel.com/docs/5.5/eloquent

If you're a visual learner, I highly recommend watching this course: https://laravelfromscratch.com

**Comment by fabiolrs** [comment]
If this helps anyone that is learning and would serve as a good starting point for beginners to look for the right stuff, this is how I do it.

On my controller, I have:

```
// latest 15 activities logged
$activity = Activity::orderBy('created_at', 'desc')->paginate(15);
// all unique actions, put these on a select to filter for specific actions
$actions = Activity::orderBy('description', 'asc')->groupBy('description')->pluck('description', 'description')->prepend('Select', '');
// all models that suffered some kind of action, also to be put on a select
$objects = Activity::orderBy('subject_type', 'asc')->groupBy('subject_type')->pluck('subject_type', 'subject_type')->prepend('Select', '');
// users
$users = User::all();
```

I then show the last 15 activities but also put the other stuff on combo boxes so the user can, lets say, select model A, that were subject to an update by user 15.

```
<div>Log ID: <b>{{ $activity->id }}</b></div>
<div>Description: <b>{{ $activity->description }}</b></div>
<div>Subject tyoe: <b>{{ $activity->subject_type or "-" }}</b></div>
<div>Subject ID: <b>{{ $activity->subject_id or "-" }}</b></div>
<div>
	@if ($activity->subject_type && $activity->subject_type::where('id', '=', $activity->subject_id)->exists())
		<span>{{ $activity->subject_type::find($activity->subject_id)->name }}</span>
		{{-- all models must have name propertie, on models that a name is not applicable, i create example: getNamePropertie() { return "relation of model A with B" } --}}
	@endif
</div>
<div>Type of causer: <b>{{ $activity->causer_type }}</b></div>
<div>ID of causer: <b>{{ $activity->causer_id }}</b></div>
<div>
@if ($activity->causer_type && $activity->causer_type::where('id', '=', $activity->causer_id)->exists())
<span>{{ $activity->causer_type::find($activity->causer_id)->name }}</span>
@endif
</div>
<div>Date and time: <b>{{ Carbon\Carbon::parse($activity->created_at)->format('Y-m-d - G:i:s') }}</b></div>
<div>
<h3>CHANGES</h3>
<pre>
<p>{{ json_encode($activity->changes(), JSON_PRETTY_PRINT) }}</p>
</pre>
<h3>PROPERTIES</h3>
<pre>
<p>{{ json_encode($activity->properties, JSON_PRETTY_PRINT) }}</p>
</pre>
</div>
```

Hope it helps the beginners of this amazing package.

**Comment by dcaldessa** [comment]
Thank you for the replies and tips Ill see what I can do once I process the information.

**Comment by Amrgumaa** [comment]
thanks alot
