### ISSUE TITLE
Logging model events: $logAttributes = all attributes of the model

### ISSUE THREAD

**Issue by vincentkedison** [spatie/laravel-activitylog#311]
Hello, is there any feature to simply define all attribute in $logAttributes?
I have model with more than 50 fields, and It's challenging to define all of this attribute in $logAttributes variable. I imagine like $fillable and $guard, when I add $guard = [], all attribute of the model is mass assignable.

Thankyou

**Comment by freekmurze** [comment]
Try using `*` in `$logAttributes`.

**Comment by vincentkedison** [comment]
Hi @freekmurze, thanks for your answer.
```
protected static $logAttributes = ["*"];
```
Do you mean like that?
I've try it but it's not working.
{"attributes":[],"old":[]} in properties field.

**Comment by AlexVanderbist** [comment]
Hi @vincentkedison,

I gave this a quick test and it seems to work for me. See the following gist: 
https://gist.github.com/AlexVanderbist/432a6d4253cd425aa17ab638bd91f2e3

**Comment by webenformasyon** [comment]
it would be nice if we could see this in doc.

thanks for this nice package.

**Comment by josefernandoperezgarcia1998** [comment]
**For Laravel v9 and ActivityLog v4**
Im doing this [tutorial ](https://www.youtube.com/watch?v=j6FB5WelWZY) without tinker, im using the views Blade... Its almost the same think. Just kind of custom code be cause the ActivityLog package update...

```
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class YourModel extends Authenticable
{

use LogsActivity;

           protected $fillable = [
                      'x',
                       'y',
                       'z',
              ];

            //This function is important, if you dont add this function it will be fail
             public function getActivitylogOptions(): LogOptions
            {
                  return LogOptions::defaults()->logOnly(['*']);
            }

}
```

it works 100%
![image](https://user-images.githubusercontent.com/66925963/196227625-a01dde8c-f20e-4419-bcd7-c577f85ac204.png)

![image](https://user-images.githubusercontent.com/66925963/196227654-a288f64d-6801-44cb-9542-edac4f2b505b.png)
