### ISSUE TITLE
User activity as causer

### ISSUE THREAD

**Issue by m4rl0ne** [spatie/laravel-activitylog#312]
When I use the eloquent relationship `\Auth::user()->activity`, it returns all the logs where the authenticated user was altered. How can I return all the logs where the user given is the causer? Like I want to get all the rows of the log table where the authenticated was involved either as subject or as causer. I hope you understand what I mean.

Sorry for my bad english and greetings from Germany,
Marlon

` class User extends Authenticatable
{
    use Notifiable;
    use LogsActivity;
    `
`
    protected static $logAttributes = ['name', 'email', 'password', 'role', 'active'];
    protected static $logOnlyDirty = true;
    ...`

`\Auth::user()->activity`

**Comment by freekmurze** [comment]
You're probably looking for this

```php
$activities = Activity::causedBy($causer)->get();
```
