### ISSUE TITLE
Proper way to check if property exists

### ISSUE THREAD

**Issue by nexxai** [spatie/laravel-activitylog#313]
I'm having a very stupid (me being the stupid one) issue where my log contains events from multiple models, and then using a view, I'm trying to print out the details of the events.

The issue I'm having is that one of the models has an attribute called "first_name" and the other model doesn't, so what I *think* I need to be doing is checking if that property exists before trying to print it, but I can't figure out the correct way to do that.

I've tried the following:

`@if ($event->getExtraProperty('attributes.first_name') != NULL)`

`@if ($event->getExtraProperty('attributes.first_name'))`

`@if (isset($event->getExtraProperty('attributes.first_name')))`

but none of them trigger like I'd expect them to.

Can someone tell me what I'm missing?

**Comment by AlexVanderbist** [comment]
Hi, 

Have you tried `dump`ing the `$event->getExtraProperty('attributes.first_name')` output to see what's actually being returned?

Normally when the extra property doesn't exist `null` should be returned so your approach is correct.

**Comment by saqueib** [comment]
There are many ways but I find myself using laravel `array_get` to check and print the properties.

```blade
@if( $first_name = array_get($event->properties, 'first_name') )
   First Name:  {{ $first_name }}
@endif
```

**Comment by AlexVanderbist** [comment]
Closing this for now. Feel free to open a new issue if you're still having this issue.
