### ISSUE TITLE
subject or causer is null

### ISSUE THREAD

**Issue by imranicp** [spatie/laravel-activitylog#314]
I am trying to understand this package, i did a test log, trying to access the causer or the subject of the log returns null. description is ok. 
`$item=Item::first();`
`$user=User::first();`
`activity()->peformedOn($item)->by($user)->log('This is a test log');`
`$lastActivity=Activity::all()->last();`
`$subject=$last->subject;`
`$causer=$last->causer;`

both the subject variable as well as the causer variables are null, is there something that i am doing in correctly or why is it returning null. Activity logs the model name and id correctly to the database but returns null on subject or cause.

Laravel 5.5
Activitylog: 2.3

**Comment by saqueib** [comment]
there is a typo in the provided code
```
$lastActivity=Activity::all()->last();
$subject=$lastActivity->subject;
$causer=$lastActivity->causer;

// dry dumping it
dd($subject, $causer);
```

Make sure you have stored $item and $user in db, if related model were not found it will return `null`

**Comment by imranicp** [comment]
I tried dry dumping, still they are null. as can be seen in the code above, i passed the models of item and user to the activity(), and saved a test log. the related model is present in the database. is there something i am missing ?

**Comment by AlexVanderbist** [comment]
Hi! 

Taken from the readme: 
```php
activity()
   ->performedOn($anEloquentModel)
   ->causedBy($user)
   ->log('something')
```

The method name is called `causedBy`, not `by`. Not sure why the `subject` is `null` as well but this might solve both of the issues.

**Comment by imranicp** [comment]
Sorry for the typos in the example code above. i ran the code without typos, still its returning null. 
As explained in the documentation, the alias for causedBy is "by" and the alias for performedOn() us On. so technically this should work. any other help apart from typos ?
