### ISSUE TITLE
how can I Activity::orderBy('subject.followers_count', 'desc')

### ISSUE THREAD

**Issue by saqueib** [spatie/laravel-activitylog#315]
I want to get all the activity by ordering by `subject.followers_count`, I have tried following but no luck.

> posts table has a column `followers_count`

```php
Activity::with('subject', 'causer')
              ->where('subject_type', Post::class)
              ->orderBy('subject.followers_count', 'desc')
              ->paginate();
```
and 

```php
return Activity::where('subject_type', Post::class)
       ->with(['subject' => function ($query) {
            $query->orderBy('followers_count', 'desc');
            // $query->latest('followers_count');
          }, 'causer'])->paginate();
```

both options doesn't work, please help how can do it

**Comment by freekmurze** [comment]
This question isn't related to this package per sé, but more to eloquent.

Have a look here: https://laracasts.com/discuss/channels/laravel/laravel-eloquent-sort-by-related-field

If that doesn't your question create a new thread there.
