### ISSUE TITLE
Question: User logins considered as updates?

### ISSUE THREAD

**Issue by austintoddj** [spatie/laravel-activitylog#316]
After playing around with the Activity Log for a little bit now and having my Models logged per the documentation, it looks as if a User login is considered an update and thus added to the log. 

First off, am I correct in assuming this since the changed `updated_at` field technically makes it an update?

Finally, is there a way that I could modify the description of the update described above so that the log is a bit more clear as to when a user update is merely a login?

Love the package, keep up the great work!

**Comment by freekmurze** [comment]
You're right.

There are several ways to add a description to that "logged in" activity item.

One could be that you use your own Activity model and in the `boot` method listen for `creating` events. When an activity item is created while the url is the login url you could add a little description to the new activity being logged.

**Comment by marcelogarbin** [comment]
@austintoddj Hi, did you get around this? thanks
