### ISSUE TITLE
set causer type and Id in model

### ISSUE THREAD

**Issue by dcaldessa** [spatie/laravel-activitylog#318]
I have been using the LogActivity trait in my user model, I would like to know how I can set the causer id and causer type to be recorded when the log is created ? right now it is showing up null.

**Comment by freekmurze** [comment]
Here you go: https://docs.spatie.be/laravel-activitylog/v2/basic-usage/logging-activity#setting-a-causer

**Comment by hwkprice** [comment]
> Here you go: https://docs.spatie.be/laravel-activitylog/v2/basic-usage/logging-activity#setting-a-causer
I assume you are referring to the following snippet:

```
activity()
   ->causedBy($userModel)
   ->performedOn($someContentModel)
   ->log('edited'); 
```

Where in the laravel project code do you put that code? The article doesn't explain this.

Also how do you initialize the $userModel and $someContentModel variables?

**Comment by Gummibeer** [comment]
Wherever you want and check the Laravel docs on how to get instances of eloquent models.
