### ISSUE TITLE
Better usage examples for "multiple logs"

### ISSUE THREAD

**Issue by simplenotezy** [spatie/laravel-activitylog#321]
Would be really helpful if some more real-world examples were used for Multiple Logs in the documentation: https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/using-multiple-logs

I'd like to know if this is something that could be useful for my project.

**Comment by freekmurze** [comment]
I think the current examples make it clear what this package can do. If you need some more examples, take a look at the testsuite of the package.
