### ISSUE TITLE
Deleting model is not logged

### ISSUE THREAD

**Issue by Jonathan57500** [spatie/laravel-activitylog#327]
Hi,
For my application, I have a Roles assignment system where model is:
```
<?php
namespace App\Models\Users;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class UserRole extends Model
{
	use LogsActivity;
	protected static $logFillable = true;
	
	protected $table = 'user_role';
	protected $fillable = ['user_id', 'role_id'];
	public $timestamps = false;
	
}
```
In my controller, I have this method:
```
public function assign(Request $request) {
		$user = User::where('id', $request->input('user_id'))->first();
		$role_id = $request->input('role_id');
		
		if($request->input('action') == 'assign')
		{
			$addUserRole = new UserRole;
			$addUserRole->user_id = $user->id;
			$addUserRole->role_id = $role_id;
			
			$addUserRole->save();
		}
		
		elseif($request->input('action') == 'remove')
		{
			UserRole::where('user_id', $user->id)->where('role_id', $role_id)->delete();
		}
		
		return response()->json();
	}
}
```
When I want to assign a role to a user, this 'created' activity is correctly logged. But when I want to unassign a role to a user, this 'deleted' activity is not logged. I tried to add some Debugbar logs everywhere in traits but it's like if Activity log is not at all called when deleting a record from its model.

**Comment by freekmurze** [comment]
Our package used Model events to determine when a model is being deleted. When you use the query builder do delete models Laravel will not fire model events.

In Laravel 5.5 you can do this do delete each model separately (and fire off model events):

```php
UserRole::where('user_id', $user->id)->where('role_id', $role_id)->get()->each->delete();
```

**Comment by Jonathan57500** [comment]
Looks working correctly now, good to know :)
Sorry for inconvenience
