### ISSUE TITLE
ActivityLog does not log sync activities

### ISSUE THREAD

**Issue by bankork** [spatie/laravel-activitylog#334]
Kindly help me out. I have a project am working on but I discovered from my repository it does not log any SNYC activities I made call to. Can someone assist pls. I am using spatie/laravel-activity package using the model log

**Comment by AlexVanderbist** [comment]
We're gonna need some more information first. What version of Laravel are you using? Are you sure you registere the serviceprovider if it's < L5.5?

**Comment by bankork** [comment]
Thanks @AlexVanderbist , I have registered the serviceprovider in my config/app.php like below
Spatie\Activitylog\ActivitylogServiceProvider::class,

If I do create on a model, it logs it but whenever I do sync 

$employee = Employee::find($data['user_id']);
$ret_val = $employee->sites()->sync($details);

it doesnt log the activities.

Thanks in advance

**Comment by AlexVanderbist** [comment]
Glad you got that working! Syncing eloquent relationships won't log any activity since Eloquent doesn't fire events on parent models when one of it's relationships changes. You can however, build the activity record yourself (including coupling it to the relevant model).

```php
$employee = Employee::find($data['user_id']);
$ret_val = $employee->sites()->sync($details);

activity()
    ->performedOn($employee)
    ->causedBy(auth()->user())
    ->log(':causer.name changed sites for :subject.title');
```

Hopefully this helps you out! Let me know if you need any more help :)

**Comment by bankork** [comment]
Thanks @AlexVanderbist , it works for me but is there is a simpler way to get the Properties of the changes made.
I appreciate

**Comment by AlexVanderbist** [comment]
As per docs: https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events#logging-model-events

```php
$activity->changes(); //returns ['attributes' => ['name' => 'original name', 'text' => 'Lorum']];
```

**Comment by bankork** [comment]
$activity->changes() is when an activity has been logged.

I am looking forward to getting activities for the changes and old data, i mean before and after so I can save alongside in the withProperties like below or is there a better approach.

activity()
                ->performedOn($employee)
                ->causedBy(auth()->user())
                ->withProperties()
                ->log(':causer.name changed sites for :subject.surname');

**Comment by AlexVanderbist** [comment]
Hi @bankork – sorry for the late reply.

As you said; you can use `withProperties()` to save some extra data alongside the activity. I've looked into it but I don't think there's an easier way to log changes made when you sync related models.

Good luck and if you have any more questions feel free to open a new issue.

**Comment by hamza-masoud** [comment]
can you make it easier? 
it will be perfect when it logs automatically

**Comment by Gummibeer** [comment]
@hamza-masoud relation logging is discussed in "endless" issues and like always: there's no way for us to log them automatically as there's no event we could listen for.
