### ISSUE TITLE
Description using translations

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-activitylog#336]
Hey,

is there a default was to log activities using laravels translation methods?
My Idea ist to put the translation key in the description column and do the translation part in custom methods.
Is this the way to go or do you have another idea?

**Comment by AlexVanderbist** [comment]
Hi! I think this probably the easiest way to go. Another option might be to extend the `Activity` model (add you own FQCN to the config). In that custom `Activity` model you can add a [mutator and accessor](https://laravel.com/docs/5.5/eloquent-mutators#accessors-and-mutators) for the description (`getDescriptionAttribute($description)` and `setDescriptionAttribute($description)`) these will get and set the translation in a JSON array stored in the description column.
