### ISSUE TITLE
Suggestion: include url, ip address, user agent

### ISSUE THREAD

**Issue by denitsa-cm** [spatie/laravel-activitylog#338]
Maybe it would be nice to also log the source url, ip address (maybe), and user agent in the logs. :)

**Comment by freekmurze** [comment]
Those are good suggestions, but everybody has different needs, I try to keep this package a small as it can be.

You can easily add IP logging and user agent logging in your own project.

**Comment by Gummibeer** [comment]
The easiest way would be to put them in the `extras` column and use a wrapper to create them or use a model observer.

**Comment by bolechen** [comment]
see #39

**Comment by rijans** [comment]
I am using it  in `boot `method in the `AppServiceProvider.php`

```
Activity::saving(function (Activity $activity) {
            $activity->properties = $activity->properties->put('agent', [
                'ip' => Request::ip(),
                'browser' => \Browser::browserName(),
                'os' => \Browser::platformName(),
                'url' => Request::fullUrl(),
            ]);
        });
```
