### ISSUE TITLE
nothing to migrate after migration is published

### ISSUE THREAD

**Issue by vijayrana-me** [spatie/laravel-activitylog#339]
I am trying to install version one of this package as my laravel version is 5.4.36 and PHP version 7.0.27

- I installed the package(version one)
- I added service provider `Spatie\Activitylog\ActivitylogServiceProvider::class,`
- I publish the migration with `php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"`

I notice that there is migration file in package directory inside vendor folder.

But, When i run `php artisan migrate`, it shows `nothing to migrate`

I also tried migrating with path as:
`php artisan migrate --path=vendor/spatie/laravel-activitylog/mgrations/`

but result is still the same.

Could you help me please?

**Comment by freekmurze** [comment]
Run `php artisan cache:clear` and try publishing the migration again.

**Comment by vijayrana-me** [comment]
Fixed it. Thanks
