### ISSUE TITLE
Cartalyst Sentinel compatibility

### ISSUE THREAD

**Issue by sembrex** [spatie/laravel-activitylog#34]
I've problem in model logging when using sentinel as my auth manager.
I have to modify default ActivityLogger constructor to use Sentinel instead of AuthManager
Everything work fine for now.
IMHO it's better to add an config option for auth manager

sorry for my bad english.

**Comment by sebastiandedeyne** [comment]
I don't really know how Sentinel works under the hood, so hard to comment.

Would injecting `Illuminate\Contracts\Auth\Factory` instead of `AuthManager` resolve the issue?
