### ISSUE TITLE
Model events for User Model

### ISSUE THREAD

**Issue by marcelogarbin** [spatie/laravel-activitylog#341]
Hello,
I started using the package a little bit, I'm not sure which event to use in the User model.
I tried to use:
- HasActivity
- LogsActivity

It turns out that any of these that I use, when the user logs into the system, a log is created, but with UPDATE action.

This is normal? or would you have some better way to do it?

**Comment by AlexVanderbist** [comment]
Hi @marcelogarbin 

In this case I think you want the `HasActivity` as the user is both causer (causing the acitivity) and subject (the model being updated). See https://github.com/spatie/laravel-activitylog/pull/333 as well.

>It turns out that any of these that I use, when the user logs into the system, a log is created, but with UPDATE action. This is normal?

This depends on what you want to do. The update log being created is probably the user's `remember_token` being updated every time a user logs in. 

If you want to properly log users logging in and out I'd suggest creating a listener for the `Illuminate\Auth\Events\Login` event (see https://laravel.com/docs/5.5/authentication#events) and manually logging the login activity:

```php
acitivity()->log('User logged in');
```

Good luck & lmk if you need any help 👍
