### ISSUE TITLE
How to log group events

### ISSUE THREAD

**Issue by yaoshanliang** [spatie/laravel-activitylog#346]
For example，

`Admin::where('id', $request->id)->update($data);` does not work;

`Admin::where('id', $request->id)->firstOrFail()->update($data);` work;

And group operation is need, when I use the first line, it should log many lines;

**Comment by freekmurze** [comment]
When you're mass updating Laravel will not fire off model events (where this package hooks into).

The easiest way to solve this would me to update each model separately

```php
Admin::where('id', $request->id)->get()->each->update($data);
```

But keep in mind that this solution will result in multiple queries being executed.

**Comment by yaoshanliang** [comment]
Yes，that solution will query more, which is not wanted. Hope to a better way.
