### ISSUE TITLE
Clash between logAttributes and ignoreChangedAttributes

### ISSUE THREAD

**Issue by designvoid** [spatie/laravel-activitylog#347]
So I have:

```
    protected static $ignoreChangedAttributes = ['visible','not_running','updated_at','updated_by'];

    protected static $logAttributes = ['*'];
```

And my logs seem to contain updated_at and updated_by? Is this expected due to the wildcard overriding the ignore array?

**Comment by freekmurze** [comment]
The purpose `ignoreChangedAttributes` differs slightly from what your expecting. It only controls the triggering of logging the activity.

https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events#ignoring-changes-to-certain-attributes

**Comment by Gummibeer** [comment]
In my opinion a Blacklist should be more important than a Whitelist.

**Comment by designvoid** [comment]
Agreed - I have quite a big model and being able to manage a smaller blacklist would be great

**Comment by Gummibeer** [comment]
https://github.com/Gummibeer/laravel-activitylog/blob/master/src/Traits/DetectsChanges.php#L26
This is the method that should get adjusted to remove blacklisted attributes.
But for this a new property should be added, like `$notLogAttributes` or `$hiddenAttributes`.

**Comment by designvoid** [comment]
Agreed, it seems like a pretty minor addition that would give even more flexibility to an already killer package
