### ISSUE TITLE
spatie installation failed

### ISSUE THREAD

**Issue by mehakjami** [spatie/laravel-activitylog#349]
When i try to install spatie its says
Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Why did your installation fail? Do you have more info for us to go on?

**Comment by mehakjami** [comment]
when i add this in providers array
 Spatie\Activitylog\Traits\LogsActivity::class,
it says this class not found, please help i'm seriously unable to integrate the package

**Comment by TVke** [comment]
Hi @mehakjami  

You don't need to add anything to the providers array, because since Laravel 5.5it happens automatic.
If you are on a lower version or want to set it explicit you should add `Spatie\Activitylog\ActivitylogServiceProvider::class` to the providers array.

Hope this helps.

**Comment by mehakjami** [comment]
yes i'm using laravel 5.4, but this solution didn't work ,

**Comment by TVke** [comment]
Could you share some more info about the error you get? 
Could you copy the full error message from composer?

**Comment by ptuchik** [comment]
You need to install the package, and only after that add the provider

**Comment by freekmurze** [comment]
@ptuchik bingo!
