### ISSUE TITLE
Possibility to pass custom value 

### ISSUE THREAD

**Issue by freel132** [spatie/laravel-activitylog#35]
Hello,

 Thats awesome package! Thx

I have issue with some of my models. In some models I have name field but in some no.
Is any chance to pass custom value by default to this? 

lets say: $name = $this->size->name;
and latter pass it to  $logAttributes

```
use LogsActivity;

    protected static $logAttributes = ['name'];

    public function getDescriptionForEvent(string $eventName): string
    {
        return "This target has been {$eventName}";
    }
public function size()
    {
        return $this->belongsTo('App\Models\Size');
    }
```

Thank you for answer.

**Comment by sebastiandedeyne** [comment]
The `$logAttributes` property is actually just there for convenience, you have full control if you overwrite the `logChanges` method: https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/DetectsChanges.php#L51-L54

Would looks something like this:

```php
public static function logChanges(Model $model): array
{
    return ['name' => $model->size->name];
}
```

**Comment by freel132** [comment]
Thank you for answer . Well in my situation probably not gona work.  Size is just example I have loads of tables where I am sending $this->MODEL->name 
But anyway thank you for solution.
