### ISSUE TITLE
utf-8 properties

### ISSUE THREAD

**Issue by davoudrafati** [spatie/laravel-activitylog#351]
this is my data on MySQL table with ut8mb4_unicode collation

{"firstname":"\u0632\u0647\u0631\u0627","lastname":"\u0634\u06cc\u062e\u0633\u0627\u0631\u0627\u0646"}

**Comment by freekmurze** [comment]
I don't understand the problem. Could you give more info in a new issue so we can understand and recreate the problem?

If possible PR a failing test for us to look at.
