### ISSUE TITLE
Delete event log when model is deleted

### ISSUE THREAD

**Issue by bubblemedialtd** [spatie/laravel-activitylog#353]
Is it possible to delete any related event logs, when the model is removed.

For example.

````
User 1 created Book 1
User 1 was then subsequently removed, thus meaning the activity would need to be deleted too
````

At the moment, if I delete `User 1` I now get `Trying to get property of non-object` in the activity log.

**Comment by freekmurze** [comment]
The package does not do that for you, you'll need to take care of this yourself.
