### ISSUE TITLE
$logUnguarded [idea]

### ISSUE THREAD

**Issue by rico** [spatie/laravel-activitylog#356]
Hi,

Just started to use your package - great work, thanks!

In my models, I'm using `$guarded` much more than `$fillable`. So, `$logFillable` is not very useful for me ;-)

But something like `$logUnguarded` definitely would be. I have implemented / added it like this:

    if (isset(static::$logUnguarded) && static::$logUnguarded) {
        $attributes = array_except($this->attributes, $this->guarded);
    }

as I said, just an idea...

**Comment by Gummibeer** [comment]
You can get the same with existing variables by doing this in the `boot` method and assign the `$logFillable`.

```php
$this->logFillable array_keys(array_except($this->attributes, $this->guarded));
```

The problem I see ist to decide which variable that defines available attributes ist the most important. So If you have an attribute guarded but listet in `$logFillables` - will it be logged or not!?

**Comment by freekmurze** [comment]
I'll improve on this when creating a new major version.

**Comment by skalero01** [comment]
@rico 's code works well adding it on `DetectsChange.php`, why hasnt it been added yet?

And by the way, i cannot find the way @Gummibeer said it could be added directly on the model.. the boot method is static, how could it be done? is there any example code on the boot method?

**Comment by Gummibeer** [comment]
@skalero01 you have to specify a event listener for `booting` or `booted` event.
https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L189

You could do it multiple ways - the laravel core code is https://github.com/illuminate/database/blob/master/Eloquent/Concerns/HasEvents.php

The easiest would be to use `registerModelEvent()` in the model boot method. If you have more listeners it would be a good idea to use an observer class - to let this class cover the boot events you have to add them to `$observables` used in `getObservableEvents()`. And if you want to manage all your events in your service provider add a listener for the full event name `"eloquent.{$event}: {$name}"`. All these changes are non-destructive in opposit to your way by overriding package methods.

To move this into the package I will try to get time and take a look into laravel core how they manage `$fillable` and `$guarded`.

@freekmurze this could be a decision for the whitelist blacklist question in #347 and some other issues. Which one will lead the decision.
An idea I have in my head to solve both issues, untested, would be:

```php
$blacklist = array_merge($this->logAttributeBlack, $this->guarded);
$whitelist = array_merge($this->logAttributesWhite, $this->fillable);

$logAttributes = array_diff($whitelist, $blacklist);
```

*Some conditions missing and readable not final variable names.*

Have to check if this works but this could be the easiest way to give the most flexibility.

**Comment by freekmurze** [comment]
@Gummibeer Feel free to whip up a PR for this.
