### ISSUE TITLE
Trait not found  error on upgrade from old activity log package to new.

### ISSUE THREAD

**Issue by atulshrma91** [spatie/laravel-activitylog#362]
I have upgraded laravel 5.1 to laravel 5.5.
I did this -

Simply comment out the line within the ServiceProvider, publish the migration, rename the class in the new migration file to something like CreateNewActivityLogTable and then run composer dump

But now project I'm getting trait missing. "Trait 'Spatie\Activitylog\LogsActivity' not found"

LogsActivity.php is found in \vendor\spatie\laravel-activitylog\src\Traits in my installation. my composer has "spatie/laravel-activitylog": "^2.5"

I have migrated the new activity log table, manually added content to app/activitylog.php and in service provider array added "Spatie\Activitylog\ActivitylogServiceProvider::class,"

**Comment by freekmurze** [comment]
Did you try dumping your autoloader?

**Comment by atulshrma91** [comment]
yes. I did composer dump-autoload.

my model is like 

use Spatie\Activitylog\LogsActivityInterface;
use Spatie\Activitylog\LogsActivity;
 
class Rol extends Model implements LogsActivityInterface
{
    use LogsActivity;
}

**Comment by atulshrma91** [comment]
ok I got it I have to update the class the on every model that I have created . 

use Spatie\Activitylog\Traits\LogsActivity;

it works. thanks
