### ISSUE TITLE
Log property updates as separate entries

### ISSUE THREAD

**Issue by randohinn** [spatie/laravel-activitylog#365]
Is there a way to log each property update on a `$model->save();`, as a separate `updated` entry to the logs database? If so, then how?

**Comment by Gummibeer** [comment]
For what? If it's for display you can simply achieve this by `foreach activity - foreach changedAttribute`.
This will save you from exploding your database (big models or frequent changes).
Cause of the fact that the properties are stored as collection and not as JSON you can't query it in any case.
If you want to be able to do things like `$model->activities()->byProperty('column')->get()` you have to change the whole logic and model including database.
What's possible, but it would be easier to copy the remaining used code (observer) and do it your own.
