### ISSUE TITLE
Migration .stub

### ISSUE THREAD

**Issue by EmilMoe** [spatie/laravel-activitylog#366]
How come the migration file is called `.stub`? As far as I can see, it's impossible to migrate it?

`laravel-activitylog/migrations/create_activity_log_table.php.stub`

**Comment by freekmurze** [comment]
The service provider publishes that stub when publishing the migration: https://github.com/spatie/laravel-activitylog/blob/8dc0d56ecc53f8a87ca0dad8ba97663e1205f2f1/src/ActivitylogServiceProvider.php#L27
