### ISSUE TITLE
activitylog:clean

### ISSUE THREAD

**Issue by freel132** [spatie/laravel-activitylog#37]
Command php artisan activitylog:clean not working. 
I have records in table activity_log

Artisan returns:
Cleaning activity log...
Deleted 0 record(s) from the activity log.
All done!

**Comment by freel132** [comment]
Ups.. forgot to change check what is in config file.

**Comment by sanjeevkse** [comment]
@freel132 May I know, what is the solution? how did you fixed it?

**Comment by alexteh** [comment]
@freel132 May I know what config key did you change to make that solution?

**Comment by Benyaminrmb** [comment]
`php artisan activitylog:clean --days=0`
will do the job

**Comment by dedysquarepant** [comment]
> `php artisan activitylog:clean --days=0` will do the job

it works! thank you Mr.Benyaminrmb
