### ISSUE TITLE
Feature: rollback function

### ISSUE THREAD

**Issue by jozeflambrecht** [spatie/laravel-activitylog#371]
I am using this wonderful package to log my model events (updated attributes). I was wondering if a rollback function (to a previous state) would be a useful enhancement for this package or if this would be considered as not in the scope of this package ..

**Comment by freekmurze** [comment]
I consider rolling back out of scope for this package.

**Comment by Gummibeer** [comment]
@jozeflambrecht cause of the complexity I agree that it's out of scope. But I think that this could be a perfect extension package for this one. 

Why so complex? Cause there are a lot of variables depending on use case how to roll back.
Do you want to roll back a single field or everything that happens back to wanted log entry. The most complex and possibly "unsolvable" problem are relationships - in most cases it's not enough to roll back a single entity.

**Comment by dicarlosystems** [comment]
I agree about the out of scope but also agree @Gummibeer about the possibility of an extension.  Rolling back would necessitate rolling back the entire hierarchy of changes above the point of rollback but would provide a useful means of "undoing" mistakes.  It does bring up security concerns undoing things but a complete log could be made by logging the rollback actions.  I think it could get a bit messy though with all the possibly related entities.
