### ISSUE TITLE
Log everything

### ISSUE THREAD

**Issue by leopinzon** [spatie/laravel-activitylog#372]
Hi guys, in advanced thanks for the effort, really.

I need to log _everything_ that my users do in the app... How can I achieve that without writing model per model the fields to be listened?

thanks a lot

**Comment by Gummibeer** [comment]
https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events

Just use `$logFillables`.

**Comment by leopinzon** [comment]
@Gummibeer Thanks a lot for the response Gummibeer. That is exactly my question; following the documentation and your link, we all have to write each column to listen at for changes. Isn't there an option to listen just ALL the columns in all the models?

**Comment by Gummibeer** [comment]
@leopinzon no, after the first code-block it says:
> If you want to log changes to all the $fillable attributes of the model, you can specify `protected static $logFillable = true;` on the model. Let's see what gets logged when creating an instance of that model.

With this it will log changes on every fillable attribute. If you want to log every-everything you can also use the wildcard `*` - just to say it: this will also log potential private informations (passwords, tokens and other sensitive data).
> The attributes that need to be logged can be defined either by their name or you can put in a wildcard `'*'` to log any attribute that has changed.

**Comment by leopinzon** [comment]
@Gummibeer You're a saint!
I tried these options without much luck. Maybe (and I apologize for not having mentioned before) it is because I'm using the 1.* version of the package since my Laravel version is 5.3.  Anyway, writing each important column to listen at in the $logAttributes variable is working like a swiss clock. More writing at the beginning but awesome reward in the long run. Thanks gummi!

**Comment by leopinzon** [comment]
You couldn't be more right, the only problem in my case is that the system is built on a LaraAdmin system that supports - at the most- Laravel 5.3. Not happy with that but trying to make the best of it.

**Comment by JoseDguez** [comment]
Hi @leopinzon, this is what I did (laravel 5.6), I hope it helps you on 5.3...

I created a Class named BaseModel which extends from Eloquent's Model and added the attributes for log there:

`protected static $logAttributes = ['*'];`
`protected static $ignoreChangedAttributes = ['updated_by','updated_at','last_action'];`
`protected static $logOnlyDirty = true;`

The simply extend this Class in all of your models instead of Eloquent's Model

**Comment by Gummibeer** [comment]
@JoseDguez the wildcard isn't available, following the docs, in v1. But the idea with the BaseModel is good - I've switched to traits cause they are also bootable and more modular. If I need one model without a single feature but with all other I can simply don't use the particular trait. With the BaseModel I had to copy all needed features or add feature switch properties.
