### ISSUE TITLE
Subject type for class that extends

### ISSUE THREAD

**Issue by gogromat** [spatie/laravel-activitylog#378]
I have a question about the subject_type.

I have two classes like so

```php
namespace App;

use Spatie\Activitylog\Traits\LogsActivity;

class File extends Model {
   use LogsActivity;
}

class SomeSpecialFile extends File {
}
```

and when I try to save an activity on an instance of ```App\SomeSpecialFile```, I see that
the subject type becomes ```App\SomeSpecialFile``` instead of ```App\File``` (which is probably expected).

My question is if a library can define $subject_type on a class so that I can say something like
```public $subject_type = File::class;``` or ```performedOn``` could accept a second parameter to specify a "real" subject type, like ```->performedOn($someSpecialFile, File::class)```

**Comment by Gummibeer** [comment]
Subject type is part of the eloquent Morph Relation. You can define the morph type but it will lead to problems if two models have the same type. So I would say: let it like it is and adjust your switch, add another method like `getSubjectType` for your own use.

**Comment by gogromat** [comment]
Sorry @Gummibeer, I did not understand about the switch.

But I looked more into morph relation and I ended up adding getMorphClass method
to my SomeSpecialFile class:

```php
class SomeSpecialFile extends File {
    function getMorphClass () {
        return File::class;
    }
}
```
and now logs generate desired subject_type.

Thanks a lot!

**Comment by Gummibeer** [comment]
But keep in mind that all morphed relations will resolve to the simple file, if possible. That was the thing I mean.
