### ISSUE TITLE
Do not log unchanged attributes

### ISSUE THREAD

**Issue by uyab** [spatie/laravel-activitylog#38]
`$activity->changes` should only return attributes that changes and listed in `$logAttributes`. 

Maybe by utilize Eloquent `getDirty()` method when saving logs.

**Comment by sebastiandedeyne** [comment]
I don't think it's necessarily wrong to keep all values in `changes`. Gonna need @freekmurze's opinion on this.

Either way it would be a breaking change, so not for this version anymore.

**Comment by freekmurze** [comment]
Changing the behaviour now would indeed be a breaking change. I'll consider changing this in the next major release.
