### ISSUE TITLE
Customizing the (login / logout) log name

### ISSUE THREAD

**Issue by DjKhireddine** [spatie/laravel-activitylog#381]
Other question please,

How to customize the (login / logout) log name?
I alredy customized the user Model but still have 'default' when login/logout activity.

THanks

**Comment by Gummibeer** [comment]
Which login/logout (auth) event do you mean? So far I know there is no auth-event logging by default!?

**Comment by decomstore** [comment]
Yes I mean auth event.
this is my code in AuthenticatesUsers.php

`
protected function authenticated(Request $request, $user)
	{
		activity()
			->causedBy($user)
			->performedOn($user)
			->withProperties(['type' => 'info'])
			->log('Connexion');
	}
`
The log name stored in db is 'default'

**Comment by peric0** [comment]
Hello, I am having a project with Laravel 5.6 and I want to register the login and logout of the users but I do not know where to use activity ().

**Comment by freekmurze** [comment]
@peric0 Laravel fires off an event when a user logs in / out: https://laravel.com/api/5.6/Illuminate/Auth/Events/Login.html

You can listen for those events.

If you have more questions, please open up a new issue.
