### ISSUE TITLE
Do not record the logs during the test.

### ISSUE THREAD

**Issue by pedrosalpr** [spatie/laravel-activitylog#382]
How do I not to write the logs during the test run?

Is there any property that I identify not to run in certain environments?

**Comment by Gummibeer** [comment]
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#disabling-logging-on-demand

**Comment by pedrosalpr** [comment]
I put it that way, but it did not work.

```
class FreteCreateLimiteTest extends TestCase
{

    protected $enableLoggingModelsEvents = false;

    public function setUp()
    {
        parent::setUp();
       ...
    }
}
```
Could you exemplify in test cases?

**Comment by Gummibeer** [comment]
You have to put this property on the models you are logging events on.

**Comment by pedrosalpr** [comment]
Error, when put property on the model.

`PHP Fatal error:  App\Models\Frete and Spatie\Activitylog\Traits\LogsActivity define the same property ($enableLoggingModelsEvents) in the composition of App\Models\Frete. However, the definition differs and is considered incompatible.`

**Comment by pedrosalpr** [comment]
On the model, put this:

```
public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        if (App::environment('testing')) {
            self::disableLogging();
        }
    }
```

**Comment by JonathanAspeling** [comment]
Busy looking for an answer to an issue with testing logging my side too - so just leaving this here for any future travellers:

New Method also added that you can call in test method if you want to that should solve this query too:
```
activity()->disableLogging();

/* Your Test Logic here */

activity()->enableLogging();
```
