### ISSUE TITLE
Accessor attribute doesn't log if it not in $appends array.

### ISSUE THREAD

**Issue by fotonmoton** [spatie/laravel-activitylog#383]
Is it intended behavior? If so, I think, it's good to point out this moment in documentation.

Update:
I foregt to say, that I use 1.16.0 version on laravel 5.4

Update 2:

Accessor attribute get equal value in "attributes" and "old" arrays. So, as I can see, I can't use dynamic attributes to log changes. Where I can find contribution process, maybe I can implement this feature.

**Comment by Gummibeer** [comment]
An accessor attribute isn't an attribute like all the others. And primary an accessor attribute doesn't have an old and dirty state.

**Comment by fotonmoton** [comment]
Thanks for clarifying. Maybe I can be wrong, but in $changes property of Activity class contains a serialized model (If I use LogsActivity trait). So, if I append to a serialized model dynamic attribute and in next update it changes log will contain changes. I think this is crucial feature and worth noting in documentation.

**Comment by fotonmoton** [comment]
Sorry for link to your concurrent, but it will be cool if this package has something like [this](http://www.laravel-auditing.com/docs/7.0/audit-transformation).

**Comment by freekmurze** [comment]
That's out of scope for this package, implement that in your own app.
