### ISSUE TITLE
Many to many tracking

### ISSUE THREAD

**Issue by fernandocoronatomf** [spatie/laravel-activitylog#386]
Hi there,

Is there any way to track a many to many relation?

Thank you

**Comment by Gummibeer** [comment]
What do you want to achieve? Do you want to have the relations in the log? Or do you want to trigger a log if anything on the relation happens? Or what is your goal?

**Comment by fernandocoronatomf** [comment]
For instance:

Project hasMany Tags

I added a tag on the project and that should be stored in the DB

**Comment by Gummibeer** [comment]
For this you have to use custom logging - but it's possible without problems with this library.

**Comment by fernandocoronatomf** [comment]
Where can I find an example to do that?
This is somehow difficult as Laravel does not provide a way to listen to pivotAttached events, for example

**Comment by eumanito** [comment]
@fernandocoronatomf Did you succeed? If so, please post an example. Thanks.

**Comment by fernandocoronatomf** [comment]
@eumanito I ended up not using this package and used the audit package instead...
But none of them have a out of the box solution for many to many, so I created event/listeners and added custom logic to add many to many and many to many polymorphic relations log

**Comment by eumanito** [comment]
@fernandocoronatomf 
I'm trying this with the Laravel Audits package. Please, can you send me the event/listeners files?
eumanito@gmail.com
Thanks.
