### ISSUE TITLE
Fetching activitylog for a specific model instance

### ISSUE THREAD

**Issue by sohilcodeembassy** [spatie/laravel-activitylog#388]
How to Fetch activitylog for a specific model instance

![localhost 127 0 0 1 saas activity_log phpmyadmin 4 7 4](https://user-images.githubusercontent.com/33115493/41083685-6c3244ec-6a4f-11e8-9ccd-20ef9c99c486.png)

**Comment by sohilcodeembassy** [comment]
This is working fine

1) Answer

 $inventory = new Inventory();
 Activity::where('subject_type',get_class($inventory))->get();
2) Answer

 $inventory = new Inventory();
 Activity::forSubject($inventory)->get();
You have just edit below function in this path vendor/spatie/laravel-activitylog/src/models/Activity.php

public function scopeForSubject(Builder $query, Model $subject): Builder
    {
        return $query
            ->where('subject_type', $subject->getMorphClass())
            ->orWhere('subject_id', $subject->getKey());
    }

**Comment by Gummibeer** [comment]
Just use this trait https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/HasActivity.php

**Comment by gabrielbomfimoliveira** [comment]
I have this question:
How would the query for a specific model instance look when using this trait?

$estoque = new Estoque();
Activity::query->get();

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/blob/1f5d1b966187b2d11995d0d1898a2d4fb44b5c67/src/Traits/LogsActivity.php#L120-L123
