### ISSUE TITLE
Activity Model Logging, Let us ignore console changes.

### ISSUE THREAD

**Issue by marky291** [spatie/laravel-activitylog#389]
I use migration tables for both new tables and new data inserts based on its 'revision' based system.

I have read you can use the disable logging feature however this is cumbersome when it appears on 100 different files and will appear in future files, I am proposing a change where data cannot be logged if it is running in console (config), or having a configuration for a different 'log type' to weed this out when displaying back the activity log of all users.

**Comment by Gummibeer** [comment]
But console are also other artisan commands that could add/change data. Like a `user:create` command.

So a general disable in console isn't cool.^^
I would recommend you to create a trait or abstract class with a setup/before and teardown/after method that handles the log dis/enable logic and you are fine.

**Comment by marky291** [comment]
I thought this was to show user activity?

Console isn't a user... Or am I wrong ?

**Comment by freekmurze** [comment]
Thanks for your suggestion. I think the vast majority of users doesn't need this option and I'd like to keep this package as simple as possible.

**Comment by Gummibeer** [comment]
It depends on your app - even on console you can have an user. Imagine MySQL CLI or other tools like this.
And on the other hand this also creates some kind of change log for a model.
