### ISSUE TITLE
Including IP Address of the Causer

### ISSUE THREAD

**Issue by gauravmak** [spatie/laravel-activitylog#39]
It would be a good feature specially when users are generally logging in from different places. And it would help with tracking as well.

**Comment by freekmurze** [comment]
You could use a [custom property][https://docs.spatie.be/laravel-activitylog/v1/basic-usage/logging-activity#setting-custom-properties] to hold the ip address.

**Comment by gauravmak** [comment]
Would it be possible with automatic logging model events anyhow?

**Comment by sebastiandedeyne** [comment]
Hmm not out of the box.

However, you could use an Eloquent `saving` event to add it yourself before the record gets saved.

```php
use Spatie\Activitylog\Models\Activity;

Activity::saving(function (Activity $activity) {
    $activity->properties->put('ip', '127.0.0.1');
});
```

**Comment by gauravmak** [comment]
Thank you @sebastiandedeyne. This code will need to be put in every model class for which I want to store IP adress, right? Can there be any way to achieve DRY stage?

**Comment by sebastiandedeyne** [comment]
It works the other way around, it gets called every time `Activity` gets logged, not on a per model basis. If you only want to log the IP for certain models, you'd have to add a conditional to the closure.

Quick example (untested):

```php
use Spatie\Activitylog\Models\Activity;

Activity::saving(function (Activity $activity) {

    $addIpTo = collect([
        App\Models\Foo::class,
        App\Models\Bar::class,
    ]);

    if ($addIpTo->contains(get_class($activity->subject))) {
        $activity->properties->put('ip', '127.0.0.1');
    }
});
```

**Comment by padre** [comment]
Hi, I try $activity->properties->put('ip', '127.0.0.1') but not working.

Example:

$lastActivity = Activity::all()->last();
//now $lastActivity->properties ={"attributes":{"name":"name","email":"email@domain.com"}}

$lastActivity->properties->put('ip', '127.0.0.1');
//now $lastActivity->properties = {"attributes": "name":"name","email":"email@domain.com"}}

The method "put" doesn't update the collection :-(

PD: with laravel-activitylog v1.3.1 because I use laravel 5.1. 

Thanks!

**Comment by diazsasak** [comment]
where do i place the code that you suggest ?
`use Spatie\Activitylog\Models\Activity;

Activity::saving(function (Activity $activity) {
    $activity->properties->put('ip', '127.0.0.1');
});`

**Comment by sebastiandedeyne** [comment]
Doesn't really matter, as long as it gets executed once. You could create a service provider and place it in the `boot` method.

**Comment by dct24** [comment]
The method "put" doesn't update the collection :-(

**Comment by sebastiandedeyne** [comment]
Oh, probably will have to do:

```
$activity->properties = $activity->properties->put('ip', '...');
```

**Comment by bolechen** [comment]
put this code in `boot` method in the `AppServiceProvider.php` is work for me

```php
        Activity::saving(function (Activity $activity) {
            $activity->properties = $activity->properties->put('ip', request()->ip());
        });
```

**Comment by ospira** [comment]
My apologies, but would the maintainers accept a pull request for this feature? It appears to have been [requested](https://github.com/spatie/laravel-activitylog/issues/142) [several]( https://github.com/spatie/laravel-activitylog/issues/48) [times]( https://github.com/spatie/laravel-activitylog/issues/384)  and I would love to help contribute directly to this project in this regard. I believe doing it in the package itself may be cleaner than putting code in the `AppServiceProvider` and would also be easier and more friendly for the general user. 

Furthermore, IP is not always statically derived. By this I mean, it could be `'HTTP_X_FORWARDED_FOR'` or `'REMOTE_ADDR'`, and it may be helpful for the user to make this configurable and it would seem to be useful, maybe with a flag to disable it so it does not bloat the application. We could also add an option for storing the user agent as well. :) 

Please let me know if such a pull request would be acceptable.

Thank you very much for your time and consideration. :)

**Comment by Gummibeer** [comment]
@ospira I would like to reject this because:
1. the IP is part of private/personal data - which have to be handled special in europe and I would think also in other countries
2. there are several ways users may want to save the IP address. I would like to add a relation to my `device` model which contains all data. Others may want to save it in an extra column or as part of the properties.

After all I also don't think that the effort to add this functionality is too much for the user. But if you want to provide it you can feel free to create your own package wich depends on `spatie/laravel-activitylog` and adds the logic needed to also log IP and useragent.

**Comment by amiiiiiink** [comment]
hi, I have a question related to this issue , I wanted to add ip , OS , Browser name , browser version
into my logs, i have added 
$activity->properties = $activity->properties
            ->put('ip', request()->ip())
            ->put('os', Browser::platformName())
            ->put('browser', Browser::browserName())
            ->put('BrowserVersion', Browser::browserVersion());
my question is that where is put() method? and do we have any putAll() or similar method to add all IP, OS, Browser , Browser version in an array?

**Comment by Gummibeer** [comment]
@amiiiiiink unser the hood it's a collection. So you could use the `merge()` method.
https://laravel.com/docs/5.8/collections#available-methods

**Comment by rijans** [comment]
I am using it  in `boot `method in the `AppServiceProvider.php`

```
Activity::saving(function (Activity $activity) {
            $activity->properties = $activity->properties->put('agent', [
                'ip' => Request::ip(),
                'browser' => \Browser::browserName(),
                'os' => \Browser::platformName(),
                'url' => Request::fullUrl(),
            ]);
        });
```
