### ISSUE TITLE
Logging model events for pivot table 

### ISSUE THREAD

**Issue by gamevnlc** [spatie/laravel-activitylog#390]
How to automatically log events for pivot table. I have create model for pivot table and add `HasActivity `traits but nothing logs

**Comment by freekmurze** [comment]
I guess that your pivot table is automatically updated by Laravel. In that case no model events for the model you created are fired. Our package hooks into these events.

Try manually updating the model for your pivot table and report back if that works.

**Comment by gamevnlc** [comment]
@freekmurze 
I have tried manually updating the model but it required the instance of Model but my pivot table is an instance of Pivot . How could I pass an instance of Pivot table ?

My code 

```
activity()
                ->performedOn('App\Models\Client\ClientContact\ClientContact')
                ->causedBy(auth()->user())
                ->withProperties([$contactTypeId => $data])
                ->log('Sync Client Contact');
```
