### ISSUE TITLE
Activity logs twice when extending Trait from LogsActivity

### ISSUE THREAD

**Issue by thc1967** [spatie/laravel-activitylog#392]
I've probably done something wrong, and I can stop the double logging as I describe below. But I'd like to use my own Trait as an extension of the LogsActivity Trait to keep my code just a bit cleaner.

I've extended my own Trait from Spatie\Activitylog\Traits\LogsActivity as follows:

```php
namespace App\Traits;

use Spatie\Activitylog\Traits\LogsActivity as SpatieLogsActivity;

trait LogsActivity
{
    use SpatieLogsActivity;

    /**
     * Log only changed properties
     *
     * @var boolean
     */
    protected static $logOnlyDirty = true;

    /**
     * The custom log name for the model
     *
     * @param string $eventName
     * @return string
     */
    public function getLogNameToUse(string $eventName = ''): string
    {
        return str_plural(strtolower(class_basename($this)));
    }
}
```

When I apply this Trait to any Model class, the system puts two rows in the activity_log table for each change to a Model record.

If, on the other hand, I don't use my extended Trait and instead apply the Spatie LogsActivity Trait to my Model class, I get only one entry in the activity_log table for each change to a Model record.

This seems to mean that there's something in the way I've extended the Trait, or in PHP's Trait handling, that causes the double logging. If it were something happening in the Model, I would expect to get two log entries regardless which Trait I associated to the Model.

The repo here https://github.com/thc1967/SpatieSortableExtendTraitDemo is a barebones demo of the issue.

I use Tinker to create and save a "Widget" object and poof, two entries in the activity_log table. Switch the Widget model to use the core Spatie LogsActivity trait instead of the extended one and we get one log entry.

```
// Tinker
$w = new Widget();
$w->name = 'foo';
$w->save();
```

Result is either 1 or 2 entries in activity_log depending on whether we're using the core Trait or extended Trait.

**Comment by thc1967** [comment]
This issue can be closed.

If I rename the extended Trait to anything else, even if I alias it in my `use` statement, it only logs one entry. PHP issue, perhaps? Definitely not Spatie's problem though.

**Comment by Gummibeer** [comment]
Just an idea - the trait is booted by the special bootXyzTrait method. This is generated done by a reflection class and so on. If you have two traits with the same name it could be that the method is executed two times. If so it will add the observer two times.

So if I'm right this is a laravel core issue. Could you try to verify this with a simple dump in the boot method for example?

**Comment by thc1967** [comment]
I've inserted a dump into the Laravel code's Model `bootTraits()` method as follows:

```php
    protected static function bootTraits()
    {
        $class = static::class;

        foreach (class_uses_recursive($class) as $trait) {
            if (method_exists($class, $method = 'boot'.class_basename($trait))) {
                dump('booting ' . $trait);
                forward_static_call([$class, $method]);
            }
        }
    }
```

When I Tinker and type `$w = new Widget();`, I get the following dump. Notice the two LogsActivity traits.

```
"booting App\Traits\LogsActivity"
"booting Spatie\Activitylog\Traits\LogsActivity"
"booting Spatie\Activitylog\Traits\DetectsChanges"
```
When I rename my Trait to `MyLogsActivity` and alias that as `LogsActivity` in my Model class, I get the following with the same action:

```php
use App\Traits\MyLogsActivity as LogsActivity;
class Widget extends Model
{
    use LogsActivity;
```

```
"booting Spatie\Activitylog\Traits\LogsActivity"
"booting Spatie\Activitylog\Traits\DetectsChanges"
```

Given my relative inexperience with PHP and Laravel, I'm not sure what to make of the difference. There's a simple, public Github project referenced in the original post that makes this easily reproducible.

**Comment by Gummibeer** [comment]
Ok, this is just the prove that laravel executes the same bootXyzTrait method multiple times if the base class name of multiple traits are the same.
As a solution for you I recommend to rename your trait to `AppLogsActivity` or `LogsActivityTrait or something like this to prevent this error.

https://github.com/laravel/framework/issues/24548

**Comment by Gummibeer** [comment]
It's fixed in https://github.com/laravel/framework/pull/24556

**Comment by eduarguz** [comment]
Thank you guys for the well explained issue and the given updates, fixed the same issue in no time.
