### ISSUE TITLE
ignoreChangedAttributes not working

### ISSUE THREAD

**Issue by robincsamuel** [spatie/laravel-activitylog#393]
ignoreChangedAttributes is not working for me.

The following is my configuration. 

```
    protected static $ignoreChangedAttributes = [ 'updated_at'];
    protected static $logAttributes = ['*'];
    protected static $logOnlyDirty = true;
```

Also, activity is not getting logged if I update user profile like,

`$user->profile()->update($profile);`

But it works If I do,

`$profile->save()`

**Comment by Gummibeer** [comment]
`$user->profile->update ($profile)` should work. If you use profile as a method and not as attribute you get a query builder instance instead of a model. Cause of this the observer isn't executed cause it doesn't know which model it is.

Try it with profile as a property which is the resolved model instance.

**Comment by Gummibeer** [comment]
What's not working?

I bet that you want this attribute to be removed!? This isn't the case for this setting.
It just prevents a log if only these attributes are changed.

So if you do `$model->touch()` it won't log an update. But if you do `$model->update(['name' => 'new'])` it will log `name` and `updated_at` in one entry cause another attribute is changed and it logs all dirty ones.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/DetectsChanges.php `attributesToBeLogged()`

Here you can see and/or change the logic to your needs.

**Comment by robincsamuel** [comment]
Oh ok. You're right, I just don't want to track changes to `updated_at`. Thanks for sharing the details, I'll change the logic to suit my needs :)
