### ISSUE TITLE
Manually log for pivot table not working 

### ISSUE THREAD

**Issue by gamevnlc** [spatie/laravel-activitylog#395]
I have tried manually updating the model but it required the instance of Model but my pivot table is an instance of Pivot . How could I pass an instance of Pivot table ?

My code

```
activity()->performedOn('App\Models\Client\ClientContact\ClientContact')
->causedBy(auth()->user())
->withProperties(['contact_type_id'=> $data])
->log('Sync Client Contact');
```

And if my properties structure is different to your. So I can't get my properties. it always return empty 

![image](https://user-images.githubusercontent.com/2215185/41222616-fa637694-6d99-11e8-85a4-a6b4c5254c5f.png)

![image](https://user-images.githubusercontent.com/2215185/41222641-11de5c8a-6d9a-11e8-973c-4e0555a7fd96.png)

**Comment by aleksandrkop** [comment]
I don't know if it could help you, but I had to log some activities for a pivot table sync. So, I manually put together the changed attributes and just created an Activity Log record like this:

**First I get the old attribute values, scanning the current pivot records**

```
foreach ($service->items()->where('parent_id', null)->orderBy('name')->get() as $row) {
            $oldData[] = ['service_item_id' => $row->pivot->service_item_id,
                          'checked'         => $row->pivot->checked,
                          'description'     => $row->pivot->description,
                          'name'            => $row->name
            ];
        }
```

**Then, I detach'em**

`$service->items()->detach();`

**Now I collect the new form data, and sync it**
```
foreach ($request->service_item_id as $i => $item) {
            $syncData[] = ['service_item_id' => $item,
                           'checked'         => (isset($request->service_item_checked[$i])) ? $request->service_item_checked[$i] : 0,
                           'description'     => (isset($request->service_item_description[$i])) ? $request->service_item_description[$i] : ''
            ];
        }

        $service->items()->sync($syncData);
```

**Finally, I compare the OLD DATA with the New Synced data, store it in an array and create a log with custom name (useLog) and custom properties (withProperties)**
```
foreach ($oldData as $i => $old) {
            if ($old['checked'] == 0 && $syncData[$i]['checked'] != 0) {
                $changes[$old['name']] = 'Marcado';
            } else if ($old['checked'] != 0 && $syncData[$i]['checked'] == 0) {
                $changes[$old['name']] = 'Desmarcado';
            }
        }

        if (isset($changes)) {
            activity()
                ->useLog('OSChecklist')
                ->causedBy(auth()->user()->id)
                ->performedOn($service)
                ->withProperties($changes)
                ->log('updated');
        }
```

I understand that my scenario is slightly different, but the logic is the same:

1. Get you old data before detach/sync

2. Get your new data and compare it with the old data

3. Get the result of step 2 and store a new custom log

**Comment by danhunsaker** [comment]
This is an odd behavior, since `Pivot` extends `Model` anyway...

https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Relations/Pivot.php#L9

**Comment by freekmurze** [comment]
@gamevnlc Could you PR a failing test for us to look at?

**Comment by luchorengo** [comment]
Hi, I'm working on Laravel 5.8 and this seems to be not working.

This is my custom Model that extends a Pivot model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

// Activity Log
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\Contracts\Activity;

class MaterialWork extends Pivot
{
    //
    use LogsActivity;

    protected $table 	= 'material_work';
    protected $fillable = ['qty', 'width', 'height', 'price', 'total', 'work_id', 'material_id'];
    protected $dates = ['created_at','updated_at','deleted_at'];

    // Activity Log
    protected static $logFillable = true;
    protected static $submitEmptyLogs = false;
    protected static $logOnlyDirty = true;

    public function tapActivity(Activity $activity, string $eventName)
    {
        $activity->parent_id = $this->work_id;
    }
}
```
Any recommendation about how to fix it? I'm not getting any activity on create, update nor delete.

**Comment by dmitriytretyakov** [comment]
1. I think you must use relation with using() method, like:
`return $this->belongsToMany(Employee::class)->using(DepartmentEmployee::class)`
not like:

`return $this->belongsToMany(Employee::class, 'departments_staff', 'department_id', 'employee_id');`

2. Add ID column to pivot table and add public `public $incrementing = true;`  to your pivot model class.

P.S. After first step deletes logs fixed, after second created logs fixed.
P.S.S. I don't know why, but in deletes logs for pivot tables subject_id column is null.

**Comment by dmitriytretyakov** [comment]
Update: id nullable while deleting because laravel method InteractsWithPivotTable-> detachUsingCustomClass() create pivot object from model keys

` protected function detachUsingCustomClass($ids)
    {
        $results = 0;

        foreach ($this->parseIds($ids) as $id) {
            $results += $this->newPivot([
                $this->foreignPivotKey => $this->parent->{$this->parentKey},
                $this->relatedPivotKey => $id,
            ], true)->delete();
        }

        return $results;
    }`

To fix this use can create trait with boot method:

`public static function boot()
    {
        parent::boot();

        static::deleting(function (DepartmentEmployee $model) {
            if(!$model->id) {
                $q = static::select(['id']);
                foreach($model->getAttributes() as $key => $value) {
                    $q->where($key, $value);
                }
                $model->id = $q->first()->id;
            }
        });
    }`
