### ISSUE TITLE
Custom table name on extended model breaks 

### ISSUE THREAD

**Issue by mdcass** [spatie/laravel-activitylog#396]
Updated from 2.5.1 to 2.7.0, have a custom `Activity` model with a `$table` property set.

[This](https://github.com/spatie/laravel-activitylog/commit/5b6f4d06d5b59d64f78ba127f4724cd7c776e2fb#diff-8e892e84fd9bfb4502030f42514f913fR22) change in `Spatie\Activitylog\Models\Activity` which overwrites that property from config is a bit too assumptive.

Logic should be along the lines of `$this->table = $this->table ?? config('activitylog.table_name')`

**Comment by miclf** [comment]
Hey, good catch, @mdcass !

If I understand correctly, you’re using a custom table name in a custom `Activity` model, right?

When working on #361 a few months back my focus was mainly on the migration file. As the table name in the model was hardcoded, I did not expect any side effect involving a custom child class.

The fix you propose seems right to me. Do you plan to make a pull request or would you like me to work on one? (note that I won’t really have time to do so before next week-end)

**Comment by mdcass** [comment]
If I get some time this week i'll submit a PR!

**Comment by Cholowao** [comment]
@mdcass you got time????




























..
.
.


.
.
.
.

**Comment by mdcass** [comment]
I've not had chance to take a look unfortunately, i've not got the repo set up locally

**Comment by freekmurze** [comment]
Will be fixed soon through #427
