### ISSUE TITLE
Invalid credentials on install

### ISSUE THREAD

**Issue by zauradigozalov** [spatie/laravel-activitylog#397]
Dear support,
I'm experiencing an error on installation step. After running composer install it requires authentication on packagist. After providing credentials composer returns below issue:

[Composer\Downloader\TransportException]
  Invalid credentials for 'http://packagist.org/p/spatie/laravel-activitylog%
  241ca06edcd7dfbce47886ce7243a549cf34b684bf57d4c35a4acbd09fc209aadf.json', a
  borting.

And it's crashing. Thank you

**Comment by freekmurze** [comment]
This issue is unrelated to this repo. Post your issue on the composer repo.
