### ISSUE TITLE
Encoding Characters "\u00c3"

### ISSUE THREAD

**Issue by miltonsg** [spatie/laravel-activitylog#398]
Laravel ActivityLog is encoding the characters (á, é, í...), as in the example below:

{"attributes":{"name":"\u00c3\u0089\u00c3\u00a1\u00c3\u00ad\u00c3","updated_at":"2018-07-10 17:48:03"},"old":{"name":"\u00c9\u00e1\u00ed\u00f3\u00e1","updated_at":"2018-07-10 17:47:39"}}

How to proceed?

DB: Mysql

Tks.

**Comment by Gummibeer** [comment]
This is related to the `json_encode()` which is pretty right - but it's resolved by calling `json_decode()` during get the attributes. So in your application you shouldn't see these encoded values.

**Comment by miltonsg** [comment]
I'm using the package to automatically record events in the model:

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Brand extends Model
{
    use LogsActivity;

    protected $fillable = [
        "name", "description"
    ];

    protected static $logOnlyDirty = true;
    protected static $logAttributes = ['*'];

}

Should I change the ActivityLogger class?

Tks.

**Comment by Gummibeer** [comment]
No, everything is right - but if you load the activities in your PHP code the json encoded attributes will be decoded by laravel. So if it's just "ugly" in your database everything works fine.

**Comment by miltonsg** [comment]
Thank You Gummibeer.
