### ISSUE TITLE
Customize Event Login

### ISSUE THREAD

**Issue by Tarcisiofl** [spatie/laravel-activitylog#399]
Hello Spatie,

I already have installed your package via composer, then I set it to two of my models as below:

**User Model**
  
    class User extends Authenticatable
    {
        use Notifiable;
        use SoftDeletes;
        use LogsActivity;
        use CausesActivity;
    
        protected $fillable = ['name', 'email', 'password'];
        protected $hidden = ['password', 'remember_token' ];
    
        protected static $logOnlyDirty = true;
    
        public function projects()
        {
            return $this->hasMany('App\Project', 'user_id');
        }
    }

**Project Model**

    class Project extends Model
    {
        use SoftDeletes;
        use Rememberable;
        use LogsActivity;
    
        protected $fillable = ['name', 'description', 'contract', 'price'];
        protected $guarded = ['id', 'created_at', 'update_at'];
        protected $table = 'projects';
    
        protected static $logOnlyDirty = true;
    
        public function user()
        {
            return $this->belongsTo('App\User');
        }
    }

How can I customize the description to be as in the attachment?
![q2stizy](https://user-images.githubusercontent.com/1232004/42818366-14cca18a-89a7-11e8-8e80-e587d084fafe.png)

**Comment by joveice** [comment]
https://docs.spatie.be/laravel-activitylog/v2/advanced-usage/logging-model-events#customizing-the-description
