### ISSUE TITLE
Allowing Placeholders in getDescriptionForEvent

### ISSUE THREAD

**Issue by gauravmak** [spatie/laravel-activitylog#40]
It would be nice if one could include subject, causer, etc while [customizing the description](https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#customizing-the-description) for logging model events

**Comment by freekmurze** [comment]
You're right, that would be nice. I'd accept a PR that adds this to package in a non-breaking with (with tests)

For what it's worth: `subject` is probably just the model so you could use `$this` inside `getDescriptionForEvent` and `causer` most probably is the authenticated user.

**Comment by gauravmak** [comment]
I wish to contribute but do not have enough skills yet. So, I will need wait for the update.
