### ISSUE TITLE
update on multiple rows

### ISSUE THREAD

**Issue by itxp2008** [spatie/laravel-activitylog#400]
Hi,

Searched all over the place. Can "spatie/laravel-activitylog" track changes on multiple rows?

From what my tests:

`Model::first()->update(['something' => true])); //works.`

But for multiple rows

`Model::where('something', true)->update(['something' => false])); //doesn't.`

missing something?

**Comment by Gummibeer** [comment]
The update on multiple isn't executed on the model - so no observer will catch it.
It's executed directly on the DB Query builder.

**Comment by itxp2008** [comment]
Thanks, you're right, now I've found... verifying what you've said...

https://laravel.com/docs/5.6/eloquent#updates

Mass Updates!

> When issuing a mass update via Eloquent, the saved and updated model events will not be fired for the updated models. This is because the models are never actually retrieved when issuing a mass update.

Thanks again

**Comment by Gummibeer** [comment]
But to solve your situation:

* you can save all models with a single query (not recommended for http requests)
* you can fire a custom event which contains all the mass saved data and log a custom activity (or one for all models)

I hope that this helps you!?
