### ISSUE TITLE
Allow logger to be temporarilly disabled

### ISSUE THREAD

**Issue by Mechazawa** [spatie/laravel-activitylog#401]
Some of the scheduled jobs we have running don't need their changed to be logged. The only way to disable logging that I could find was on a [per-model basis](https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events).

Something like this would be great:
```php
activity()->disableLogging();

activity()->enableLogging();
```

This would just toggle `ActivityLogger::$logEnabled`.

It could also just always check the config value of `activitylog.enabled` because `$logEnabled` seems to be only set once.

**Comment by freekmurze** [comment]
Feel free to submit a PR!

**Comment by DemianD** [comment]
I'll take this 👍

**Comment by Mechazawa** [comment]
Whoop, thanks! The only improvement that could be could be made now is a function that returns if it's enabled or not.

**Comment by freekmurze** [comment]
@Mechazawa Feel free to send a tested and documented PR for that.
