### ISSUE TITLE
`causedBy` in model event

### ISSUE THREAD

**Issue by sohelamin** [spatie/laravel-activitylog#406]
How can I track `causedBy` in a model event using the `LogsActivity` trait?

**Comment by freekmurze** [comment]
I don't understand your question. Could you give a practical example of what you are trying to achieve?

**Comment by freekmurze** [comment]
You can do something like this (untested but hopefully you'll get the idea)


```php
$post
    ->actions
    ->first(function (Activity $activity) {
        return $activity->description === 'created';
    })
    ->user;
```
