### ISSUE TITLE
Utilizing laravel-impersonate

### ISSUE THREAD

**Issue by madStitcher** [spatie/laravel-activitylog#409]
This is not a bug, just a general question.  

We are implementing 404labfr/laravel-impersonate. When a user gets impersonated, we'd like laravel-activitylog to not only log the impersonated user, but also the user id of the impersonator. 

What method would you suggest to accomplish this goal?

Really love this package, and your laravel-permission package as well!

**Comment by Gummibeer** [comment]
Just listen for the corresponding event https://github.com/404labfr/laravel-impersonate#events and log a custom activity with your needed data.
https://docs.spatie.be/laravel-activitylog/v2/basic-usage/logging-activity
