### ISSUE TITLE
Causer and Cartalyst/Sentinel

### ISSUE THREAD

**Issue by DanielRTRD** [spatie/laravel-activitylog#414]
config/auth.php
```
<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => APP\User::class,
        ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

config/activitylog.php
```
<?php

return [
    'enabled' => env('ACTIVITY_LOGGER_ENABLED', true),
    'delete_records_older_than_days' => 365,
    'default_log_name' => 'default',
    'default_auth_driver' => null,
    'subject_returns_soft_deleted_models' => false,
    'activity_model' => \Spatie\Activitylog\Models\Activity::class,
    'table_name' => 'activity_log',
];
```

Database:
![2018-08-09 22_37_14](https://user-images.githubusercontent.com/9788214/43924393-d46246fa-9c24-11e8-9a9c-ff6ccd0f9345.png)

I am using Cartalyst/Sentinel for auth, with a modified version of the original Sentinel model. It seems like this package does not know how to get the user, how can I fix this?

**Comment by freekmurze** [comment]
We don't use Sentinel, so we can't help you with this.

**Comment by DanielRTRD** [comment]
Wow, thats stupid.

**Comment by freekmurze** [comment]
What is stupid?

**Comment by DanielRTRD** [comment]
That was a stupid answer. You could at least give some form of heading to solve the problem.

**Comment by freekmurze** [comment]
Do you think calling an answer "stupid" motivates your conversation partner to further engage with you?

Here are some interesting resources for you:
- https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/
- https://www.techrepublic.com/article/why-open-source-developers-are-burning-out-no-respect/
- https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d
- https://www.youtube.com/watch?v=fMFjO2szDnk
- https://www.youtube.com/watch?v=h7975tw0EJA

**Comment by mablae** [comment]
- https://www.youtube.com/watch?v=Ci_I0ATr748

**Comment by DanielRTRD** [comment]
I think you are overracting a bit here, I am was simply saying the answer was a bit negative and fulfilling, you could at least be guiding me to something else and/or giving me som advice instead of basically saying "f*** off". I totally understand what you are meaning, but the reaction was over the top.  Thank you for doing what you do, but take into consideration that there might be a stupid developer on the other side.

**Comment by DanielRTRD** [comment]
Back at it again, just to update others on my problem. I have tested a few things and found out this:

Setting up a test url:
```
Route::get('/test', function() {
		$auth = app('auth');
		$guard = $auth->guard();
		$user = $guard->user();
		dd($guard);
	});
```

Response on dumping guard:
```
SessionGuard {#848 ▼
  #name: "web"
  #lastAttempted: null
  #viaRemember: false
  #session: Store {#800 ▶}
  #cookie: CookieJar {#788 ▶}
  #request: Request {#55 ▶}
  #events: Dispatcher {#35 ▶}
  #loggedOut: false
  #recallAttempted: false
  #user: null
  #provider: EloquentUserProvider {#843 ▼
    #hasher: BcryptHasher {#847 ▶}
    #model: "App\User"
  }
}
```

Response on dumping user:
```
null
```

Don't know where to look now...

**Comment by V0id3d** [comment]
I feel like i may perhaps be missing something but have you logged in yet? It does not seem like you have an open session for user. There are laracast videos that explain how you can hard code a login at and it seems like thats what your missing in your test.
`
Route::get('/test', function() {
                 auth()->loginUsingId(1); // The 1 being the user id of the user
                 dd(auth()->user);
	});
`

This is hard coding that you want User with the ID of one in your route, though I am not sure what your trying to achieve.

**Comment by DanielRTRD** [comment]
@V0id3d I use Cartalyst/Sentinel and it does not touch the Laravel Authmanager, that I know of. I think that is where the problem is. So I have to use the Laravel Auth to make this work, there might be a workaround tho.

**Comment by V0id3d** [comment]
@DanielRTRD then why is it in your test that you originally put up are you using the laravel auth system?

```
Route::get('/test', function() {
		$auth = app('auth');
		$guard = $auth->guard();
		$user = $guard->user();
		dd($guard);
	});
```

**Comment by V0id3d** [comment]
As this is a closed issue, I am going to stop commenting as the alerts for others are probably real annoying but I strongly recommend you going to laracast and using spatie’s permissions as it’s real easy to understand the flow. Good luck bud.

**Comment by nsorin** [comment]
For those having the same problem (Issue with activityLog not recognizing Sentinel's User), a quick fix is to create an Observer for the `Spatie\Activitylog\ModelsActivity` Model:

```php
<?php

namespace App\Observers;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Spatie\Activitylog\Models\Activity;

class ActivityObserver
{
    public function creating(Activity $activity) {
        $user = Sentinel::getUser();

        if (isset($user)) {
            $activity->causer_id = $user->id;
            $activity->causer_type = get_class($user);
        }
    }
}

```

Then register in a ServiceProvider:

```php
Activity::observe(ActivityObserver::class);
```

This way, the causer_id can be set without overwriting anything from ActivityLog.

**Comment by vsuta** [comment]
_Then register in a ServiceProvider:
_Activity::observe(ActivityObserver::class);__
This way, the causer_id can be set without overwriting anything from ActivityLog.

This works for me.
Activity::observe(\App\Observers\ActivityObserver::class);

**Comment by Gummibeer** [comment]
You can also check if the new `ActivityLogger::tap()` and `LogsActivity::tapActivity()` methods will help you to solve it. But an observer is a more global approach and could be the better solution for your issue.
https://github.com/spatie/laravel-activitylog/releases/tag/3.2.0

**Comment by Gummibeer** [comment]
@nsorin I would adjust it to use the implemented laravel logic and respect morph maps.
```php
$activity->causer()->associate($user);
```
