### ISSUE TITLE
Custom Causer Model

### ISSUE THREAD

**Issue by Braunson** [spatie/laravel-activitylog#417]
This is more a feature request with the idea being able to set a custom model for the `causedBy` method. In my example use case I don't want to track activity by a User but instead a Contact.

Perhaps I'm seeing this backwards and instead could run a search on `performedOn` for a specific Contact to get the history of that contact for this purpose?

**Comment by dicarlosystems** [comment]
I think that would just give you the actions performed on that Contact, not the actions performed _by_ that Contact, which I don't think is what you want.

Is the User also a Contact?

**Comment by Braunson** [comment]
@dicarlosystems No a Contact is separate from a user. A user manages contacts, owns them, but a contact can be unowned also.

**Comment by dicarlosystems** [comment]
Yep, sounds like that would handle your situation.  Only issue would be if you wanted to see actions performed by a contact but that would imply the contact is a user, also.

**Comment by Braunson** [comment]
Yeah good point. I wonder if adding the option to specific the Model of the `causedBy` would require a significant change in the package.

Tabling this for now, though it would be a nice option to have instead of limiting it to the User model.
