### ISSUE TITLE
Not Working At All

### ISSUE THREAD

**Issue by icangku** [spatie/laravel-activitylog#418]
I'm using this package with Laravel and VueJS, I'm using Laravel as API but its not working, I want to have Logging Model Events

`
use Spatie\Activitylog\Traits\LogsActivity;
class Type extends Model
{
    protected $table = 'types';
    use LogsActivity;
    protected static $logFillable = true;
    protected static $recordEvents = ['created', 'updated'];
    // protected static $logAttributes = '*';
    const CREATED_BY = 'created_by';
    const UPDATED_BY = 'updated_by';

I do also use jwt token

**Comment by freekmurze** [comment]
The package does noy care what your front end or auth system you use.

Please refer to the installation page on the docs to learn how to install the package

**Comment by icangku** [comment]
I did the same like in the page

**Comment by joveice** [comment]
I don't see that you have defined $fillable?
