### ISSUE TITLE
Error message: class 'Illuminate\Auth\Guard' does not have a method 'guard'

### ISSUE THREAD

**Issue by djbobbydrake** [spatie/laravel-activitylog#42]
Hi, I'm running into this error message when attempting to log an activity:
```php
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\Guard' does not have a method 'guard'
```

And the call is something like:
```php
activity($this->log)
                ->causedBy($this->user)
                ->performedOn($this->slot)
                ->log($this->description);
```

I'm on Laravel 5.1.33. I haven't implemented guards yet. We are using Json Web Tokens and are using Laravel as a web service. Any help is appreciated.

**Comment by blueclock** [comment]
I experienced the same yesterday, also L5.1

The error occurs in ActivityLogger.php here 

$this->causedBy = $auth->guard($authDriver)->user();

Previously $this->causedBy = $auth->user();

@djbobbydrake I just rolled back to V 1.2.1 for the moment

**Comment by freekmurze** [comment]
Sorry for the inconvenience, I'll fix this asap

**Comment by freekmurze** [comment]
I seem to have accidentally used some L5.2 features in version `1.3.0`. Sorry about that. We're very careful to do not introduce this kind of breaking changes into our pakcages, but have dropped the ball here.  The easiest way to fix this is to just drop L5.1 support.

I've created a new version `1.3.1` that restores the package to the state of `1.2.1` and it is L5.1 compatible. 
Version `1.3.2` restores the functionality introduced in `1.3.0`. It's only compatible with L5.2 or above. From this version on L5.1 support is dropped.

To pull in the current version in to your project you should just run `composer update`. Composer will choose the right version.

I've put in a little note about this in the [changelog](https://github.com/spatie/laravel-activitylog/blob/master/CHANGELOG.md).

**Comment by blueclock** [comment]
Thanks

**Comment by djbobbydrake** [comment]
@freekmurze Thanks for the quick fix!
