### ISSUE TITLE
Get activity of multiple subject_types

### ISSUE THREAD

**Issue by vanrijs** [spatie/laravel-activitylog#430]
Hi!

I was wondering is there is an option to get the activity for multiple subject_types.

For example, i have two tables:
contracts
meter_positions

It would be nice if i can use: \App\Contract::first()->activity i get the activity for \App\Contract and \App\MeterPositions at the same time.

Any solution for this?

**Comment by dicarlosystems** [comment]
You could get both collections and merge them

**Comment by Gummibeer** [comment]
And for which `MeterPositions` entity should the `Contract` search for activities?
Like @dicarlosystems said - you can create a custom method that loads all activities for the other model.

**Comment by vanrijs** [comment]
Ok fixed it now like this:
$contract->activity->merge($contract->meter_positions->activity)->sortByDesc('created_at')
