### ISSUE TITLE
Link to subject?

### ISSUE THREAD

**Issue by paulcanning** [spatie/laravel-activitylog#431]
Is there a way I can easily link to the subject from a view? the log has the subject model and the ID, so I assume there is a way to present a link to the user for them to click on?

**Comment by freekmurze** [comment]
This is out of scope for the package. Add a function to generate such an url in your own project.

**Comment by Gummibeer** [comment]
@pabloguerrez this depends a lot on your routes and so on. In general I would use something like this `route('get.app.user.update', ['user' => $activity->subject->getKey()])`.
