### ISSUE TITLE
Feature Request: Add Events

### ISSUE THREAD

**Issue by DeftNerd** [spatie/laravel-activitylog#432]
It would be nice if creating ActivityLogs threw Events on these actions:

* ActivityLogger::log()
* CleanActivitylogCommand::handle()

It would allow people to create listeners to easily create notifications when certain kinds of ActivityLog events occur.

**Comment by freekmurze** [comment]
You can already do this. You could use a `creating` model event on the `activity_log` table.  And I might be wrong, but I think there's also an event that Laravel fires when an artisan command is being executed. If there is no such event, it might be worth to PR it to Laravel.

**Comment by mateo2181** [comment]
@freekmurze Can I use updating or creating event to logging activity and prevent save data? I want to prevent some user roles save data but I want to log attemps to do it.

**Comment by Gummibeer** [comment]
@mateo2181 the `eventsToBeRecorded()` method is the solution to also log other actvities by model events:
https://github.com/spatie/laravel-activitylog/blob/3bee85adf8e19e3bc0cafab56599a442014a9169/src/Traits/LogsActivity.php#L21-L52

So you can define `static::$recordEvents` with any events you want to record. Keep in mind that the `old` values are only recorded in an `updated` event. So in your `updating activity you will only have the possible new values.

**Comment by mateo2181** [comment]
Thanks! I have read the trait and understood how it works. I  have created another trait to keep clean code and use it only in some cases. I have another question: Can I only save attributes with new values? I mean, sometimes in properties field I have attributes with same value in array old and attributes.

**Comment by mateo2181** [comment]
I have read this: #513. I will try to fix it.

**Comment by Gummibeer** [comment]
In general this is done by `$logOnlyDirty = true;`. But like you already linked this doesn't work if you use a model with partial selection.
