### ISSUE TITLE
Displaying a value from an id instead of the id in what's changed

### ISSUE THREAD

**Issue by XGhozt00** [spatie/laravel-activitylog#436]
I don't see anything obvious in here if we're logging everything in the model. For example, let's say the status of what we're changing has changed, it might just log "status_id" instead of the name of the status which is from the status model. What's the correct way to convert this back? Or just log the data we want instead of the id value?

In short, updating some model field "status_id" logs the numerical id instead of the name of the status (expected). How do we make this human readable again for the log?

Edit: One idea we had was to not log those fields as part of the model logging and then use an observer to log the changes manually for those specific fields.

**Comment by hulkur** [comment]
I think model should be logged as is. That is with numeric id-s.
Later when the change is displayed it can be converted to show relations as text. As every model is different with different relations, you have to create a method for each model that knows how to convert raw model data into human readable form. Something like `Model::convertLogRow($logData)`

**Comment by XGhozt00** [comment]
Thank you, that's actually what we ended up doing. The debate was sort along the lines of how best to accomplish it and where the place those methods to parse the log. It's a bit tricky because we're working with Nova.

**Comment by Gummibeer** [comment]
If you want to fix the status name during activity creation you can define `status.name` as attribute to be logged.
https://github.com/spatie/laravel-activitylog/blob/28f481486706d22255879965f4f57b7562d13c3b/src/Traits/DetectsChanges.php#L98-L100

**Comment by XGhozt00** [comment]
Thanks @Gummibeer -- this worked perfectly. I really wish this was shown in the docs though. Damn..

**Comment by Gummibeer** [comment]
You can add it to the docs ;)
https://github.com/spatie/docs.spatie.be/tree/master/resources/views/laravel-activitylog/v2

**Comment by XGhozt00** [comment]
Hah, touché.
