### ISSUE TITLE
it_will_not_log_an_update_of_the_model_if_only_ignored_attributes_are_changed fails on TravisCI

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-activitylog#448]
The mentioned test fails sometimes on travis but it's not reproducible on local machine. And even on travis it fails in different jobs. 
> Spatie\Activitylog\Test\LogsActivityTest::it_will_not_log_an_update_of_the_model_if_only_ignored_attributes_are_changed
> Failed asserting that actual size 2 matches expected size 1.
> /home/travis/build/spatie/laravel-activitylog/tests/LogsActivityTest.php:244

* https://travis-ci.org/spatie/laravel-activitylog/jobs/442928609
* https://travis-ci.org/spatie/laravel-activitylog/jobs/443055616
* https://travis-ci.org/spatie/laravel-activitylog/jobs/443055618
* https://travis-ci.org/spatie/laravel-activitylog/jobs/443059429
* https://travis-ci.org/spatie/laravel-activitylog/jobs/443059463

**Comment by Gummibeer** [comment]
@freekmurze do you have any idea why this happens (only on travis and only sometimes)? And in best case: how to fix it?
Or should we disable this test on travis until we fixed it to don't let all PRs fail!?

**Comment by freekmurze** [comment]
I spent a bit of time investigating this, but didn't find the cause/solution. Feel free to temporarely disable the test.

**Comment by Gummibeer** [comment]
Travis is replaced by GH Actions.
