### ISSUE TITLE
I want to place the actual changes made on the database via the model in the properties automatically

### ISSUE THREAD

**Issue by josina08** [spatie/laravel-activitylog#46]
I want to place the actual changes made on the database via the model in the properties automatically. i.e. on creating a new record via a model all the data added to be placed in the properties column 

see image the properties column is empty and i want it to contain the changes made, how can i do this

![image](https://cloud.githubusercontent.com/assets/8400694/17619227/9a3542e6-608c-11e6-8c87-85cd1350bf25.png)

**Comment by freekmurze** [comment]
Did you add the `LogsActivity` trait to your model?
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events

**Comment by josina08** [comment]
yes i do [ using laravel 5.2 and php 7 ]

![image](https://cloud.githubusercontent.com/assets/8400694/17620206/58ab5958-6093-11e6-9f43-4065923fd809.png)

**Comment by josina08** [comment]
just noted i have to add this line _

> protected static $logAttributes = ['name', 'text'];

_  in the model
cant it be added automatically

**Comment by freekmurze** [comment]
No, we want this to work explicit.
