### ISSUE TITLE
How do i Use this package. read the documentation still not getting it.

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-activitylog#461]
Hello i'm new.

I developing a social network for my organisatiion, was looking for a package which will help me track user activities and found this. Read the documentation more that 5 times still not getting it ithink there is something i don't understand. Can you show me the live example of how to use this package from Model to Controller?

**Comment by Gummibeer** [comment]
Hey @antweny ,

it would be good to know what you try to achieve? For sure I can help you but it's not the goal to tell you about all possibilities with this package. 😉 
So do you try to log changes on your models, or do you want to track manual activities or what do you try?

Depending on your needs it could be that this package isn't what you need - if you want to create something like a newsfeed for a user this isn't the primary-usage of this package. I think that it would be possible to use it for that but it's not made for it.

**Comment by antweny** [comment]
Thank you for the reply,

I'm developing a proffesional platform for NGO's in Tanzania and it has different roles and different admin roles. So i wat to track all the activities performed by any admin e.g i have an Organasations table all the levels of admin can access it but have different permissions so whenever any changes made on organisation table is tracked. So will be easy for me to perfom system audit

**Comment by Gummibeer** [comment]
Ok, this is possible. This will be the documentation related to your question:
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events

You have to add the `Spatie\Activitylog\Traits\LogsActivity` trait to your `Organization` model and configure it with the `protected static $...` variables.

```php
protected static $logFillable = true;
protected static $logUnguarded = true;
protected static $logOnlyDirty = true;
protected static $logAttributes = ['name', 'text'];
protected static $ignoreChangedAttributes = ['text'];
protected static $logAttributesToIgnore = ['text'];
```

**Comment by antweny** [comment]
This is my Country Model

```
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Permission\Traits\HasRoles;

class Country extends Model
{
    use Notifiable, HasRoles, LogsActivity;

    protected $table= 'countries';

    protected $fillable = [ 'country_name', 'country_code','country_region','dial_code', 'country_info'];

    protected static $logFillable = true;
    protected static $logUnguarded = true;
    protected static $logOnlyDirty = true;
    protected static $logAttributes = ['name', 'text'];
    protected static $ignoreChangedAttributes = ['text'];
    protected static $logAttributesToIgnore = ['text'];
}
```
On a static Variable $logAttributes should i use the the protected fillable Model attributes or only name and text.

And how do i use it on controller.
This is My country controller with Inndex method of fetching all countries. So i want to track everytime a person fect data the activity is tracked.

```
<?php
namespace App\Http\Controllers;
use App\Country;
use Illuminate\Http\Request;
class CountryController extends Controller
{
    // Display a listing of the resource.
    public function index()
    {
        $this->middleware('permission:country-create');
        $countries = Country::get();
        return view('admin.countries.index')->with(compact('countries'));
}
```

i thing with this example i will understand more

**Comment by Gummibeer** [comment]
Ok, using all of these configuration Properties is a bit overhead and in some cases they conflict each other.
A basic setup for your case would be `$logFillable = true` and if you only want to see changed attributes in your log `$logOnlyDirty = true`.
This is the setup for the automated logs for change events (`created`, `updated`, `deleted`).
If you don't want to log change-events you can use `protected $enableLoggingModelsEvents = false`.

For your example, logging an event everytime an user fetches countries you can use the manual activity tracking.
https://docs.spatie.be/laravel-activitylog/v3/basic-usage/logging-activity

```php
$countries = Country::get();
activity()
  ->causedBy(\Auth::user())
  ->withProperties(['countries' => $countries->pluck('id')->toArray()])
  ->log('fetched countries');
```

If you want to create a single log entry for every single model you can use the `retrieved` event.
For this you can add `protected static $recordEvents = ['created', 'updated', 'deleted', 'retrieved'];` to your country model and it will add a log everytime a country is retrieved. Keep in mind that you have to disable the auto-model-logging if you want to query a country without a log.
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/disabling-logging

Here is a link with all default model events
https://github.com/illuminate/database/blob/71ea181b6f4f47cc6155fbdc9c7de3cbf5316f08/Eloquent/Concerns/HasEvents.php#L68-L78

**Comment by antweny** [comment]
Thank you very much this is very helpfull.

So if i want to do this 
```
$countries = Country::get();
activity()
  ->causedBy(\Auth::user())
  ->withProperties(['countries' => $countries->pluck('id')->toArray()])
  ->log('fetched countries');
```
on Model to how can i do it. Also i want something like this in my log activity table 
![logactivity](https://user-images.githubusercontent.com/28085591/48710569-d8c61d80-ec19-11e8-9278-26d8ad53e16e.png)

how do i capture the subject_id and subject_type also change the log_name to from defalut to soumthing like country so will be easy on filtering

**Comment by Gummibeer** [comment]
`activity('countries')` will use `countries` as log-name: https://github.com/spatie/laravel-activitylog/blob/master/src/helpers.php

The `subject_type` und `subject_id` could only be set if you create a log for every fetched model. So if you fetch 100 countries you will create 100 activity log entries by 100 queries.
I do not recommend this, but if you still want to do it use `->performedOn($country)`.

You could create a custom wrapper and optional a custom `CountryCollection` with a `log()` method. https://laravel.com/docs/5.7/eloquent-collections#custom-collections
This `log()` method could fill and collect all activity models and save them in one query at the end. This will save you n-1 queries.
If you want to do it that way you can't use the `ActivityLogger` but you can take a look in it to find the ways how to do it. (how to create multiple models in one query: https://github.com/laravel/framework/issues/1295 )

I hope that this helps you more and you get it working!?

**Comment by antweny** [comment]
Thank you very much for your support. God bless you.  It has been a very productive conversation with you

**Comment by Gummibeer** [comment]
Thanks. And glad that I was able to help! 😊
Is your issue solved? So can I close this?

**Comment by antweny** [comment]
Yes my issue is solved. you can close this.
