### ISSUE TITLE
Can I have only one activity log per request?

### ISSUE THREAD

**Issue by PrimozRome** [spatie/laravel-activitylog#463]
I love this package but I have a question regarding the usage. 

For example. I have User, UserProfiles and UserAddresses models. 

My app sends one request which updates all three models at the same time, in the context of User create or update. 

Laravel-activity package by default will create three entries in the activity log table - for each model one. Is it possible to configure or modify it these three logs are merged into single log, bind to the root User model?

**Comment by PrimozRome** [comment]
@Gummibeer that is a good idea. We will definitely try to do what you suggested. I understand what you mean and I think we should be able to do that. I will report back to see if solutions is flexible and scalable enough for wider use.

**Comment by Gummibeer** [comment]
The `reduceAndSaveOutstandingActivities()`method is the core of everything. There you have to decide which outstanding activities you can/will combine and how.
An idea would be to use the log-names/channels extensiv and use these as a marker which activities are combinable.
But this would be the way I would try and I think that it's possible in general. The most work will be to find a good way/logic how to combine multiple activities but don't loose important information.
