### ISSUE TITLE
Add metadata to log items

### ISSUE THREAD

**Issue by denjaland** [spatie/laravel-activitylog#466]
Hi,

When our app is running, we basically have some "metadata" that we would like to see logged on _all_ activitylog entries.  For instance, we always know the "supplier" and "customer" the request is running for, so, next to the user, I would always like to see these items added to the log as well.

What's the best way to achieve this?  
Should I listen to the `Spatie\Activitylog\Models`saving event to update the properties at that time?  That'll probably work, but not sure if it's the 'best way'...

**Comment by Gummibeer** [comment]
I see two options:
1. event listener, like you said - my favorite
2. override the log method in the manager - not so cool

It could be that we add a third option - a callback function. But if you want it everytime the event listener would be the best.
Think about cronjobs, commands and so on. They don't have a session, so write your listener to respect this. 😉
