### ISSUE TITLE
why causer_id = null??

### ISSUE THREAD

**Issue by RubickLinh** [spatie/laravel-activitylog#473]
I follow your docs and i have code: 
```php
                activity('Edit Diary')
                    ->performedOn($diary)
                    ->causedBy(Auth::user())
                    ->withProperties($data)
                    ->log('Update Diary ' . $diary->id);
```
So when log save to database, flied subject_id is null can you help me ?

**Comment by Gummibeer** [comment]
First, is your question about the `subject_id` or the `causer_id`?
Second, the causer is set to the current authenticated user by default.
https://github.com/spatie/laravel-activitylog/blob/ba9e92a3cb9cdd5806eb1d42c403b9194283b041/src/ActivityLogger.php#L44-L48
