### ISSUE TITLE
Model changes not saved when $logAttributes = '*'

### ISSUE THREAD

**Issue by sirber** [spatie/laravel-activitylog#474]
Fellowing the doc...

Model has 
```
class Stylist extends Model
{
    use LogsActivity;
    use SoftDeletes;

    protected static $logAttributes = '*';
```

DB has:
![image](https://user-images.githubusercontent.com/3911428/51183041-18b62380-189e-11e9-9e04-76fbc24758cd.png)

on laravel v5.7.20, php 7.2.14
"spatie/laravel-activitylog": "^3.1"

**Comment by sirber** [comment]
```
.\vendor\spatie\laravel-activitylog\src\Traits\DetectsChanges.php:
   36          }
   37  
   38:         if (isset(static::$logAttributes) && is_array(static::$logAttributes)) {
   39:             $attributes = array_merge($attributes, array_diff(static::$logAttributes, ['*']));
   40  
   41:             if (in_array('*', static::$logAttributes)) {
   42                  $attributes = array_merge($attributes, array_keys($this->getAttributes()));
   43              }
   44          }
```

`protected static $logAttributes = ['*'];`

I think the documentation is wrong.

**Comment by sirber** [comment]
`protected static $logAttributes = ['*'];`

worked perfectly.

**Comment by Gummibeer** [comment]
Hey @sirber ,

I've checked the documentation and it describes what you told that worked:
```php
protected static $logAttributes = ['*'];
```
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events#ignoring-attributes-from-logging

I haven't found a place where it tells to use `protected static $logAttributes = '*';`?

**Comment by sirber** [comment]
I just realized I was in v1 documentation. I don't know how I got there instead of v3.
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events

Sorry!
