### ISSUE TITLE
How do i store the data updated and the data which is deleted.

### ISSUE THREAD

**Issue by sanjit11** [spatie/laravel-activitylog#476]
Hello , I am new on implementing this and also in laravel,  while updating the data how can i get the data which is updated and the new data which is going to stored in the database ?

**Comment by Gummibeer** [comment]
Do you mean during the update itself? For this you should use model observer:
https://laravel.com/docs/5.7/eloquent#observers
Methods to use could be `$model->isDirty()` and `$model->getOriginal()`
You also don't need this package for this.

This package is to log activities in the database to access them later. Which is also possible for model events, take a look in the documentation:
https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events

**Comment by sanjit11** [comment]
Hello, 
I want to save the data which is going to be updated with the modal events as per your package.
