### ISSUE TITLE
activity relationship doesn't seem to be working anymore

### ISSUE THREAD

**Issue by redf150flames** [spatie/laravel-activitylog#479]
I had this working at one point, I have the CausesActivity trait on my user model and trying to display all of a users activity by using $user->activity (as described on https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#using-the-causesactivity-trait), but its returning null even though in my database there is activity that is caused by the user entity.

**Comment by Gummibeer** [comment]
Hey,
which version do you use? The doc link you posted is from v1 - atm we are on v3.
During v3 release we changed some of the trait methods to prevent conflicts:
https://github.com/spatie/laravel-activitylog/blob/master/UPGRADING.md
