### ISSUE TITLE
Update activity instead of insert

### ISSUE THREAD

**Issue by monlighter** [spatie/laravel-activitylog#485]
Hello is it possible to update activity? I don't want to always insert new row to db with record.

**Comment by Gummibeer** [comment]
Simply retrieve it and update it. Under the hood it's a simple eloquent model.
But it's 100% against the principles of a log - so I don't recommend it and won't add any feature related to this.

**Comment by monlighter** [comment]
@Gummibeer I am worried about amount of rows so I wanted to update it

**Comment by Gummibeer** [comment]
That's what a log is about. If you worry about the max amount of rows MySQL can handle: don't worry. 😉 
* https://dev.mysql.com/doc/mysql-reslimits-excerpt/5.7/en/table-size-limit.html
* https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

If you run an app that really will run into one of these limits:
1. switch away from MySQL for logging: #81
2. use the provided or a custom cleaning tool - you will likely not need all activities from all times available via a BD query. So you can also move them to files or whatever.
3. think about what you log as activity, if it is really needed and if you could reduce them. It would be also a way to split the log channels in multiple tables/databases.

Some of these will need adjustments to package logic - but will be possible to do without enormous effort.

Related to updating: I still have no idea what you want to update? the `updated_at` timestamp for repeated activities (login) or the properties saved in the `properties` column?
Independent of what: I don't recommend it! You will also delete old information/entries so you could also add/enable a cleaner which deletes them hard and let your table grow.

To get to the last limit - the `ID`. Atm the migration uses the `increment()` column type - which is a normal `unsigned int`.
You can change this to `bigIncrement()` which uses a `unsigned big int`. The `bigint` column type has a limit of `2^64-1` (`1.8446744e+19`) https://dev.mysql.com/doc/refman/5.5/en/integer-types.html . I know that, primary with logging, this isn't this much but the maximum MySQL provides in the fast way.
You could change this to a custom uuid column (string) - this will allow options depending of the length of your used uuid scheme. The most common `uuid4` has a maximum unique amount of `2^122` (`5.316912e+36`) https://de.wikipedia.org/wiki/Universally_Unique_Identifier .

There are also laravel packages that do this - like https://github.com/spatie/laravel-binary-uuid *unmaintained*. 

I hope that I could help you with all these information!?

**Comment by monlighter** [comment]
@Gummibeer Thank you very much!
