### ISSUE TITLE
>PHP7.2: Declaration of Orchestra\Testbench\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp()

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-activitylog#486]
> phpunit --coverage-text --coverage-clover=coverage.clover
PHP Fatal error:  Declaration of Orchestra\Testbench\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/spatie/laravel-activitylog/vendor/orchestra/testbench-core/src/TestCase.php on line 15

**Comment by freekmurze** [comment]
Feel free to require PHP 7.2 and PHPUnit 8. Support for PHP 7.1, PHPUnit 7 may be dropped. We're doing this with all our other packages too whenever we touch them..

**Comment by Gummibeer** [comment]
@freekmurze the problem was the global `phpunit` instead of our `vendor/bin/phpunit`.

**Comment by freekmurze** [comment]
👍

**Comment by nanophp** [comment]
laravel 5.8 <, phpunit8<, I got same error. @freekmurze, how can I fix? @Gummibeer

**Comment by Gummibeer** [comment]
@nanophp could you provide the precise versions you use? This will allow me to check what's going wrong and where we have to fix something.

**Comment by haiphan2710** [comment]
Hi @Gummibeer, I got the same problem after upgrade Laravel version to 5.8
I added setUp() function to test files, but it can't resolve, still above error
public function setUp()
{
    parent::setUp();
}

**Comment by nusendra** [comment]
same with me. Still got this error on TestCase

**Comment by haiphan2710** [comment]
I use phpunit 8 and laravel 5.8
solved, thanks

**Comment by AndresMatta** [comment]
and how did you solved it?

> I use phpunit 8 and laravel 5.8
> solved, thanks

and how did you solved it?

**Comment by AndresMatta** [comment]
> I use phpunit 8 and laravel 5.8
> solved, thanks

and how did you solved it?

**Comment by nusendra** [comment]
@AndresMatta in TestCase.php file add `:void`

`public function setUp(): void`

**Comment by majorsabbir** [comment]
I got the same problem with laravel 5.8 and phpunit 8. Thanks @nusendra

**Comment by nusendra** [comment]
you're welcome @majorsabbir

**Comment by jordanboston** [comment]
> : void

this works along with version 8 of phpunit.  What is the :void for though?

**Comment by haiphan2710** [comment]
@jordanboston yes, add :void to setUp()

**Comment by jordanboston** [comment]
Yes, `:void ` it works, I was just not sure what it's doing. :)

**Comment by GusAntoniassi** [comment]
@jordanboston `void` is the return type, meaning that the `setUp` method will return nothing. 

The error was thrown because we're overriding the method from PHPUnit, so it must use exactly the same signature PHPUnit uses:

```php
/**
 * This method is called before each test.
 */
protected function setUp(): void
{
}
```

See [the docs](https://www.php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration) for more info on return types.

**Comment by shabancareer** [comment]
i used laravel5.8 and enter :void but error the same why?

**Comment by shabancareer** [comment]
![void](https://user-images.githubusercontent.com/51951669/63637758-06a12c80-c69a-11e9-82cc-198a7975e39a.png)

**Comment by GusAntoniassi** [comment]
@shabancareer did you declare your method as `protected`? Can you share the code in for the method `Tests\TestCase::setUp()`?

**Comment by vishal-chauhan97** [comment]
@shabancareer did you solve this problem ?
I am also stuck here even after adding void still the same error.

**Comment by tigusigalpa** [comment]
My solution is to downgrade phpunit in the peoject composer.json to ^7.0 `"phpunit/phpunit": "^7.0"` and everything works because some packages still follows phunit7

**Comment by l3ss13ux** [comment]
Thanks @tigusigalpa now it works for me!

**Comment by NguyenNhutTien** [comment]
> @AndresMatta in TestCase.php file add `:void`
> 
> `public function setUp(): void`

I had to login to like you, thank you so much
