### ISSUE TITLE
The documentation link in the header is to V1

### ISSUE THREAD

**Issue by fgilio** [spatie/laravel-activitylog#491]
Hi guys! I think a PR will not solve this, so I opened an issue. The link in the repo header points to the v1 docs:
![screen shot 2019-02-21 at 16 17 41](https://user-images.githubusercontent.com/6857732/53195409-62f49800-35f4-11e9-9efb-c9f8b54a7cc0.png)

This bite me hard a couple of times.

**Comment by Gummibeer** [comment]
You are right.
@freekmurze could you change it to https://docs.spatie.be/laravel-activitylog
This will prevent needed updates after new releases.

**Comment by freekmurze** [comment]
Fixed! Thanks for notifying us @fgilio 👍

**Comment by fgilio** [comment]
Thank you guys
