### ISSUE TITLE
Manual logging + use SoftDeletes; trait duplicates

### ISSUE THREAD

**Issue by RomkaLTU** [spatie/laravel-activitylog#495]
Use case:

I have API endpoint which creating some model. I also using LogsActivity trait on that model. But I need to explicitly define Causer because causer_id is unknown when request is coming from outside. When I put this inside API and-point method:

```
...
activity()
            ->causedBy( User::find($request->user_id) )
            ->performedOn( Inquiry::find($inquiry->id) )
            ->withProperties($inquiry->toArray())
            ->log('created');
...
```

2 logs entries being created. One by trait and another from manual method. This is understandable, but how to avoid this without removing trait?

**Comment by Gummibeer** [comment]
Hey,

Checkout the `tapActivity()` method on your subject model: https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events#tap-activity-before-logged-from-event

From there you can access the request via facade, app make or global helper function.
