### ISSUE TITLE
Allow passing snake_case in "getRelatedModelAttributeValue"

### ISSUE THREAD

**Issue by blindsz** [spatie/laravel-activitylog#499]
Hi. Just wanted to suggest to allow snake_case when passing value to `getRelatedModelAttributeValue()` to be able to sync with laravel naming convention. 

```php
// so for example we have the following correct code:  
protected static $logAttributes = array(
 sampleRelationship.name
);

// Instead it should be like this:
protected static $logAttributes = array(
 sample_relationship.name
);

public function sampleRelationship() {
   return $this->belongsTo("App\SampleRelationship");
}
```

We can just convert the string under `getRelatedModelAttributeValue()` back to camelCase to match the method inside our model.

**Comment by Gummibeer** [comment]
Hey, feel free to send a PR that fixes this.
And do you have a reference that describes this convention?

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.9.0
