### ISSUE TITLE
Does this package log relationship changes?

### ISSUE THREAD

**Issue by jamiehd** [spatie/laravel-activitylog#5]
Hi,

I have recently been working on a more basic version of this package that is designed to log administrator activity. I have been having trouble working out an automatic way of logging changes to relationships (for example deleting a many-to-many relationship),

Have you found a way round this or are you not currently logging this information?

Thanks

**Comment by sebastiandedeyne** [comment]
It won't if you're logging activity through the model events, since Eloquent doesn't fire events on parent classes when one of it's relationships changes. You can however, build the activity record yourself (including coupling it to the relevant model).

```php
// First do stuff with relations on $myModel...

activity()
    ->performedOn($myModel)
    ->causedBy(auth()->user())
    ->log(':causer.name changed some relationships on :subject.title');
```

**Comment by jamiehd** [comment]
Ok thanks for the info!
