### ISSUE TITLE
How to disable logging when migrating

### ISSUE THREAD

**Issue by Saarik** [spatie/laravel-activitylog#50]
Hello,

I'm running artisan migrate:reset on my app before seeding new data for testing. Problem is that the package tries to log even when the activity_log table has been deleted. 

Any way around that? Or should I make pull request with the solution?

Best wishes,
Siim

**Comment by freekmurze** [comment]
I'd accept a PR that fixes that problem. Be sure to include a test as well.

**Comment by Saarik** [comment]
Resolved with PR#51

**Comment by freekmurze** [comment]
Thank you very much for that PR. 

Changes tagged as version `1.7.0`
