### ISSUE TITLE
Saving activity with changes

### ISSUE THREAD

**Issue by muscle-rhnkyr** [spatie/laravel-activitylog#500]
Hi guys,

in fact this is a question rather than bug or error. How can I implement changes when i use activity helper. For instance :

```
$order = .....
activity('order-activity')
            ->by(auth()->user())
            ->on($order)
            ->withProperty('order_id', $order->id)
            ->withChanges() // Is it possible ??
            ->tap(function (Activity $activity) use ($order) {
                $activity->parent_id = $order->id;
            })
            ->log('Order ##LINK## has been updated');
```

as you notice **->withChanges()** was added by me but I wonder any method or way to implement it.

Thanks in advance.

Cheers.

**Comment by Gummibeer** [comment]
Hey,
not this way but it is - see below:

First, this is the point where the auto-logging trait magic happens https://github.com/spatie/laravel-activitylog/blob/2e451503a02ba98067de0f56a51ea7ceaf45487d/src/Traits/LogsActivity.php#L35-L38
like you see it utilises the `DetectsChanges:: attributeValuesToBeLogged()` method https://github.com/spatie/laravel-activitylog/blob/2e451503a02ba98067de0f56a51ea7ceaf45487d/src/Traits/DetectsChanges.php#L80-L112 this method is public so you can use it everywhere.

The solution would be:
```php
activity('order-activity')
    ->by(auth()->user())
    ->on($order)
    ->withProperties($order->attributeValuesToBeLogged())
    ->withProperty('order_id', $order->id)
    ->tap(function (Activity $activity) use ($order) {
        $activity->parent_id = $order->id;
    })
    ->log('Order ##LINK## has been updated');
```
To let this work your `Order` model has to implement at least the `DetectsChanges` trait - the `LogsActivity` would be optional.

**warning:** the `withProperties()` overrides the properties, the `withProperty()` just puts the given one in. So if you want to use `withProperties()` multiple times you will have to merge them before `collect()->merge()` or you split them in `withProperties()` and multiple `withProperty()` calls.

**Comment by muscle-rhnkyr** [comment]
@Gummibeer thanks for that m8. I did implement as you suggest but now it throws 

`Call to undefined method App\\Models\\Order::eventsToBeRecorded()`

exception. Any idea?

**Comment by Gummibeer** [comment]
Ok, you discovered something like a bug 👍 😂 

The `DetectsChanges` trait has a direct dependency on the `LogsActivity` one (your first exception). The `attributeValuesToBeLogged()` method requires a `$processingEvent` - this is the name of your model event. Most times this will be `created`, `updated` or `deleted`. https://laravel.com/docs/5.8/eloquent#events
The `eventsToBeRecorded()` contains all 3 of these events https://github.com/spatie/laravel-activitylog/blob/2e451503a02ba98067de0f56a51ea7ceaf45487d/src/Traits/LogsActivity.php#L85-L102

To prevent duplicate logs - if you don't want the auto created ones I recommend to set `protected $enableLoggingModelsEvents = false`.

But after all this, if you want to log all these events (or just a set of these) have you checked this: https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events#tap-activity-before-logged-from-event
You can log model events automatically and manipulate the `Activity` model before it's saved in the `tapActivity()` method (should be placed in the `Order` model).
This would reduce your work to 2 lines in this method:
```php
class Order extends Model
{
    use LogsActivity;

    public function tapActivity(Activity $activity, string $eventName)
    {
        $activity->properties = $activity->properties->put('order_id', $this->getKey());
        $activity->description = 'Order ##LINK## has been updated';
    }
}
```

**Comment by muscle-rhnkyr** [comment]
@Gummibeer :). What I want is maybe so specific lol. BTW I did again implement what you suggest but now got another exception which is

`App\\Models\\Order and Spatie\\Activitylog\\Traits\\LogsActivity define the same property ($enableLoggingModelsEvents) in the composition of App\\Models\\Order. However, the definition differs and is considered incompatible. Class was composed`

What I did is remove helper from controller. 

 ```
public function update(Request $request, $id)
    {
        $order               = app(Order::class)->where('minja_id', $id)->firstOrFail();
        $order->mc_status_id = $request->mc_status_id;
        $order->save();

        return response()->json(['message' => 'success']);
    }
```

And modified Model as below 

```
class Order extends Eloquent
{
    use LogsActivity;

    protected $enableLoggingModelsEvents = false;

    protected static $logAttributes = ['mc_status_id'];

.
.
.
.
.
.

/**
     * Spatie Activity
     * @param \Spatie\Activitylog\Models\Activity $activity
     * @param string $eventName
     */
    public function tapActivity(Activity $activity, string $eventName)
    {
        $activity->properties = $activity->properties->put('order_id', $this->getKey());
        $activity->description = 'Order ##LINK## has been updated';
    }
}
```

thanks for your time again!

**Comment by Gummibeer** [comment]
Ok, this is something php related that you can't override trait properties.

But if you want to use the auto-logging you even don't need to disable it. Because you want to let the trait log all defined events. So remove the `$enableLoggingModelsEvents` property.

Otherwise you can set it in the construct.

**Comment by muscle-rhnkyr** [comment]
Thanks @Gummibeer . I used another way to achieve what I want. Cheers.

**Comment by chiragshahphp** [comment]
> 
> 
> Thanks @Gummibeer . I used another way to achieve what I want. Cheers.

Can you please share it? I am also looking same solution.
