### ISSUE TITLE
Not working with Eloquent Resources

### ISSUE THREAD

**Issue by webmasterdro** [spatie/laravel-activitylog#502]
Hello 👋,

I feel that's a stupid question and I'm misunderstanding something. But I can't get activity log working properly using Eloquent Resources.

Transformers:
```
    public function includeHistory(Payments $payment)
    {
        return $this->collection($payment->activity, new IpnTransformer());
    }
```

However, when I try using resources: `'history' => new OrderLogResource($this->activity)`

I receive this `Method Illuminate\Database\Eloquent\Collection::getExtraProperty does not exist.`

What am I doing wrong? 😕

**Comment by Gummibeer** [comment]
Hey,

because of the missing stacktrace and executed code I've no idea what's going on. But it looks like you are calling `getExtraProperty()` on a collection instead of the model.

**Comment by webmasterdro** [comment]
Hi @Gummibeer 

I'm doing this way:

```
/**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'history' => new OrderLogResource($this->whenLoaded('activity')),
        ];
  }
```
And yes, activity is a collection because payment can multiple events attached. How is the best way to handle, then? I don't get it.

**Comment by Gummibeer** [comment]
@webmasterdro would you mind to share the package(s) you are using - if so? Just to have these keywords here for following developers.

**Comment by webmasterdro** [comment]
@Gummibeer I'm using [Eloquent Resources](https://laravel.com/docs/5.8/eloquent-resources) now, previously was https://fractal.thephpleague.com/
