### ISSUE TITLE
Detect changes from another related model

### ISSUE THREAD

**Issue by blindsz** [spatie/laravel-activitylog#504]
is there anyone out there that has any idea on how to achieve this? For example there is a **User** model and it is connected to another model let say one to one relationship on **UserDetail**. how can we achieve a feature that we can also detect changes on UserDetail model? under the User model. It's like a one lo only for one to one relationship.

**Comment by Gummibeer** [comment]
If the user is also saved/touched it's relatively simple. You only have to check for changes (isDirty(), getDirty() ...) on the related models and put them in the activity `tapActivity()` would be a good place.

If this isn't the case you will have to observe the related model and log the changes by your own or let the related model use the traits.

**Comment by blindsz** [comment]
The problem is sometimes the User & UserDetail model get touched and sometimes its not. right now I just put two logs for both but it just feels like a little dirty because they should be in one log not separated but I don't have anything in mind on how to achieve this feature.

**Comment by Gummibeer** [comment]
The solution in #526 is the other way but I think that this is the safest way to do it. Log the changes in different records and combine them in your view into one list.
