### ISSUE TITLE
Why is the link to the documentation not working? :(

### ISSUE THREAD

**Issue by khamsolt** [spatie/laravel-activitylog#506]
https://docs.spatie.be/laravel-activitylog

**Comment by Gummibeer** [comment]
Hey, for me it works and redirects to https://docs.spatie.be/laravel-activitylog/v3/introduction - like expected.

**Comment by khamsolt** [comment]
@Gummibeer Hey. You're right, this link does not work for Russia (it works with VPN). =(

**Comment by Gummibeer** [comment]
I would like to pass it to @freekmurze - eventually he can do something to make this work also in russia.

**Comment by khamsolt** [comment]
Thank you, I will use the VPN for access to the documentation.
