### ISSUE TITLE
Cleaning up the log by overwriting days to keep per call not supported

### ISSUE THREAD

**Issue by erikscheepers** [spatie/laravel-activitylog#515]
In the [current docs](https://docs.spatie.be/laravel-activitylog/v3/basic-usage/cleaning-up-the-log#overwrite-the-days-to-keep-per-call) it's mentioned you can overwrite the default config value of the days to keep by passing --days to your call. But:

>  The "--days" option does not exist. 

Looking at the code this option is not supported (anymore?).

**Comment by Gummibeer** [comment]
I've already pinged @freekmurze in https://github.com/spatie/laravel-activitylog/pull/497 to release it.

**Comment by Gummibeer** [comment]
was released in https://github.com/spatie/laravel-activitylog/releases/tag/3.5.0
