### ISSUE TITLE
bug in models with 'unique' fields

### ISSUE THREAD

**Issue by piovani** [spatie/laravel-activitylog#517]
In migrate models programmed with 'unique', when making an object creation in the database it creates two times, the first one is done by ActivityLog and the second by the requesting request, so it does not let it proceed because the field has already been registered with the bank.
In case I am working with users with unique email accounts on my system.

**Comment by Gummibeer** [comment]
Hey,
I'm sorry but I don't get what you mean. 🤔

This package doesn't create log entries by request - only if you have added a custom log.
Could you explain in depth what you do, get as result and expect?
In best case with the relevant code snippets.
