### ISSUE TITLE
Improve `submitEmptyLogs`

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-activitylog#518]
Let's rename this to `preventEmptyLogs` with `true` if you want to enable it.

Can we have this behaviour by default?

**Comment by Gummibeer** [comment]
So you mean that we should prevent empty logs by default? And the user has to set `false` if he wants to log empty logs?
Would be ok for me in a BC release.

**Comment by fgilio** [comment]
Just searched `submitEmptyLogs` in the repo looking for something like this exactly, what a coincidence 🤯.

I agree with this default, we currently have `58165` entries that are just `{"old": [], "attributes": []}`. `52580` of those being just updates to a User model, and seems to be being generated on logins and logouts.
