### ISSUE TITLE
Issue with fields in casts float

### ISSUE THREAD

**Issue by matthewscalf** [spatie/laravel-activitylog#520]
I have some variables are are using Eloquent `$casts` as `float`, they are not included in the activity log when they are changed. Any ideas/clues?

**Comment by Gummibeer** [comment]
Hey,

like in the most recent issues I will try to add a unittest that does what you described and check if it fails or not.
I will get back if I've pushed the unittest with the result.

**Comment by Gummibeer** [comment]
@matthewscalf I've added an unittest in #543 but it passes. Could you check if this is what you meant? If it now also works for you it could be that #534 fixed this - it's released in `v3.6.0`.
