### ISSUE TITLE
Add possibility to override ActivityLogger

### ISSUE THREAD

**Issue by maciejfikus** [spatie/laravel-activitylog#536]
Hi.
I have quite specific scenario in my app where I need to override some functions in ActivityLogger in order to perform some actions on the model before actually passing it futher (`performedOn()`).

It is nice that we can already use customized Activity model, but would be also nice to add possibility to do same with ActivityLogger. 

I would just override `activity()` helper function, but as it is loaded before app helpers it is impossible to do so without ugly hacks with composer autoloader.  
For now, I am just using custom function `act()` witch is using my own Logger.

**Comment by Gummibeer** [comment]
It is already possible. The class is bind to the service container in the ServiceProvider. You only have to bind your own class to it.
https://github.com/spatie/laravel-activitylog/blob/3bee85adf8e19e3bc0cafab56599a442014a9169/src/ActivitylogServiceProvider.php#L39

```php
$this->app->bind(\Spatie\Activitylog\ActivityLogger::class, \App\ActivityLogger::class);
```

**Comment by maciejfikus** [comment]
Well, fun thing is that I even tried to override it in IoC before, but for some reason it didn't work (maybe misspelled?).
This time it worked. 

Thank you @Gummibeer, issue solved :-)
