### ISSUE TITLE
3.6 update causes issues with null dates

### ISSUE THREAD

**Issue by bryanrscott** [spatie/laravel-activitylog#545]
Just updated to 3.6 and it causes issues with fields that are in the $fillable and $dates, and have null values.

![image](https://user-images.githubusercontent.com/4473505/58529738-bb58b880-8227-11e9-8ab2-ec81c0b882d8.png)

**Comment by bryanrscott** [comment]
Not quite sure but here is a suggested change to src/Traits/DetectsChanges.php
------------------------------------------------
From
`} elseif (in_array($attribute, $model->getDates())) {
                $changes[$attribute] = $model->serializeDate(
                    $model->asDateTime($model->getAttribute($attribute))
                );
} else {`
---------------------------------------------
To
`} elseif (in_array($attribute, $model->getDates())) {
           $value = $model->getAttribute($attribute);
                $changes[$attribute] = empty($value) 
                              ? ''
                              : $model->serializeDate($model->asDateTime($value));
} else {	    
`

**Comment by Gummibeer** [comment]
Thanks for your issue and suggestion. Will fix it today but close this issue now because it duplicates #544
