### ISSUE TITLE
DB connection activity-log.

### ISSUE THREAD

**Issue by 1benayatei** [spatie/laravel-activitylog#549]
**Can I change the database connection?**

I do not want to be hit hard by the site's main database, so I'm going to use another database.

**Comment by Gummibeer** [comment]
Atm you only can customize the table via config. But you are able to override the whole model and set your connection as normal with eloquent.

**Comment by 1benayatei** [comment]
> Atm you only can customize the table via config. But you are able to override the whole model and set your connection as normal with eloquent.

Yes, I know the table.
Please explain more about the model.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/blob/c1113b5eb9235ff465e6108f4d911da8fcbbbfaf/config/activitylog.php#L38

Only extend the default activity model and set the connection property and put the new model FQCN in the config.

**Comment by 1benayatei** [comment]
> https://github.com/spatie/laravel-activitylog/blob/c1113b5eb9235ff465e6108f4d911da8fcbbbfaf/config/activitylog.php#L38
> 
> Only extend the default activity model and set the connection property and put the new model FQCN in the config.

Thanks 🌹
