### ISSUE TITLE
Spatie\Activitylog\ActivityLogger::useLog() must be of the type string, null given

### ISSUE THREAD

**Issue by akimcsm** [spatie/laravel-activitylog#55]
On my homestead VM there seems to be no problem whatsoever with the logging process, however on a DigitalOcean droplet I'm getting this error and can't seem to find the cause.
<img width="1051" alt="screen shot 2016-08-22 at 18 11 56" src="https://cloud.githubusercontent.com/assets/15095392/17859874/feedc596-6893-11e6-90a0-b920dd682b53.png">

**Comment by freekmurze** [comment]
Do you specify a log name in the configuration of the package?
https://github.com/spatie/laravel-activitylog/blob/master/config/laravel-activitylog.php#L20

**Comment by akimcsm** [comment]
Yes, it's the default text

**Comment by akimcsm** [comment]
I've edited /vendor/spatie/laravel-activitylog/src/helpers.php and changed $defaultLogName to a string 'default'. It works now.

**Comment by fabiolrs** [comment]
I had the exact same problem. Installed the package on a brand new project on friday, it worked on my Homestead VM but it fails on the AWS server. Publishing the config and editing the helpers.php file didn't help, thou.

Will try more tonight.

Weird is that I have the exact same configuration on another project on AWS, for another project, and it works perfectly.

**Comment by Sjoerdjanssenen** [comment]
You can solve this issue by clearing the config cache. To do that, just run `php artisan config:cache`.
