### ISSUE TITLE
Transcoded Chinese that cannot be searched for properties with AJAX

### ISSUE THREAD

**Issue by szwss** [spatie/laravel-activitylog#551]
My request is like this:
```
http/index_main_data?search=%E6%B8%B8%E5%AE%A2&sort=id&order=desc&offset=0&limit=10&main_page=1
```
The data of the properties in the database is like this:
```
{"attributes":{"id":1,"contacts":"\u5c60\u6842\u5170"},"causer_name":null,"causer_type":"\u6e38\u5ba2","ip":"192.168.10.1"}
```
My controller is like this, but it is always empty when searching for Chinese.
```
 $models->when(isset($request->query()['search']), function ($query, $term) use($request) {
            return $query
                ->orWhere('description', 'like', '%'.$request->query()['search'].'%')
                ->orWhere('log_name', 'like', '%'.$request->query()['search'].'%')
                ->orWhere('causer_type', 'like', '%'.$request->query()['search'].'%')
                ->orWhere('properties', 'like', '%'.trim(json_encode(urldecode($request->query()['search'])),"\"").'%');
        });
```

**Comment by Gummibeer** [comment]
Hey,

at first sight I would say that this is something eloquent or MySQL related. We don't do anything special with the data in this package and primary nothing with queries.

**Comment by Gummibeer** [comment]
https://stackoverflow.com/questions/41942374/json-search-in-laravel-eloquent

It could be that you have to play around with the DB::raw() to prevent escaping of your already transformed search query. But at first I would try to find a running query in MySQL direct. After this you have a goal to reach with eloquent.

**Comment by szwss** [comment]
thank you very much
