### ISSUE TITLE
 get last activity of an object

### ISSUE THREAD

**Issue by FerCruzBanegas** [spatie/laravel-activitylog#556]
What is the best way to obtain the last event of a specific object? For example, an object can be updated many times, I would like to obtain the last update record on that object

**Comment by Gummibeer** [comment]
To get the last activity for a specific model you can use
```php
$model->activities()->order_by('created_at', 'desc')->first();
```

But if you want to get the last activity by a specific type you have to adjust the codebase. The easiest way would be to use the `custom_properties` and the `tapActivity()` method to add something like `type => update`. To access this you would need to use a database which supports JSON columns and to query them (eg. MySQL 5.7).
The more advanced solution would be to add a nullable column `type` and fill it. If you want to I think that this would be a good addition so you could also create a PR and add it to the package itself.

**Comment by ahmadyousefdev** [comment]
Hi, `order_by('created_at', 'desc')` returns

```
Call to undefined method Illuminate\Database\Eloquent\Relations\MorphMany::order_by()
```

**Comment by Gummibeer** [comment]
@ahmadyousefdev sorry, my bad - was a typo: it's `orderBy()`
https://laravel.com/docs/8.x/queries#orderby

**Comment by ahmadyousefdev** [comment]
we can use `last()` too, for example

```
$model->activities->last()->causer->name
```
