### ISSUE TITLE
Composer\Downloader\TransportException while installation

### ISSUE THREAD

**Issue by devendra-gohil-plenar** [spatie/laravel-activitylog#557]
I am using **Laravel 5.4** with **PHP 7.1.22**

I tried installing old version (1.16.0) using following command: 

`composer require spatie/laravel-activitylog:^1.16.0`

But it gives following error: 

  ```
[Composer\Downloader\TransportException]
  The "https://packagist.org/p/symfony/translation%240f07a0ad207f4459726b657a
  3c6a63cc81fa332e2c991d0eeca33bc3e61854e8.json" file could not be downloaded
   (HTTP/1.1 404 Not Found)
```

Before that I also tried installing the package with `composer require spatie/laravel-activitylog` but it also returns that same error. 

Am I missing something?

**Comment by Gummibeer** [comment]
Hey,

this issue is composer and/or packagist related and nothing we could fix.
