### ISSUE TITLE
Custom properties documentation appears to be wrong

### ISSUE THREAD

**Issue by forby** [spatie/laravel-activitylog#56]
Possibly a bug, but maybe just a discrepancy in the documentation.  Currently in 1.7, if I log with the following line from documentation:

```php
activity()
   ->performedOn($anEloquentModel)
   ->causedBy($user)
   ->withProperties(['customProperty' => 'customValue'])
   ->log('Look mum, I logged something');
```

and then try to access it with the recommended syntax:

```php
$lastLoggedActivity = Activity::all()->last();
$lastLoggedActivity->property('customProperty');
```

I get an error, even though calls like `->description` work fine:

```php
Call to undefined method Illuminate\Database\Query\Builder::property()
```

The only way I am able to access the custom properties is like this:

```php
$lastLoggedActivity->properties['customProperty'];
```

This works fine for me, but I just wanted to make sure that's correct or if the documented method should be the correct way.

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. The right method name is `getExtraProperty`. I fixed this in the docs.
