### ISSUE TITLE
tapactivity description does not save properly

### ISSUE THREAD

**Issue by rxng** [spatie/laravel-activitylog#562]
Hi,

Not sure if this is a bug, but I am trying to get `tapActivity()` to save meaningful descriptions besides just "Update".

For example, when a user logs in, I need it to save a log with description "Logged in"
```php
public function tapActivity(Activity $activity, string $eventName)
{
    if($activity->properties["attributes"]["last_login"]) {
        $activity->description = "Logged in";
    }
}
```

However, this code doesn't work and description keeps defaulting back to "Update". It's really frustrating and wonder if anyone has a solution?

**Comment by Gummibeer** [comment]
Hey,
do you have started to debug it? So dump if it goes into the `if`, what is the value of `$activity->description` after the `if` and so on?

**Comment by Gummibeer** [comment]
Ok, I've checked the code and found the problem:
https://github.com/spatie/laravel-activitylog/blob/9b0e2daa9352fa9ab73a34b4656caf714f1916d2/src/Traits/LogsActivity.php#L41-L50

https://github.com/spatie/laravel-activitylog/blob/9b0e2daa9352fa9ab73a34b4656caf714f1916d2/src/ActivityLogger.php#L135

The description is the only attribute set after the `tapActivity()` call. I will try to find a way to fix it.

**Comment by rxng** [comment]
Confirming that 

dd($activity->description) at the end of the function yields correct new description, just not saving to database correctly.

**Comment by Gummibeer** [comment]
@rxng could you please test and verify [dev-fix-issue-562](https://packagist.org/packages/spatie/laravel-activitylog#dev-fix-issue-562)? The unittest passes but a realworld test would be great.

**Comment by rxng** [comment]
@Gummibeer sure thing, how do I get this? I ran 

composer require spatie/laravel-activitylog      

but got

Using version ^3.2 for spatie/laravel-activitylog
Nothing to install or update

**Comment by Gummibeer** [comment]
You have to run it with the version, or just edit the version in `composer.json`

```
composer require spatie/laravel-activitylog:dev-fix-issue-562
```

**Comment by rxng** [comment]
@Gummibeer  

"Package spatie/laravel-activitylog at version dev-fix-issue-562 has a PHP requirement incompatible with your PHP version (7.1.25) "

**Comment by Gummibeer** [comment]
That's right - the latest versions require PHP7.2.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.6.2

**Comment by rxng** [comment]
I'm having trouble installing this into my Laravel 5.5 after upgrading to php 7.2

Noticed, you released into 3.6.2, so I tried to get that version but am getting this

spatie/laravel-activitylog 3.6.2 requires illuminate/database ~5.8.0

Any chance I can try and get the fix in? Sorry for the inconvenience but I am stuck!

Thanks :)

**Comment by Gummibeer** [comment]
As first solution I can only recommend you to upgrade to the latest laravel version. => [LTS is a lie](https://connortumbleson.com/2019/01/28/lts-is-a-lie/)

As second solution you could override the `ActivityLogger` service and paste the fix from the PR in your overridden service.

Because it's not a security fix I won't add it to an older version.

**Comment by rxng** [comment]
Thank you, Tom. I will try to work around that until I can safely upgrade all my systems. 

Sorry to be a pain, could you advise on how we might achieve this override? 

Hopefully someone else can benefit from this too!

**Comment by Gummibeer** [comment]
Hey,

You just have to create a new class which extends the package `ActivityLogger` and copy the method updated in the PR in the new class.
After this you just have to bind your new class to the old one in a service provider.
```php
$this->app->bind(
    ActivityLogger::class,
    YourNewActivityLogger::class
);
```
