### ISSUE TITLE
Migration Isssue 

### ISSUE THREAD

**Issue by nikulnayi** [spatie/laravel-activitylog#565]
I M trying to migrate activity log table but it returning error as mention below 

SQLSTATE[42000]: Syntax error or access
 violation: 1064 You have an error in your SQL syntax; check the manual that cor
responds to your MariaDB server version for the right syntax to use near 'json n
ull, `created_at` timestamp null, `updated_at` timestamp null) default cha' at l
ine 1 (SQL: create table `activity_log` (`id` bigint unsigned not null auto_incr
ement primary key, `log_name` varchar(191) null, `description` text not null, `s
ubject_id` bigint unsigned null, `subject_type` varchar(191) null, `causer_id` b
igint unsigned null, `causer_type` varchar(191) null, `properties` json null, `c
reated_at` timestamp null, `updated_at` timestamp null) default character set ut
f8mb4 collate 'utf8mb4_unicode_ci')

**Comment by Gummibeer** [comment]
https://mariadb.com/kb/en/library/json-data-type/
Do you use MariaB v10.2.7 or above? Otherwise the `json` column type doesn't exist.

**Comment by atymic** [comment]
@nikulnayi did you get a chance to check the version and try Gummibeer's suggestion above?

**Comment by ariefyudia** [comment]
i'm trying migration, but error this below

SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `log_name` varchar(255) null, `description` text not null, `subject_id` bigint unsigned null, `subject_type` varchar(255) null, `causer_id` bigint unsigned null, `causer_type` varchar(255) null, `properties` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by Gummibeer** [comment]
@ariefyudia this looks like a missing config. Have you published the config file? If so is your config possibly cached - `artisan config:clear`?

**Comment by ariefyudia** [comment]
> 
> 
> @ariefyudia this looks like a missing config. Have you published the config file? If so is your config possibly cached - `artisan config:clear`?

solved ! thank you

**Comment by ifly-leonard** [comment]
I was using phpmyadmin with 10.1.38-MariaDB on shared host. In my case, updating isn't an option. So a quick workaround was to change the `$table->json('properties')->nullable();` to ` $table->string('properties')->nullable();`. 

Worked for me.

**Comment by rendell04** [comment]
Using phpmyadmin with 10.3.12-MariaDB (WAMP). After changing   $table->json('properties')->nullable() into $table->text('properties')->nullable(), then running php artisan migrate.

I got this error. 

[41;1m ErrorException [49;22m

[39;1m  array_key_exists(): The first argument should be either a string or an integer[39;22m

  at [32mC:\Users\Administrator\Desktop\Work'Task\JD-Eversun\project\conx_backup\server\vendor\laravel\framework\src\Illuminate\Support\Arr.php[39m:[32m151[39m
    147|         if ($array instanceof ArrayAccess) {
    148|             return $array->offsetExists($key);
    149|         }
    150|
  > 151|         return array_key_exists($key, $array);
    152|     }
    153|
    154|     /**
    155|      * Return the first element in an array passing a given truth test.

  [37m    Illuminate\Support\Arr::exists([])[39m

**Comment by nikulnayi** [comment]
you guys must have to use use TEXT instead of json in case ur not using latest spl database 
and most probably Xamp doesnt support json datatype for column so use TEXT data type instead

**Comment by masoudganji** [comment]
I have this error:
[ERROR 4856:  Syntax error at or near "returning" at character 162] 42601 (SQL: insert into "activity_log" ("log_name", "properties", "causer_id", "causer_type", "description", "updated_at", "created_at") values (default, [], 2, App\User, Filter Alert, 2020-09-22 12:40:29, 2020-09-22 12:40:29) returning "id")
Any idea?

**Comment by AR-Shahin** [comment]
I have got this Error: 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'log.activity_log' doesn't exist (SQL: insert into `activity_log` (`log_name`, `properties`, `description`, `updated_at`, `created_at`) values (default, [], Look mum, I logged something, 2021-05-29 05:10:04, 2021-05-29 05:10:04))

**Comment by masoudganji** [comment]
> 
> 
> I have got this Error:
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'log.activity_log' doesn't exist (SQL: insert into `activity_log` (`log_name`, `properties`, `description`, `updated_at`, `created_at`) values (default, [], Look mum, I logged something, 2021-05-29 05:10:04, 2021-05-29 05:10:04))

 @AR-Shahin see this: 'Table 'log.activity_log' doesn't exist'. You should create the table at first.

**Comment by Redemple332** [comment]
array_key_exists(): The first argument should be either a string or an integer

**Comment by satriyoz** [comment]
> 

I also have this kind of error when trying to migrate. 
is there any solution for this?

**Comment by ifly-leonard** [comment]
> > 
> 
> I also have this kind of error when trying to migrate. is there any solution for this?

Try to change the json() columns to string(). It's a quick solution, but it's recommended that you upgrade your MariaDB to the latest version.

**Comment by satriyoz** [comment]
> > > 
> > 
> > 
> > I also have this kind of error when trying to migrate. is there any solution for this?
> 
> Try to change the json() columns to string(). It's a quick solution, but it's recommended that you upgrade your MariaDB to the latest version.

thankyou for the suggestion, but i solved this problem by deleting the migration file and then republish it using 
`php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider"`
without any tags and I can migrate successfully without changing json() to string() or text().
