### ISSUE TITLE
Allow to log system activity without a causer or a null causer

### ISSUE THREAD

**Issue by EMediaAndroid** [spatie/laravel-activitylog#567]
It's not clear from the documentation if this can be done or not.

Sometimes there can be activity triggered on events without a causer. Examples are when an action is taken by an unregistered user, a SYSTEM Cron, or a Bot. 

Example log items can be:
'Project 123 was archived by the SYSTEM due to non-activity'
'GithubBot locked this thread on 23/05/2019'
'Anonymous user viewed the phone number'
etc

I think the workaround would be to create users with the names 'SYSTEM', 'Bot' etc, and hardcode that userID. Which can cause problems in production and testing environments.

Is there a better way to log such activities?

**Comment by Gummibeer** [comment]
Hey,

the causer columns are already `nullable` if this line returns `null` https://github.com/spatie/laravel-activitylog/blob/d5fd05eb9edcb2416ada4f1e026d47ee9f8706a3/src/ActivityLogger.php#L196 you won't have a causer.

If you want to log a system activity with a logged in user this could be done by creating the `Activity` model directly or override the logger service and change some methods.

**Comment by junaid-A-khan** [comment]
as explained by @Gummibeer.
If you would want to customize "causedBy" logic then you will need to do following steps to accomplish that:

1. Create a new ActivityLogger class which will extend "Spatie\Activitylog\ActivityLogger" and add following code in its construct method:
    
       use Illuminate\Auth\AuthManager;
       use Illuminate\Contracts\Config\Repository;
       use Spatie\Activitylog\ActivityLogStatus;
       use Spatie\Activitylog\ActivityLogger as SpatieActivityLogger;

       class ActivityLogger extends SpatieActivityLogger
       {
          public function __construct(AuthManager $auth, Repository $config, ActivityLogStatus $logStatus)
          {
              parent::__construct($auth, $config, $logStatus);

                 // Your logic if the causer is null
                 if(empty($this->causedBy)){
                     // do something when causer is null.
                  }
          }
       }
<br>
2. Create a new ActivitylogServiceProvider which will extend "Spatie\Activitylog\ActivitylogServiceProvider" and register it in "config/app.php". <br>
Add following code in register method of newly created service provider:
       <br>
<br>

       use App\ActivityLogger;
       use \Spatie\Activitylog\ActivitylogServiceProvider as SpatieActivitylogServiceProvider;

       class ActivitylogServiceProvider extends SpatieActivitylogServiceProvider
       {

           public function register()
           {
               $this->app->alias (ActivityLogger::class, \Spatie\Activitylog\ActivityLogger::class );
           }
       }

This is tested so you should get no issue.

**Comment by Gummibeer** [comment]
@junaid-A-khan instead of the `__construct()` I would adjust the `getActivity()` method https://github.com/spatie/laravel-activitylog/blob/d5fd05eb9edcb2416ada4f1e026d47ee9f8706a3/src/ActivityLogger.php#L189-L200

This does set the init causer - so if you remove this line or adjust the condition when the causer is set yo have a `null` causer. The construct doesn't have to be executed for every activity log because it's a binded service which you could cache in a variable.

**Comment by junaid-A-khan** [comment]
@Gummibeer yes, parent construct call can be removed and I'm sorry, my bad, as I tested it on an old Laravel 5.7 witch has v2.8. 
I am going to update previous answer.
Thanks

**Comment by Gummibeer** [comment]
Because atm it's impossible to set the causer to `null` and by default it's loaded from the current auth. Is an `anonymous()` method wanted which forces the activity to have no causer?
```php
activity()
    ->anonymous()
    ->log('my log message');
```

Doing this for a whole runtime could belong to:
* #503 
* #521 
* #560

**Comment by shanecp** [comment]
Perhaps we can use,

```
activity()
    ->causedByAnonymous()
    ->log('my log message');
```

or
```
activity()
    ->causedBy('SYSTEM')
    ->log('my log message');
```

or
```
activity()
    ->causedBy(ActivityCauserInterface)
    ->log('my log message');
```

**Comment by Jhnbrn90** [comment]
I had a look today at a possible solution introducing an AnonymousCauser model which should function as a "null object". Therefore, I would propose the following PR: #603 , though I have some doubt if this approach is suitable.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.9.0
