### ISSUE TITLE
Log only dirty fields

### ISSUE THREAD

**Issue by aydot** [spatie/laravel-activitylog#57]
Really nice package! Is there a way to log only dirty fields?
Currently I have to do a small hack like so:

```
protected static $logAttributes = [];     

public static function boot()
{
    parent::boot();
    static::saving(function (Model $model) {
        static::$logAttributes = array_keys($model->getDirty());
    });
}
```

Would be nice to have something baked in.

**Comment by freekmurze** [comment]
For now, I'd like to keep the package simple and not add this functionality. I'll reconsider if more users are asking for this.

**Comment by theatrain** [comment]
+1 for this feature

**Comment by LasseRafn** [comment]
+1 :)

**Comment by Rhincodon** [comment]
+1

**Comment by ahjorth** [comment]
+1

For a proper log, to inform admins of changes, it would be helpful to be able to see what fields have changed on a model without having to mess around with array_diff :)

**Comment by ahmadalukah** [comment]
+1 , very important

**Comment by freekmurze** [comment]
Ok, I'd accept a PR that adds this functionality in a convenient way.

**Comment by LasseRafn** [comment]
@freekmurze I'll work on it tomorrow. How do you typically have your env when creating packages (so that I can write tests) 

Clean Laravel installation with the library included, I guess?

I might have a clean solution that allows the user to specify if they want to enable this functionality or not as well.

**Comment by freekmurze** [comment]
@LasseRafn great! Usually I use the `path` option from composer: https://getcomposer.org/doc/05-repositories.md#path

**Comment by LasseRafn** [comment]
@freekmurze never heard about that before, will go ahead and try, thanks! 👍 

Will be created here: https://github.com/LasseRafn/laravel-activitylog — working on it right now.

**Comment by LasseRafn** [comment]
**Question for everyone:** What would be most preferred, having it log ALL changed fields or still only those defined in the models `$logAttributes`?

**Comment by LasseRafn** [comment]
Example output after enable dirty logging (from one of the current tests):

## Current

```
array:2 [
  "attributes" => array:3 [
    "name" => "updated name"
    "text" => "updated text"
    "user.name" => "user name"
  ]
  "old" => array:3 [
    "name" => "original name"
    "text" => "original text"
    "user.name" => "user name"
  ]
]
```

## New

```
array:2 [
  "attributes" => array:2 [
    "name" => "updated name"
    "text" => "updated text"
  ]
  "old" => array:2 [
    "name" => "original name"
    "text" => "original text"
  ]
]
```

**Comment by LasseRafn** [comment]
Pull request: #171

**Comment by freekmurze** [comment]
This feature has been added in `v1.13` of the package (thanks @LasseRafn)

Documentation coming soon.
