### ISSUE TITLE
inegrate activity log with any no sql database

### ISSUE THREAD

**Issue by farshadff** [spatie/laravel-activitylog#574]
hi,
if i have some crazy loging record can i integrate this package with elk Stack or some mongo db to save logs any where out of my  database ???
thanks

**Comment by Gummibeer** [comment]
Hey,

we allow to customize the activity model in the config. The custom model should implement the `Spatie\Activitylog\Contracts\Activity` interface. So you could create a custom model, use [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) for example and everything should be fine.
This is also related to #81

**Comment by farshadff** [comment]
Thanks @Gummibeer But still no luck for logstash and elastic right ??

**Comment by Gummibeer** [comment]
If you find any eloquent package which works with them it will work. But we only provide the basic eloquent implementation and don't care about the underlying database.
To bring them in elastic for read you could use [laravel scout](https://laravel.com/docs/5.8/scout) with one of the available ES drivers. But this is only for read and you still need a database which persists everything.

**Comment by Ahmed-Aboud** [comment]
https://packagist.org/packages/sormagec/laravel-activitylog-mongo is a fork of laravel-activitylog that  works with mongo

**Comment by Gummibeer** [comment]
Why a fork? A simple extension that adds a new activity model would be enough? 🤔

**Comment by bukela** [comment]
Hi, can you please explain how to implement this package with Jenssegers mongodb? I tried many times and it is not working. Thanx

**Comment by Gummibeer** [comment]
Could you provide your exact problems?

**Comment by bukela** [comment]
Thanks for quick reply. I implementing Spatie\Activitylog\Contracts\Activity interface into my model but then getting Class App\Province contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (Spatie\\Activitylog\\Contracts\\Activity::subject, Spatie\\Activitylog\\Contracts\\Activity::causer, Spatie\\Activitylog\\Contracts\\Activity::getExtraProperty...
i know it's begginers question but i'm begginer :)

**Comment by Gummibeer** [comment]
The interface defines a public API without implementing them. So it only tells you that this method has to be defined by the class implementing the interface.

You can check out the package model (for SQL database) to copy the methods or adjust them if needed.

**Comment by bukela** [comment]
OK, got it :) Thank you very much

**Comment by AnkitgargAI** [comment]
> Hey,
> 
> we allow to customize the activity model in the config. The custom model should implement the `Spatie\Activitylog\Contracts\Activity` interface. So you could create a custom model, use [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) for example and everything should be fine.
> This is also related to #81

I'm not able to integrate mongodb in activity log

**Comment by nick322** [comment]
> > Hey,
> > we allow to customize the activity model in the config. The custom model should implement the `Spatie\Activitylog\Contracts\Activity` interface. So you could create a custom model, use [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) for example and everything should be fine.
> > This is also related to #81
> 
> I'm not able to integrate mongodb in activity log
 try
https://nickdevs.wordpress.com/2022/05/17/laravel-laravel-activitylog-inegrate-activity-log-with-mongodb/

**Comment by ohmydevops** [comment]
Same problem
