### ISSUE TITLE
show properties in view

### ISSUE THREAD

**Issue by Lolisicat** [spatie/laravel-activitylog#577]
Hello, 
I want to display properties in my view but with a comprehensive visual for customer : 

In my view : 
<ul>
    @foreach($activity as $activities)
    <li>{{ $activities->description }}</li>
    <li>{{ \Carbon\Carbon::parse($activities->created_at)->format('d-m-Y') }}</li>
    <li>{{ $activities->properties  }}</li>
    @endforeach
</ul>

But  $activities->properties give : {"attributes":{"projectStatus_id":4},"old":{"projectStatus_id":4}}

How transform this into a comprehensive visual ?

**Comment by Gummibeer** [comment]
It's a collection so you can loop over it. An idea is to access the top level keys and loop over the sub-array to list all changes.

**Comment by Lolisicat** [comment]
After many difficults with my co-worker, we found an issues : 
$activity = Activity::where('subject_id', $project->id)->get();
        $arr = [];
        foreach($activity as $activities) {
          $properties = $activities->properties->toArray();
          $subArr['attributes'] = $properties['attributes']['projectStatus_id'];
          if (isset($properties['old'])){
            $subArr['old'] = $properties['old']['projectStatus_id'];
          }
          array_push($arr, $subArr);
        }

Ps : $collection->attributes / items doesn't work...

**Comment by Gummibeer** [comment]
First of all your variables are named wrong. The `$activity` should be `$activities` and the `$activities` should be `$activity`. You switched the singular plural - kind of confusing. 😉 

And what's your issue? At first sight everything looks good and I can't see at which place you would try to use `$collection`?

**Comment by Lolisicat** [comment]
I changed variables's name but i have another problems in view.
I separated $activity with the new array $arr so i have difficult to put this in table.
They do not coordinate...

Controller : 
$activities = Activity::where('subject_id', $project->id)->get();
        $arr = [];

        foreach($activities as $activity) {
          $properties = $activity->properties->toArray();

          $subArr['attributes'] = $properties['attributes']['projectStatus_id'];
          if(isset($properties['old'])){
            $subArr['old'] = $properties['old']['projectStatus_id'];
          }
          array_push($arr, $subArr);
        }

        return view('pages.backoffice.partials.projectDetailsHistory', [
          'project' => $project,
          'activities' => $activities,
          'status' => $status,
          'arr' => $arr
        ]);
        break;

In my view : 
<table>
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Type d'événement</th>
            <th scope="col">Détails</th>
        </tr>
    </thead>
    <tbody>         
        @foreach($activities as $activity)
        <tr>     
            <td>{{ \Carbon\Carbon::parse($activity->created_at)->format('d-m-Y') }}</td>
            <td>{{ $activity->description }}</td>             
        @endforeach   
        @foreach($arr as $log)
            @isset($log['old'])
                <td>Passage du statut "{{ $status[$log['old']]->name }}" au statut "{{ $status[$log['attributes']]->name }}"</td>
            @else
                <td>Passage au statut {{ $status[$log['attributes']]->name }}</td>
            @endisset
        </tr>
        @endforeach              
    </tbody>
</table>

I want to show properties in table depending to the name and date of activity

**Comment by Gummibeer** [comment]
Ok, and your current issue is that it shows all changes of all activities in the table?

Why don't you use `$activity->properties` in your view?

```blade
@foreach($activities as $activity)
<tr> 
    <td>{{ \Carbon\Carbon::parse($activity->created_at)->format('d-m-Y') }}</td>
    <td>{{ $activity->description }}</td>
    @isset($activity->properties['old']['projectStatus_id'])
        <td>Passage du statut "{{ $status[$activity->properties['old']['projectStatus_id']]->name }}" au statut "{{ $status[$activity->properties['attributes']['projectStatus_id']]->name }}"</td>
    @else
        <td>Passage au statut {{ $status[$activity->properties['attributes']['projectStatus_id']]->name }}</td>
    @endisset
</tr>
@endforeach
```

**Comment by Lolisicat** [comment]
Oook !

I tried with $activity->properties->attributes...
I did not realize that they used this like this...
As the properties as collection with object, i did'nt use that like array

I'm just starting with Laravel ^^"

Thank You, it's works :)

**Comment by Gummibeer** [comment]
You will have to use it like an array - it implements `ArrayAccess` interface or use the dedicated [methods](https://laravel.com/docs/5.8/collections#available-methods) like `get()` in your case.
You could also use `data_get()` helper function https://laravel.com/docs/5.8/helpers#method-data-get to use `dot.notation.keys` and also have a simple default value to don't care about `isset()` or `??` yourself. In your case not easier because you don't need a fallback value but want to change the whole surrounding text.

As a hint: use translations from the beginning and everywhere. This will make it lot easier if you need to translate sometimes but also separates your views from language aware content. You can also pass parameters to translation strings to display dynamic content in it.
https://laravel.com/docs/5.8/localization#replacing-parameters-in-translation-strings
