### ISSUE TITLE
Error in Model

### ISSUE THREAD

**Issue by backend01** [spatie/laravel-activitylog#579]
Hi, this is the error. 

**The given model class `Spatie\Activitylog\Models\Activity` does not extend `Spatie\Activitylog\Models\Activity`**

**Comment by Gummibeer** [comment]
Hey,

during which call, where is the exception thrown? Could you please provide a full stack-trace?

**Comment by backend01** [comment]
<?php
 
namespace Spatie\Activitylog\Exceptions;
 
use Exception;
use Spatie\Activitylog\Models\Activity;
 
class InvalidConfiguration extends Exception
{
    public static function modelIsNotValid(string $className)
    {
        **return new static("The given model class `$className` does not extend `".Activity::class.'`');**
    }
}

**Comment by backend01** [comment]
namespace Spatie\Activitylog\Exceptions;
 
use Exception;
use Spatie\Activitylog\Models\Activity;
 
class InvalidConfiguration extends Exception
{
    public static function modelIsNotValid(string $className)
    {
        **return new static("The given model class `$className` does not extend `".Activity::class.'`');**
    }
}

**Comment by Gummibeer** [comment]
And what's your code which forces the exception? And could you please provide a whole stack trace to the exception? Otherwise we can't really help you.

**Comment by backend01** [comment]
The error is generate when login in the application.  

Spatie\Activitylog\Exceptions\InvalidConfiguration thrown with message "The given model class `Spatie\Activitylog\Models\Activity` does not extend `Spatie\Activitylog\Models\Activity`"

Stacktrace:
#72 Spatie\Activitylog\Exceptions\InvalidConfiguration in /opt/lampp/htdocs/plataforma/vendor/spatie/laravel-activitylog/src/Exceptions/InvalidConfiguration.php:12
#71 Spatie\Activitylog\Exceptions\InvalidConfiguration:modelIsNotValid in /opt/lampp/htdocs/plataforma/vendor/spatie/laravel-activitylog/src/ActivitylogServiceProvider.php:47
#70 Spatie\Activitylog\ActivitylogServiceProvider:determineActivityModel in /opt/lampp/htdocs/plataforma/vendor/spatie/laravel-activitylog/src/ActivitylogServiceProvider.php:55
#69 Spatie\Activitylog\ActivitylogServiceProvider:getActivityModelInstance in /opt/lampp/htdocs/plataforma/app/Classes/ActivityLogger.php:22
#68 App\Classes\ActivityLogger:log in /opt/lampp/htdocs/plataforma/app/Listeners/UserEventListener.php:78
#67 App\Listeners\UserEventListener:onUserLogin in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:369
#66 call_user_func_array in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:369
#65 Illuminate\Events\Dispatcher:Illuminate\Events\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
#64 Illuminate\Events\Dispatcher:dispatch in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:580
#63 Illuminate\Auth\SessionGuard:fireLoginEvent in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:428
#62 Illuminate\Auth\SessionGuard:login in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php:362
#61 Illuminate\Auth\SessionGuard:attempt in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php:77
#60 App\Http\Controllers\Auth\LoginController:attemptLogin in /opt/lampp/htdocs/plataforma/app/Http/Controllers/Auth/LoginController.php:93
#59 App\Http\Controllers\Auth\LoginController:login in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#58 call_user_func_array in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#57 Illuminate\Routing\Controller:callAction in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#56 Illuminate\Routing\ControllerDispatcher:dispatch in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#55 Illuminate\Routing\Route:runController in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#54 Illuminate\Routing\Route:run in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/RedirectIfAuthenticated.php:43
#51 App\Http\Middleware\RedirectIfAuthenticated:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/EncuestaGeneral.php:60
#48 App\Http\Middleware\EncuestaGeneral:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Commitment.php:61
#45 App\Http\Middleware\Commitment:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Requirements.php:69
#42 App\Http\Middleware\Requirements:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Confirm.php:61
#39 App\Http\Middleware\Confirm:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Email.php:62
#36 App\Http\Middleware\Email:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Terms.php:60
#33 App\Http\Middleware\Terms:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:68
#30 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#27 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#24 Illuminate\Cookie\Middleware\EncryptCookies:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#23 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#22 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#21 Illuminate\Pipeline\Pipeline:then in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
#20 Illuminate\Routing\Router:runRouteWithinStack in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#19 Illuminate\Routing\Router:runRoute in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#18 Illuminate\Routing\Router:dispatchToRoute in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#17 Illuminate\Routing\Router:dispatch in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/app/Http/Middleware/Institution.php:30
#14 App\Http\Middleware\Institution:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#11 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#8 Illuminate\Session\Middleware\StartSession:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /opt/lampp/htdocs/plataforma/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /opt/lampp/htdocs/plataforma/public/index.php:53

**Comment by Gummibeer** [comment]
Thanks. So you are still on a v2 setup. 
This check fails https://github.com/spatie/laravel-activitylog/blob/9d9033978584d21138af86035957f341666188e7/src/ActivitylogServiceProvider.php#L46-L48 but I see no point why it could fail. The two class names are 100% equal and the `is_a()` function wasn't changed since PHP v5.3.9. 🤔

Could you check if the model is available at all? A simple `new \Spatie\Activitylog\Models\Activity()` should be enough. In addition I would recommend to delete your local composer cache `composer clearcache` and afterwards delete your vendor dir `rm -r ./vendor` and after that install all composer dependencies again `composer install`.
This should resolve any possible problems during installation.
