### ISSUE TITLE
Guard

### ISSUE THREAD

**Issue by suadikhasen** [spatie/laravel-activitylog#583]
I didnt use laravel default guard i use my guard and i config in configuration  file but still it doesnt store data on the database
When some one log to my application  how can i config to my own guard

**Comment by Gummibeer** [comment]
We use the default `$auth->getDefaultDriver()` as long as the `default_auth_driver` config keeps `null`. So if you've configured your custom guard as default auth driver it will be used. 

https://github.com/spatie/laravel-activitylog/blob/ef174eaf65f04e64f17cf01d477a48002a3d8c62/src/ActivityLogger.php#L36

https://github.com/spatie/laravel-activitylog/blob/ef174eaf65f04e64f17cf01d477a48002a3d8c62/src/ActivityLogger.php#L196

**Comment by suadikhasen** [comment]
ok i have a guard and its name is sancofa and i write 'sancofa' like this instead  of null in my config file but still database is empty it doesnt store is there a broblem in my config

**Comment by Gummibeer** [comment]
If there is nothing and not just an empty causer there is no problem with your guard but simply no "activity" to get logged.
A login doesn't get logged as long as there is no update to the user model and it implements the package trait. And even than it's not logged as login but as update.
So logging a login should be done by a manual call.

**Comment by suadikhasen** [comment]
So what you recommend me

**Comment by Gummibeer** [comment]
If you want to log the user login as a dedicated activity I recommend to log it in an event listener.
https://laravel.com/docs/5.8/authentication#events
https://docs.spatie.be/laravel-activitylog/v3/basic-usage/logging-activity/
