### ISSUE TITLE
CausedBy not detecting logged in user

### ISSUE THREAD

**Issue by Zolak94** [spatie/laravel-activitylog#588]
I made a new app and installed the latest version and activity log is not detecting logged in user. This is what I have in my `ServerObserver.php`
```php
    activity('Server updated')
        ->causedBy(Auth::user())
        ->performedOn($server)
        ->log($server->name.', '.$server->ip_address);
```
But in my database the columns `causer_id` and `causer_type`  are still `null`, I read the docs and it even says there `If you’re not using causedBy the package will automatically use the logged in user.` . 
In my other app, it's working normally with the same code.

**Comment by Gummibeer** [comment]
This method https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/ActivityLogger.php#L147-L162 is responsible to normalize your causer.
`Auth::user()` returns a model instance, if there is a logged in user. So it would instantly return the passed model and associate it https://github.com/spatie/laravel-activitylog/blob/89bbdbea8f085d72ba7513af989e2e54366f5794/src/ActivityLogger.php#L62-L73 with the activity. So could it be that you use different gate but haven't configured it as default? Or the moment you log the activity you don't have a logged in user?

**Comment by Zolak94** [comment]
It's a fresh app I didn't do anything with gates and User is logged for sure.

**Comment by Zolak94** [comment]
I think I know what's the problem. I'm updating server through job using pusher and echo. Can that cause behavior like this?

**Comment by Gummibeer** [comment]
I haven't used pusher, but does it keep the user session? To debug it you could add `dump()`/`dd()` calls to the linked methods and check what is passed in and how it get's processed.
