### ISSUE TITLE
Authomatic log not working on update event

### ISSUE THREAD

**Issue by 1988gadocansey** [spatie/laravel-activitylog#59]
Activity log automatic model log on work on create  but update and delete not being log. Example

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class BankModel extends Model
{
     use LogsActivity;
    //
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'tpoly_banks';
      protected static $logAttributes = ['NAME', 'ACCOUNT_NUMBER'];
    protected $primaryKey="ID";
    protected $fillable=array ('NAME','ACCOUNT_NUMBER');
    
}

**Comment by freekmurze** [comment]
The tests seems to confirm that the functionality is working. Please submit a failing test to prove that there is a problem.
