### ISSUE TITLE
[QUESTION] Emit broadcasting events when logging model events

### ISSUE THREAD

**Issue by luchorengo** [spatie/laravel-activitylog#591]
Is it possible to extend the Class to emit broadcasting events when activity model events happen?
I would like to listen for a specific channel which alerts app users about new activities.
I was thinking about such a handle function which dispatches a specific event as per activity model.

**Comment by Gummibeer** [comment]
The easiest way would be an observer that observes the activity model and dispatches your wanted events.
https://laravel.com/docs/5.8/eloquent#observers
https://stackoverflow.com/a/46461789/4907524

**Comment by luchorengo** [comment]
OK, that sounds good, but anyway I need to create a model that extends the ActivityLog model right?
Unfortunately, I'm not sure how to do it. This is not working so far, the observer is not being triggered:
```<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class ActivityLog extends Model
{
    protected $table = 'activity_log';
}
```
I've also tried this, but no luck
```<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Models\Activity as ActivityModel;

class ActivityLog extends ActivityModel
{
    protected $table = 'activity_log';
}
```

**Comment by luchorengo** [comment]
I found out how to proceed on this. For those who are facing the same issue, here is how I did it:

1. Create the ActivityLog observer that uses `Spatie\Activitylog\Models\Activity` as model
```
<?php

namespace App\Observers;

use Spatie\Activitylog\Models\Activity as ActivityLog;

class ActivityLogObserver
{
    /**
     * Handle the activity log "created" event.
     *
     * @param  \App\ActivityLog  $activityLog
     * @return void
     */
    public function created(ActivityLog $activityLog)
    {
        //
        \Log::debug('ActivityLog observer triggered!');
    }

    /**
     * Handle the activity log "updated" event.
     *
     * @param  \App\ActivityLog  $activityLog
     * @return void
     */
    public function updated(ActivityLog $activityLog)
    {
        //
    }

    /**
     * Handle the activity log "deleted" event.
     *
     * @param  \App\ActivityLog  $activityLog
     * @return void
     */
    public function deleted(ActivityLog $activityLog)
    {
        //
    }

    /**
     * Handle the activity log "restored" event.
     *
     * @param  \App\ActivityLog  $activityLog
     * @return void
     */
    public function restored(ActivityLog $activityLog)
    {
        //
    }

    /**
     * Handle the activity log "force deleted" event.
     *
     * @param  \App\ActivityLog  $activityLog
     * @return void
     */
    public function forceDeleted(ActivityLog $activityLog)
    {
        //
    }
}
```
2. Add the ActivityLog observer to the  `AppServiceProvider.php` boot and `use Spatie\Activitylog\Models\Activity as ActivityLog;` as the model
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Spatie\Activitylog\Models\Activity as ActivityLog;
use App\Observers\ActivityLogObserver;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        ActivityLog::observe(ActivityLogObserver::class);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
That's it. Every time ActivityLog stores a new record in the DB, you will have a new line in laravel log: `ActivityLog observer triggered!`

Thanks a lot for your guidance @Gummibeer !!!

**Comment by Gummibeer** [comment]
No problem, just for completion: you have to "register" your custom model in the package config.

**Comment by luchorengo** [comment]
Hi @Gummibeer , sorry to insist on this. I wanted to implement my custom model despite the previous solutions that I've posted works fine.
I created a new Model `ActivityLog` with this content:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Contracts\Activity;

class ActivityLog extends Model
{
    //
    protected $table    = 'activity_log';
}
```
Then in `activitylog.php` config file I've defined the model as
`'activity_model' => App\ActivityLog::class,`

But I'm getting this error

> The given model class `App\ActivityLog` does not implement `Spatie\Activitylog\Contracts\Activity` or it does not extend `Illuminate\Database\Eloquent\Model`

Any idea about what's wrong? Using any non-existent model like `App\ActivityLogQwerty` throws the same error message, so I'm guessing that something is wrong in config file.

Thanks in advance

**Comment by Gummibeer** [comment]
You already have the `use` but not the `implement`. 😉
`https://github.com/spatie/laravel-activitylog/blob/master/src/Contracts/Activity.php`
But the easiest is to `extend` the original `Activity` model and just add/change what you want. This prevents you from writing all the interface methods your own.
