### ISSUE TITLE
How to query all logs within a certain "Category"

### ISSUE THREAD

**Issue by TutanRamon** [spatie/laravel-activitylog#593]
Lets say I have two Models (among other models):
- NewsItem
- Category

Each newsItem has only 1 category. 

I've your beautiful package up and running and its perfectly logging all changes to NewsItem. 
However, on the category page, I want to display all changes that where logged for all the newsitems within that category. How can I do that? Can you point me in the right direction? 

Thanks, and thanks for this package.

**Comment by Gummibeer** [comment]
In #526 the question is already answered.

If you have any additional questions: just ask.
