### ISSUE TITLE
Can you change the JSON column type for `properties`?

### ISSUE THREAD

**Issue by GlitterCakes** [spatie/laravel-activitylog#596]
Hello,

I am wondering if it is possible to change the column type for `properties` in the activity_log table from JSON to anything else that would be supported in MySQL 5.5. Unfortunately our database cluster is running on MySQL 5.5 and it's not in my power to change it.

**Comment by Gummibeer** [comment]
Yes you can do so. The migration is copied in your project and you can manipulate it. We don't use any of the JSON features yet.

**Comment by GlitterCakes** [comment]
Thank you =]
