### ISSUE TITLE
This package requires PHP ^7.0, isn't too much updated requirement?

### ISSUE THREAD

**Issue by pacoorozco** [spatie/laravel-activitylog#60]
Hi, when I try to use this package on a PHP 5.6.5 box, composer throws:

    Your requirements could not be resolved to an installable set of packages.
    Problem 1

    - Installation request for spatie/laravel-activitylog 1.7.1 -> satisfiable by spatie/laravel-activitylog[1.7.1].
    - spatie/laravel-activitylog 1.7.1 requires php ^7.0 -> your PHP version (5.6.5) does not satisfy that requirement.

I think this is a **very strong** requirement. Is there any version for PHP 5.6?

Thanks in advance.

**Comment by pacoorozco** [comment]
I've seen a older issue #31 which explain your decision... OMG I've coded using your package but my ISP doesn't update to PHP 7.0, yet!!!

:-(

**Comment by freekmurze** [comment]
To me PHP 5 is dead ☠️

You're free to fork our code and maintain your own PHP 5 compatible version.
