### ISSUE TITLE
Table Name and Custom Column Name

### ISSUE THREAD

**Issue by lramondev** [spatie/laravel-activitylog#606]
Hello. Would you have any way to change the name of the table columns?
In the configuration file I can change the table name.

Just like that

```
public function getAuthPassword() {
    return $this->new_name;
}
```

**Comment by Gummibeer** [comment]
Hey,

the only way would be to override all places where the columns/attributes are used. You could try to map the new columns to the old attributes via accessor/mutator. But all this isn't a supported usecase. So on your own risk.

Why do you want/need to change column names? 🤔

**Comment by lramondev** [comment]
I would like to keep my standard table naming.
Thanks I'll try.

**Comment by lramondev** [comment]
I would like to keep my default names in the tables.
Thanks. I'll try!
