### ISSUE TITLE
Correct documentation for tapActivity() under Logging model events

### ISSUE THREAD

**Issue by tomfortmuller** [spatie/laravel-activitylog#613]
The current code found in the documentation for tapActivity() doesn't appear to be correct. https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/#tap-activity-before-logged-from-event

```php
public function tapActivity(Activity $activity, string $eventName)
{
    $activity->comment_count = $this->comments()->count();
}
```

This results in a column not found exception. I was able to correct the issue by using this code:

```php
public function tapActivity(Activity $activity, string $eventName)
{
    $activity->properties = $activity->properties->put('comment_count', $this->comments()->count());
}
```

**Comment by weidmaster** [comment]
Thank you @tomfortmuller 
I had issues with the documentation as well and your example works!
