### ISSUE TITLE
Object activity changes 

### ISSUE THREAD

**Issue by sevmardi** [spatie/laravel-activitylog#617]
Based on #556 I would like to fetch the activities and along with the changes. 

Something along the lines of 

```
$object = Model::findOrFail(1);
$object->activities->changes; 
```

Should return activities + changes 

Is is possible?

**Comment by Gummibeer** [comment]
The changes are an appended model attribute.
https://github.com/spatie/laravel-activitylog/blob/808a3e5c119d31d1115ff7831efa866aa3fe9692/src/Models/Activity.php#L61-L64
So you have to access them per activity and not on the collection. But you can use any collection method and merge/reduce them, pluck single entries or whatever you need.

```php
foreach($model->activities as $activity) {
    $activity->changes; // do what you want to do with the changes
}
```
