### ISSUE TITLE
Date casting and attribute logging

### ISSUE THREAD

**Issue by mpryvkin** [spatie/laravel-activitylog#623]
I am using date casting for some model attributes using the code below.

```
protected $casts = [
    'signed_date' => 'date',
];
```
When `signed_date` field is updated `properties` field contains the following value:
>{"attributes":{"signed_date":{"date":"2018-09-25 00:00:00.000000","timezone_type":3,"timezone":"UTC"}},"old":{"signed_date":{"date":"2018-09-26 00:00:00.000000","timezone_type":3,"timezone":"UTC"}}}

However because the attribute is listed in `$casts`, it seems that it makes more sense to produce a string in `Y-m-d` format which is what `getAttributes()` or `attributesToArray()` (although produces date/time) do.

```
>>> $model->getAttributes()
=> [
     "signed_date" => "2018-09-25",
   ]
```

```
>>> $model->attributesToArray()
=> [
     "signed_date" => "2018-09-25 00:00:00",
   ]
```

From reading the source code I see that you specifically serialize dates as DateTime object.

https://github.com/spatie/laravel-activitylog/blob/091efc48be732e8704e2bd2bc9aa332f78800bb9/src/Traits/DetectsChanges.php#L142-L144

This code seemed to copied from Laravel framework `addDateAttributesToArray()` method called from `attributesToArray()` method.

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L89-L94

```
        // If an attribute is a date, we will cast it to a string after converting it
        // to a DateTime / Carbon instance. This is so we will get some consistent
        // formatting while accessing attributes vs. arraying / JSONing a model.
        $attributes = $this->addDateAttributesToArray(
            $attributes = $this->getArrayableAttributes()
        );
```
However later in `attributesToArray()` it specifically detects casts with the following code.

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L100-L105

```
        // Next we will handle any casts that have been setup for this model and cast
        // the values to their appropriate type. If the attribute has a mutator we
        // will not perform the cast on those attributes to avoid any confusion.
        $attributes = $this->addCastAttributesToArray(
            $attributes, $mutatedAttributes
        );
```
Is there a reason you don't use `attributesToArray()` internally to serialize attributes? 

Otherwise values of logged attributes differ from expected as with date casting.

**Comment by Gummibeer** [comment]
Hey,

thanks for this very well explained report. :)

I've checked it out and also opened a PR. I've improved the existing date casting and added the custom date casting.
It's now the same like `attributesToArray()` does.
To your question why we don't use `attributesToArray()`: because we also support attributes that aren't appended but have an accessor. So we have to use our custom logic and rebuild core logic because there's no `attributeToArray($key, $value)` method. :(
But I've moved more towards core logic by using `isDateAttribute()` to include `$dates` and `$casts` date without custom format.

**Comment by mpryvkin** [comment]
Thanks for quick reply and posted code, I will check it out.

I had to mention that my post was rather a question to better understand the package as I was researching the format of the date fields.

It seems that this can may be a breaking change for some (if merged into master) if someone is relying on array date format rather than string.

**Comment by Gummibeer** [comment]
Good point.
@freekmurze do you want to have this in a new major release? Or do we argue that this is a fix because dates should be serialized to strings and the current array is a bug.

**Comment by mpryvkin** [comment]
After upgrading to Laravel 6 and Carbon 2, all attributes that are listed in `$casts` are now serialized as strings in ISO 8601 format instead of arrays according to Carbon 2 [migration notes](https://carbon.nesbot.com/docs/#api-carbon-2).

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.12.0
