### ISSUE TITLE
I get syntax error when run my app ( unexpected ':', expecting '{' ) in helpers.php on line 6

### ISSUE THREAD

**Issue by rsteveyoung** [spatie/laravel-activitylog#63]
While trying to execute my app, after laravel-activitylog properly installed and configured, got this error:

( ! ) Parse error: syntax error, unexpected ':', expecting '{' in /home/vagrant/Code/laravel-app/vendor/spatie/laravel-activitylog/src/helpers.php on line 6

The helper file has this content:
`<?php

use Spatie\Activitylog\ActivityLogger;

if (! function_exists('activity')) {
    function activity(string $logName = null): ActivityLogger
    {
        $defaultLogName = config('laravel-activitylog.default_log_name');

        return app(ActivityLogger::class)->useLog($logName ?? $defaultLogName);
    }
}`

What can i do in order to solve this problem ?

Atte., R. Steve Young.

**Comment by rsteveyoung** [comment]
![captura de pantalla 2016-09-07 a las 23 22 39](https://cloud.githubusercontent.com/assets/12772826/18335017/5033b256-7552-11e6-94ae-df6d29ac5056.png)

**Comment by CrashSensei** [comment]
It looks like you are using PHP5 instead of PHP7 which is not supported by laravel-activitylog.

If you cannot upgrade to PHP7 then I suggest using my backport of laravel-activitylog which works with PHP5 [laravel-activitylog-backport](https://github.com/LinearSoft/laravel-activitylog-backport)

**Comment by kikz4life** [comment]
I'm having this problem also. I'm running on php 7.  Here is my php -v result
`PHP 7.0.15 (cli) (built: Feb 13 2017 10:30:54) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans`

By the way this only happens when I'm running cron jobs. :(. Please help

**Comment by freekmurze** [comment]
Probably your cron jobs are still using an old PHP version.

Inside a cronjob try running this code (typed up quick, not tested)

```php
<?php
ob_start();
phpinfo();
$phpinfoContents = ob_get_contents();
ob_clean();
file_put_contents('path_to_a_file', $phpinfoContents);
```

Of course change that `path_to_a_file` to something real.

Check the PHP version in that file.

**Comment by kikz4life** [comment]
oh its showing 
`phpinfo()
PHP Version => 5.6.30`
