### ISSUE TITLE
AuthManager issue while integrating with lumen 5.8

### ISSUE THREAD

**Issue by ak7240** [spatie/laravel-activitylog#630]
[ Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Auth\AuthManager ]

(1/1) BindingResolutionExceptionUnresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Auth\AuthManager
--
in Container.php line 975
at Container->unresolvablePrimitive(object(ReflectionParameter))in Container.php line 913
at Container->resolvePrimitive(object(ReflectionParameter))in Container.php line 854
at Container->resolveDependencies(array(object(ReflectionParameter)))in Container.php line 816
at Container->build('Illuminate\\Auth\\AuthManager')in Container.php line 667
at Container->resolve('Illuminate\\Auth\\AuthManager', array())in Container.php line 615
at Container->make('Illuminate\\Auth\\AuthManager', array())in Application.php line 267
at Application->make('Illuminate\\Auth\\AuthManager')in Container.php line 927
at Container->resolveClass(object(ReflectionParameter))in Container.php line 855
at Container->resolveDependencies(array(object(ReflectionParameter), object(ReflectionParameter), object(ReflectionParameter)))in Container.php line 816
at Container->build('Spatie\\Activitylog\\ActivityLogger')in Container.php line 261
at Container->Illuminate\Container\{closure}(object(Application), array())in Container.php line 785
at Container->build(object(Closure))in Container.php line 667
at Container->resolve('Spatie\\Activitylog\\ActivityLogger', array())in Container.php line 615
at Container->make('Spatie\\Activitylog\\ActivityLogger', array())in Application.php line 267
at Application->make('Spatie\\Activitylog\\ActivityLogger', array())in helpers.php line 42
at app('Spatie\\Activitylog\\ActivityLogger')in LogsActivity.php line 41
at User::Spatie\Activitylog\Traits\{closure}(object(User))in Dispatcher.php line 347
at Dispatcher->Illuminate\Events\{closure}('eloquent.updated: App\\Models\\User', array(object(User)))in Dispatcher.php line 196
at Dispatcher->dispatch('eloquent.updated: App\\Models\\User', array(object(User)))in HasEvents.php line 188
at Model->fireModelEvent('updated', false)in Model.php line 749
at Model->performUpdate(object(Builder))in Model.php line 660
at Model->save()in User.php line 580

**Comment by Gummibeer** [comment]
Hey,

Lumen isn't primary supported. It could be that it works but only with adjustments.
#160 provides several steps to integrate this package into Lumen. But I don't know if they are still up2date. https://github.com/spatie/laravel-activitylog/issues/160#issuecomment-307615980 should solve your issue. You could even reduce it to `$app->alias('auth', \Illuminate\Auth\AuthManager::class);`.
