### ISSUE TITLE
Causer By and Causer Type is not registered for other users than Default

### ISSUE THREAD

**Issue by salahy** [spatie/laravel-activitylog#631]
Hello,
I have 3 different guards and I am using model logs, everything works perfectly but for logs for the guards not saving, they are always null except for User which is default.
What could be the problem ?
Thanks

**Comment by Gummibeer** [comment]
Hey,
We use the configured auth driver and load it during service construction.
So you have to set your auth driver before the activity logger is bound.

https://github.com/spatie/laravel-activitylog/blob/35949d8ad0f049998f82c92c0cd7da4390305950/src/ActivityLogger.php#L32-L41

**Comment by salahy** [comment]
Thanks for the reply, I am using Logging model events, where I can set my auth driver ?

**Comment by Gummibeer** [comment]
You can use the explicit default auth driver config in activitylog config or use the Laravel core auth config.
But you aren't the first one with problems in a multi auth driver app.
So I would also accept a PR that improves the package ability to handle multiple drivers. The easiest would be a `setAuthDriver()` method!?
