### ISSUE TITLE
composer require failed

### ISSUE THREAD

**Issue by s9ul3ss** [spatie/laravel-activitylog#635]
Hello, i'm trying to install but it gives an me error.
![image](https://user-images.githubusercontent.com/36394543/68889167-c4b0e100-06f2-11ea-9af5-85e5935e7d4b.png)

**Comment by s9ul3ss** [comment]
i'm using php 7.3 and laravel 6

**Comment by Gummibeer** [comment]
Could you try to run the composer command with `-v` flag? This should add the exception stack trace. I think that it doesn't belong to this package but would like to see where it is thrown.

**Comment by s9ul3ss** [comment]
![image](https://user-images.githubusercontent.com/36394543/68974083-3d34a200-07c6-11ea-9273-a2829b500270.png)

**Comment by Gummibeer** [comment]
Thanks! But I can't find anything about our package. Are you able to require any other package? Have you tried `composer self-update` to get to latest version? It looks like an incompatible or damaged composer.
