### ISSUE TITLE
extending Moloquent not Model

### ISSUE THREAD

**Issue by mohamedFatehy** [spatie/laravel-activitylog#636]
we are using Moloquent jessenqer package instead of elquent package 
so every time we want to update composer package the file Activity.php change the extends from Moloquent to Model
and we have to manually change it back 

so is there any permenent solution that we cant use the activity log with Moloquent not Eloquent

**Comment by Gummibeer** [comment]
Hey,

you can configure your own model in the config file.
https://github.com/spatie/laravel-activitylog/blob/195887d440ba4664fdea4c2fb8fbc67adb34a291/config/activitylog.php#L33-L38

Your custom model only has to implement the interface https://github.com/spatie/laravel-activitylog/blob/master/src/Contracts/Activity.php 

#574 
#81

**Comment by mohamedFatehy** [comment]
i created another class outside the vendor called activity.php and put the content of the old class except the old model and replaced the new model but it dident work 

so the bring back the same old content but the same error messges keeps showing 
that 
The given model class `Packages\Activity` does not implement `Spatie\Activitylog\Contracts\Activity` or it does not extend `Illuminate\Database\Eloquent\Model`

the code is blew
![22](https://user-images.githubusercontent.com/36978568/69047909-ebc62600-0a04-11ea-914d-e858f61a29dc.png)
![11](https://user-images.githubusercontent.com/36978568/69047910-ebc62600-0a04-11ea-8501-5522531e0ee3.png)

![33](https://user-images.githubusercontent.com/36978568/69048073-3fd10a80-0a05-11ea-8183-f409e261702c.png)

**Comment by nick322** [comment]
@mohamedFatehy 
I also have the same problem
Later, I directly switched to inheriting MongoDBModel to solve the problem.

![截圖 2022-05-17 10 35 17](https://user-images.githubusercontent.com/9151347/168716713-c0514675-b4ec-4954-8682-14b78c0dfc2e.png)
