### ISSUE TITLE
Subject id not inserting while update

### ISSUE THREAD

**Issue by skrbalamurugan** [spatie/laravel-activitylog#638]
Subject Id not inserting while updating data 

```php
activity()->causedBy(Auth::user()->id)
        ->performedOn(New User)
        ->withProperties(['attributes' => $request->all()')])
        ->log('User Edited');
```

**Comment by Gummibeer** [comment]
Hey,
a `new User` does not have any ID - so there is no way to log it as subject. If you want to log model changes you should also use the package provided log model events trait: https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

Your code snippet could be changed to:
```php
activity()
    ->causedBy($request->user())
    ->performedOn($user)
    ->withProperties(['attributes' => $request->all()])
    ->log('User Edited');
```

**Comment by skrbalamurugan** [comment]
> Hey,
> a `new User` does not have any ID - so there is no way to log it as subject. If you want to log model changes you should also use the package provided log model events trait: https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/
> 
> Your code snippet could be changed to:
> 
> ```
> activity()
>     ->causedBy($request->user())
>     ->performedOn($user)
>     ->withProperties(['attributes' => $request->all()])
>     ->log('User Edited');
> ```

**Comment by skrbalamurugan** [comment]
`->performedOn($user)` what is $user here

**Comment by Gummibeer** [comment]
It's the user or any other model you've edited, created or done any other action on.
