### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by sevmardi** [spatie/laravel-activitylog#64]
Hi there, 

I was trying to install package which installs perfectly fine without errors, but than afterwards getting a parse error as I refresh the page. 
`
Parse error: syntax error, unexpected ':', expecting '{' in /var/www/localhost/api/vendor/spatie/laravel-activitylog/src/helpers.php on line 6
`

Am I the only one getting this error?

**Comment by freekmurze** [comment]
Please upgrade to PHP 7 to use this package.
