### ISSUE TITLE
properties column content is []

### ISSUE THREAD

**Issue by IManAsap** [spatie/laravel-activitylog#640]
Lavravel "^6.2"
spatie/laravel-activitylog "^3.9"
MySql 5.6

due MySql version i change properties column type to text, but the content of this column rows is always []

Can you help me ?

Regards

**Comment by Gummibeer** [comment]
Hey,

could you get into more detail? What's your code that should produce a log with properties? Do you use the model trait or custom activity logging?

**Comment by IManAsap** [comment]
Hi,
i use the model trait

**Comment by IManAsap** [comment]
Sorry i forget to set $logFillable property
