### ISSUE TITLE
Method Illuminate\Database\Query\Builder::withProperties does not exist.

### ISSUE THREAD

**Issue by sunnyjayjay** [spatie/laravel-activitylog#642]
I am trying to use the withProperties function as follows:

    activity()
                ->log('Bulk item deletion: ' . $id)
                ->causedBy(Auth::user())
                ->withProperties(['title' => $title]);

But I get the error shown in the title above. I am using version 2.5 and Laravel 5.6.

**Comment by coderiki** [comment]
Please try this way;
```
activity()
            ->log('Bulk item deletion: ' . $id)
            ->withProperties(['title' => $title]);
```

If the user is logged in, the causer_type and causer_id fields are filled in automatically.

**Comment by sunnyjayjay** [comment]
coderiki is correct - but the real answer is the sequence: you must use ->log() at the end;
