### ISSUE TITLE
Logging directly related model attributes

### ISSUE THREAD

**Issue by VictorMonroyHz** [spatie/laravel-activitylog#645]
Hi!
I need to save the value of my id and not the id in the properties field.

```php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;

class User extends Authenticatable
{
    use Notifiable, LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'id_rol'
    ];

    protected static $logAttributes = ['name', 'email', 'rol.nombre'];
    //protected static $logFillable = true;
    //protected static $logOnlyDirty = true;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function rol(){
        return $this->belongsTo('App\Rol');
    }

}
```

**Comment by Gummibeer** [comment]
Hey,

could you get into more detail? Right now I've no idea what you try to accomplish and why it doesn't work. If you want to log the user ID simply add it to the list of loggable attributes. Even if I don't know why the ID should be monitored because if it's changeable it isn't an ID.

**Comment by halah-m** [comment]
I have the same issue, every other model I can save its logs, but when I add it to User model it didn't save anything.

My User Model

`class User extends Authenticatable
{
    use Notifiable;
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $logAttributes = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}`

properties column data `{"ip": "127.0.0.1"}`

**Comment by Gummibeer** [comment]
@halah-m what's exactly your issue? Because I still don't know what's the real issue in this report I would like to ask you to open your own one with a detailed explanation of your problem.
