### ISSUE TITLE
Performance difference using model vs global enable/disable logging

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-activitylog#650]
There seems to be a performance difference between using the model->disableLogging() vs activity()->disableLogging(). This seems to stem from the latter only getting checked after the model has already created the activity and tried to log it. Seems like adding a check to the model level to see if activity logging is enabled would address it and make so that the model level doesn't have to do the work if global logging is disabled in the first place.

**Comment by Gummibeer** [comment]
Hey, thanks for reporting this issue! 😊
Are you able / do you want to open a PR and fix it? If not, totally fine!

**Comment by ragingdave** [comment]
I should be able to work up something around this. Will give it a shot!

**Comment by Gummibeer** [comment]
Great! If you need some input, feedback, help or something don't hesitate to ask. 😊

**Comment by ragingdave** [comment]
So I got back to finally working on fixing this, but I'm having trouble testing the change, as I can't figure out how to mock the anonymous class in the LogsActivityTest to confirm that my chance actually has fixed the performance issue. I've pushed up the PR at least in the fixed state, but would be happy to be able to properly confirm the fix.

**Comment by Gummibeer** [comment]
released as https://github.com/spatie/laravel-activitylog/releases/tag/3.11.3

**Comment by vahidalvandi** [comment]
how i can disable globaly just in user area ? in admin enable automatilay?

**Comment by Gummibeer** [comment]
@vahidalvandi I would recommend a middleware that enables/disables logging.
