### ISSUE TITLE
Does this support email to developer?

### ISSUE THREAD

**Issue by RVP04** [spatie/laravel-activitylog#652]
Sir,
     I want to know whether the log will support to send email to developer. Please add that feature also.

**Comment by Gummibeer** [comment]
Hey,

in which case do you want to email someone? And with which content? Right now there's no build in feature - but we have several events you could use to listen on and send and email via normal laravel logic.

**Comment by RVP04** [comment]
Yes i understand. But if it has feature to send email. It will be awesome.

**Comment by Gummibeer** [comment]
Hey,

to think about any implementation we have to know in which case and with which content you want to send an email?
I think that we won't add any feature like that. But depending on the answers we can help you to add it in your app.
