### ISSUE TITLE
Logging Model Events with a Causer when User not logged in (Jobs and Seeders)

### ISSUE THREAD

**Issue by fredbradley** [spatie/laravel-activitylog#661]
Is there a way of populating the `causer_id` and `causer_type` fields for Model Event logging when the user isn't logged in. 

For example in Seeders, and (most importantly) in Queued Jobs.

**Comment by Gummibeer** [comment]
This relates to #649 & #582 

Right now there are multiple ways doing so.
* do `Auth::login()` in your Commands
* use the `tapActivity()` method on the models
* use an observer on the activity model

But the best would be to implement something like requested in #582

**Comment by Gummibeer** [comment]
I will close this issue even if v4 isn't released yet. But the task itself is done and I want to check which tasks are really open. Please keep an eye on #787

**Comment by freekmurze** [comment]
Addressed in v5 (#1452) with `CauserResolver::withCauser()`. Works for seeders, jobs, and any context without an authenticated user.
