### ISSUE TITLE
Users login and logout 

### ISSUE THREAD

**Issue by kazemimorteza68** [spatie/laravel-activitylog#662]
Hi.
I have 2 questions about this package:
1-can i register users login and logout using this package? after i install and setup this package on User model only CRUD event are registered.How can i register users login and logout using this Package ?

2-can i register  and log all URLs come to my site using this package ?

Thanks.

**Comment by Gummibeer** [comment]
Hey, you have to use custom activities to log login/logout.
https://docs.spatie.be/laravel-activitylog/v3/basic-usage/logging-activity/

This package isn't made for tracking - so if you want to track your referers or any other tracking like things you have to use another package - for example: https://github.com/antonioribeiro/tracker
