### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by ekandreas** [spatie/laravel-activitylog#664]
The command `php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"` just gives us:
`Unable to locate publishable resources`
We have all the models in a "Models" folder. Can it be the case here?

**Comment by Gummibeer** [comment]
Hey,
could it be that you already have a class named `CreateActivityLogTable`? The models aren't important for the publish step.

https://github.com/spatie/laravel-activitylog/blob/553449686115b3ca0dfffb152699204386f9ed52/src/ActivitylogServiceProvider.php#L22-L28

**Comment by ekandreas** [comment]
Ohh, my. So sorry! Thanks!

**Comment by datlechin** [comment]
same issue

```php
class ActivitylogServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
        ->name('laravel-activitylog')
        ->hasConfigFile('activitylog')
        ->hasMigrations([
            'CreateActivityLogTable',
            'AddEventColumnToActivityLogTable',
            'AddBatchUuidColumnToActivityLogTable',
        ])
        ->hasCommand(CleanActivitylogCommand::class);
    }

    public function registeringPackage()
    {
        $this->app->bind(ActivityLogger::class);

        $this->app->singleton(LogBatch::class);

        $this->app->singleton(CauserResolver::class);

        $this->app->singleton(ActivityLogStatus::class);
    }

    public static function determineActivityModel(): string
    {
        $activityModel = config('activitylog.activity_model') ?? ActivityModel::class;

        if (! is_a($activityModel, Activity::class, true)
            || ! is_a($activityModel, Model::class, true)) {
            throw InvalidConfiguration::modelIsNotValid($activityModel);
        }

        return $activityModel;
    }

    public static function getActivityModelInstance(): ActivityContract
    {
        $activityModelClassName = self::determineActivityModel();

        return new $activityModelClassName();
    }
}
```

**Comment by alinmiron** [comment]
Hi, 
Had the same issue when I ran
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-migrations"
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-config"

I got rid of it by running:
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"

**Comment by Gummibeer** [comment]
@alinmiron please check your local installed and the referenced documentation version.
I expect that you've installed v3 but checked v4 documentation (default).

**Comment by alinmiron** [comment]
all i did was to run:

composer require spatie/laravel-activitylog

and I got this, in composer.json:   "spatie/laravel-activitylog": "^3.17",

**Comment by warifp** [comment]
> Hi,
> Had the same issue when I ran
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-migrations"
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-config"
> 
> I got rid of it by running:
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"

Thank!

**Comment by hoangphidev** [comment]
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"

Thanks

**Comment by warifp** [comment]
> php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"

Thank!

**Comment by samuelvs** [comment]
Hi, the same problem is avaiable in https://github.com/spatie/laravel-health

**Comment by bfuzze** [comment]
For future readers: The above did not work for me.  I am trying to upgrade an old site currently on L6.  This issue is the --provider option strips slashes from the value, and so it does not match the registered providers list.  Running without the provider option works, although this may not be a good work-around depending on your situation.

**Comment by sueboy19** [comment]
Hi everybody

php: 8.2.8
laravel: v10.37.3
spatie/laravel-activitylog: 4.7.3

I try  --tag="migrations"    --tag="config" is faild
```php
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"
```

```shell
 INFO  No publishable resources for tag [migrations].
 INFO  No publishable resources for tag [config].
```

Now  try is correct, because README.md content like under
```php
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-migrations"
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-config"
```

```shell
   INFO  Publishing [activitylog-migrations] assets.

_table.php]  DONE
  Copying file [C:\WinNMP\WWW\acc_hr\vendor\spatie\laravel-activitylog\database\migrations\add_event_column_to_activity_log_table.php.stub] to [C:\WinNMP\WWW\acc_hr\database\migrations\2023_12_20_141207_add_event_column_to_activity_log_table.php]  DONE
  Copying file [C:\WinNMP\WWW\acc_hr\vendor\spatie\laravel-activitylog\database\migrations\add_batch_uuid_column_to_activity_log_table.php.stub] to [C:\WinNMP\WWW\acc_hr\database\migrations\2023_12_20_141208_add_batch_uuid_column_to_activity_log_table.php]  DONE

Copying file [C:\WinNMP\WWW\acc_hr\vendor\spatie\laravel-activitylog\config\activitylog.php] to [C:\WinNMP\WWW\acc_hr\config\activitylog.php]  DONE
```

Just confused ？
