### ISSUE TITLE
Run code after an activity is logged

### ISSUE THREAD

**Issue by grenadecx** [spatie/laravel-activitylog#665]
Okay I feel kinda stupid, but is there a way to run code after an activity have been logged? Maybe it's an edge case, but I wanna send an notification after and activity has been logged and I can't quite figure out how I would do that.

The package seems pretty extendable and I have extended the functionality quite a bit with macros and traits and what not, but can't figure this out.

If you don't mind, any help would be appreciated, thanks!

**Comment by Gummibeer** [comment]
The easiest way would be to use an observer on the activity model.

**Comment by grenadecx** [comment]
That makes sense. Guess I was just too tired today... Thanks!
