### ISSUE TITLE
Change primary key to use uuid

### ISSUE THREAD

**Issue by jeangomes** [spatie/laravel-activitylog#666]
I have diferents logs, and legacy tables. I need merge, and I will generate log offline.
How can I change the primary key.

**Comment by Gummibeer** [comment]
Hey,
you will have to override the model, register your new one in the config and update the migration.
After this your activities will get a uuid instead of an autoincrement.

**Comment by jeangomes** [comment]
Do you intend to develop something to facilitate this in the future, something configurable?

**Comment by Gummibeer** [comment]
Because there is a simple to implement solution we won't add any `uses_uuid` or similar config value.
If there's any code part in the package that assumes that the ID is an `int` we will try to fix this to make this change easier. But none of the spatie packages provides UUID primary key support out of the box.
That's why we publish the migration and allow to override the model.

**Comment by jeangomes** [comment]
Thanks.

**Comment by newtenchi** [comment]
Make this change in migration

**Comment by gabrielbidula** [comment]
This change in the migration file worked for me:

`$table->nullableUuidMorphs('subject', 'subject');`
`$table->nullableUuidMorphs('causer', 'causer');`

**Comment by kiraware** [comment]
What if in some model i use bigint and some model use uuid for primary key? The `subject_id` is completely changed to uuid if i use `$table->nullableUuidMorphs('subject', 'subject');`. While it fix the uuid problem, it create problem for bigint primary key. So basically, does it mean that i cant use both bigint and uuid together in my application models?

**Comment by kiraware** [comment]
> What if in some model i use bigint and some model use uuid for primary key? The `subject_id` is completely changed to uuid if i use `$table->nullableUuidMorphs('subject', 'subject');`. While it fix the uuid problem, it create problem for bigint primary key. So basically, does it mean that i cant use both bigint and uuid together in my application models?

After see some answer in https://github.com/Z3d0X/filament-logger/issues/35#issuecomment-1431687981 and https://github.com/spatie/laravel-activitylog/discussions/771#discussioncomment-63446, you have to change it to string in order to use bigint and uuid together.

```php
$table->string('subject_id')->nullable();
$table->string('subject_type')->nullable();
```

Hope this help.

**Comment by maurolacerda-tech** [comment]
> > What if in some model i use bigint and some model use uuid for primary key? The `subject_id` is completely changed to uuid if i use `$table->nullableUuidMorphs('subject', 'subject');`. While it fix the uuid problem, it create problem for bigint primary key. So basically, does it mean that i cant use both bigint and uuid together in my application models?
> 
> After see some answer in [Z3d0X/filament-logger#35 (comment)](https://github.com/Z3d0X/filament-logger/issues/35#issuecomment-1431687981) and [#771 (comment)](https://github.com/spatie/laravel-activitylog/discussions/771#discussioncomment-63446), you have to change it to string in order to use bigint and uuid together.
> 
> $table->string('subject_id')->nullable();
> $table->string('subject_type')->nullable();
> Hope this help.

![Image](https://github.com/user-attachments/assets/a623cf0d-0bc6-4188-ac19-f5873b7ceb17)
