### ISSUE TITLE
do we have putAll method?

### ISSUE THREAD

**Issue by amiiiiiink** [spatie/laravel-activitylog#667]
hi, I have a question  , I wanted to add ip , OS , Browser name , browser version
into my logs, i have added
$activity->properties = $activity->properties
->put('ip', request()->ip())
->put('os', Browser::platformName())
->put('browser', Browser::browserName())
->put('BrowserVersion', Browser::browserVersion());
my question is that where is put() method? and do we have any putAll() or similar method to add all IP, OS, Browser , Browser version in an array?

**Comment by Gummibeer** [comment]
Hey,
Like said in #39 

@amiiiiiink unser the hood it's a collection. So you could use the merge() method.
https://laravel.com/docs/5.8/collections#available-methods

**Comment by amiiiiiink** [comment]
> Hey,
> Like said in #39
> 
> @amiiiiiink under the hood it's a collection. So you could use the `merge() `method.
> https://laravel.com/docs/5.8/collections#available-methods

thanks :smiley:
