### ISSUE TITLE
Add SubjectOfActivity trait

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-activitylog#67]
Hey @freekmurze ,

what do you think of another trait `SubjectOfActivity`. It would basically be the opposite of the `CausesActivity`. 

However we would need to find a good name for the relationship, as `activity` can not be used, as the causer model might also be the subject model in some cases.

Maybe also `subjectOfActivity`? Or maybe you have a better idea?

**Comment by freekmurze** [comment]
My first thought is that this trait isn't really needed. What's your use case for this?

**Comment by lukasoppermann** [comment]
Well, I have two use cases: 

1. When an admin does a user-reset I want to retrieve it for the user who is the subject when he tries to log in, to alert him that he needs to actually create a new password.

2. When storing activity for a model, like a piece of content, I want to show a list of most recent activities for this model, which might not be (only) by the current active user, who is the `causer`. So in this case I also need to retrieve activities for the `subject` that I am currently working with.

I think there could be many use cases, where the subject is actually more interesting than the causer.

**Comment by freekmurze** [comment]
Thank you for these good examples. However I think these scenarios are not the common. If you need this functionality, it can be added in your own project(s).

**Comment by lukasoppermann** [comment]
Not a problem to add it myself, however, I don't see the problem with adding it the the package, as it is basically only a tiny function:

```php
    public function subjectOfActivitie(): MorphMany
    {
        return $this->morphMany(Activity::class, 'subject');
    }
```

**Comment by freekmurze** [comment]
Technically there certainly is no problem. It's good code. However I like to keep the packages as small as they can be. I only take on functions that I feel are needed by a lot of people (or if I need it myself). Choosing what goes in and what not is certainly very subjective, it's a large grey area.

In this case I'm thinking I don't need this, I don't think the majority of users needs this, the ones who do can easily implement it themselves.

**Comment by lukasoppermann** [comment]
While I do not agree with this not being useful, I do understand your decision. Thanks for explaining.
