### ISSUE TITLE
How do I go about starting an Activity Log

### ISSUE THREAD

**Issue by Kushal-u1462694** [spatie/laravel-activitylog#672]
I'm developing a medicine management system I have done all my features but one of the features I would like is an activity log where the admin can have that tracebeility incase a carer deletes a medicine from the system. I have been following a tutorial but only tells me info about it not actually how to do it. Thank You.

**Comment by vdbelt** [comment]
If you use the `LogsActivity` trait on your model, the package should automatically log the `deleted` event. 

See the docs at https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

**Comment by Kushal-u1462694** [comment]
> If you use the `LogsActivity` trait on your model, the package should automatically log the `deleted` event.
> 
> See the docs at https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

Hi I have used this on all my models such as carer, patients etc but it doesn't seem to work it showing a red line underneath I think it's not recognising it. 
    public function activity() {
                ->performedOn($anEloquentModel)
                ->causedBy($user)
    ->withProperties(['shouldBeFired' => true])
    ->log('Deleted a patients records! Oh no! ');

    }

**Comment by Kushal-u1462694** [comment]
> If you use the `LogsActivity` trait on your model, the package should automatically log the `deleted` event.
> 
> See the docs at https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/

Hi I have used protected static $logAttributes = ['*']; in my model when I do an activity it logs it in my database, if I want to put it in my view page like an activity feed how do I go and do this.

**Comment by Gummibeer** [comment]
Related to displaying the activities there are some closed issues/discussions in this repo - like:
* #360 
* #186 

At the end it's not part of this package and because it's a normal eloquent model you can use whatever matches your frontend the best. So you can render a blade view(partial) or have an API endpoint and use Vue or any other SPA frontend, you can for sure also use it in a native app.

**Comment by Kushal-u1462694** [comment]
It's already working I got my activity log fully working, by using laracasts thank you for all your help.
