### ISSUE TITLE
Adding a new column for events

### ISSUE THREAD

**Issue by chistel** [spatie/laravel-activitylog#673]
Good day, am proposing a new column for storing the type of event carried out, i.e deleted, updated, created. instead of storing the event by default in the description column.

**Comment by Gummibeer** [comment]
Hey,
sorry for the delay. I welcome this change. To make it compatible with everything the column should be `nullable` and there should be a method on the `ActivityLogger` to allow an event type on custom activities.

**Comment by AbdullahFaqeir** [comment]
I’d love to work on this.

**Comment by Gummibeer** [comment]
@AbdullahFaqeir any further questions? Or is everything clear and you want to start?
Something special: like before I think that we won't create a new migration file but add it to the existing and mention it in the changelog.
So just add the column to the existing migration file.
Or should we start with a new migration for this @freekmurze ?

**Comment by AbdullahFaqeir** [comment]
I believe the is pretty clear so far, and while planning it - if anything new popped up - I’ll surely let you know. Regarding the migration, I’d suggest adding a new migration file which will only alter the current table for the updates to allow current users to roll the update easily.

**Comment by Gummibeer** [comment]
You are right, the last changes were only new indexes and changed column types. A new column should be done the right way! :+1:

**Comment by chistel** [comment]
is anyone intending to submit a PR?? or should i proceed to to submit a PR

**Comment by Gummibeer** [comment]
@AbdullahFaqeir has said that he wants to create a PR.

**Comment by chistel** [comment]
oh great

**Comment by Gummibeer** [comment]
hey @AbdullahFaqeir ,
I only want to inform you that I will release it if you finish the PR before I'm done with the new v4 #699 release (1-2 weeks is my first timing).
If you don't have time, don't want to or anything else I will do it in the new v4.

**Comment by AbdullahFaqeir** [comment]
@Gummibeer at first please allow me to apologize for taking so long to reply, I'll be working on it and will submit my PR ASAP

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.14.0
