### ISSUE TITLE
Add CausesActivity to docs

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-activitylog#68]
Hey, I did not find the `CausesActivity` trait in the docs, but I think it would be very helpful to mention it there.

**Comment by freekmurze** [comment]
It's mentioned here:  https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#customizing-the-events-being-logged

**Comment by lukasoppermann** [comment]
Yes, I saw this, but it does not mention what it does there, does it? You actually do not know why it is added here at all.

**Comment by freekmurze** [comment]
You're right, an explanation would be nice. I'd accept a PR for that 😄 
(there a little edit button on the top of every page)

**Comment by lukasoppermann** [comment]
Will do! 👍
