### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by parimahziyi** [spatie/laravel-activitylog#684]
hello
at installing step i have this error
please help me
   - don't install illuminate/support v6.8.0|don't install laravel/framework v5.8.35

**Comment by Gummibeer** [comment]
You have to pick a version with Laravel 5.8 support from packagist or upgrade your app (highly recommended) for example using https://laravelshift.com/ .

https://packagist.org/packages/spatie/laravel-activitylog#3.9.1 was the last with L5.8 support.
