### ISSUE TITLE
LogsActivity trait is undefined

### ISSUE THREAD

**Issue by Greenvold** [spatie/laravel-activitylog#685]
Hi folks,

I implemented the activity log successfully however im still getting undefined type Logsactivity when i use LogsActivity in my model.

```
namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model as BaseModel;
use Spatie\Activitylog\Traits\LogsActivity;

class Model extends BaseModel
{
    use LogsActivity;
    //
    public $incrementing = false;

    protected $guarded = [];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->{$model->getKeyName()} = (string) Str::uuid();
        });
    }
}
```

All works fine but i am wondering what might be wrong?

Thank you.

**Comment by Gummibeer** [comment]
You should set the keyType property to string and also change the subject_id column type to varchar if you want to use UUIDs. After all this package isn't tested with UUID primary keys.
It's based on the fact that non-int PKs aren't performant enough in SQL DBs.
It could be an idea for you to keep int PKs and use the UUID as secondary key.
