### ISSUE TITLE
Support 5.7

### ISSUE THREAD

**Issue by HELMAB** [spatie/laravel-activitylog#686]
When installing Laravel Activity Log, I got with the errors.

Using version ^3.11 for spatie/laravel-activitylog
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-activitylog 3.11.0 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - spatie/laravel-activitylog 3.11.1 requires illuminate/database ^6.0|^7.0 -> satisfiable by laravel/framework[7.x-dev], illuminate/database[6.x-dev, 7.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8].
    - Can only install one of: laravel/framework[7.x-dev, v5.7.28].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/database 7.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.0.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.0.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.0.2|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.0.3|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.0.4|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.1.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.10.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.11.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.12.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.13.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.13.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.14.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.15.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.15.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.16.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.17.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.17.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.18.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.2.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.3.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.4.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.5.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.5.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.5.2|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.6.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.6.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.6.2|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.7.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v6.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.0|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.1|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.2|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.3|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.4|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.5|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.6|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.7|don't install laravel/framework v5.7.28
    - don't install illuminate/database v7.0.8|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].
    - Installation request for spatie/laravel-activitylog ^3.11 -> satisfiable by spatie/laravel-activitylog[3.11.0, 3.11.1].

**Comment by vdbelt** [comment]
The latest versions only supports Laravel 6 and above. Upgrade your dependencies to keep using this package.

**Comment by Gummibeer** [comment]
v3.2.2 was the last with Laravel 5.7 support.
https://packagist.org/packages/spatie/laravel-activitylog#3.2.2
I can only second @vdbelt to upgrade your app. https://laravelshift.com/ is your friend doing so.
