### ISSUE TITLE
Warning: 1265 Data truncated for column 'causer_id'

### ISSUE THREAD

**Issue by ssuhat** [spatie/laravel-activitylog#69]
Hi, I want try use this package. After installation and run a migration I try simple logging like at example

`activity()->log('Look mum, I logged something');` But it always return me this error:

![untitled](https://cloud.githubusercontent.com/assets/10653041/18433472/ec0a3624-7911-11e6-8567-7ded540a94d3.png)

Any additional step to prevent this error?

Thanks

**Comment by sebastiandedeyne** [comment]
It looks like you're using a uuid in your application for your user model. By default, this package expects an integer. To avoid this, you'll need to publish the migration, and edit the `causer_id` column's type.

```
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
```

This line needs to be replaced: https://github.com/spatie/laravel-activitylog/blob/master/migrations/create_activity_log_table.php.stub#L19
