### ISSUE TITLE
Logged attributes ordering by key length

### ISSUE THREAD

**Issue by wrabit** [spatie/laravel-activitylog#691]
I am not sure of it's this package which is doing this, but if it is, is it possible to allow the natural order to follow through from the order they are defined in the request?

**Comment by Gummibeer** [comment]
Hey, @wrabit I'm sorry but I have no idea what you refer to?

Do you mean the order of the logged attributes in the JSON column? Right now we don't do any special sorting. We only call Laravel core methods to retrieve the attributes.

**Comment by wrabit** [comment]
Yes, the order in the JSON column, ok thanks for confirming, I'll look a bit further.

This is how it's storing:

![image](https://user-images.githubusercontent.com/5918271/76520921-20526780-6464-11ea-998e-71e080176280.png)

![image](https://user-images.githubusercontent.com/5918271/76521069-61e31280-6464-11ea-915b-0b82b5577956.png)
