### ISSUE TITLE
Running bulk changes without logging is....not great

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-activitylog#693]
As an example, if there was a bulk import process that updated 100 records, you would either need to wrap it with an disable and enable call, but then also need to wrap it in potentially a transaction to confirm that all changes went through plus handling forcing global logging back enabled on exception in case it's a job.....it's just all nasty like this:

    try {
        activity()->disableLogging();
        DB::transaction(function () {
            <STUFF HAPPENS HERE THAT MAY OR MAY NOT ERROR OUT>
        });
    } catch (Exception $ex) {
        <RETHROW THE EXCEPTION>
    } finally {
        activity()->enableLogging();
    }

I propose that to fix that, we bring that whole mess into a method on the Logger something with the use of:

    activity()->withoutLogging(function () {
        <DANGEROUS STUFF/TRANSACTIONS/ETC>
    });

This way it's far simpler to handle this kind of case, and with the performance parity from a previous PR (😉), there is no performance improvement to be had to manually disablelogging per model.

Thoughts/additional considerations before I take the time to make a PR on this?

Maybe making it chainable instead for potential other modifications like `forUser()` or `inBatch()` so instead of a single callback, it could be the addition of like a `run($callback)` sort of interface?

**Comment by Gummibeer** [comment]
Cool idea, I think if you use the `Model::withoutEvents()` method as an idea/base/reference (which seems you already did(?) everything will be fine.

Something we could think about is the naming - following `withoutEvents()`, `withoutJobs()`, `withoutNotifications()` and so on from the core I would throw in `withoutLogs()`.

The chaining: I don't see any reason to return an instance of the activitylogger - instead I would stick to the core pendants and return the result of the callback.

```php
$user = activity()->withoutLogs(function () {
  return User::create(...);
});
```

**Comment by ragingdave** [comment]
Good point yeah, don't really need to chain on something that isn't logging anything the chain would affect....I'll see what I can do in the next few days hopefully
