### ISSUE TITLE
Laravel spatie activtiy-log does not update properties column

### ISSUE THREAD

**Issue by ssnatu** [spatie/laravel-activitylog#694]
When there is a new activity logged, it should also set the properties column with new and old values as per the [documentation ](https://docs.spatie.be/laravel-activitylog/v3/advanced-usage/logging-model-events/)
But it doesn't update properties column, it's an empty array. I tried everything from the documentation, like setting property
`protected static $logAttributes = ['name', 'text'];` , 
and 
`protected static $logFillable = true;` 
 but no luck

I am using Laravel 7. Can you please help me? Thanks

**Comment by Gummibeer** [comment]
Could you add some more details? The model code, the code you use to save the model and the activity record that's saved to the database.

**Comment by ssnatu** [comment]
@Gummibeer , I can now see the properties with old and new attributes after running fresh migration. Don't know what was the issue, but it's working now. But there is an another issue now.
This is my `PostController`

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Spatie\Activitylog\Models\Activity;

class PostController extends Controller
{
    public function create()
    {
        $post = Post::create([
            'title' => 'Post 1',
            'body' => 'This is post 1'
         ]);

         $activity = Activity::all()->last();

         return $activity;
    }

    public function update()
    {
        $post = Post::find(1);

        $post->update(['title' => 'Updated post title 1']);
        $post->save();

        activity()
            ->performedOn($post)
            ->withProperties(['url' => 'testurl', 'user' => 'testUser']);

        $activity = Activity::all()->last();

        return $activity;

    }
} 
```

Here is my `Post `model
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class Post extends Model
{
    use LogsActivity;
    
     protected $table = 'posts';
     public $primaryKey = 'id';

     protected $fillable = [
        'title', 'body'
    ];

    protected static $logAttributes = ['title', 'body'];
    protected static $logOnlyDirty = true;

     public function user()
     {
         return $this->belongsTo('App\User');
     }
}
```

and code from migration file
```
public function up()
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->mediumText('body');
            $table->timestamps();
        });
    }
```

and this is my properties look after creating post for the first time

![image](https://user-images.githubusercontent.com/31346079/76550258-bf3d8a80-6489-11ea-9ea0-e7f71d0b48d1.png)


and after updating it looks like

![image](https://user-images.githubusercontent.com/31346079/76550351-e98f4800-6489-11ea-8484-d50bcf47634a.png)

 which is fine, but it does not merge this `['url' => 'testurl', 'user' => 'testUser']` into properties when using `withProperties()` (please see above update()), should it merge into properties, I am not sure. I want to have extra properties with default shown in the images. Is it possible?

**Comment by ragingdave** [comment]
@ssnatu  I think you might be not using this quite right, as `withProperties` on it's own doesn't actually log anything, and it seems like you are trying to adjust a model level activity log after it's been logged via the model events.

I think what you are looking for is the tapActivity method that you can add on the model itself.
Found here: https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/LogsActivity.php#L48

You can basically define the method tapActivity on the model, which can then alter the model event level activities being generated. This runs on every model event activity generated so perhaps this isn't what you're going for, but I believe is the only way to handle modifying the model event driven activities.

Aside from that, just from the code itself, you don't have a user_id on the posts to store a user in the first place so perhaps that's contributing as well.

**Comment by shafeeqmk046** [comment]
just try to clear the config cache
php artisan config:clear

**Comment by codeArtisanry** [comment]
Same thing is happening with me, 
I recently updated the application to php 81 & laravel 9xx

Can anyone help me out on this ?
Thanks
