### ISSUE TITLE
anahkiasen/underscore-php is abandoned

### ISSUE THREAD

**Issue by IManAsap** [spatie/laravel-activitylog#696]
Hello,
When I add the spatie/laravel-activitylog package, I get the following message. Is this normal?

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing patchwork/utf8 (v1.3.2): Loading from cache
  - Installing anahkiasen/underscore-php (2.0.0): Loading from cache
  - Installing spatie/string (2.2.2): Loading from cache
  - Installing spatie/laravel-activitylog (3.11.3): Loading from cache
patchwork/utf8 suggests installing ext-wfio (Use WFIO for UTF-8 filesystem access on Windows)
Package anahkiasen/underscore-php is abandoned, you should avoid using it. No replacement was suggested.

**Comment by Gummibeer** [comment]
#690 should solve it.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.11.4
