### ISSUE TITLE
Laravel spatie logging activity with withProperties() function, doesn't set properties properly

### ISSUE THREAD

**Issue by ssnatu** [spatie/laravel-activitylog#698]
I need to log custom properties with default logged properties, but when I update a post (a single update), it log two activities, i.e. it create two records for a single update

Properties from the first activity
`{"attributes":{"title":"Updated post title 1"},"old":{"title":"Post 1"}}`

and from the second activity
`{"user":"testUser"}`

But what I want it to log one activity for a single update and properties will look like
`{"attributes":{"title":"Updated post title 1"},"old":{"title":"Post 1"}, {"user":"testUser"}}`

@Gummibeer  How can I do this? Thanks in advance.

```
public function update()
{
        $post = Post::find(1);

        $post->update(['title' => 'Updated post title 1']);
        $post->save();

        activity()
            ->withProperties(['user' => 'testUser'])
            ->log('updated');
            ;

        $activity = Activity::all()->last();

        return $activity;

}
```

**Comment by Gummibeer** [comment]
Hey, sorry for the delay.
You should use the `tapActivity()` method on the `Post` model. This means that you will have to put code inside that will work with all activities on the model.
I've linked an issue that could make it easier - but I don't know if it will make it into v3 or if I will add them to v4.

**Comment by ssnatu** [comment]
@Gummibeer Thanks a lot for your help. It logs two activities because of using LogsActivity trait on model and activity()->log() method into controller. I set `protected static $recordEvents = [];` on model then it's worked as expected. Thanks again
