### ISSUE TITLE
new major version - v4

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-activitylog#699]
**PR:** #787 

https://github.com/spatie/laravel-activitylog/issues?q=is%3Aissue+is%3Aopen+label%3A%22revisit+for+next+major+version%22

**Comment by gpressutto5** [comment]
@Gummibeer That else do we need for the next major release? Is 4.0.0-rc.2 stable?

**Comment by Gummibeer** [comment]
@gpressutto5 everything in #787 without a checked box is missing for a final release.
The RCs should be stable in meaning that they shouldn't contain a bug. But as it's a new major version all following RCs can contain breaking changes. So if you really want to use them you should pin the version.

**Comment by Gummibeer** [comment]
I will close this issue even if v4 isn't released yet. But the task itself is done and I want to check which tasks are really open. Please keep an eye on #787
