### ISSUE TITLE
Logging missing on pivot models

### ISSUE THREAD

**Issue by Hesesses** [spatie/laravel-activitylog#703]
Hello and thank you for creating this package, its been great help for us.

We have been running the activity log for few months and now noticed that we dont have any logging for pivot data.

For example we have:
```
class LocationRelation extends Model
{
    use LogsActivity;
    protected static $logAttributes = ['*'];
}
```
We use `->attach() ->detach() ->sync()` to add/remove/sync the data.

Are we doing something wrong or do we need to manually log these changes?

**Comment by Gummibeer** [comment]
Hey,

this was already requested several times. The key point is that your pivot model needs a PK and the pivot model has to set `$incrementing = true`.
As suggested in one of these issues: it would be a good idea to add it to the docs.
I would be happy to review a PR that adds it and merge it in.
Would you be available to work on one?

* https://github.com/spatie/laravel-activitylog/issues/598
* https://github.com/spatie/laravel-activitylog/issues/487
* https://github.com/spatie/laravel-activitylog/issues/395
* https://github.com/spatie/laravel-activitylog/issues/390

**Comment by izshreyansh** [comment]
Hello this might be useful if anyone is still looking for an answer.

> Laravel Relationship Events is a package by Viacheslav Ostrovskiy that adds extra model relationship events. This package comes with the following traits that are used to register listeners on a model’s boot() method
[Relationship Events](https://laravel-news.com/relationship-events)

**Comment by Gummibeer** [comment]
For all getting here: that's the open task in question.

> As suggested in one of these issues: it would be a good idea to add it to the docs.
> I would be happy to review a PR that adds it and merge it in.
> - https://github.com/spatie/laravel-activitylog/issues/703#issuecomment-602535620

**Comment by VictorDauchy** [comment]
Hi,

I needed to track the relation `Role<->Permissions` on the Spatie Permission package (https://github.com/spatie/laravel-permission).

So following the different threads I came up with this `boot()` method being set in the `Role` model and using the package: https://github.com/chelout/laravel-relationship-events.

```
    public static function boot() {
        parent::boot();
        static::belongsToManySyncing(function (string $relation, Role $role) {
            /* Only track sync of permissions */
            if ($relation === 'permissions') {
                /* Mimic the logic used on `updating` event */
                $role->oldAttributes = static::logChanges((new static)->setRawAttributes($role->getOriginal()));
            }
        });
        static::belongsToManySynced(function (string $relation, Role $role) {
            /* Only track sync of permissions */
            if ($relation === 'permissions') {
                /* Trigger 'updated' event to trigger existing diff logic */
                $attrs = $role->attributeValuesToBeLogged('updated');
                if ($role->isLogEmpty($attrs) && !$role->shouldSubmitEmptyLogs()) {
                    return;
                }
                /* Clean the relation: Extract names from permissions */
                $attrs = collect($attrs)
                    ->map(fn(array $element) => collect($element)
                        ->map(fn($attribute) => ($attribute instanceof Collection) ? $attribute->pluck('name') : $attribute))
                    ->toArray();
                /* Save the diff */
                app(ActivityLogger::class)
                    ->useLog($role->getLogNameToUse())
                    ->performedOn($role)
                    ->withProperties($attrs)
                    ->log($role->getDescriptionForEvent("updated:sync.{$relation}"));
            }
        });
    }
```

This will generate an activity log with the followings changes when syncing permissions `A` and `B` to role `someRole` which had no permissions:
```
[
    "attributes" =>  [
        'name' =>'someRole',
        'guard_name' => 'admin',
        'permissions' => ['A', 'B']
    ],
    "old" => [
        'name' =>'someRole',
        'guard_name' => 'admin',
        'permissions' => []
    ]
]
```
Good luck.

**Comment by cerw** [comment]
So I need to use the 3rd party package to support detaching? I am correct?

**Comment by duisekov** [comment]
> Hi,
> 
> I needed to track the relation `Role<->Permissions` on the Spatie Permission package (https://github.com/spatie/laravel-permission).
> 
> So following the different threads I came up with this `boot()` method being set in the `Role` model and using the package: https://github.com/chelout/laravel-relationship-events.
> 
> ```
>     public static function boot() {
>         parent::boot();
>         static::belongsToManySyncing(function (string $relation, Role $role) {
>             /* Only track sync of permissions */
>             if ($relation === 'permissions') {
>                 /* Mimic the logic used on `updating` event */
>                 $role->oldAttributes = static::logChanges((new static)->setRawAttributes($role->getOriginal()));
>             }
>         });
>         static::belongsToManySynced(function (string $relation, Role $role) {
>             /* Only track sync of permissions */
>             if ($relation === 'permissions') {
>                 /* Trigger 'updated' event to trigger existing diff logic */
>                 $attrs = $role->attributeValuesToBeLogged('updated');
>                 if ($role->isLogEmpty($attrs) && !$role->shouldSubmitEmptyLogs()) {
>                     return;
>                 }
>                 /* Clean the relation: Extract names from permissions */
>                 $attrs = collect($attrs)
>                     ->map(fn(array $element) => collect($element)
>                         ->map(fn($attribute) => ($attribute instanceof Collection) ? $attribute->pluck('name') : $attribute))
>                     ->toArray();
>                 /* Save the diff */
>                 app(ActivityLogger::class)
>                     ->useLog($role->getLogNameToUse())
>                     ->performedOn($role)
>                     ->withProperties($attrs)
>                     ->log($role->getDescriptionForEvent("updated:sync.{$relation}"));
>             }
>         });
>     }
> ```
> 
> This will generate an activity log with the followings changes when syncing permissions `A` and `B` to role `someRole` which had no permissions:
> 
> ```
> [
>     "attributes" =>  [
>         'name' =>'someRole',
>         'guard_name' => 'admin',
>         'permissions' => ['A', 'B']
>     ],
>     "old" => [
>         'name' =>'someRole',
>         'guard_name' => 'admin',
>         'permissions' => []
>     ]
> ]
> ```
> 
> Good luck.

works well, but two logs are created, first from library itself, second buy your function, how to fix this? 
i have idea of using ```protected static $recordEvents = ['created', 'deleted'];``

**Comment by duisekov** [comment]
@vdauchy 

works well, but two logs are created, first from library itself, second buy your function, how to fix this?
i have idea of using ```protected static $recordEvents = ['created', 'deleted'];``

or there is another option to solve pivot model logging in 2021?

**Comment by cerw** [comment]
@Gummibeer Hello there, I have tried this several times with Primary ID and own Pivot class and its not logging anything? 

What is the right solutions 2 years later? 

ta

**Comment by gijsbeijer** [comment]
> 

Also not seeing the pivot table record creation in logs.

I have a pivot table (also assigned it to the relation with ->using([model]::class), it has an id, it has been set to $incrementing = true.

Anybody else?

**Comment by codinglife456** [comment]
Same situation for me,

users table
user_role pivot table
roles table

when the role of a user is modified via the user's CRUD page, all changes are tracked except for the role due to it being a many to many relationship

**Comment by anvarulugov** [comment]
> @vdauchy
> 
> works well, but two logs are created, first from library itself, second buy your function, how to fix this? i have idea of using `protected` static $recordEvents = ['created', 'deleted'];`
> 
> or there is another option to solve pivot model logging in 2021?

I faced the same issue, I tried many different ways, but stopped on this option:

```
/* Save the diff */
$activity = Activity::where('subject_id', $transfer->id)
    ->where('subject_type', Transfer::class)
    ->where('causer_id', auth()->id())
    ->where('description', 'updated')
    ->where('created_at', '>', now()->subSeconds(1))
    ->latest()
    ->first();
if ($activity) {
    $properties = $activity->properties->toArray();
    $properties['old']['products'] = $attrs['old']['products'];
    $properties['attributes']['products'] = $attrs['attributes']['products'];
    $activity->properties = $properties;
    $activity->save();
} else {
    app(ActivityLogger::class)
        ->useLog($transfer->getLogNameToUse())
        ->performedOn($transfer)
        ->withProperties($attrs)
        ->log($transfer->getDescriptionForEvent("updated"));
}
```
