### ISSUE TITLE
Migration Stub Problem

### ISSUE THREAD

**Issue by rakishii13** [spatie/laravel-activitylog#705]
As I was trying to update to the latest version of 3.14.0, I noticed the change of adding a new column called event. This raised a few issues for my code. 
1. It broke the ability of activity log doing its thing because event is required column and if attention is not paid to having a new column on the table, people will just upgrade the package and continue on with their work, since it is a minor version upgrade.
2. The migration stub. The down() function on it seems to remove the entire activity log table and not just the event column, so that would break/delete all activity log for all users who would revert their migrations.  https://github.com/spatie/laravel-activitylog/blob/master/migrations/add_event_column_to_activity_log_table.php.stub#L24

**Comment by Gummibeer** [comment]
Hey,

I'm sorry for the broken release. There is a fix release https://github.com/spatie/laravel-activitylog/releases/tag/3.14.1 that reverts it and a release candidate for the new v4 major version https://github.com/spatie/laravel-activitylog/releases/tag/4.0.0-rc.1 if you want to use the new feature already.
The feature itself is stable and working, but for sure it's breaking - my bad!

**Comment by rakishii13** [comment]
Okay, I will update and test and keep you posted!
