### ISSUE TITLE
Log a user password change

### ISSUE THREAD

**Issue by TheFrankman** [spatie/laravel-activitylog#708]
Hello There,

I haven't been able to find a related issue for this so forgive me if this has already been asked. I'd like to log that a users password has been changed BUT without the hash ending up in the activity log. What would be the best way to go about this ? 

I can see that I can use `tapActivity` then mutate the value of `properties->attributes->password && properties->old->password` but is there a better way ?

**Comment by Gummibeer** [comment]
Because in most apps the `password` change is a dedicated form action or even in general profile forms you can use custom activities.
https://docs.spatie.be/laravel-activitylog/v3/basic-usage/logging-activity/

**Comment by vaibhavpandeyvpz** [comment]
@TheFrankman You can use the `tapActivity` method like below:

**Comment by TheFrankman** [comment]
@vaibhavpandeyvpz - Perfect, that's literally what i was just writing haha.

**Comment by Gummibeer** [comment]
You can use `Arr::has()` with `dot.notation` to combine the two `if`s.

```php
if (Arr::has($properties, 'attributes.password')) {
    $attributes = $properties->get('attributes');
    $attributes['password'] = '<secret>';
    $properties->put('attributes', $attributes);
}
```

These three lines can't be reduced because of the overloading and magic - otherwise you will get
> PHP Notice:  Indirect modification of overloaded element of Illuminate/Support/Collection has no effect

**Comment by daraghoshea** [comment]
In case anyone stumbles upon this, the solution I went with was to setup a separate observer on the password changing.

I let the trait handle logging of the `name` and `email`.

```php
use LogsActivity;

protected static $logAttributes = [
        'name', 'email',
    ];
```

A separate check on when the `User` is updated checks to see if the `password` was changed and logs the password was changed.

```php
public static function booted()
    {
        static::updated(function(User $user) {
            if($user->wasChanged('password')) {
                activity()
                    ->causedBy(auth()->user())
                    ->on($user)
                    ->log('password changed');
            }
        });
    }
```

**Comment by sorwaar** [comment]
> @TheFrankman You can use the `tapActivity` method like below:
> 
> ```
> public function tapActivity(Activity $activity, string $event)
> {
>     /** @var Collection $properties */
>     if ($properties = $activity->properties) {
>         if ($properties->has('attributes')) {
>             $attributes = $properties->get('attributes');
>             if (isset($attributes['password'])) {
>                 $attributes['password'] = '<secret>';
>             }
>             $properties->put('attributes', $attributes);
>         }
>         if ($properties->has('old')) {
>             $old = $properties->get('old');
>             if (isset($old['password'])) {
>                 $old['password'] = '<secret>';
>             }
>             $properties->put('old', $old);
>         }
>         $activity->properties = $properties;
>     }
> }
> ```

It works fine . Thanks
