### ISSUE TITLE
Adding a custom Type field to records

### ISSUE THREAD

**Issue by jschutt** [spatie/laravel-activitylog#71]
Good morning - I'm attempting to add a `type` field to the `activity_log` table and would like to pass a value to it like this:

`activity()
    ->ofType('item.added')
    ->log('Item added!');`

I've set up my own custom model which extends `\Spatie\Activitylog\Models\Activity` and specified it be used in the config.

However, the `activity()` helper automatically loads up the `ActivityLogger` model, instead of mine, which means that I can't implement the `ofType()` method... unless I'm misunderstanding how to implement this.

Thanks for your thoughts and work on this package!

**Comment by freekmurze** [comment]
`activity()` returns the default `Spatie\Activitylog\ActivityLogger`. If you want to customise that, create your own `ActivityLogger` class extending from the default one. Add your `ofType` function to that class. 

Also make your own `activity` function that returns your custom instance of the activityLogger.

I know this is a hassle, and I'm considering adding the `Macroable` trait to our `ActivityLogger`.

**Comment by freekmurze** [comment]
💥  The `Macroable` trait as been added to `Activitylogger` in version 1.9.0. 💥

**Comment by jschutt** [comment]
Thank you!

With this enabled where would I need to set up my custom macro?

**Comment by freekmurze** [comment]
Easiest place would be in the `AppServiceProvider`, or you make create your own custom service provider for this.

**Comment by chelout** [comment]
@jschutt did you managed to add macro? I'm also trying to add new field to table, but can't set the value. If it possible to provide some code example that would be great! Thanks!

**Comment by jschutt** [comment]
@chelout - I ended up forking this package and adding the functionality I desired 👍

**Comment by chelout** [comment]
@jschutt may i have a look?
