### ISSUE TITLE
Provide support for logging snake_cased relationship attributes.

### ISSUE THREAD

**Issue by nico-sorice** [spatie/laravel-activitylog#712]
Hi, this issue is related to [#499 ](https://github.com/spatie/laravel-activitylog/issues/499), i see that if you pass a snake_case relationship name to $logAttributes, it will look for a camelCased relationship method.

As @blindsz stated it is a convention to name your relationships with camelCase names, and your model fields with snake_case. But it is only a convention/suggestion and you are not forced to actually use it like that.

I personally name my relationships with snake_case names, and i don't believe the current behavior is actually the expected one, it is my understanding that it works like this:

if given a relationship name with dot notation in logAttributes containing an underscore (_), it will only search for the camelCase version of that name, even if the relationship_name(), "just as provided" method exists.

How I'm proposing it to work:

if given a relationship name with dot notation in logAttributes, no matter its pattern, it will first search for an exact match method, if it cant be found, it then applies the current behavior.

What are your thoughts on this matter? Is using snake_case relationships supported any other way that I'm not seeing? 

I'm willing to provide a PR if this is something we can merge. I don't think it will be considered a breaking change, since it would only affect people that both have a relationship_name method and a relationshipName method at the same time in their model, and seems highly unlikely.

Thanks!

Edit: typo

**Comment by Gummibeer** [comment]
Hey,

thanks for reporting. At first, I also use `snake_case` so you aren't alone. But I don't use relationship logging.^^

I agree with your recommendation but would like to add that I would like to use Laravel core logic - if possible. Something like `getRelationship()` that handles all the formatting the same like it's done if you call `$model->my_relation`.

If you create a PR I will be happy to review and merge. Because it shouldn't break any existing code I will also release it before v4.

**Comment by blindsz** [comment]
> But it is only a convention/suggestion and yo

I agree with your proposal. This way we can add support to both convention. I might also create a PR if I can have time.

**Comment by Gummibeer** [comment]
Cool, please write here if you start and/or if you won't finish it to prevent duplicated work or endless waiting.
Like said I would favor a solution that utilises Laravel core functionality to prevent us from handling all possible string transformations.

**Comment by AbdullahFaqeir** [comment]
Hello,

I’d love to do it ✌🏻

**Comment by Gummibeer** [comment]
@AbdullahFaqeir since now no one has send a PR or commented that he does it now.
Until someone says that he really starts now - I won't lock this topic. So I would be happy with every PR by everyone.

**Comment by yaim** [comment]
Disclaimer, I'm a PSR-1 fan! :sweat_smile:

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/3.16.0
