### ISSUE TITLE
How to group user activities by created date 

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-activitylog#717]
I'm using UUID data type as primary key
So want o display activity log to every user group by created date 
 here is what i have tried on controller
```
    public function index()
    {
        $logs = Activity::with('user')
                            ->where('causer_id',$this->userLoggedID())
                            ->orderBy('created_at','desc')
                            ->groupBy('created_at')
                            ->paginate(15);
            
        dd($logs);
        return view('users.settings.logs.index',compact('logs'));
    }
```

I'm getting this error  
```
ErrorException
array_key_exists(): The first argument should be either a string or an integer 
```
But if i remove the groupby function working perfect but will display every activity with its date while i want to group on date activities

and my view file is
```
<ul class="list-group list-group-flush">
                @foreach($logs as $log)
                    @switch($log->description)
                        @case('created')
                        <li class="list-group-item p-2"><a href="{{route('profile')}}">{{strtolower(auth()->user()->full_name)}}</a> {{$log->description.' new '.$log->log_name}}
                            <div class="float-right">
                            </div>
                        </li>
                        @break

                        @case('updated')
                        <li class="list-group-item p-2"><a href="{{route('profile')}}">{{strtolower(auth()->user()->full_name)}}</a> {{$log->description.' '.$log->log_name}}  </li>
                        @break

                        @case('deleted')
                        <li class="list-group-item p-2"><a href="{{route('profile')}}">{{strtolower(auth()->user()->full_name)}}</a> {{$log->description.' '.$log->log_name}}  </li>
                        @break
                        @default
                        <li class="list-group-item p-2"><a href="{{route('profile')}}">{{strtolower(auth()->user()->full_name)}}</a> {{$log->description.' '.$log->log_name}}  </li>
                    @endswitch
                @endforeach
            </ul>
            <div class="float-right mt-3"> {{ $logs->links() }}</div>
```

i need help. Thank you

**Comment by Gummibeer** [comment]
Hey at first this package provides a trait to get all activities by user as relationship.
```php
$user->activities();
```
And could you provide the whole stacktrace? This exception message isn't this helpful without knowing where it's thrown and how it got there.
A flare shared exception would be even better. 😉
https://flareapp.io/

**Comment by antweny** [comment]
i tried to use the trait on Current Logged user but throw error
```
BadMethodCallException
Call to undefined method App\User::activities()
```
also the first error i'm getting on the controller only when i use groupBy

**Comment by Gummibeer** [comment]
I'm sorry, it's `actions()` but for sure you have to use the trait in your user model.
https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/CausesActivity.php

But a full stacktrace would still be helpful.

**Comment by antweny** [comment]
Also the actions() not working exception [LINK](https://flareapp.io/errors/73288-call-to-undefined-method-appuseractions/latest#F52)

And about the first error this is the exception [LINK](https://flareapp.io/errors/73652-array-key-exists-the-first-argument-should-be-either-a-string-or-an-integer/latest#F54)

**Comment by Gummibeer** [comment]
For your first exception: your method calls are in the wrong order.
`groupBy()->paginate()` and not the other way. The order is important if it's called on the query builder or the collection.

The `actions()` exception: does your user model use the referenced trait?

**Comment by antweny** [comment]
sorry groupBy() before paginate() didn't work but this one works perfect which also include the CauseActivity Trait
```
 $logs = $this->userLogged()->actions()
                   ->orderBy('created_at','asc')
                   ->paginate(15)
                   ->groupBy(function ($val) {
                        return $val->created_at->format('d-M-y');
                });
```
Thank you for your support.
