### ISSUE TITLE
Call to undefined function App\Http\Controllers\Admin\activity()

### ISSUE THREAD

**Issue by joshilomas** [spatie/laravel-activitylog#718]
Hello,
I have followed the steps in 
> https://docs.spatie.be/laravel-activitylog/v3/installation-and-setup/ 

and everything working fine on local host...and now i pushed the code to live server and just run 
```bash
php artisan migrate
```
and it creates the table and everything looks fine in command line.

But while i run the site it shows the error.

> Call to undefined function App\Http\Controllers\Admin\activity()

**Comment by Gummibeer** [comment]
Hey,

just to be sure: have you run `composer update/install` and `composer dump-autoload` on your production server?
The function is part of the package and the file is loaded via composer autoloading.
So as long as the package is installed via composer everything should be fine.
Nearly all times this comes down to a failed composer step during deployment.

**Comment by joshilomas** [comment]
@Gummibeer Thank you. 

> Hey,
> 
> just to be sure: have you run composer update/install and composer dump-autoload on your production server?
> The function is part of the package and the file is loaded via composer autoloading.
> So as long as the package is installed via composer everything should be fine.
> Nearly all times this comes down to a failed composer step during deployment

**Comment by sayeedazmal** [comment]
anyone can help me in this error??
Call to undefined function App\Http\Controllers\Admin\unique()

**Comment by Gummibeer** [comment]
> Hey,
> 
> just to be sure: have you run `composer update/install` and `composer dump-autoload` on your production server?
> The function is part of the package and the file is loaded via composer autoloading.
> So as long as the package is installed via composer everything should be fine.
> Nearly all times this comes down to a failed composer step during deployment.

https://github.com/spatie/laravel-activitylog/issues/718#issuecomment-618237178

**Comment by davyalex** [comment]
![alerte-info-connexion-divine1](https://github.com/spatie/laravel-activitylog/assets/87180241/eb02c4c4-3331-466b-96f0-6d6d480fae56)
