### ISSUE TITLE
log() method returning $this

### ISSUE THREAD

**Issue by jschutt** [spatie/laravel-activitylog#72]
I'm curious why the `log()` method returns `$this` instead of the newly created `Activity` item?

Thanks for helping me understand!

**Comment by freekmurze** [comment]
You're right, it's better if this function would return the activity. I'll change this.

It's a breaking change, but I'll still tag it as a minor release because probably nobody uses `activity()->log()->log()`. With a little bit of goodwill this change can be seen as a bugfix.

**Comment by jschutt** [comment]
Perfect! That's going to be very helpful in my situation! Thank you

**Comment by freekmurze** [comment]
Done in v1.9.1
