### ISSUE TITLE
Including hasMany relationship changes in activity log

### ISSUE THREAD

**Issue by dirkam** [spatie/laravel-activitylog#723]
I have a Model (ModelA) with a relationship with another Model (ModelB).

ModelA:
```
    public function modelbfields()
    {
        return $this->hasMany('App\ModelB');
    }
```

ModelB:
```
    public function modela()
    {
        return $this->belongsTo('App\ModelA');
    }
```

When ModelA is edited via a form there is a form field to edit related ModelB values.

Is it possible to have the changes in the associated ModelB values logged when ModelA is edited?
Don't want to have separate logs for ModelB changes, it should only be included when ModelA is added/edited/deleted.

Thanks!

**Comment by Gummibeer** [comment]
Hey,

there's no way to combine these two logs. Your only option would be a custom activity log.
There is an open issue that could help but wouldn't solve this #560

**Comment by sayedahmadnawid** [comment]
Though it is so late, but I think you can log the way around. I mean log ModelB where you can log ModelA's attributes. For example: 
```
->logOnly([
 'modelBattribute1',
 'modelBattribute2',
 'modelA.attribute1',
'modelA.attribute2',
 ])
```
