### ISSUE TITLE
Double Slash on String

### ISSUE THREAD

**Issue by blindsz** [spatie/laravel-activitylog#725]
Hi. do you have any idea why this is having a double slash? I have a polymorphic table and wanted to log also the model type. but instead i got this result. As you can see there is a double slash now on the type instead of one. Anyone know why this is happening? Thanks!

```
"addresser_id":20,
"addresser_type":"App\\Models\\Creditor"
```

**Comment by Gummibeer** [comment]
Hey,
I assume that what you have posted is the JSON reprasantation of theattributes?
If so JSON has reserved characters that have to be escaped. The moment any library parses the JSON to an array/object in the corresponding language these characters are unescaped and will be the same what they were before.

> The following characters are reserved in JSON and must be properly escaped to be used in strings:
> * Backspace is replaced with `\b`
> * Form feed is replaced with `\f`
> * Newline is replaced with `\n`
> * Carriage return is replaced with `\r`
> * Tab is replaced with `\t`
> * Double quote is replaced with `\"`
> * Backslash is replaced with `\\`

**Comment by blindsz** [comment]
> Hey,
> I assume that what you have posted is the JSON reprasantation of theattributes?
> If so JSON has reserved characters that have to be escaped. The moment any library parses the JSON to an array/object in the corresponding language these characters are unescaped and will be the same what they were before.
> 
> > The following characters are reserved in JSON and must be properly escaped to be used in strings:
> > 
> > * Backspace is replaced with `\b`
> > * Form feed is replaced with `\f`
> > * Newline is replaced with `\n`
> > * Carriage return is replaced with `\r`
> > * Tab is replaced with `\t`
> > * Double quote is replaced with `\"`
> > * Backslash is replaced with `\\`

Thank You!
