### ISSUE TITLE
How activitylog get old changed values? Where it stores them?

### ISSUE THREAD

**Issue by Losmi076** [spatie/laravel-activitylog#726]
All day I'm trying to figure out how activitylog stores model change data, I'm actually trying to figure out where it stores this data?
I don't see any traces of field changes in the database, I only see information that the model has changed in the aćtivitj_log table.

For example, I have a message model that contains only one field "content";
I add new message to database with content "first", and than change this message content value to "second".
I can see in activity_log table of database that activitylog add row with data that App\Message is created, and App\Message with subject_id 1 is updated, but I cant see any old and new values!

Now if I call `Activity::all()->last()` from code I will get all data:
...`{"old":{"id":1,"content":"First","created_at":"2020-05-06T21:40:55.000000Z","updated_at":"2020-05-06T21:40:55.000000Z"},"attributes":{"id":1,"content":"Second","created_at":"2020-05-06T21:40:55.000000Z","updated_at":"2020-05-06T21:41:22.000000Z"}}`...

How is this possible?
Where is this change data stored?
In some log file on disk or in database?

Please help me understand how this works :) 
Thanks in advance!

**Comment by Gummibeer** [comment]
Hey, the `Activity` model has `properties` attribute/column which is a simple JSON and we have two reserved keywords `attributes` and `old` where the new and old attribute values are stored.

https://github.com/spatie/laravel-activitylog/blob/e895bde2a3bc9a9936bfc5119b30a7154af6f9b9/migrations/create_activity_log_table.php.stub#L22
https://github.com/spatie/laravel-activitylog/blob/e895bde2a3bc9a9936bfc5119b30a7154af6f9b9/src/Models/Activity.php#L17
https://github.com/spatie/laravel-activitylog/blob/e895bde2a3bc9a9936bfc5119b30a7154af6f9b9/src/Models/Activity.php#L52-L64
https://github.com/spatie/laravel-activitylog/blob/e895bde2a3bc9a9936bfc5119b30a7154af6f9b9/src/Traits/LogsActivity.php#L36

**Comment by Losmi076** [comment]
Thank you so much friend! :)
At this example I experienced a very strange behavior of the Navicat 11, database manipulation software, which simply ignored to display json field 'properties', and therefore I could not see where this data is stored! 
I apologize for wasting your time and not being more careful to notice json property field in migration file.
Thank again!
