### ISSUE TITLE
IN installation-and-setup

### ISSUE THREAD

**Issue by abdosaeedelhassan** [spatie/laravel-activitylog#739]
in your documention at https://docs.spatie.be/laravel-activitylog/v3/installation-and-setup/#

you are added migration step before publishing config file step, because migration depend on config fi e this make migration error.

SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name

**Comment by jamieshiers** [comment]
@abdosaeedelhassan could you provide some more details on how you're getting this error. Please make sure that you've published the migration by running: 

`php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
`

**Comment by abdosaeedelhassan** [comment]
it worked for me, but i mean that the error in documentation in ordering steps:
**firstly**: publishing config file
**second**: doing migration
in the documentaion described in revese, please look at  https://docs.spatie.be/laravel-activitylog/v3/installation-and-setup/#

**Comment by jamieshiers** [comment]
@abdosaeedelhassan I've reviewed the documentation. The order that is presented on the documentation is correct. The migrations will run successfully without publishing the config file. I've verified this on a new install this morning.

**Comment by JanickOtten** [comment]
@abdosaeedelhassan try to run `php artisan config:clear` or `php artisan config:cache` before migrating
