### ISSUE TITLE
Not An issue only question

### ISSUE THREAD

**Issue by lapswr** [spatie/laravel-activitylog#75]
Hi,

This package is working only with php7?
have anyone tried php5?

**Comment by franciscocorrales** [comment]
See these issues:
https://github.com/spatie/laravel-activitylog/issues/31
https://github.com/spatie/laravel-activitylog/issues/60

**Comment by lapswr** [comment]
thanks i forgot to see at closed issues

**Comment by lapswr** [comment]
thanks i forgot to look at closed issues
