### ISSUE TITLE
Retrieve Activity Logs on a Model with LogActivity Trait

### ISSUE THREAD

**Issue by FallenKnight85** [spatie/laravel-activitylog#750]
Hi, been trying to find in your docs on how do I retrieve the logs on a Specific Model? (it's always "get last activity" on examples but I'm looking for enumerating logs that have been performed on that specific model)

I'm not getting results from

return $model->activity;

Do I need to define the relationship of the Model with the Activity Model?

My aim is to get logs of the model and show the causer and changes made by the causer.

**Comment by danord24** [comment]
Hi, you can do: `Activity::where('subject_type', YourModel::class)->with('causer')->get();`

Hope that helps.
