### ISSUE TITLE
Log activity not working with soft delete

### ISSUE THREAD

**Issue by fayroz** [spatie/laravel-activitylog#751]
**Describe the bug**
Log activity not working with soft delete
**To Reproduce**
Things needed to reproduce the error.
eg: Configuration, Migration, Model, Controller/Command

**Expected behavior**

**Screenshots**

**Versions (please complete the following information)**
- PHP: 
- Database: 
- Laravel: 
- Package: 

**Additional context**

**Exception**
The thrown exception message.

**Stack Trace**
The full stack trace of the thrown exception.

**Comment by Gummibeer** [comment]
Please fill all parts needed for a bug report. Otherwise we can't handle it and it will get closed in near future.
