### ISSUE TITLE
Disabling through environmental variable doesnt disable package

### ISSUE THREAD

**Issue by NEGits** [spatie/laravel-activitylog#807]
**Describe the bug**
I'm trying this package in our application to see if it will add any value for us. We have an extensive test suite, with lots of functional tests that hit the database. After installing this package the total runtime for the whole suite increased by approx. 30%. We use https://github.com/liuggio/fastest to speed up our tests, installing this package increases runtime on 8 cores from a little under 2 minutes to a little over 3 minutes on my computer. If using just PHPUnit the time increases from about 13 to about 17 minutes. (Hence the need for fastest)

As we're not really interested in the activity log for our test suite we tried to disable it by setting the `ACTIVITY_LOGGER_ENABLED` variable to false in testing. ~~I can see that this disabled logging, but it did nothing to the total runtime of our testsuite, the package still does its thing, it's only the actual insert into the database that seems to be disabled.~~ (edit: this was mistaken, because of the parallel execution of fastest which uses a number of databases combined with running tests in transactions I missed that setting `ACTIVITY_LOGGER_ENABLED` to false actually did nothing at all)

If I disable the package by adding the line `activity()->disableLogging();` to a ServiceProvider the test runtime is back to normal.

I expected the environmental variable to do the same thing. I'm not quite sure if this is a bug report or a feature request, but I would like to avoid an environment check in a service provider to enable/disable this package if possible. 

Oh and while I expected this package to slow us down a bit I was surprised by the 30% runtime increase, but I'm not sure if anything can be done about that..  

**To Reproduce**
Run a testsuite with `ACTIVITY_LOGGER_ENABLED` false, then run it again with `activity()->disableLogging();`, observe difference in runtime

**Expected behavior**
Setting `ACTIVITY_LOGGER_ENABLED` to false should disable the package. 

**Versions**
- PHP: 7.4.11
- Database: MySQL 5.7
- Laravel: 8.x
- PHPUnit 9.4.2
- Package: 3.16

**Comment by Gummibeer** [comment]
Hey,
the problem shouldn't be the way the `ACTIVITY_LOGGER_ENABLED` env is implemented but that you define the env-var in the wrong place so it doesn't take effect at all.
The env is used in the config - which results in a value "copy" during app bootstrapping. If the ENV is changed after the bootstrap it doesn't take effect in any way. That's nothing special about this package but how ENVs are used in Laravel and how/when the config is built.

That's the class that is used all over the package to check if it should log or not.
https://github.com/spatie/laravel-activitylog/blob/master/src/ActivityLogStatus.php

As you can see the config var is used in the construct and defines the same property as the method calls `disable()`. So as long as you don't define this ENV var before the app bootstrap you will have to use the `disable()` & `enable()` methods.

**Comment by NEGits** [comment]
I think I know what the problem is. It's in this line: 

https://github.com/spatie/laravel-activitylog/blob/ade270f291f4cb5883b3653919304a0b4e1cc284/src/ActivityLogStatus.php#L28

If the framework is running from PHPUnit, and the environmental variable is set to `false` in `phpunit.xml`, it is parsed as an empty string, not as a boolean `false`. So this method returns `false` where it should return `true` because of the strict comparison

**Comment by Gummibeer** [comment]
Which isn't a problem with this package but phpunit.
https://github.com/sebastianbergmann/phpunit/issues/2331

**Comment by NEGits** [comment]
While that might be true, I think this is the only package we are using or have used in the past that doesn't handle this case.

Are you willing to change that comparison to a weak one, accomodating this PHPUnit problem, or should I use some kind of workaround?

**Comment by Gummibeer** [comment]
This would only "fix" the issue until we drop everything below PHP 7.4 as the property will be typed to `boolean` afterward.
As this package provides everything you need to disable logging and we try to be as strict as possible in most cases the condition will keep its strict comparison. Otherwise we will have to start to test with PHP type-juggling and that's, primary in boolean casting, not cool.
You could "fix" your environment issue in the config file by adding a `boolval()` function call - this should solve your issue.

**Comment by NEGits** [comment]
I'm not quite sure I agree with you on being as strict as possible, but I see where you're coming from, so fair enough. 

After some digging I found another fix: using a `.env.testing` file, which works fine. Thanks for your time and for the package!
