### ISSUE TITLE
Could not log model events for Models without id field

### ISSUE THREAD

**Issue by sishirrijal** [spatie/laravel-activitylog#809]
I am facing a serious issue after including and implementing this package and I am not sure how is this happening.

Environment
---
PHP Version: 7.2.19
Laravel Version: 5.8.29
Package Version: 3.9.1

Scenario
---
I have **table_first** with its model TableFirst with some attributes say: ['id', 't1_first_col', 't1_second_col'].

I have implemented model event logging mechanism in following way.

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class TableFirst extends Model
{
    use LogsActivity;

    protected $table = 'table_first';
    protected static $logFillable = true;
    protected static $logOnlyDirty = true;
    protected static $logName = 'table_first_log';
    protected $fillable = ['t1_first_col', 't1_second_col'];
}
```

I also have **table_second** with a model TableSecond with some attributes: ['table_first_id', 't2_first_col', 't2_second_col']

Model for this table_second is set same as that of first with its corresponding attributes.

i.e.
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class TableSecond extends Model
{
    use LogsActivity;

    protected $table = 'table_second';
    protected static $logFillable = true;
    protected static $logOnlyDirty = true;
    protected static $logName = 'table_first_log';
    protected $fillable = ['table_first_id', 't2_first_col', 't2_second_col'];
}
```

This second table is created for storing some data that might be supplementary for first one so I haven't put an id field in this table.

Expected Behaviour
---
When I try to insert data to `TableFirst` & `TableSecond` using model from my respective controllers it should work fine and should create a log instance in database.

Actual Behaviour
---
It inserts the data into `table_first` table i.e. `TableFirst` model instance is created and also logs the fillable attributes of same.
However, for `TableSecond` neither it creates the instance nor logs the fillable attributes, rather, it throws following sort of error.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `table_second` where `id` = 0 limit 1)
```

I am damn sure that, It is not working on the models without id attributes as this is happening in every tables with same scenario on my project

Kindly help me figure this issue.

> Excuse me for not mentioning actual table names and model names from my project.

> Excuse me for typo errors and other silly mistakes as well.

Thanks in advance.

**Comment by Gummibeer** [comment]
Hey,

the requirement isn't an `id` column but a primary key - which is, by the way, a requirement by Laravel Eloquent Models in general.
You can change the primary key and it also doesn't have to be an auto-increment column.
```php
protected $primaryKey = 'table_first_id';
protected $keyType = 'int';
public $incrementing = false;
```

In general I can only recommend to have a dedicated PK (in best case AI) because it makes a lot of things a lot easier.
Try to configure your second model properly and everything should work.
