### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by rjcrystal** [spatie/laravel-activitylog#81]
we've got lot of activities to log, so instead of using mysql can i use mongo db for logging activities ? 
and how can i do it?.
thanks

**Comment by freekmurze** [comment]
This package only supports the database supported by Laravel itself. Currently these four db's are supported:

- MySQL
- Postgres
- SQLite
- SQL Server

So no Mongo DB sorry...

**Comment by rjcrystal** [comment]
There is eloquent driver for mongodb by jessengers can i use that ?

**Comment by freekmurze** [comment]
I haven't tested it out. It might work. Try it out and let me know 😄

**Comment by mwei0210** [comment]
@rjcrystal , did you mange to get it work? :)

**Comment by msonowal** [comment]
@rjcrystal @mwei0210 
I have added a package support for mongodb with base implementation inspired by this package
https://github.com/msonowal/laravel-auditor
