### ISSUE TITLE
Model with non-numeric primary key

### ISSUE THREAD

**Issue by shahidkarimi** [spatie/laravel-activitylog#813]
**Describe the bug**
If the models' primary key is not numeric and hence the subject in the activity log is numeric this cause problem

**To Reproduce**
Things needed to reproduce the error.
Create a model with non numeric primary key

**Expected behavior**
``General error: 1366 Incorrect integer value: 'c48de54e-11fd-47a5-ae08-880291786806' for column 'subject_id' at row 1 ``

**Versions (please complete the following information)**
- PHP: 7.4
- Database: Mariadb
- Laravel: 8
- Package: Activity Log

**Comment by Gummibeer** [comment]
Hey,

as you've seen in #121 that's not an issue with the package and fixable in userland. There's nothing we can do in the package to fix this for users using UUID instead of AI.
