### ISSUE TITLE
Log is Saving Text old empty attrebute as Array

### ISSUE THREAD

**Issue by ahmadyousefdev** [spatie/laravel-activitylog#818]
**Describe the bug**
I have a column in my model named "personal_photo" which is a nullable text type, when I change the value of this specific column it shows it in the log as an array, here is the log:

```
{
	"old": {
		"personal_photo": {}
	},
	"attributes": {
		"personal_photo": "2020/12/IX6VA08910.jpeg"
	}
}
```

**Expected behavior**
It should show the old value as Null

**Versions (please complete the following information)**
- PHP: 3.7
- Laravel: ^8.0
- Package: ^3.16

**Additional context**
the `personal_photo` in the form is type `file`, I noticed that it saves two logs for this input, and they are in order:
```
{
	"old": {
		"personal_photo": null
	},
	"attributes": {
		"personal_photo": "/tmp/php9RrwZd"
	}
}
```
```
{
	"old": {
		"personal_photo": {}
	},
	"attributes": {
		"personal_photo": "2020/12/IX6VA08910.jpeg"
	}
}
```
Notice the first one is right, it shows the old value as null (which is the right behaviour), the second one shows it as an array `{}`. I don't know why it's even saving the temporary value as it's not the value that is being saved in the database.

**Comment by nagi1** [comment]
Please provide the action or controller that responsible for saving the image (personal_photo).
