### ISSUE TITLE
Put custom property not working

### ISSUE THREAD

**Issue by padre** [spatie/laravel-activitylog#83]
Hi, when I try put custom property to activity not working.

Example:

$lastActivity = Activity::all()->last();
//now $lastActivity->properties ={"attributes":{"name":"name","email":"email@domain.com"}}

$lastActivity->properties->put('ip', '127.0.0.1');
//now $lastActivity->properties = {"attributes": "name":"name","email":"email@domain.com"}}

The method "put" doesn't update the properties :-(

Thanks!

**Comment by sebastiandedeyne** [comment]
I think this is an Eloquent thing. Does it work if you reassign `properties`?

```php
$lastActivity = Activity::all()->last();
$lastActivity->properties = $lastActivity->properties->put('ip', '127.0.0.1');
```

**Comment by padre** [comment]
Oh, yes! Thank you very much! :+1:
