### ISSUE TITLE
updating without model->find() object not recording log

### ISSUE THREAD

**Issue by webblufter** [spatie/laravel-activitylog#830]
**1 - Its recording log as expected**
`$Provider = Provider::findOrFail($id);`
`$Provider->update(['status' => 'banned']);`
[DB Screenshot](https://i.imgur.com/q4OLr3w.png)

**2 - And its not recording activity log, as it should record too**
`Provider::where('id',$id)->update(['status' => 'banned']);`
[Screenshot of working and not working code](https://i.imgur.com/03VRtb7.png)

**My Provider model using LogActivity as**
`use LogsActivity, CausesActivity; // record activity log for current model`
`protected static $logOnlyDirty = true; // record only changed attributes in activity log`
`protected static $logAttributes = ['*']; // record all changed attributes of the current model in logs`
[Model Screenshot](https://i.imgur.com/xWKxyxV.png)

**It should record activity log for both cases, Anyone know the reason?**

**ActivityLog version from Composer with Laravel 5.7**
`"spatie/laravel-activitylog": "3.2.*",`

**Comment by Gummibeer** [comment]
Hey,
both cases run different code and therefore only one triggers the event.
The first runs the update through eloquent and calls all the eloquent logic and fires events.
The second one runs the update on the database query builder which doesn't know anything about the eloquent model.
So everything is correct and the second example can't trigger model logic.

**Comment by webblufter** [comment]
So that means i need to update code everywhere in my application code to overcome this?
Or is there any workaround for this possible?

**Comment by Gummibeer** [comment]
Hey,
no way around this. Two totally different classes and methods.

**Comment by webblufter** [comment]
Alright - thanks for you quick reply 
Appreciated
