### ISSUE TITLE
Warning when trying to performedOn() on a model with UUID

### ISSUE THREAD

**Issue by pacoorozco** [spatie/laravel-activitylog#835]
**Describe the bug**
When you try to use `performedOn()` method on a model using a UUID as `id`, a warning is raised:

```
SQLSTATE[HY000]: General error: 1366 
Incorrect integer value: 'a0e74c95-b860-4457-b0cb-c1c5bf482a6a' for column 'subject_id' at row 1
(SQL: insert into `activity_log` (`log_name`, `properties`, `causer_id`, `causer_type`, `subject_id`, `subject_type`, `description`, `updated_at`, `created_at`) values (default, {"status":"STATUS_SUCCESS"}, 1, App\User, a0e74c95-b860-4457-b0cb-c1c5bf482a6a, App\Key, CREATE_OR_UPDATE, 2021-01-15 08:15:21, 2021-01-15 08:15:21)) 
```

**To Reproduce**
The `App\Key` model definition is:

```php
class Key extends Model implements Searchable
{
    use UsesUUID;

    protected $fillable = [
        'username',
        'enabled',
    ];

    protected $casts = [
        'id' => 'string',
        'username' => 'string',
        'public' => 'string',
        'private' => 'string',
        'fingerprint' => 'string',
        'enabled' => 'boolean',
    ];
```

The column `id` is defined as:

```php
$table->uuid('id')->primary();
```

And the code is trying to add a log line like:

```php
$key = Key::create([
                'username' => $request->username,
            ]);
 activity()
            ->causedBy(Auth::user())
            ->performedOn($key)
            ->withProperties(['status' => Activity::STATUS_SUCCESS])
            ->log(Activity::EVENT_CREATE_OR_UPDATE);
```

**Expected behavior**
No warning should be raised.

**Additional context**
I've been reading the code and I understand that the problem is defining the migration with `nullableMorphs()` which is only intended for `int` and not `uuid` (strings).

**Comment by Gummibeer** [comment]
Hey,
if you UUIDs instead of numeric ones you can adjust the migration to use `nullableUuidMorphs()` instead of `nullableMorphs()`.
That's why we publish the migration to allow the user to alter it.
There is nothing we could do here as the migration code is part of the userland code.

**Comment by pacoorozco** [comment]
Thanks for the quick answer... 
What If I have some models using UUID and others using ID... I guess I should use two different tables, am i right?

**Comment by Gummibeer** [comment]
You should be able to solve this by using a simple `string` column and add both columns created by the `morphs` macro yourself.
But this will lead to the same bad performance for the numeric IDs as for the UUIDs.
I haven't tried a mixed setup as it's also very uncommon to mix primary key types in the same database/application.

**Comment by pacoorozco** [comment]
Ok... thanks !
