### ISSUE TITLE
->changes is always empty when using the LogsActivity trait

### ISSUE THREAD

**Issue by ohnotnow** [spatie/laravel-activitylog#837]
**Describe the bug**
I've added the `LogsActivity` trait to a model and was writing a quick test to make sure it was doing what I expected.  But `->changes` always returns :
```
Illuminate\Support\Collection {#2547 ▼
  #items: []
}
```
I can see other people reporting this - but not really explaining their solution - sorry :-/

**To Reproduce**
My model :
```
class Fault extends Model
{
    use CanHaveComments;
    use CanConvertMarkdown;
    use HasFactory;
    use LogsActivity;
...
    protected $guarded = [];

    protected $logAttributes = ['status'];  // I've tried putting ['*'] in there too
    protected $logUnguarded = true; // I've tried with and without this 'just in case'
    protected static $recordEvents = ['updated'];
    protected static $logName = 'faults';
```
In my test :
```
$this->assertEquals(0, $fault->activities()->get()->count());

$fault->update(['status' => 'Smells a little of marshmallow']);
$fault->update(['status' => 'JActually, smells a little of chocolate']);

$this->assertEquals(2, $fault->activities()->get()->count());
$fault->fresh()->activities->each(fn ($act) => ray($act->changes));  // debugging using this app called 'ray' I found - you should try it out!... ;-p
```

**Expected behavior**
I'm expecting to see the changes to the `status` field.

**Screenshots**
The full dump of the activity itself :
```
array:10 [▼
  "id" => 3
  "log_name" => "faults"
  "description" => "updated"
  "subject_id" => "1"
  "subject_type" => "fault"
  "causer_id" => "1"
  "causer_type" => "App\User"
  "properties" => []
  "created_at" => "2021-01-25T12:07:46.000000Z"
  "updated_at" => "2021-01-25T12:07:46.000000Z"
]
```

**Versions (please complete the following information)**
- PHP: 7.4.3
- Database: tests are running with sqlite
- Laravel: 8.22.1
- Package: 3.16.1

**Additional context**
The app has gone from using v1 of the activity log to v2 then v3.  I can see some changes to the db schema, but even ditching my existing migration and replacing it makes no difference.

**Exception**
N/A

**Stack Trace**
N/A

**Comment by donmbelembe** [comment]
Same problem, did you resolve your issue ?

**Comment by ohnotnow** [comment]
I'm afraid not.  Just gave up on it and rolled my own solution in the end.

**Comment by nagi1** [comment]
I don't think this is a bug, you may not have read the docs well.

Form the docs:
> If you want to log changes to all the $fillable attributes of the model, you can specify protected static $logFillable = true; on the model. If you have a lot of attributes and use $guarded instead of $fillable you can also set protected static $logUnguarded = true; to add all attributes that are not listed in $guarded. For both boolean flags it will respect the possible wildcard and add all ($logFillable) or no ($logUnguarded) attributes.

The problem was the `static` keyword before any properties i.e. `$logUnguarded`.

@Gummibeer I have tested this on a fresh laravel application and I can confirm that this issue not a BUG.

**Comment by Gummibeer** [comment]
Thanks @nagi1 ! 😊
