### ISSUE TITLE
Log on a single model

### ISSUE THREAD

**Issue by sevmardi** [spatie/laravel-activitylog#84]
Hi! I went through the issues and couldn't really find it. So I was wondering If it is possible to fetch the logs of a single instance model. I went through the documentation, but wasn't really able to find what I was looking for. 

Thanks and sorry if I mist a spot in the docs,

**Comment by pabloguerrez** [comment]
Hey,
you can specify a `log_name` for each model by implementing `getLogNameToUse()` to your Model. To retreive use `Activity::where('log_name')->get()`.
Link to Docs:
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/using-multiple-logs#specifying-a-log-for-each-model
Have fun!

**Comment by sevmardi** [comment]
hi @pabloguerrez   Thanks for taking the time! I knew I could do that. But I was wondering if I could just do something along the lines of of this for example. 

`$stack = Stack::find(1)->activity(); // returning a collection of activities of this particular instance` 

But yeah I guess doing that works as well.

**Comment by pabloguerrez** [comment]
like that?
https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#using-the-causesactivity-trait

**Comment by sevmardi** [comment]
I guess I did missed a spot. Thanks! This did the trick.
