### ISSUE TITLE
Can't log 'restored'-Event

### ISSUE THREAD

**Issue by pabloguerrez** [spatie/laravel-activitylog#85]
[This](https://github.com/spatie/laravel-activitylog/blob/master/src/Traits/LogsActivity.php#L19-L21) if-statement prevents 'restored'-Events from being logged.
Would be nice to change that :)

**Comment by pabloguerrez** [comment]
before you ask:
I added the 'restored'-Event by implementing 
`protected static $recordEvents = ['created', 'restored', 'updated', 'deleted'];`
in my model.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes the logging of `restored` events.

**Comment by freekmurze** [comment]
Fixed in `v1.10.0`
