### ISSUE TITLE
Migration issue SQLSTATE[HY000]

### ISSUE THREAD

**Issue by zekuraz** [spatie/laravel-activitylog#869]
**Describe the bug**
Hi ! When I trying to migrate activity log table but it returning error "SQLSTATE[HY000]: General error: -101".

**To Reproduce**

```bash
composer require spatie/laravel-activitylog
php artisan config:clear
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
php artisan migrate
```

**Expected behavior**
running the migrations

**Versions (please complete the following information)**
- PHP: PHP 7.4.16
- Database: DB2 / AS400
- Laravel: Laravel Framework 8.28.1
- Package: cooperl/laravel-db2 : 8.0, spatie/laravel-activitylog

**Exception**
`Illuminate\Database\QueryException`

**Stack Trace**
Migrating: 2015_04_16_073458_create_activity_log_table

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: -101 [IBM][Pilote ODBC System i Access][DB2 for i5/OS]SQL0101 - L'instruction SQL est trop longue ou trop complexe. (SQLExecute[4294967195] at /build/php7.4-kRpGR0/php7.4-7.4.16/ext/pdo_odbc/odbc_stmt.c:259) (SQL: create table activity_log (id bigint not null generated by default as identity constraint activity_log_id_primary primary key, log_name varchar(255), description varchar(16369) not null, subject_type varchar(255), subject_id bigint, causer_type varchar(255), causer_id bigint, properties varchar(16369), created_at timestamp, updated_at timestamp))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +8 vendor frames 
  9   database/migrations/2015_04_16_073458_create_activity_log_table.php:23
      Illuminate\Database\Schema\Builder::create()

      +21 vendor frames 
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by zekuraz** [comment]
I think i found where is the issue for IBMi/AS400

> VARCHAR(n) Varying-length character strings with a maximum length of n bytes. n must be greater than 0 and less than a number that depends on the page size of the table space. The maximum length is 32704.

Can anyone tell me the exact value required for the "properties" and "description" attributes?

**Comment by Gummibeer** [comment]
I assume it's a problem in the DB2 driver by @cooperl22
The default migration uses `text` and `json` column definitions which are translated to the `varchar(16369)` by the database driver/grammar.
I can't tell you an exact length as this totally depends on your app. The `properties` column contains the JSON object of the logged changes and the `description` the text you use as the description for the activity.
As the DB2 driver isn't officially supported by Laravel nor this package I will close this issue as it's in no way something we can/will fix.
