### ISSUE TITLE
How to log visited Page ?

### ISSUE THREAD

**Issue by Astroop** [spatie/laravel-activitylog#88]
Hello, I tried this package and it works very well !
But i can't find if there is any way to log the visited pages, for example i want to know all the pages visited by one connected user. How can I do this kind of tracking with this package please ???
Thanks :)

**Comment by sebastiandedeyne** [comment]
You could write a middleware that logs activity.

```php
use Closure;

class LogsActivity
{
    public function handle($request, Closure $next)
    {
        if (auth()->check()) {
            activity()->causedBy(auth()->user())->log("User visited {$request->fullUrl()}");
        }
        return $next($request);
    }
}
```

**Comment by Astroop** [comment]
It works perfectly ! Thanks, this package is really really useful/powerful !

**Comment by iwasherefirst2** [comment]
@Astroop Which package do you mean?
