### ISSUE TITLE
Return type :LogOptions is mandatory when logging Model events

### ISSUE THREAD

**Issue by nckrtl** [spatie/laravel-activitylog#887]
**Describe the bug**
A return type is required when implementing Model event logging. The documentation is not reflecting this requirement. I could create a PR to update documentation or the return type could not be made mandatory

**To Reproduce**
Install package, following instruction for logging model events:

```php
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class NewsItem extends Model
{
    use LogsActivity;

    protected $fillable = ['name', 'text'];

    public function getActivitylogOptions()
    {
        return LogOptions::defaults()
        ->logOnly(['name', 'text']);
        // Chain fluent methods for configuration options
    }
}
```

**Expected behavior**
No errors to show

However, return type LogOptions is required in Model:
```
public function getActivitylogOptions(): LogOptions
...
```

**Screenshots**
<img width="815" alt="Screenshot 2021-05-17 at 11 43 26" src="https://user-images.githubusercontent.com/18613261/118468487-1cc00d80-b705-11eb-91f7-a0404a8f42c0.png">

**Versions (please complete the following information)**
- PHP: 8.0.6
- Database: MariaDB
- Laravel: latest
- Package: -

**Additional context**
-

**Exception**
See screenshot (this is only when not having a return type)

**Stack Trace**
-

**Comment by Gummibeer** [comment]
Hey,
thanks for reporting - I would accept a PR that fixes the documentation.
So far I've seen https://github.com/spatie/laravel-activitylog/blob/master/docs/advanced-usage/logging-model-events.md should be the only one. The related API documentation is correct.

**Comment by nckrtl** [comment]
Thanks for your quick response @Gummibeer.

PR created: https://github.com/spatie/laravel-activitylog/pull/888

**Comment by rognales** [comment]
Hi there, my IDE is complaining that LogOption does not exists in that namespace. My checks on vendor and as well as master branch also unable to find LogOption file. 

Is this expected?
