### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by Muhammad-Sarfaraz** [spatie/laravel-activitylog#896]
**Unable to locate publishable resources**

While publishing resources package shows "Unable to locate publishable resources."

![Screenshot 2021-05-30 180815](https://user-images.githubusercontent.com/50302555/120103618-54519f80-c172-11eb-81fb-4bca6fd567a0.png)

**Versions (please complete the following information)**
- PHP:  7.3
- Database: 5.8
- Laravel: 8
- Package: 4.0.0

**Comment by Gummibeer** [comment]
#892

**Comment by Muhammad-Sarfaraz** [comment]
Future Folks,It's a versioning problem. Check your package version. If it is below the current version (4.0.0) you may use 
"php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="migrations"
and
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="config"
It will work fine.

**Comment by Gummibeer** [comment]
It's not a version problem. Just read the docs matching your installed version.
The docs are also versions and you have a vX toggle in the upper left corner.

**Comment by Muhammad-Sarfaraz** [comment]
Whoops sorry. Didn't noticed that docs has version as well. 
Thanks a lot.
