### ISSUE TITLE
Adding Related Columns to `$logAttributes`

### ISSUE THREAD

**Issue by archy-bold** [spatie/laravel-activitylog#90]
Hi there. Just wondering if it's possible to log changes to relationships through the automatic model logging?

For example, I've got an entity related to a status entity through a `belongsTo` relationship. Ideally I'd like to show the change through a column on the related status entity and not the id.

So, I'd like to do something such as the following:

```
protected $logAttributes = ['title', 'status.label'];
```

Is this something that's possible?

Thanks!

**Comment by freekmurze** [comment]
This isn't possible now. If the code to enable this is relatively simple I'd accept a fully tested PR that adds this to the package.
