### ISSUE TITLE
Is there a way to configure ACTIVITY_LOGGER_DB_CONNECTION with dynamic connection? For example, tenancy (https://spatie.be/docs/laravel-multitenancy/v2/introduction)

### ISSUE THREAD

**Issue by isaacdarcilla** [spatie/laravel-activitylog#916]
Is there a way to configure ACTIVITY_LOGGER_DB_CONNECTION with dynamic connection? For example, tenancy (https://spatie.be/docs/laravel-multitenancy/v2/introduction)

Since that database connection has for `tenant` (dynamic) and `landlord`.

$ php artisan tinker
$ activity()->log('Look mum, I logged something');

Got some error.

`error : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected`

**Comment by pathros** [comment]
I also have a similar issue.

I am working with two databases.

For a `User.php` model that works with the dafult connection:

```php
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class User
{
    use LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'email_verified_at',
    ];

    /**
     * Spatie's activity log settings.
     * @return LogOptions
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logFillable();
    }
```

The logging is working fine.

*However*, with another model that connects to another database:

```php
class Event extends Model
{
    use LogsActivity;

    /**
     * External DB connection
     * @var string
     */
    public function __construct()
    {
        $this->connection = config('database.connections.external');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ ... ]

    /**
     * Spatie's activity log settings.
     * @return LogOptions
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logFillable();
    }
```
The logging is not working at all.

Why is this happenig? Any workaround to fix this?

**Comment by muba00** [comment]
I have the same issue, I got 2 models, each use different connection. LogsActivity ignores $connection of the model.

**Comment by bretto36** [comment]
You can add this to the model

    public function tapActivity(Activity $activity): void
    {
        // Ensure activity is logged in the tenant's database
        $activity->setConnection('connection_name');
    }
