### ISSUE TITLE
It creates a row with an empty array of attributes

### ISSUE THREAD

**Issue by rafaelxavierborges** [spatie/laravel-activitylog#923]
**Describe the bug**
It creates a row with an empty array of attributes when saving automatically using model events

**To Reproduce**
Model methods ->update() or ->save() produces a record like this bellow:

**Expected behavior**

**Screenshots**
[https://payo.com.br/uploads/spatie/laravel-activitylog/print_empty_properties.png](https://payo.com.br/uploads/spatie/laravel-activitylog/print_empty_properties.png)

**Versions (please complete the following information)**
- PHP: 7.4.15
- Database: MySQL
- Laravel: 8.49.2
- Package: 3.17.0

**Additional context**

**Exception**
None.

**Stack Trace**
None.

**My User model is attached here**
[Usuario.txt](https://github.com/spatie/laravel-activitylog/files/6803724/Usuario.txt)

**Comment by tabirkeland** [comment]
@rafaelxavierborges I just experienced the same issue, and played with `LogOptions`.  I believe you need to define `logAll()` or `logOnly()`.

After adding `logAll()` my properties were populated:

```
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
			->useLogName('models')
			->logAll()
			->logOnlyDirty()
			->dontSubmitEmptyLogs();
    }
```

**Comment by ajuchacko91** [comment]
Hi @rafaelxavierborges,

I had a quick look and What I think is, you're using ```Package: 3.17.0``` and using ```docs v4```.
I don't think ```getActivitylogOptions()``` would work on this version use[ this docs instead](https://spatie.be/docs/laravel-activitylog/v3/introduction) or you could upgrade it to ```package 4.0```

**Comment by rafaelxavierborges** [comment]
Thanks a lot @ajuchacko91 after applied what you said now it works really well !!!
