### ISSUE TITLE
The Contributing link in the README on the master and v3 branches does not show up

### ISSUE THREAD

**Issue by fumiya5863** [spatie/laravel-activitylog#928]
**Describe the bug**
The Contributing link in the README on the master and v3 branches does not show up.

**To Reproduce**
Press the Contributing link in the README on the master and v3 branches.

**Expected behavior**
A description of Contributing will be displayed.

**Screenshots**
![1](https://user-images.githubusercontent.com/60251958/126060978-a74affb3-e814-47c9-9272-cd24e9f2d8af.PNG)

![2](https://user-images.githubusercontent.com/60251958/126060999-5e62917f-69c2-4cfd-a79a-e682277e9406.PNG)

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/blob/master/.github/CONTRIBUTING.md
