### ISSUE TITLE
Causer may me simple Illuminate\Contracts\Auth\Authenticatable

### ISSUE THREAD

**Issue by 5n00p4eg** [spatie/laravel-activitylog#937]
I have UserProvider that works with Authenticatable users which is not Eloquent models. 

So activity log now working and fails on 
```
    protected function getDefaultCauser(): ?Model
    {
        return $this->authManager->guard($this->authDriver)->user();
    }
```

Result user is not Model.

For example, Laravel has \Illuminate\Auth\GenericUser users, they also will not work with a CauserResolver.

**Comment by Gummibeer** [comment]
Hey,

the solution would be to change your user to be an eloquent model. We need eloquent functionality as we have to identify the model for the activities causer relationship. The other way would be to override the causer resolver and always return `null` or any other model you want.

```php
use Spatie\Activitylog\Facade\CauserResolver;
use Illuminate\Database\Eloquent\Model;

CauserResolver::resolveUsing(function(Model | int | string | null $subject): ?Model {
    return null; // or whatever you want to do here
});
```

This code should be placed in the boot method of the app service provider.

**Comment by 5n00p4eg** [comment]
@Gummibeer Thanks for a really fast response.

Can I define a resolver witch will return simple user ids ?  As I see, no.

But, then, how to track who did a change in this case?

**Comment by Gummibeer** [comment]
If you really can't come up with an eloquent model for your causer the only way would be to use the `tap()` functionality and add the `auth()->id` to the JSON properties or a custom column you can add in your migration.
https://spatie.be/docs/laravel-activitylog/v4/basic-usage/logging-activity#tap-activity-before-logged
 
 But as we rely on eloquent morph relationship there's no way for us to keep track of a causer that isn't an eloquent model.
 I don't know how your users work - but possibly tools like https://github.com/ryangjchandler/orbit or https://github.com/calebporzio/sushi could help you to make them an eloquent model.

**Comment by 5n00p4eg** [comment]
Yup, not it's more clear for me.

My Laravel application is only microservice, users located in another service. As I see from examples, I can make Eloquent model even without creating a table.

Anyway, thanks a lot!!!
