### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'batch_uuid' in 'field list'

### ISSUE THREAD

**Issue by loicgeek** [spatie/laravel-activitylog#943]
**Describe the bug**
I am getting an error trying to log user activity manually.

**To Reproduce**
name     : spatie/laravel-activitylog
versions : * 4.1.1
In a controller when an api call is executer, I tested the code ```activity()->log('Look mum, I logged something');```
eg: Configuration, Migration, Model, Controller/Command

**Expected behavior**
Log this test into the database

**Screenshots**

**Versions (please complete the following information)**
- PHP: 8.0
- Database:  MySql
- Laravel: 8.40
- Package: 4.1.1

**Additional context**

**Exception**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'batch_uuid' in 'field list' (SQL: insert into `activity_log` (`log_name`, `properties`, `causer_id`, `causer_type`, `batch_uuid`, `description`, `updated_at`, `created_at`) values (default, [], 1, App\\User, ?, Look mum, I logged something, 2021-08-17 23:07:13, 2021-08-17 23:07:13))

**Stack Trace**
{
    "message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'batch_uuid' in 'field list' (SQL: insert into `activity_log` (`log_name`, `properties`, `causer_id`, `causer_type`, `batch_uuid`, `description`, `updated_at`, `created_at`) values (default, [], 1, App\\User, ?, Look mum, I logged something, 2021-08-17 23:07:13, 2021-08-17 23:07:13))",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 692,
    "trace": [
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 652,
            "function": "runQueryCallback",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 486,
            "function": "run",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 438,
            "function": "statement",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php",
            "line": 32,
            "function": "insert",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2964,
            "function": "processInsertGetId",
            "class": "Illuminate\\Database\\Query\\Processors\\Processor",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 1617,
            "function": "insertGetId",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 1123,
            "function": "__call",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 1088,
            "function": "insertAndSetId",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 929,
            "function": "performInsert",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/spatie/laravel-activitylog/src/ActivityLogger.php",
            "line": 169,
            "function": "save",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/app/Http/Controllers/Web/ClaimsController.php",
            "line": 65,
            "function": "log",
            "class": "Spatie\\Activitylog\\ActivityLogger",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "acceptClaim",
            "class": "App\\Http\\Controllers\\Web\\ClaimsController",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 254,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 197,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 695,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 127,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 63,
            "function": "handleRequest",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 697,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 672,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/loic/afrika_lyrics/web/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 636,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {

**Comment by Gummibeer** [comment]
Is the v4 a fresh installation or have you migrated from v3 to v4?
The `batch_uuid` column was added during v4 in a new migration: https://github.com/spatie/laravel-activitylog/blob/master/database/migrations/add_batch_uuid_column_to_activity_log_table.php.stub

**Comment by loicgeek** [comment]
@Gummibeer  thanks, I reinstalled the package and ran migrations.

**Comment by beyto1974** [comment]
This also happens when you have migrations yet to be executing which execute model modifications and the new activity log migrations come after these.

The fix is to rename the activity log migrations to a prior date or run them using tinker.

**Comment by douglasrono** [comment]
how did u resolve this? I am facing same issue after upgrading to v4

**Comment by facu-alba** [comment]
@douglasrono you need to put some date in the beginning of file add_event_column_to_activity_log_table.php for example 2023_04_16_040660_add_batch_uuid_column_to_activity_log_table.php then run php artisan migrate --seed

**Comment by AlfaVila** [comment]
Run:
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-migrations"
and
php artisan migrate

**Comment by douglasrono** [comment]
Thanks this has worked
