### ISSUE TITLE
php artisan vendor:publish --provider="Spa...

### ISSUE THREAD

**Issue by jackdaniel9** [spatie/laravel-activitylog#953]
Hi,

When i make the command (after composer require) nothing append, no migration are create:
php artisan vendor:publish --provider="Spatie\Activitylog\ActivitylogServiceProvider" --tag="activitylog-migrations"

The console says:
No publishable resources for tag [activitylog-migrations].

Thank you to help me

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/issues/664
