### ISSUE TITLE
Do not log remember_token on User model

### ISSUE THREAD

**Issue by rodurma** [spatie/laravel-activitylog#96]
When I do logout in my app, the remember_token column is changed. This add a new record in activity_log table.

My User Model:

~~~php
class User extends Authenticatable
{
    use HasDefender, LogsActivity;

    protected static $logAttributes = ['name', 'email'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}
~~~

**Comment by wartent** [comment]
protected static $ignoreChangedAttributes = ['remember_token'];

**Comment by freekmurze** [comment]
@wartent provided the correct answer. Here's the [documentation on that feature](https://docs.spatie.be/laravel-activitylog/v1/advanced-usage/logging-model-events#ignoring-changes-to-certain-attributes).

**Comment by rodurma** [comment]
I added this configuration in my `User` model, but is not working.

```php
class User extends Authenticatable
{

    use Notifiable, SoftDeletes, LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $dates = ['deleted_at'];

    protected static $logAttributes = [
        'client_id', 'name', 'email', 'password', 'is_active'
    ];

    protected static $ignoreChangedAttributes = ['remember_token'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}
```

**Comment by aboldyrev** [comment]
I have the same problem:
`class User extends Authenticatable
{
	use
		BelongsToEditors,
		Comparable,
		Nullable,
		IsRelatedWith,
		LogsActivity,
		CausesActivity {
			CausesActivity::activity insteadof LogsActivity;
			CausesActivity::activity as causesActivity;
		}

	public $table = 'base_users';

	protected $nullable = [ 'name' ];

	protected $fillable = [
		'login',
		'password',
		'email',
		'name',
		'is_subscribed',
		'is_blocked',
		'is_admin'
	];

	protected $hidden = [
		'password',
		'remember_token',
	];

	protected $casts = [
		'is_subscribed' => 'boolean',
		'is_blocked'    => true,
		'is_admin'      => false
	];

	protected static $ignoreChangedAttributes = [
		'login',
		'password',
		'email',
		'name',
		'is_subscribed',
		'is_blocked',
		'is_admin',
		'remember_token',
		'updated_at',
		'created_at'
	];
}`
