### ISSUE TITLE
Route Logs

### ISSUE THREAD

**Issue by Emmanavimex** [spatie/laravel-activitylog#968]
Hello, how can i get a log when users login or access pages or activity via web routes

**Comment by Gummibeer** [comment]
https://spatie.be/docs/laravel-activitylog/v4/basic-usage/logging-activity

**Comment by Emmanavimex** [comment]
Hello, am asking about how can you records the route logs ?

Example user login or user visit a pages

**Comment by Gummibeer** [comment]
With that method how and wherever you want. In a middleware, controller, event listener ...
There's no special "log every route/http call" logic. So you have to build it your own with the activity logger.
