### ISSUE TITLE
Delete event

### ISSUE THREAD

**Issue by cesarcruzc** [spatie/laravel-activitylog#97]
The delete event does not working

**Comment by freekmurze** [comment]
According to [our tests](https://github.com/spatie/laravel-activitylog/blob/master/tests/LogsActivityTest.php#L55-L84) deletion logging should work just fine. What are you doing differently from the tests?

Without any extra info regarding the issue you're having it's impossible for me to help you. How can I recreate the problem?

**Comment by cesarcruzc** [comment]
Hi @freekmurze,

I'm using on the module like this:

`
class ContractorBenefit extends Model
{
    use LogsActivity;
}
`

**Comment by cesarcruzc** [comment]
What am I doing wrong?

**Comment by freekmurze** [comment]
It's impossible to say with so little code to go on. 

My suggestion is that you examine the tests that go along with this package. They prove the deletion logging is working. Try to find how your code differs from the tests.
