### ISSUE TITLE
 Parse error: syntax error, unexpected ':', expecting '{' in /vendor/spatie/laravel-activitylog/src/helpers.php on line 6

### ISSUE THREAD

**Issue by mtuchi** [spatie/laravel-activitylog#98]
I keep getting this error. 
`Parse error: syntax error, unexpected ':', expecting '{' in /home/admin/web/client.irabu.co.tz/vendor/spatie/laravel-activitylog/src/helpers.php on line 6`.

**Comment by freekmurze** [comment]
You need PHP 7 in order to use this package.

**Comment by elephantux** [comment]
The same problem with PHP 7

**Comment by hassanzreik** [comment]
same problem here using php7.1
Parse error: syntax error, unexpected ':', expecting '{' in vendor/spatie/laravel-permission/src/helpers.php on line 16
