### ISSUE TITLE
logOnly() triggering "Illegal offset type" for a specific model

### ISSUE THREAD

**Issue by iec989** [spatie/laravel-activitylog#982]
**Describe the bug**
`logOnly()` triggering "Illegal offset type" for a specific model (1 out of 84). It doesn't matter if I run `logOnly(['*'])` or with actual column names. I also tried adding fillable columns, but that didn't solve the issue.

**To Reproduce**
This is the model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use Illuminate\Database\Eloquent\Builder;

use App\Traits\HasCompositePrimaryKeyTrait;

class UserCompany extends Model
{
	use LogsActivity;
    
	use HasCompositePrimaryKeyTrait;

	public $incrementing = false;
	protected $primaryKey = ['user_id', 'company_id'];

	public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logOnly(['*'])->logOnlyDirty()->dontLogIfAttributesChangedOnly(['updated_at'])->dontSubmitEmptyLogs();    
    }
	public function user(){
		return $this->belongsTo('App\User');
	}

	public function company(){
		return $this->belongsTo('App\Company');
	}
}
```

**Expected behavior**
That `logOnly()` doesn't fail

**Screenshots**

**Versions (please complete the following information)**
- PHP: 8
- Database: Mysql
- Laravel: 8
- Package: v4

**Additional context**

**Exception**
TypeError: Illegal offset type

**Stack Trace**
[2021-11-09 17:27:49] local.ERROR: Illegal offset type {"userId":3,"exception":"[object] (TypeError(code: 0): Illegal offset type at /var/www/gdpr/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1094)
[stacktrace]
#0 /var/www/gdpr/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1082): Illuminate\\Database\\Eloquent\\Model->getKeyForSelectQuery()
#1 /var/www/gdpr/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1522): Illuminate\\Database\\Eloquent\\Model->setKeysForSelectQuery()
#2 /var/www/gdpr/vendor/spatie/laravel-activitylog/src/Traits/LogsActivity.php(266): Illuminate\\Database\\Eloquent\\Model->fresh()
#3 /var/www/gdpr/vendor/spatie/laravel-activitylog/src/Traits/LogsActivity.php(54): App\\UserCompany->attributeValuesToBeLogged()

**Comment by karam-mustafa** [comment]
I think the default values are inserted by execution the "logOnly()" are ['*'], so there is no need to use it.

**Comment by debuqer** [comment]
This happens because laravel eloquent can't use fresh() method for models with composite keys.
Laravel activitylog uses fresh method to save new changes.

You can override **setKeysForSelectQuery** method  in your Model
```php
class UserCompany extends Model
{
	use LogsActivity;

	public $incrementing = false;
	protected $primaryKey = ['user_id', 'company_id'];
        
        // other methods
        
        protected function setKeysForSelectQuery($query)
         {
                foreach($this->primaryKey as $key) {
                    $query->where($key, '=', $this->$key);
                }

                return $query;
         }
}

```
So eloquent would be able to fresh your model and logger can log new changes.


 [see here for the reference](https://github.com/laravel/framework/issues/5355#issuecomment-63573747)
