### ISSUE TITLE
Using this library but the branch l5.2

### ISSUE THREAD

**Issue by krugerdavid** [spatie/laravel-activitylog#99]
Hi
Is there a way to use this package but with php 5.6? I saw the other repository but this one relates to a model and is the perfect case scenario I'm looking.
Hope to hear back from you guys
Great work!

**Comment by freekmurze** [comment]
Some users have created a backport for PHP 5.6. I think you'll find the fork when searching for it on packagist.

**Comment by krugerdavid** [comment]
thanks @freekmurze after the post, I found the backport listed on the issues here in this repo.
